'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname,root=path.resolve(dir,'../../..'),baseDir=path.resolve(dir,'../../customer-support-action/20260906');
const read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function overlay(){let source=read(path.join(baseDir,'operational-overlay.candidate.js'));
 const anchor="  root.addEventListener('phase1:queue',syncQueue);";
 if(!source.includes(anchor))throw Error('queue retry overlay anchor missing');
 const retry=`  function queueCount(statuses){return root.Phase1.queue.list().filter(q=>statuses.includes(q.status)).length;}
  function retryUncertain(){const retryable=queueCount(['uncertain']);if(!retryable){syncQueue();return Promise.resolve(root.WRITE_Q);}return root.Phase1.queue.flush().finally(syncQueue);}
  root.retryFailedWrites=retryUncertain;root.retryFailed=retryUncertain;
  if(typeof root.updateSyncBadge==='function')root.updateSyncBadge=function(){const el=root.document&&root.document.getElementById&&root.document.getElementById('syncBadge');if(!el)return;const pending=queueCount(['pending','sending']),uncertain=queueCount(['uncertain']),blocked=queueCount(['conflict','rejected']);if(uncertain){el.textContent='🔴 처리 결과 미확인 '+uncertain+'건 — 같은 요청 다시 시도';el.className='syncbadge bad';el.onclick=retryUncertain;}else if(pending){el.textContent='🟡 서버 반영 중 '+pending+'건';el.className='syncbadge wait';el.onclick=null;}else if(blocked){el.textContent='🔴 서버 확인 필요 '+blocked+'건';el.className='syncbadge bad';el.onclick=null;}else{el.textContent='🟢 서버 동기화 완료';el.className='syncbadge ok';el.onclick=null;}};
  if(typeof root.updatePendingBadge==='function')root.updatePendingBadge=function(){const el=root.document&&root.document.getElementById&&root.document.getElementById('pendBadge');if(!el)return;const pending=queueCount(['pending','sending']),uncertain=queueCount(['uncertain']),blocked=queueCount(['conflict','rejected']);el.textContent=uncertain?('결과 미확인 '+uncertain+'건 · 같은 요청 다시 시도'):blocked?('서버 확인 필요 '+blocked+'건'):pending?('서버 반영 대기 '+pending+'건'):'';el.style.display=(pending||uncertain||blocked)?'':'none';el.style.cursor=uncertain?'pointer':'default';el.onclick=uncertain?retryUncertain:null;};
`;
 return source.replace(anchor,retry+anchor);
}
function build(){const generated={'operational-adapter.candidate.js':read(path.join(baseDir,'operational-adapter.candidate.js')),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':read(path.join(baseDir,'transport.candidate.js'))};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','review.md','contract.test.cjs','ui.test.cjs',...Object.keys(generated)],sources=['sql/customer-support-action/20260906/manifest.json','crm.html','mobile.html','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',capability:'queue_retry',ui_coverage_candidate:['C04'],prerequisite:'customer-support-action/20260906',surface:'pc_mobile',meaning:'manual retry reuses the exact uncertain queue command and request_id',retryable_statuses:['uncertain'],non_retryable_statuses:['conflict','rejected'],server_dependency:'existing common command receipt and operation-specific ACK',database_changes:false,staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={overlay,build};
