'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=require('../../technical-inquiry-transfer/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const read=name=>fs.readFileSync(path.join(dir,name),'utf8').replace(/\r\n?/g,'\n');
const readRoot=name=>fs.readFileSync(path.join(root,name),'utf8').replace(/\r\n?/g,'\n');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function replaceOne(source,pattern,replacement,label){const next=source.replace(pattern,replacement);if(next===source)throw Error('attachment compatibility build anchor missing: '+label);return next;}
function adapter(){let source=base.adapter();
 source=replaceOne(source,"'opportunity_create','lineage_link']","'opportunity_create','lineage_link','attachment_prepare','attachment_complete']",'operation list');
 source=replaceOne(source,' function normalize(operation,objectId,expectedVersion,payload){',` function normalizeAttachment(operation,objectId,payload){if(payload.opportunity_id!==undefined&&payload.opportunity_id!==objectId)fail('OBJECT_MISMATCH');if(operation==='attachment_complete'){const allowed=['opportunity_id','attachment_id','object_path','file_name','mime_type','size_bytes','category','tags','memo','uploaded_by'];if(Object.keys(payload).some(k=>!allowed.includes(k))||!UUID.test(payload.attachment_id))fail('INVALID_ATTACHMENT_COMPLETE');return {attachment_id:payload.attachment_id};}const allowed=['opportunity_id','file_name','mime_type','size_bytes','category','tags','memo','uploaded_by'];if(Object.keys(payload).some(k=>!allowed.includes(k))||typeof payload.file_name!=='string'||!payload.file_name.trim()||payload.file_name.length>255||typeof payload.mime_type!=='string'||!payload.mime_type.trim()||payload.mime_type.length>200||!Number.isSafeInteger(payload.size_bytes)||payload.size_bytes<1||payload.size_bytes>20971520||!['현장사진','견적자료','도면','회의자료','계약관련','기타'].includes(payload.category)||!Array.isArray(payload.tags)||payload.tags.length>20||payload.tags.some(x=>typeof x!=='string'||!x.trim()||x.length>100)||new Set(payload.tags.map(x=>x.trim())).size!==payload.tags.length||payload.memo!=null&&(typeof payload.memo!=='string'||payload.memo.length>4000))fail('INVALID_ATTACHMENT_PREPARE');return {file_name:payload.file_name.trim(),mime_type:payload.mime_type.trim().toLowerCase(),size_bytes:payload.size_bytes,category:payload.category,tags:payload.tags.map(x=>x.trim()),memo:String(payload.memo||'').trim()||null};}\n function normalize(operation,objectId,expectedVersion,payload){`,'attachment normalizer');
 source=replaceOne(source,"'opportunity_create','favorite_set','opportunity_touch'].includes(operation)","'opportunity_create','favorite_set','opportunity_touch','attachment_prepare','attachment_complete'].includes(operation)",'sentinel');
 source=replaceOne(source,"else if(operation==='lineage_link')normalized=normalizeLineage(objectId,payload);else normalized=normalizeTrash", "else if(operation==='lineage_link')normalized=normalizeLineage(objectId,payload);else if(operation==='attachment_prepare'||operation==='attachment_complete')normalized=normalizeAttachment(operation,objectId,payload);else normalized=normalizeTrash",'normalize dispatch');
 source=replaceOne(source,"  if(command.operation==='opportunity_work_set'",`  if(command.operation==='attachment_prepare'&&(ack.status!=='pending'||!UUID.test(ack.attachment_id)||ack.bucket_id!=='crm-site-files'||typeof ack.object_path!=='string'||!ack.object_path.startsWith('deals/'+command.object_id+'/')||typeof ack.pending_expires_at!=='string'||!UUID.test(ack.audit_event_id)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='attachment_complete'&&(ack.status!=='ready'||ack.attachment_id!==command.payload.attachment_id||!UUID.test(ack.audit_event_id)||!ack.attachment||ack.attachment.id!==ack.attachment_id||ack.attachment.status!=='ready'||typeof ack.attachment.file_name!=='string'||!Array.isArray(ack.attachment.tags)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='opportunity_work_set'`,'attachment ACK');
 return source;
}
function transport(){let source=readRoot('sql/reachable-operations-bundle/20260906/transport.candidate.js');
 source=replaceOne(source,"if(u.origin===origin&&(u.pathname.startsWith('/auth/v1/')||rpcAllow.has", "if(u.origin===origin&&(u.pathname.startsWith('/auth/v1/')||u.pathname.startsWith('/storage/v1/object/upload/sign/crm-site-files/deals/')||rpcAllow.has",'storage allowlist');
 source=replaceOne(source,' function restoreQueue(){',` async function attachmentCommand(operation,objectId,payload){const q=enqueue(operation,objectId,0,payload,crypto.randomUUID());await flush();const row=list().find(x=>x.request_id===q.request_id);if(!row||row.status!=='done'||!row.ack)throw Error(row&&row.error||'ATTACHMENT_COMMAND_UNCERTAIN');return row.ack;}
 async function uploadAttachment(meta,file){if(!profile||!client)throw Error('AUTH_REQUIRED');if(!meta||!file||meta.size_bytes!==file.size)throw Error('INVALID_ATTACHMENT_FILE');const prep=await attachmentCommand('attachment_prepare',meta.opportunity_id,meta),bucket=client.storage.from(prep.bucket_id),signed=await bucket.createSignedUploadUrl(prep.object_path);if(signed.error||!signed.data?.token)throw Error(signed.error?.message||'ATTACHMENT_SIGN_FAILED');const uploaded=await bucket.uploadToSignedUrl(prep.object_path,signed.data.token,file,{contentType:meta.mime_type,upsert:false});if(uploaded.error)throw Error(uploaded.error.message||'ATTACHMENT_UPLOAD_FAILED');const done=await attachmentCommand('attachment_complete',meta.opportunity_id,{opportunity_id:meta.opportunity_id,attachment_id:prep.attachment_id,object_path:prep.object_path,file_name:meta.file_name,mime_type:meta.mime_type,size_bytes:meta.size_bytes,category:meta.category,tags:meta.tags,memo:meta.memo,uploaded_by:meta.uploaded_by});return Object.assign({},meta,done.attachment||{},{id:done.attachment_id,status:'ready'});}
 function restoreQueue(){`,'attachment transport');
 source=replaceOne(source,'queue:{enqueue,flush,list,validateAck},get profile',"queue:{enqueue,flush,list,validateAck},uploadAttachment,get profile",'transport export');
 return source;
}
function overlay(){let source=base.overlay();
 source=replaceOne(source,'  root.addEventListener(\'phase1:queue\'',`  if(typeof root.uploadExecAttachment==='function')root.uploadExecAttachment=async function(d,f,cat,tags,memo){return root.Phase1.uploadAttachment({opportunity_id:d.id,file_name:f.name,mime_type:f.type||'application/octet-stream',size_bytes:f.size||0,category:cat,tags:tags,memo:memo,uploaded_by:(root.ME&&root.ME.name)||(root.repN&&root.repN(d.assignee))||''},f);};
  if(typeof root.uploadAttachmentM==='function')root.uploadAttachmentM=async function(d,f,category,tags,memo){return root.Phase1.uploadAttachment({opportunity_id:d.id,file_name:f.name,mime_type:f.type||'application/octet-stream',size_bytes:f.size||0,category:category,tags:tags,memo:memo,uploaded_by:(root.G&&root.G.user&&root.G.user.nm)||d.rep||''},f);};
  root.addEventListener('phase1:queue'`,'upload helper override');
 source=replaceOne(source,'quote_versions:d.quote_versions||[],won_amount:',"quote_versions:d.quote_versions||[],attachments:d.attachments||[],won_amount:",'mobile attachment hydration');
 return source;
}
function applySql(){return tx(read('helper.sql'));}
function rollbackSql(){return tx(read('rollback-fragment.sql'));}
function build(){const files={'staging-apply-after-technical-transfer.sql':applySql(),'rollback-before-technical-transfer.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':transport()};for(const [name,value] of Object.entries(files))fs.writeFileSync(path.join(dir,name),value);
 const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs',...Object.keys(files)];
 const sources=['sql/technical-inquiry-transfer/20260906/manifest.json','sql/reachable-operations-bundle/20260906/transport.candidate.js','crm.html','mobile.html','docs/operational-cutover-20260906/attachment-contracts.md'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',operations:['attachment_prepare','attachment_complete'],ui_coverage_candidate:['T01','T02'],status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',bucket:{id:'crm-site-files',public:false,file_size_limit:20971520,allowed_mime_types:['image/*','pdf','office','application/octet-stream with filename validation']},metadata_relation:'crm_security.deal_attachments',read_projection:'deal_core.items[].attachments ready-only safe metadata',upload:'authenticated JWT createSignedUploadUrl + uploadToSignedUrl; no service role in browser',partial_batch:'completed ready files remain canonical and reappear after refresh; batch activity remains existing all-complete behavior',pending_ttl_hours:24,storage_cleanup:'not performed by SQL; expired pending/object cleanup requires Storage API operator before cutover',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={applySql,rollbackSql,adapter,overlay,transport,build};
