'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),build=require('./build.cjs');
function load(text,name){const m=new Module(name);m._compile(text,name+'.js');return m.exports;}
const deal='f6090500-0006-4000-8000-000000000001',request='f6090600-0120-4000-8000-000000000001',attachment='f6090600-0120-4000-8000-000000000002',actor='f6090500-0001-4000-8000-000000000001';
test('prepare keeps only canonical file metadata and rejects client paths',()=>{const a=load(build.adapter(),'attachment-adapter'),c=a.normalize('attachment_prepare',deal,0,{opportunity_id:deal,file_name:' 현장.jpg ',mime_type:'IMAGE/JPEG',size_bytes:1234,category:'현장사진',tags:['현장'],memo:' 메모 ',uploaded_by:'forged'});assert.deepEqual(c.payload,{file_name:'현장.jpg',mime_type:'image/jpeg',size_bytes:1234,category:'현장사진',tags:['현장'],memo:'메모'});assert.throws(()=>a.normalize('attachment_prepare',deal,0,{...c.payload,object_path:'forged'}),/INVALID_ATTACHMENT_PREPARE/);});
test('complete collapses legacy payload to server attachment identity',()=>{const a=load(build.adapter(),'attachment-complete'),c=a.normalize('attachment_complete',deal,0,{opportunity_id:deal,attachment_id:attachment,object_path:'forged',file_name:'forged',mime_type:'text/plain',size_bytes:1,category:'기타',tags:[],memo:'',uploaded_by:'forged'});assert.deepEqual(c.payload,{attachment_id:attachment});});
test('attachment ACKs remain correlated and expose no signed URL in receipt',()=>{const a=load(build.adapter(),'attachment-ack'),command={request_id:request,operation:'attachment_prepare',object_id:deal,auth_uid:actor,user_id:actor,payload:{}},ack={contract_version:1,ok:true,request_id:request,operation:'attachment_prepare',object_id:deal,actor_auth_uid:actor,actor_user_id:actor,replayed:false,status:'pending',attachment_id:attachment,bucket_id:'crm-site-files',object_path:`deals/${deal}/${attachment}`,pending_expires_at:'2026-09-07T00:00:00Z',audit_event_id:actor,server_at:'2026-09-06T00:00:00Z'};assert.equal(a.validateAck(ack,command),ack);assert.equal('signed_url' in ack,false);assert.throws(()=>a.validateAck({...ack,object_path:'other'},command),/ACK_CONTRACT_MISMATCH/);});
test('transport uses authenticated Storage SDK signer/upload and narrow URL allowlist',()=>{const s=build.transport();assert.match(s,/createSignedUploadUrl\(prep\.object_path\)/);assert.match(s,/uploadToSignedUrl\(prep\.object_path,signed\.data\.token,file/);assert.match(s,/storage\/v1\/object\/upload\/sign\/crm-site-files\/deals\//);assert.doesNotMatch(s,/service[_-]?role/i);});
test('SQL keeps storage objects API-owned and ready projection excludes path and URLs',()=>{const s=build.applySql();assert.match(s,/metadata->>'size'/);assert.match(s,/metadata->>'mimetype'/);assert.doesNotMatch(s,/INSERT INTO storage\.objects/i);assert.doesNotMatch(s,/DELETE FROM storage\.objects/i);const projection=s.slice(s.indexOf("CREATE FUNCTION public.crm_operational_source_v1"));assert.match(projection,/'attachments'/);assert.doesNotMatch(projection,/object_path|signed_url|download_url/);});
