'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const personal=require('../../personal-state-compat/20260906/build.cjs'),cutover=require('../../operational-cutover-candidate/20260906/build.cjs'),build=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const deal=n=>s.uid(6,n),request=n=>`f6090600-0121-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(cutover.compose('apply',{localPersonalCandidate:true,skipAttachment:true}));await db.exec(build.applySql());return db;}
async function actor(db,index=0){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[s.mapping.accounts[index].auth_uid]);await db.exec('SET ROLE authenticated');}
async function call(db,op,rid,payload,index=0){await actor(db,index);try{return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,0,$4) a',[rid,op,deal(1),JSON.stringify(payload)])).rows[0].a;}finally{await db.exec('RESET ROLE');}}
async function prepare(db,rid=request(1),index=0){return call(db,'attachment_prepare',rid,{file_name:'현장.jpg',mime_type:'image/jpeg',size_bytes:1234,category:'현장사진',tags:['현장'],memo:'확인'},index);}
async function one(db,sql,params=[]){return (await db.query(sql,params)).rows[0];}
test('prepare creates one pending row, private audit and replay-safe receipt',async()=>{const db=await setup();try{const a=await prepare(db),replay=await prepare(db);assert.equal(a.status,'pending');assert.equal(replay.replayed,true);assert.equal(replay.attachment_id,a.attachment_id);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_security.deal_attachments')).n,1);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_security.attachment_audit_events WHERE action='attachment_prepare'")).n,1);await assert.rejects(call(db,'attachment_prepare',request(1),{file_name:'다름.pdf',mime_type:'application/pdf',size_bytes:5,category:'기타',tags:[]}),e=>e.code==='PT409');}finally{await db.close();}});
test('complete verifies Storage owner, size and MIME then read returns safe ready metadata',async()=>{const db=await setup();try{const p=await prepare(db);await db.query('INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES($1,$2,$3,$4)',[p.bucket_id,p.object_path,s.mapping.accounts[0].auth_uid,JSON.stringify({size:1234,mimetype:'image/jpeg'})]);const a=await call(db,'attachment_complete',request(2),{attachment_id:p.attachment_id});assert.equal(a.status,'ready');assert.equal(a.attachment.file_name,'현장.jpg');await actor(db);const source=(await db.query("SELECT public.crm_operational_source_v1('deal_core',null,100) a")).rows[0].a;await db.exec('RESET ROLE');const row=source.items.find(x=>x.id===deal(1)),listed=row.attachments[0];assert.equal(listed.id,p.attachment_id);assert.equal(listed.status,'ready');assert.equal('object_path' in listed,false);assert.equal('signed_url' in listed,false);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_security.attachment_audit_events WHERE action='attachment_complete'")).n,1);}finally{await db.close();}});
test('mismatch and unauthorized actor cannot complete',async()=>{const db=await setup();try{const p=await prepare(db);await db.query('INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES($1,$2,$3,$4)',[p.bucket_id,p.object_path,s.mapping.accounts[0].auth_uid,JSON.stringify({size:999,mimetype:'image/jpeg'})]);await assert.rejects(call(db,'attachment_complete',request(3),{attachment_id:p.attachment_id}),e=>e.code==='PT409');assert.equal((await one(db,'SELECT status FROM crm_security.deal_attachments WHERE attachment_id=$1',[p.attachment_id])).status,'pending');await assert.rejects(call(db,'attachment_complete',request(4),{attachment_id:p.attachment_id},1),e=>e.code==='42501');}finally{await db.close();}});
test('rollback restores previous dispatcher/read and archives attachment evidence without deleting Storage',async()=>{const db=await setup();try{const beforeWrite=(await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_write_command_v2_technical_transfer_20260906(uuid,text,uuid,integer,jsonb)'::regprocedure")).d,beforeRead=(await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_operational_source_v1_technical_transfer_20260906(text,uuid,integer)'::regprocedure")).d,p=await prepare(db);await db.query('INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES($1,$2,$3,$4)',[p.bucket_id,p.object_path,s.mapping.accounts[0].auth_uid,JSON.stringify({size:1234,mimetype:'image/jpeg'})]);await db.exec(build.rollbackSql());assert.equal((await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)'::regprocedure")).d,beforeWrite);assert.equal((await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='public.crm_operational_source_v1(text,uuid,integer)'::regprocedure")).d,beforeRead);assert.equal((await one(db,'SELECT count(*)::int n FROM storage.objects')).n,1);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_attachment_compat_archive.deal_attachments')).n,1);}finally{await db.close();}});
