'use strict';
// This entry never loads crm.html/mobile.html legacy scripts or their caches.
(()=>{
const root=document.getElementById('app');
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const append=(parent,...nodes)=>{parent.append(...nodes);return parent;};
const btn=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.addEventListener('click',fn);return b;};
const input=(form,label,type='text',value='')=>{const id='field-'+(++seq);const l=el('label',label),i=el(type==='textarea'?'textarea':'input');l.htmlFor=id;i.id=id;if(type!=='textarea')i.type=type;i.value=value;form.append(l,i);return i;};
const select=(form,label,values)=>{const id='field-'+(++seq),l=el('label',label),s=el('select');l.htmlFor=id;s.id=id;for(const [v,t] of values){const o=el('option',t);o.value=v;s.append(o);}form.append(l,s);return s;};
const money=v=>v===null?'이용 불가':BigInt(v||'0').toLocaleString('ko-KR');
const token=(k,r)=>k==='deal'?String(r.version):r.updated_at;
let seq=0,client,profile=null,data=null,view='dashboard',selected=null,busy=false,message='',failed=false;
const labels={dashboard:'대시보드',inquiries:'견적문의',pipeline:'Pipeline',today:'오늘업무'};
try{client=StagingCRM.create(window.STAGING_CONFIG);}catch(e){root.append(el('div','실행 차단: '+e.message,'notice error'));return;}
function notice(parent){if(message)parent.append(el('div',message,failed?'notice error':'notice'));}
function fail(e){failed=true;message=e.message;render();}
function contract(x){if(x?.contract_version!==3||x.scope!=='authorized_only'||!['complete','partial'].includes(x.coverage))throw Error('응답 계약 불일치: 화면을 중단합니다.');return x;}
async function load(){const [d,q,dash,t]=await Promise.all(['crm_deals_scoped_v2','crm_inquiries_scoped_v2','crm_dashboard_scoped_v2','crm_today_scoped_v2'].map(n=>client.rpc(n)));data={deals:contract(d),inquiries:contract(q),dashboard:contract(dash),today:contract(t)};}
async function refresh(){if(busy)return;busy=true;try{await load();failed=false;message='서버에서 새로 조회했습니다.';}catch(e){data=null;failed=true;message=e.message;}finally{busy=false;render();}}
async function mutate(name,args){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await client.rpc(name,args);await load();message='저장 완료 · 서버에서 다시 확인했습니다.';failed=false;}catch(e){message=e.message;failed=true;try{await load();}catch{data=null;message+=' / 재조회 실패: 기존 화면 데이터를 폐기했습니다.';}}finally{busy=false;render();}}
function login(){const c=el('section',undefined,'login');append(c,el('div','NETFORM / SANDBOX','eyebrow'),el('h1','업무의 새 경로'),el('p','테스트 계정으로만 로그인하세요. 운영 데이터와 연결되지 않습니다.','subtle'));notice(c);const f=el('form'),email=input(f,'이메일','email'),password=input(f,'비밀번호','password');email.autocomplete='username';password.autocomplete='current-password';email.required=password.required=true;const submit=el('button','Staging 로그인','primary');submit.type='submit';f.append(submit);f.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;try{profile=await client.login(email.value,password.value);password.value='';await load();const saved=sessionStorage.getItem(client.storageKey()+':view');view=labels[saved]?saved:'dashboard';message='';failed=false;render();}catch(err){profile=null;data=null;password.value='';fail(err);}});append(c,f,el('p',StagingCRM.REF+' · Contract 3 · 토큰 메모리 보관','subtle'));root.append(c);}
async function logout(){let key;try{key=client.storageKey();}catch{}if(key)sessionStorage.removeItem(key+':view');profile=null;data=null;selected=null;view='dashboard';message='';try{await client.logout();}catch(e){message=e.message;failed=true;}render();}
function change(v){view=v;selected=null;sessionStorage.setItem(client.storageKey()+':view',v);render();}
function render(){root.replaceChildren();if(!profile){login();return;}const shell=el('div',undefined,'shell'),side=el('aside'),main=el('section');append(side,el('div','CONTROLLED ACCESS','eyebrow'),el('h2','NETFORM.'));append(side,append(el('div',undefined,'identity'),el('strong',profile.display_name||profile.name||'테스트 사용자'),el('p',profile.permission_role+' · AAL1 / 고위험 기능 미제공','subtle'),el('p',profile.auth_uid,'mono')));const nav=el('nav');for(const [v,l]of Object.entries(labels))nav.append(btn(l,()=>change(v),v===view?'active':''));append(side,nav,btn('로그아웃',logout),el('p','Storage · Export · MFA 등록\n이번 단계 범위 밖','subtle'));const tools=el('div',undefined,'toolbar');append(tools,append(el('div'),el('div','STAGING / CONTRACT 3','eyebrow'),el('h1',labels[view])),btn('새로 조회',refresh));append(main,tools,el('div','허용된 범위만 표시합니다. 이 화면은 회사 전체 실적이 아닙니다.','notice'));notice(main);if(!data)main.append(el('div','데이터를 가져오지 못했습니다. 새로 조회하세요. 캐시 fallback은 사용하지 않습니다.','empty'));else if(view==='dashboard')dashboard(main);else if(view==='today')today(main);else list(main,view==='pipeline'?'deal':'inquiry');append(shell,side,main);root.append(shell);}
function dashboard(main){const d=data.dashboard,f=el('form',undefined,'filters');const from=input(f,'시작일','date'),to=input(f,'종료일','date');const brands=[...new Set([...data.deals.rows,...data.inquiries.rows].map(r=>r.brand).filter(Boolean))];const brand=select(f,'브랜드',[['','전체 허용 브랜드'],...brands.map(x=>[x,x])]);const owners=new Map([...data.deals.rows,...data.inquiries.rows].map(r=>[r.owner_id||r.assigned_to,r.owner_name]));const owner=select(f,'담당자',[['','전체 허용 담당자'],...[...owners].filter(x=>x[0]).map(([id,n])=>[id,n||id])]);const submit=el('button','집계 조회');submit.type='submit';f.append(submit);f.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;try{data.dashboard=contract(await client.rpc('crm_dashboard_scoped_v2',{p_from:from.value||null,p_to:to.value||null,p_brand:brand.value||null,p_owner:owner.value||null}));message='필터 적용 · 생성/접수일 기준';failed=false;render();}catch(err){fail(err);}});main.append(f);const stats=el('div',undefined,'stats');for(const [l,v]of [['허용 Deal',d.deals===null?'이용 불가':d.deals],['허용 문의',d.inquiries],['허용 Deal 금액 (원)',money(d.amount)]])stats.append(append(el('div',undefined,'stat'),el('span',l),el('strong',String(v))));main.append(stats,el('p',`범위 내 집계: ${d.coverage} / 회사 전체: ${d.company_coverage}`,'subtle'));if(d.sales_status==='unavailable'){main.append(el('div','상담 권한: 영업실적을 제공하지 않습니다.','empty'));return;}const table=el('table'),head=el('tr');for(const h of ['브랜드','단계','담당자 UUID','건수','금액'])head.append(el('th',h));table.append(head);for(const g of d.groups){const tr=el('tr');for(const v of [g.brand||'미지정',g.stage_code,g.owner_id,g.count,money(g.amount)])tr.append(el('td',String(v)));table.append(tr);}main.append(table);}
function list(main,k){const result=k==='deal'?data.deals:data.inquiries;if(k==='deal'&&profile.permission_role==='consultation'){main.append(el('div','상담 권한은 Pipeline·금액·공종에 접근할 수 없습니다.','empty'));return;}main.append(el('p',`조회 상태: ${result.coverage} · ${result.rows.length}건${result.has_more?' (추가 페이지 있음)':''}`,'subtle'));if(result.has_more)main.append(btn('다음 페이지 더 보기',async()=>{try{const next=contract(await client.rpc(k==='deal'?'crm_deals_scoped_v2':'crm_inquiries_scoped_v2',{p_after:result.rows.at(-1).id}));result.rows.push(...next.rows);result.coverage=next.coverage;result.has_more=next.has_more;render();}catch(e){fail(e);}}));const rows=el('div',undefined,'list');for(const r of result.rows){const info=el('div');append(info,el('strong',r.site_name||'현장명 없음'),el('small',`${r.owner_name||'미배정'} · ${k==='deal'?r.stage_code+' · '+money(r.amount)+'원':r.status||'접수'}`),el('p',r.id,'mono'));const open=btn('열기',()=>{selected=r.id;render();});open.setAttribute('aria-label',r.id+' 열기');const row=append(el('article',undefined,'row'),info,open);row.dataset.objectId=r.id;rows.append(row);}main.append(rows);if(!result.rows.length)main.append(el('div','허용된 데이터가 없습니다.','empty'));const r=result.rows.find(x=>x.id===selected);if(r)detail(main,k,r);}
function operation(parent,title,fields,run){const details=el('details');details.append(el('summary',title));const f=el('form');const values=fields(f);const save=el('button',title+' 저장','primary');save.type='submit';f.append(save);f.addEventListener('submit',e=>{e.preventDefault();run(values);});details.append(f);parent.append(details);}
function detail(main,k,r){const box=el('section',undefined,'detail');box.dataset.detailId=r.id;append(box,el('h2',r.site_name),el('p',r.id,'mono'),el('p',k==='deal'?`Version ${r.version} · 공종 ${r.work_summary||r.primary_work||'미지정'}`:`${r.contact_name||''} · ${r.phone||''} · ${r.address||''}`,'subtle'));if(k==='inquiry'){append(box,el('p',r.content||'문의 내용 없음'),el('p',`최초 응대: ${r.first_response_at||'미응대'} / 최근 응대: ${r.responded_at||'없음'}`,'subtle'));}if(k==='deal')box.append(btn('연락처 확인',async()=>{try{const c=await client.rpc('crm_contacts_scoped_v2',{p_opportunity_id:r.id});box.append(el('p',JSON.stringify(c),'subtle'));}catch(e){fail(e);}}));if(!r.can_write){box.append(el('div','이 객체는 조회만 승인되었습니다.','notice'));main.append(box);return;}
const common=()=>({p_kind:k,p_id:r.id,p_token:token(k,r)});
if(k==='inquiry'){
operation(box,'응대 기록',f=>[input(f,'응대 내용','textarea')],([n])=>mutate('crm_inquiry_response_scoped_v2',{p_id:r.id,p_token:token(k,r),p_note:n.value}));
operation(box,'문의 상태',f=>[select(f,'새 상태',['접수','배정완료','응대중','전화응대 완료','현장방문예정','견적진행','종료'].map(x=>[x,x])),input(f,'상태 변경 사유')],([s,n])=>mutate('crm_inquiry_status_scoped_v2',{p_id:r.id,p_token:token(k,r),p_status:s.value,p_reason:n.value}));
}else{
operation(box,'단계 변경',f=>[select(f,'새 단계',['first_contact','consulting','sent','rapport','silent','waiting','compete','imminent','bidding','contract','construction','completion','won','lost','badfit','badfit_lead','badfit_pipe','nocontact'].map(x=>[x,x])),input(f,'단계 변경 사유')],([s,n])=>mutate('crm_deal_stage_scoped_v2',{p_id:r.id,p_version:r.version,p_stage:s.value,p_reason:n.value}));
operation(box,'금액 변경',f=>[input(f,'새 금액','number',r.amount||'0'),input(f,'금액 변경 사유')],([a,n])=>mutate('crm_deal_amount_scoped_v2',{p_id:r.id,p_version:r.version,p_amount:a.value,p_reason:n.value}));
operation(box,'공종 변경',f=>[input(f,'대표 공종','text',r.primary_work||''),input(f,'공종 목록 (쉼표 구분)'),input(f,'공종 변경 사유')],([w,items,reason])=>mutate('crm_work_set_scoped_v2',{p_opportunity_id:r.id,p_primary_work:w.value,p_work_items:items.value.split(',').map(s=>s.trim()).filter(Boolean),p_reason:reason.value,p_expected_version:r.version}));
}
operation(box,'활동 기록',f=>[select(f,'활동 유형',['전화','미팅','업무','메모'].map(x=>[x,x])),input(f,'활동 내용','textarea')],([t,n])=>mutate('crm_activity_add_scoped_v2',{...common(),p_type:t.value,p_note:n.value}));
operation(box,'Next 등록',f=>[select(f,'Next 유형',['전화','미팅','업무','후속확인'].map(x=>[x,x])),input(f,'Next 제목'),input(f,'예정 시각 (로컬 시간)','datetime-local')],([t,n,d])=>{if(!d.value){fail(Error('예정 시각을 입력하세요.'));return;}mutate('crm_next_add_scoped_v2',{...common(),p_type:t.value,p_title:n.value,p_due:new Date(d.value).toISOString()});});
if(r.can_assign)box.append(btn('담당자 변경 준비',async()=>{try{const targets=await client.rpc('crm_assignment_targets_scoped_v2',{p_kind:k,p_id:r.id});operation(box,'담당자 변경',f=>[select(f,'새 담당자 UUID',targets.map(t=>[t.user_id,t.name+' · '+t.user_id])),input(f,'담당자 변경 사유')],([t,n])=>mutate('crm_assign_scoped_v2',{...common(),p_target:t.value,p_reason:n.value}));}catch(e){fail(e);}}));main.append(box);}
function today(main){const t=data.today;main.append(el('p',`${t.day} · Asia/Seoul · ${t.coverage} · 최근 활동 최대 30건`,'subtle'));const missed=el('section');missed.append(el('h2','미응대 문의'));for(const q of t.unresponded)missed.append(el('p',`${q.site_name} · inquiry · ${q.id}`));if(!t.unresponded.length)missed.append(el('p','미응대 없음','subtle'));main.append(missed);for(const [bucket,title]of [['overdue','기한 초과'],['today','오늘 할 일'],['upcoming','예정된 Next']]){main.append(el('h2',title));for(const a of t.tasks.filter(x=>x.bucket===bucket)){const r=(a.entity_kind==='deal'?data.deals:data.inquiries).rows.find(x=>x.id===a.object_id);const row=append(el('article',undefined,'row'),append(el('div'),el('strong',a.title),el('p',a.entity_kind+' · '+a.object_id,'mono'),el('small',a.due_at)));row.dataset.actionId=a.id;if(r?.can_write)row.append(btn('완료',()=>mutate('crm_next_complete_scoped_v2',{p_action_id:a.id,p_token:token(a.entity_kind,r)})));main.append(row);}}main.append(el('h2','최근 활동'));for(const a of t.recent_activity)main.append(append(el('article',undefined,'row'),append(el('div'),el('strong',a.action+' · '+a.actor_name),el('p',a.reason),el('small',a.entity_kind+' · '+a.object_id))));}
render();
})();
