(function(root){
'use strict';
let actor='',expanded=false;
const h=v=>root.esc(String(v??''));
function state(){const id=String(root.ME?.id||root.ME?.name||'');if(actor!==id||!root.G.salesScope){actor=id;root.G.salesScope={type:'all',owner:'전체',organization:'all',assignment:'all'};}return root.G.salesScope;}
function people(){return (root.SALES_PEOPLE_MASTER||[]).filter(p=>p.active&&p.salesRep&&p.performanceIncluded&&(p.employeeType==='INTERNAL'||p.employeeType==='EXTERNAL'&&p.analysisIncluded));}
function candidates(){const f=state();return people().filter(p=>(f.type==='all'||p.employeeType===f.type)&&(f.organization==='all'||p.team===f.organization));}
function change(key,value){const f=state();f[key]=value;if(key!=='owner'&&(f.assignment==='unassigned'||!candidates().some(p=>p.name===f.owner)))f.owner='전체';if(key==='owner'&&value!=='전체')f.assignment='assigned';if(root.G.insights)root.G.insights.owner=f.owner;root.G.rep=f.owner;}
function matches(owner,item){const f=state(),p=root.repProfile(owner),unassigned=!owner||owner==='미배정'||p.role==='branch_pool';if(f.owner!=='전체'&&owner!==f.owner)return false;if(f.assignment==='assigned'&&unassigned||f.assignment==='unassigned'&&!unassigned)return false;if(unassigned){const team=p.role==='branch_pool'?p.team:item?.owner_group||item?.assignment_group||item?.branch_code||'';return f.type==='all'&&(f.organization==='all'||team===f.organization);}return candidates().some(x=>x.name===owner);}
function controls(){const f=state(),names=candidates(),option=(v,t,selected)=>'<option value="'+h(v)+'"'+(v===selected?' selected':'')+'>'+h(t)+'</option>';return '<section class="sales-scope" aria-label="영업 담당 범위"><div class="sales-type" role="group" aria-label="담당자 구분">'+[['all','전체'],['INTERNAL','내부직원'],['EXTERNAL','외부직원']].map(([v,t])=>'<button type="button" data-sales-type="'+v+'" aria-pressed="'+(f.type===v)+'">'+t+'</button>').join('')+'</div><div class="sales-scope-fields"><label>담당자<select aria-label="담당자" data-sales-scope="owner">'+option('전체',f.type==='INTERNAL'?'전체 내부직원':f.type==='EXTERNAL'?'전체 외부직원':'전체 담당자',f.owner)+[['INTERNAL','내부직원'],['EXTERNAL','외부직원']].map(([v,t])=>'<optgroup label="'+t+'">'+names.filter(p=>p.employeeType===v).map(p=>option(p.name,p.name,f.owner)).join('')+'</optgroup>').join('')+'</select></label><label>소속<select aria-label="소속" data-sales-scope="organization">'+[['all','전체 조직'],['head_office','본사'],['external','외부영업'],['gyeongnam','경남지사']].map(([v,t])=>option(v,t,f.organization)).join('')+'</select></label><label>배정상태<select aria-label="배정상태" data-sales-scope="assignment">'+[['all','전체'],['assigned','배정'],['unassigned','미배정']].map(([v,t])=>option(v,t,f.assignment)).join('')+'</select></label></div></section>';}
function sidebar(){const admin=!!root.ME&&(root.Phase1?.profile?.allowed_modes?root.Phase1.profile.allowed_modes.includes('admin'):root.todayIsAdmin());document.querySelectorAll('.menu [data-admin-nav]').forEach(el=>el.hidden=!admin);const parent=document.querySelector('.menu [data-p="dash"]');if(!parent||!root.B)return;state();let nav=document.getElementById('sales-analysis-menu');if(!nav){nav=document.createElement('nav');nav.id='sales-analysis-menu';nav.setAttribute('aria-label','영업 대시보드 하위 메뉴');parent.after(nav);parent.setAttribute('role','button');parent.tabIndex=0;parent.onclick=()=>{if(root.G.page==='dash'){expanded=!expanded;sidebar();}else{expanded=true;root.goPage('dash');}};parent.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();parent.click();}};}
const active=['dash','control','perf'].includes(root.G.page);if(active&&root.G.page!=='dash')expanded=true;parent.classList.toggle('sales-parent-active',active);parent.classList.remove('on');parent.setAttribute('aria-expanded',String(expanded));parent.setAttribute('aria-controls',nav.id);nav.hidden=!expanded;nav.innerHTML=[['dash','전체 현황'],['control','컨트롤타워'],['perf','성과 분석']].map(([p,t])=>'<button type="button" data-sales-page="'+p+'"'+(root.G.page===p?' class="selected" aria-current="page"':'')+'>'+t+'</button>').join('');nav.onclick=e=>{const b=e.target.closest('[data-sales-page]');if(b){expanded=true;root.goPage(b.dataset.salesPage);}};document.querySelectorAll('.menu>.mi[data-p="control"],.menu>.mi[data-p="perf"]').forEach(e=>e.hidden=true);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-sales-type]');if(!b)return;change('type',b.dataset.salesType);if(root.G.insights)root.G.insights.page=1;if(root.G.pipelineQueue)root.G.pipelineQueue.page=1;root.paint();});
document.addEventListener('change',e=>{const key=e.target.dataset.salesScope;if(!key)return;change(key,e.target.value);if(root.G.insights)root.G.insights.page=1;if(root.G.pipelineQueue)root.G.pipelineQueue.page=1;root.paint();});
root.addEventListener('phase1:identity-cleared',()=>{actor='';expanded=false;root.G.salesScope=null;document.querySelectorAll('.menu [data-admin-nav]').forEach(el=>el.hidden=true);document.getElementById('sales-analysis-menu')?.replaceChildren();});
root.SalesScope={state,people,candidates,change,matches,controls,sidebar};
})(window);
