'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8');
const personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),deal=s.uid(6,1),auth=s.mapping.accounts[0].auth_uid;
const rid=n=>`f6090600-0060-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());return db;}
async function write(db,account,op,id,version,payload,request){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[request,op,id,version,JSON.stringify(payload)])).rows[0].a;}
test('next action completion chains after operational source and is atomic',async t=>{const db=await setup();try{
 const created=await write(db,0,'next_action',deal,1,{type:'전화',text:'견적 회신 확인',due_at:'2026-09-12'},rid(1));
 await t.test('server UUID completes one action and creates one activity/audit',async()=>{const ack=await write(db,0,'next_action_complete',deal,2,{action_id:created.next_action_id},rid(2));assert.equal(ack.actor_auth_uid,auth);assert.equal(ack.version,3);assert.equal(ack.next_action_id,created.next_action_id);const row=(await db.query('SELECT status,completed_at IS NOT NULL done FROM public.next_actions WHERE id=$1',[created.next_action_id])).rows[0];assert.deepEqual(row,{status:'completed',done:true});assert.deepEqual((await db.query('SELECT next_action,next_action_date,version FROM public.deals WHERE id=$1',[deal])).rows[0],{next_action:null,next_action_date:null,version:3});assert.equal((await db.query("SELECT count(*)::int n FROM public.activities WHERE deal_id=$1 AND type='다음 행동 완료'",[deal])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='next_action_complete'",[deal])).rows[0].n,1);});
 await t.test('replay is exact and changed reuse creates no duplicates',async()=>{const replay=await write(db,0,'next_action_complete',deal,2,{action_id:created.next_action_id},rid(2));assert.equal(replay.replayed,true);await assert.rejects(write(db,0,'next_action_complete',deal,2,{action_id:s.uid(10,1)},rid(2)),e=>e.code==='PT409');assert.equal((await db.query("SELECT count(*)::int n FROM public.activities WHERE deal_id=$1 AND type='다음 행동 완료'",[deal])).rows[0].n,1);});
 await t.test('stale, already-completed, foreign scope and direct helper access fail',async()=>{await assert.rejects(write(db,0,'next_action_complete',deal,2,{action_id:created.next_action_id},rid(3)),e=>e.code==='PT409');await assert.rejects(write(db,0,'next_action_complete',deal,3,{action_id:created.next_action_id},rid(4)),e=>e.code==='PT409');await assert.rejects(write(db,1,'next_action_complete',deal,3,{action_id:created.next_action_id},rid(5)),e=>e.code==='42501');for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'crm_security.crm_next_action_complete_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('rollback restores quote layer and preserves completed business evidence',async()=>{const db=await setup();try{const created=await write(db,0,'next_action',deal,1,{type:'전화',text:'후속 확인',due_at:'2026-09-12'},rid(8));await write(db,0,'next_action_complete',deal,2,{action_id:created.next_action_id},rid(9));await db.exec(next.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_quote_version_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query('SELECT status FROM public.next_actions WHERE id=$1',[created.next_action_id])).rows[0].status,'completed');assert.equal((await db.query('SELECT count(*)::int n FROM crm_next_complete_archive.command_receipts')).rows[0].n,1);}finally{await db.close();}});
