'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),build=require('./build.cjs');
const deal='f6090500-0006-4000-8000-000000000001',action='f6090600-0060-4000-8000-000000000001';
function load(text,name){const m=new Module(name);m._compile(text,name+'.js');return m.exports;}
function base(extra={}){const queued=[],listeners={},adapter=load(build.adapter(),'next-complete-adapter');const root={OperationalAdapter:adapter,TOKEN:'jwt',ME:{id:'u'},WRITE_Q:[],console,B:{deals:[]},Phase1:{read:async()=>({data:{deals:[],inquiries:[]}}),queue:{list:()=>[],enqueue:(op,id,version,payload)=>{const c=adapter.normalize(op,id,version,payload),q={...c,payload:c.payload,request_id:'f6090600-0060-4000-8000-000000000099'};queued.push(q);return q;},flush:async()=>{}}},addEventListener:(n,fn)=>{listeners[n]=fn},...extra};return {root,queued,ui:load(build.overlay(),'next-complete-overlay')};}
test('PC Today converts legacy text/due payload to the captured server UUID and absorbs activity',()=>{const d={id:deal,nextActionObj:{id:action,type:'전화',text:'후속 확인',due:'2026-09-12'}};const x=base({B:{deals:[d]},dealKey:v=>v.id,itemPatch:()=>({}),actionObj:v=>v.nextActionObj,todoDone(k){this.pushWrite('activity',{opportunity_id:k,type:'완료',note:'완료',occurred_at:new Date().toISOString()});this.pushWrite('next_action_complete',{opportunity_id:k,text:'후속 확인',due_at:'2026-09-12',at:'client'});}});const state=x.ui.install(x.root);state.versions.set(deal,4);x.root.todoDone(deal);assert.equal(x.queued.length,1);assert.equal(x.queued[0].operation,'next_action_complete');assert.deepEqual(x.queued[0].payload,{action_id:action});});
test('PC detail adds its missing server write after the existing local completion',()=>{const d={id:deal,nextActionObj:{id:action,text:'후속 확인'}};let local=0;const x=base({CUR_DETAIL:{kind:'deal',item:d},itemPatch:()=>({}),actionObj:v=>v.nextActionObj,completeNextAction(){local++;}});const state=x.ui.install(x.root);state.versions.set(deal,7);x.root.completeNextAction();assert.equal(local,1);assert.equal(x.queued.length,1);assert.equal(x.queued[0].payload.action_id,action);});
test('mobile Today uses the read UUID and absorbs its derived Activity',()=>{const d={id:deal,nextAction:{id:action,type:'전화',text:'확인',due_at:'2026-09-12'}};const x=base({todayDeal:()=>d,execNextM:v=>v.nextAction,G:{_today:[{ref:deal}]},completeNextAction(v){this.pushWrite('next_action_complete',{opportunity_id:v.id,action_id:v.nextAction.id});},addActivity(v){this.pushWrite('activity',{opportunity_id:v.id,type:'완료',note:'완료',occurred_at:new Date().toISOString()});},todayCompleteM(i){const v=this.todayDeal(i);this.completeNextAction(v);this.addActivity(v);}});const state=x.ui.install(x.root);state.versions.set(deal,9);x.root.todayCompleteM(0);assert.equal(x.queued.length,1);assert.equal(x.queued[0].payload.action_id,action);});
test('completion outside named handlers fails closed',()=>{const x=base();x.ui.install(x.root);assert.throws(()=>x.root.pushWrite('next_action_complete',{opportunity_id:deal,action_id:action}),/NEXT_ACTION_ID_REQUIRED/);});
