'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),close=require('../../pipeline-close-nonwon/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),thirteen=close.thirteen;
const fourteen=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text]))`;
const helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');
function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function adapter(){let text=close.adapter();const ops="'stage_check','transition','close']";one(text,ops,'amount adapter operations');text=text.replace(ops,"'stage_check','transition','close','amount']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'amount normalize marker');
 const fn=" function normalizeAmount(objectId,payload){const allowed=['opportunity_id','amount','quote_amount','won_amount'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||payload.won_amount!=null||!Number.isSafeInteger(payload.amount)||payload.amount<0||(payload.quote_amount!=null&&(!Number.isSafeInteger(payload.quote_amount)||payload.quote_amount<=0)))fail('AMOUNT_INTENT_NOT_CONNECTED');return {amount:payload.amount,quote_amount:payload.quote_amount==null?null:payload.quote_amount,won_amount:null};}\n";text=text.replace(marker,fn+marker);
 const dispatch="else if(operation==='transition')normalized=normalizeTransition(objectId,payload);else normalized=normalizeClose(objectId,payload);";one(text,dispatch,'amount dispatch');text=text.replace(dispatch,"else if(operation==='transition')normalized=normalizeTransition(objectId,payload);else if(operation==='close')normalized=normalizeClose(objectId,payload);else normalized=normalizeAmount(objectId,payload);");
 const ack="  if(command.operation==='amount'&&(ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||ack.amount!==command.payload.amount||ack.quote_amount!==command.payload.quote_amount||ack.won_amount!==null||!UUID.test(ack.audit_event_id)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','amount ACK return');return text.replace('  return ack;}',ack+'  return ack;}');}
function overlay(){let text=close.overlay();const connected="'stage_check','transition','close']";one(text,connected,'amount overlay connected');text=text.replace(connected,"'stage_check','transition','close','amount']");
 const closeAck="  function applyCloseAck(q){const a=q.ack;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.outcome=a.outcome;d.lifecycle_status='closed';d.closed_at=a.closed_at;d.stage_contexts=d.stageContexts=a.stage_contexts;d.lost_reason=a.lost_reason;d.lost_kind=a.lost_kind;d.badfit_type=a.badfit_type;d.nextAction=d.nextActionObj=null;if(Array.isArray(d.stageHistory))d.stageHistory.push({id:a.stage_history_id,from:a.from_stage,to:a.outcome,at:a.closed_at});}}";one(text,closeAck,'amount ACK marker');text=text.replace(closeAck,closeAck+"\n  function applyAmountAck(q){const a=q.ack;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.amount=d.amt=a.amount;d.quote_amount=d.quoteAmt=a.quote_amount;}} ");
 const sync="if(q.operation==='close')applyCloseAck(q);";one(text,sync,'amount ACK sync');text=text.replace(sync,sync+"if(q.operation==='amount')applyAmountAck(q);");
 const pc="return {...d,opportunity_id:d.id,code:d.stage_code,currentBusiness:d.brand,current_business:d.brand,nextActionObj:n,nextAction:n,stageContexts:d.stage_contexts||{},stageHistory:d.stage_history||[]};";one(text,pc,'PC amount aliases');text=text.replace(pc,"return {...d,opportunity_id:d.id,code:d.stage_code,currentBusiness:d.brand,current_business:d.brand,amt:d.amount??0,quoteAmt:d.quote_amount??0,quoteVersions:d.quote_versions||[],nextActionObj:n,nextAction:n,stageContexts:d.stage_contexts||{},stageHistory:d.stage_history||[]};");
 const mobile="nm:'\\uD604\\uC7A5\\uBA85 \\uBBF8\\uC81C\\uACF5',rep:'',code:d.stage_code||'first_contact',sub:d.brand||''";one(text,mobile,'mobile amount aliases');text=text.replace(mobile,"nm:'\\uD604\\uC7A5\\uBA85 \\uBBF8\\uC81C\\uACF5',rep:'',code:d.stage_code||'first_contact',amt:d.amount??0,quote_amount:d.quote_amount??0,quote_versions:d.quote_versions||[],sub:d.brand||''");
 return text;}
function applySql(){return `SET crm.expected_amount_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.expected_amount_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu'
 OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb)') IS NULL OR to_regclass('crm_security.deal_close_events') IS NULL OR to_regclass('crm_security.quote_versions') IS NULL
 OR to_regprocedure('crm_security.crm_write_command_v2_close_nonwon_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL
 OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${thirteen}$expected$
 THEN RAISE EXCEPTION 'expected amount after-close prerequisite drift';END IF;END $guard$;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_close_nonwon_20260906;ALTER FUNCTION public.crm_write_command_v2_close_nonwon_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;
REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_close_nonwon_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount'));
${helper()}
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN IF p_operation='amount' THEN RETURN crm_security.crm_deal_expected_amount_command_v1(p_request_id,p_object_id,p_expected_version,p_payload);END IF;RETURN crm_security.crm_write_command_v2_close_nonwon_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ BEGIN IF has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fourteen}$expected$ THEN RAISE EXCEPTION 'expected amount post-apply drift';END IF;END $post$;
COMMIT;`}
function rollbackSql(){return `SET crm.expected_amount_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.expected_amount_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_close_nonwon_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)') IS NULL OR to_regnamespace('crm_expected_amount_archive') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fourteen}$expected$ THEN RAISE EXCEPTION 'expected amount rollback drift';END IF;END $guard$;
CREATE SCHEMA crm_expected_amount_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_expected_amount_archive FROM PUBLIC,anon,authenticated,service_role;CREATE TABLE crm_expected_amount_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation='amount';REVOKE ALL ON crm_expected_amount_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;
DELETE FROM crm_security.command_receipts WHERE operation='amount';DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb);
ALTER FUNCTION crm_security.crm_write_command_v2_close_nonwon_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_close_nonwon_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${thirteen}$expected$ THEN RAISE EXCEPTION 'expected amount rollback verification drift';END IF;END $post$;COMMIT;`}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-close.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-close.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-close.sql','rollback-after-close.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_CLOSE_NOT_APPLIED',prerequisites:['pipeline-close-nonwon/20260906'],operation:'amount',intent:'expected_amount_only',quote_amount_semantics:'latest_quote_concurrency_snapshot',won_amount_semantics:'must_be_null',blocked_meanings:['direct_quote_amount_edit','won_amount_edit','closed_deal_amount_edit'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),golden_mobile:sha(fs.readFileSync(path.join(root,'mobile.html'))),issue_modal:sha(fs.readFileSync(path.join(root,'issue-modal.js'))),quote_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-quote-version/20260906/manifest.json'))),close_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-close-nonwon/20260906/manifest.json')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,build,thirteen,fourteen};
