'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('../../pipeline-stage-check/20260906/build.cjs'),transition=require('../../pipeline-transition/20260906/build.cjs'),close=require('../../pipeline-close-nonwon/20260906/build.cjs'),amount=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),deal=s.uid(6,1),auth=s.mapping.accounts[0].auth_uid;
const rid=n=>`f6090600-0091-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());await db.exec(transition.applySql());await db.exec(close.applySql());await db.exec(amount.applySql());return db;}
async function write(db,account,version,payload,request,op='amount'){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[request,op,deal,version,JSON.stringify(payload)])).rows[0].a;}
const p=(value,quoteAmount=null)=>({amount:value,quote_amount:quoteAmount,won_amount:null});
test('expected amount is actor-scoped, versioned and separated from quote/won truth',async t=>{const db=await setup();try{
 await t.test('zero clears expected amount without inventing unknown reason',async()=>{const ack=await write(db,0,1,p(0),rid(1));assert.equal(ack.actor_auth_uid,auth);assert.equal(ack.amount,0);assert.equal(ack.quote_amount,null);assert.equal(ack.won_amount,null);const row=(await db.query('SELECT amount,amount_unknown_reason,version FROM public.deals WHERE id=$1',[deal])).rows[0];assert.deepEqual(row,{amount:0,amount_unknown_reason:null,version:2});assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='amount'",[deal])).rows[0].n,1);});
 await t.test('latest append-only quote is a required snapshot and remains untouched',async()=>{await write(db,0,2,{amount:120000000,reason:'범위 확정'},rid(2),'quote_version');await assert.rejects(write(db,0,3,p(88000000,null),rid(3)),e=>e.code==='PT409');const ack=await write(db,0,3,p(88000000,120000000),rid(4));assert.equal(ack.amount,88000000);assert.equal(ack.quote_amount,120000000);assert.equal((await db.query('SELECT amount FROM crm_security.quote_versions WHERE deal_id=$1',[deal])).rows[0].amount,120000000);});
 await t.test('replay is exact; reuse, stale, foreign scope, won field and closed state fail',async()=>{const replay=await write(db,0,3,p(88000000,120000000),rid(4));assert.equal(replay.replayed,true);await assert.rejects(write(db,0,3,p(88000001,120000000),rid(4)),e=>e.code==='PT409');await assert.rejects(write(db,0,3,p(1,120000000),rid(5)),e=>e.code==='PT409');await assert.rejects(write(db,1,4,p(1,120000000),rid(6)),e=>e.code==='42501');await assert.rejects(write(db,0,4,{amount:1,quote_amount:120000000,won_amount:1},rid(7)),e=>e.code==='22023');await db.exec("UPDATE public.deals SET lifecycle_status='closed',outcome='lost' WHERE id='"+deal+"'");await assert.rejects(write(db,0,4,p(1,120000000),rid(8)),e=>e.code==='PT409');assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='amount'",[deal])).rows[0].n,2);for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('injected audit failure rolls back amount and version',async()=>{const db=await setup();try{await db.exec("CREATE FUNCTION pg_temp.fail_amount_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='amount' THEN RAISE EXCEPTION 'injected';END IF;RETURN NEW;END$$;CREATE TRIGGER fail_amount_audit BEFORE INSERT ON crm_security.audit_events FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_amount_audit();");await assert.rejects(write(db,0,1,p(99),rid(20)),/injected/);assert.deepEqual((await db.query('SELECT amount,version FROM public.deals WHERE id=$1',[deal])).rows[0],{amount:10000,version:1});assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE object_id=$1 AND operation='amount'",[deal])).rows[0].n,0);}finally{await db.close();}});
test('rollback restores close layer and privately archives amount receipts',async()=>{const db=await setup();try{await write(db,0,1,p(99),rid(30));await db.exec(amount.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query('SELECT count(*)::int n FROM crm_expected_amount_archive.command_receipts')).rows[0].n,1);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)') IS NULL dropped")).rows[0].dropped,true);}finally{await db.close();}});
