'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),reclassify=require('../../inquiry-reclassify/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),sixteen=reclassify.sixteen;
const seventeen=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text, 'waiting_context'::text, 'inquiry_reclassify'::text, 'inquiry_status'::text]))`;
const auditBefore=reclassify.auditAfter;
const auditAfter=`CHECK (action = ANY (ARRAY['direct_assign'::text, 'direct_reassign'::text, 'inquiry_unassign'::text, 'inquiry_reclassify'::text, 'inquiry_hold'::text]))`;
const helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');
function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function sourceFragment(){
 let fn=reclassify.sourceFragment();
 const old=`coalesce((SELECT jsonb_agg(jsonb_build_object('id',e.event_id,'type','데이터정리','note',coalesce(e.before_data->>'brand','기술자문')||' → '||coalesce(e.after_data->>'brand',''),'result','정상 견적문의로 재분류','at',e.created_at,'actor',e.after_data->>'reviewed_by') ORDER BY e.created_at,e.event_id) FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_reclassify'),'[]'::jsonb) AS activities`;
 one(fn,old,'reclassify activity projection');
 const next=`(SELECT e.after_data->>'hold_reason' FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_hold' ORDER BY e.created_at DESC,e.event_id DESC LIMIT 1) AS hold_reason,
    (SELECT e.created_at FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_hold' ORDER BY e.created_at DESC,e.event_id DESC LIMIT 1) AS held_at,
    (SELECT e.after_data->>'held_by' FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_hold' ORDER BY e.created_at DESC,e.event_id DESC LIMIT 1) AS held_by,
    coalesce((SELECT jsonb_agg(jsonb_build_object('id',e.event_id,'type','데이터정리','note',coalesce(e.before_data->>'brand','기술자문')||' → '||coalesce(e.after_data->>'brand',''),'result','정상 견적문의로 재분류','at',e.created_at,'actor',e.after_data->>'reviewed_by') ORDER BY e.created_at,e.event_id) FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_reclassify'),'[]'::jsonb)
    ||coalesce((SELECT jsonb_agg(jsonb_build_object('id',e.event_id,'type','상태변경','note','보류','result',e.reason,'at',e.created_at,'actor',e.after_data->>'held_by') ORDER BY e.created_at,e.event_id) FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_hold'),'[]'::jsonb) AS activities`;
 return fn.replace(old,next);
}
function adapter(){
 let text=reclassify.adapter();
 const ops="'waiting_context','inquiry_reclassify']";one(text,ops,'adapter operations');text=text.replace(ops,"'waiting_context','inquiry_reclassify','inquiry_status']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'normalize marker');
 text=text.replace(marker," function normalizeHold(objectId,payload){const allowed=['inquiry_id','from_status','to_status','reason','changed_by','at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.inquiry_id!==objectId||payload.to_status!=='보류'||typeof payload.reason!=='string'||!payload.reason.trim()||payload.reason.length>2000)fail('INQUIRY_STATUS_INTENT_NOT_CONNECTED');return {intent:'hold',reason:payload.reason.trim()};}\n"+marker);
 const sentinel="['inquiry_assign','inquiry_unassign','inquiry_reclassify','favorite_set','opportunity_touch'].includes(operation)";one(text,sentinel,'sentinel operations');text=text.replace(sentinel,"['inquiry_assign','inquiry_unassign','inquiry_reclassify','inquiry_status','favorite_set','opportunity_touch'].includes(operation)");
 const dispatch="else if(operation==='waiting_context')normalized=normalizeWaiting(objectId,payload);else normalized=normalizeReclassify(objectId,payload);";one(text,dispatch,'adapter dispatch');text=text.replace(dispatch,"else if(operation==='waiting_context')normalized=normalizeWaiting(objectId,payload);else if(operation==='inquiry_reclassify')normalized=normalizeReclassify(objectId,payload);else normalized=normalizeHold(objectId,payload);");
 const ack="  if(command.operation==='inquiry_status'&&(ack.intent!=='hold'||ack.to_status!=='보류'||ack.hold_reason!==command.payload.reason||typeof ack.from_status!=='string'||typeof ack.held_at!=='string'||typeof ack.held_by!=='string'||!UUID.test(ack.inquiry_audit_event_id)))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','ACK return');return text.replace('  return ack;}',ack+'  return ack;}');
}
function overlay(){
 let text=reclassify.overlay();
 const connected="'waiting_context','inquiry_reclassify']";one(text,connected,'overlay connected');text=text.replace(connected,"'waiting_context','inquiry_reclassify','inquiry_status']");
 const state='reclassifyIntent=false;const versions';one(text,state,'overlay state');text=text.replace(state,'reclassifyIntent=false,holdIntent=false;const versions');
 const marker='  function syncQueue(){';one(text,marker,'queue marker');
 const apply="  function applyHoldAck(q){const a=q.ack;for(const rows of [root.B&&root.B.inquiries,root.INQUIRIES])if(Array.isArray(rows))for(const i of rows)if(String(i.id||i.inquiry_id)===String(q.object_id)){i.status='보류';i.hold_reason=a.hold_reason;i.held_at=a.held_at;i.held_by=a.held_by;i.activities=Array.isArray(i.activities)?i.activities:[];let h=i.activities.find(x=>!x.id&&x.type==='상태변경'&&x.note==='보류'&&x.result===a.hold_reason);if(h)Object.assign(h,{id:a.inquiry_audit_event_id,at:a.held_at,actor:a.held_by});else if(!i.activities.some(x=>x.id===a.inquiry_audit_event_id))i.activities.push({id:a.inquiry_audit_event_id,type:'상태변경',note:'보류',result:a.hold_reason,at:a.held_at,actor:a.held_by});}}\n";
 text=text.replace(marker,apply+marker);
 const sync="if(q.operation==='inquiry_reclassify')applyReclassifyAck(q);";one(text,sync,'queue sync');text=text.replace(sync,sync+"if(q.operation==='inquiry_status')applyHoldAck(q);");
 const push='root.pushWrite=function(op,payload){';one(text,push,'push marker');text=text.replace(push,push+"if(op==='inquiry_status'&&!holdIntent)throw error('INQUIRY_STATUS_INTENT_NOT_CONNECTED');");
 const wrapper="  if(typeof root.inqTechReclassify==='function'){const original=root.inqTechReclassify;root.inqTechReclassify=function(){const previous=reclassifyIntent;reclassifyIntent=true;try{return original.apply(this,arguments);}finally{reclassifyIntent=previous;}};}";one(text,wrapper,'wrapper marker');
 text=text.replace(wrapper,wrapper+"\n  if(typeof root.inqCtlConfirmReason==='function'){const original=root.inqCtlConfirmReason;root.inqCtlConfirmReason=function(){const previous=holdIntent;holdIntent=!!(root.INQ_CTL_MODAL&&root.INQ_CTL_MODAL.mode==='hold');try{return original.apply(this,arguments);}finally{holdIntent=previous;}};}");
 return text;
}
function applySql(){return `SET crm.inquiry_hold_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.inquiry_hold_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_v1(text,uuid,integer)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_reclassify_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_inquiry_hold_20260906(text,uuid,integer)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_hold_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${sixteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry hold after-reclassify prerequisite drift';END IF;END $guard$;
CREATE TEMP TABLE inquiry_hold_source_guard AS SELECT p.oid,p.prosrc,p.proconfig,coalesce(p.proacl::text,'') acl FROM pg_proc p WHERE p.oid='public.crm_operational_source_v1(text,uuid,integer)'::regprocedure;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_inquiry_reclassify_20260906;ALTER FUNCTION public.crm_write_command_v2_inquiry_reclassify_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_inquiry_reclassify_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) RENAME TO crm_operational_source_fragment_pre_inquiry_hold_20260906;REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_pre_inquiry_hold_20260906(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign','inquiry_reclassify','inquiry_hold'));
${helper()}
${sourceFragment()}
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN IF p_operation='inquiry_status' THEN IF p_expected_version IS DISTINCT FROM 0 THEN RAISE EXCEPTION 'invalid inquiry status version sentinel' USING ERRCODE='22023';END IF;RETURN crm_security.crm_inquiry_hold_command_v1(p_request_id,p_object_id,p_payload);END IF;RETURN crm_security.crm_write_command_v2_inquiry_reclassify_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ DECLARE changed integer;BEGIN SELECT count(*) INTO changed FROM inquiry_hold_source_guard g JOIN pg_proc p ON p.oid=g.oid WHERE p.prosrc IS DISTINCT FROM g.prosrc OR p.proconfig IS DISTINCT FROM g.proconfig OR coalesce(p.proacl::text,'') IS DISTINCT FROM g.acl;IF changed<>0 OR has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_inquiry_hold_command_v1(uuid,uuid,jsonb)','EXECUTE') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${seventeen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry hold post-apply drift';END IF;END $post$;COMMIT;`;}
function rollbackSql(){return `SET crm.inquiry_hold_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.inquiry_hold_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_reclassify_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_hold_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_inquiry_hold_20260906(text,uuid,integer)') IS NULL OR to_regnamespace('crm_inquiry_hold_archive') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${seventeen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry hold rollback drift';END IF;END $guard$;
CREATE SCHEMA crm_inquiry_hold_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_inquiry_hold_archive FROM PUBLIC,anon,authenticated,service_role;CREATE TABLE crm_inquiry_hold_archive.audit_events AS SELECT * FROM crm_security.inquiry_audit_events WHERE action='inquiry_hold';CREATE TABLE crm_inquiry_hold_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation='inquiry_status';REVOKE ALL ON crm_inquiry_hold_archive.audit_events,crm_inquiry_hold_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;
UPDATE public.inquiries i SET status=x.before_data->>'status',updated_at=clock_timestamp() FROM (SELECT DISTINCT ON(inquiry_id) inquiry_id,before_data FROM crm_inquiry_hold_archive.audit_events ORDER BY inquiry_id,created_at DESC,event_id DESC)x WHERE i.id=x.inquiry_id AND i.status='보류';
DELETE FROM crm_security.command_receipts WHERE operation='inquiry_status';DELETE FROM crm_security.inquiry_audit_events WHERE action='inquiry_hold';
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_inquiry_hold_command_v1(uuid,uuid,jsonb);ALTER FUNCTION crm_security.crm_write_command_v2_inquiry_reclassify_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DROP FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer);ALTER FUNCTION crm_security.crm_operational_source_fragment_pre_inquiry_hold_20260906(text,uuid,integer) RENAME TO crm_operational_source_fragment_v1;REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign','inquiry_reclassify'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_inquiry_reclassify_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_hold_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${sixteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry hold rollback verification drift';END IF;END $post$;COMMIT;`;}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-reclassify.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-reclassify.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-reclassify.sql','rollback-after-reclassify.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_RECLASSIFY_NOT_APPLIED',prerequisites:['inquiry-reclassify/20260906'],operation:'inquiry_status',intent:'hold_only',blocked_meanings:['technical_inquiry_promote','arbitrary_status_change','hold_release'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),reclassify_manifest:sha(fs.readFileSync(path.join(root,'sql/inquiry-reclassify/20260906/manifest.json'))),inquiry_contracts:sha(fs.readFileSync(path.join(root,'docs/operational-cutover-20260906/inquiry-management-contracts.md')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,sourceFragment,build,sixteen,seventeen,auditBefore,auditAfter};
