'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('../../pipeline-stage-check/20260906/build.cjs'),transition=require('../../pipeline-transition/20260906/build.cjs'),close=require('../../pipeline-close-nonwon/20260906/build.cjs'),amount=require('../../pipeline-amount-expected/20260906/build.cjs'),waiting=require('../../pipeline-waiting-context/20260906/build.cjs'),reclassify=require('../../inquiry-reclassify/20260906/build.cjs'),hold=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),inquiry=s.uid(5,5),admin=s.mapping.accounts[4].auth_uid,assignee=s.fixture.mapped[0].user_id;const rid=n=>`f6090600-0094-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());await db.exec(transition.applySql());await db.exec(close.applySql());await db.exec(amount.applySql());await db.exec(waiting.applySql());await db.exec(reclassify.applySql());await db.exec(hold.applySql());await db.query("UPDATE public.inquiries SET status='접수',assigned_to=$2 WHERE id=$1",[inquiry,assignee]);return db;}
async function write(db,account,reason,request,payload={intent:'hold',reason}){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query("SELECT public.crm_write_command_v2($1,'inquiry_status',$2,0,$3) a",[request,inquiry,JSON.stringify(payload)])).rows[0].a;}
test('inquiry hold is one scoped transaction',async t=>{const db=await setup();try{
 await t.test('status, durable hold audit, receipt and read projection are exact',async()=>{const ack=await write(db,4,'고객 요청 대기',rid(1));assert.equal(ack.actor_auth_uid,admin);assert.equal(ack.from_status,'접수');assert.equal(ack.to_status,'보류');const row=(await db.query('SELECT status,assigned_to FROM public.inquiries WHERE id=$1',[inquiry])).rows[0];assert.equal(row.status,'보류');assert.equal(row.assigned_to,assignee);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_hold'",[inquiry])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE object_id=$1 AND operation='inquiry_status'",[inquiry])).rows[0].n,1);await db.exec(`SET request.jwt.claim.sub='${admin}';`);const data=(await db.query("SELECT public.crm_operational_source_v1('inquiry_core',null,100) a")).rows[0].a,read=data.items.find(x=>x.id===inquiry);assert.equal(read.status,'보류');assert.equal(read.hold_reason,'고객 요청 대기');assert.equal(read.held_by,'TEST ADMIN');assert.equal(read.activities.length,1);assert.equal(read.activities[0].type,'상태변경');});
 await t.test('replay exact; reuse, second hold, promotion and non-admin fail',async()=>{const replay=await write(db,4,'고객 요청 대기',rid(1));assert.equal(replay.replayed,true);await assert.rejects(write(db,4,'다른 사유',rid(1)),e=>e.code==='PT409');await assert.rejects(write(db,4,'새 요청',rid(2)),e=>e.code==='PT409');await assert.rejects(write(db,4,'이관',rid(3),{inquiry_id:inquiry,from_status:'보류',to_status:'영업전환',reason:'이관'}),e=>e.code==='22023');await assert.rejects(write(db,0,'권한 없음',rid(4)),e=>e.code==='42501');assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_hold'",[inquiry])).rows[0].n,1);for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'crm_security.crm_inquiry_hold_command_v1(uuid,uuid,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('late audit failure rolls back inquiry status',async()=>{const db=await setup();try{await db.exec("CREATE FUNCTION pg_temp.fail_hold_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='inquiry_hold' THEN RAISE EXCEPTION 'injected';END IF;RETURN NEW;END$$;CREATE TRIGGER fail_hold_audit BEFORE INSERT ON crm_security.inquiry_audit_events FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_hold_audit();");await assert.rejects(write(db,4,'고객 요청 대기',rid(20)),/injected/);assert.equal((await db.query('SELECT status FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].status,'접수');assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE object_id=$1 AND operation='inquiry_status'",[inquiry])).rows[0].n,0);}finally{await db.close();}});
test('rollback restores prior status and reclassification layer',async()=>{const db=await setup();try{await write(db,4,'고객 요청 대기',rid(30));await db.exec(hold.rollbackSql());assert.equal((await db.query('SELECT status FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].status,'접수');assert.equal((await db.query('SELECT count(*)::int n FROM crm_inquiry_hold_archive.audit_events')).rows[0].n,1);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_inquiry_hold_command_v1(uuid,uuid,jsonb)') IS NULL dropped")).rows[0].dropped,true);}finally{await db.close();}});
