'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),base=require('../../expansion-note-context/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),baseDir=path.resolve(dir,'../../expansion-note-context/20260906'),read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function replaceOne(source,from,to,label){if(!source.includes(from))throw Error('message reminder build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=read(path.join(baseDir,'operational-adapter.candidate.js'));
 source=replaceOne(source,' function normalizeNext(objectId,payload){if(payload&&payload.inquiry_id!==undefined){',` function normalizeMessageReminder(objectId,payload){const allowed=['opportunity_id','intent','type','text','due_at','scheduled_at','channel','template_key','draft_body'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||payload.intent!=='message_reminder'||payload.type!=='메시지발송'||!['sms','kakao'].includes(payload.channel))fail('MESSAGE_REMINDER_INTENT_NOT_CONNECTED');const scheduled=new Date(payload.scheduled_at);if(!Number.isFinite(scheduled.getTime())||scheduled.getTime()<=Date.now())fail('INVALID_MESSAGE_REMINDER_SCHEDULE');const due=date(payload.due_at),kst=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(scheduled);if(due!==kst)fail('MESSAGE_REMINDER_DATE_MISMATCH');return {intent:'message_reminder',type:'메시지발송',text:text(payload.text,1,500,'INVALID_NEXT_TEXT'),due_at:due,scheduled_at:scheduled.toISOString(),channel:payload.channel,template_key:text(payload.template_key,1,100,'INVALID_TEMPLATE_KEY'),draft_body:text(payload.draft_body,1,8000,'INVALID_DRAFT_BODY')};}
 function normalizeNext(objectId,payload){if(payload&&payload.intent==='message_reminder')return normalizeMessageReminder(objectId,payload);if(payload&&payload.inquiry_id!==undefined){`,'normalizer');
 source=replaceOne(source,"if(command.operation==='next_action'&&command.payload.intent!=='inquiry_next_set'&&(","if(command.operation==='next_action'&&!['inquiry_next_set','message_reminder'].includes(command.payload.intent)&&(",'generic ACK exclusion');
 source=replaceOne(source,"  if(command.operation==='next_action'&&command.payload.intent==='inquiry_next_set'",`  if(command.operation==='next_action'&&command.payload.intent==='message_reminder'&&(ack.intent!=='message_reminder'||ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||!UUID.test(ack.next_action_id)||!UUID.test(ack.activity_id)||!UUID.test(ack.audit_event_id)||!Array.isArray(ack.cancelled_action_ids)||ack.due_at!==command.payload.due_at||ack.channel!==command.payload.channel||ack.template_key!==command.payload.template_key||typeof ack.scheduled_at!=='string'||typeof ack.assignee_name!=='string'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='next_action'&&command.payload.intent==='inquiry_next_set'`,'reminder ACK');
 return source;
}
function overlay(){let source=read(path.join(baseDir,'operational-overlay.candidate.js'));
 source=replaceOne(source,"due_at:(d.stage_code==='waiting'&&w.contact_date)||d.next_action.due_at,assignee:d.next_action.assignee_name,status:d.next_action.status","due_at:(d.stage_code==='waiting'&&w.contact_date)||d.next_action.due_at,assignee:d.next_action.assignee_name,status:d.next_action.status,scheduled_at:d.next_action.scheduled_at||null,scheduledAt:d.next_action.scheduled_at||null,channel:d.next_action.channel||null,template_key:d.next_action.template_key||null,templateKey:d.next_action.template_key||null,draft_body:d.next_action.draft_body||null,draftBody:d.next_action.draft_body||null",'read shell');
 source=replaceOne(source,"function applyNextAck(q){const id=q.ack&&q.ack.next_action_id;if(!id)return;","function applyNextAck(q){const id=q.ack&&q.ack.next_action_id;if(!id)return;",'ACK anchor');
 source=replaceOne(source,"if(d.nextAction&&typeof d.nextAction==='object')d.nextAction.id=id;}","if(d.nextAction&&typeof d.nextAction==='object')d.nextAction.id=id;if(q.payload.intent==='message_reminder'){const n=d.nextActionObj||(d.nextAction&&typeof d.nextAction==='object'?d.nextAction:null);if(n){n.scheduled_at=n.scheduledAt=q.ack.scheduled_at;n.channel=q.ack.channel;n.template_key=n.templateKey=q.ack.template_key;n.draft_body=n.draftBody=q.payload.draft_body;}}}",'ACK hydration');
 source=replaceOne(source,"if(op==='contact'&&actionIntent==='activity_contact')return 'absorbed:contact';","if(actionIntent==='message_reminder'&&op==='activity')return 'absorbed:activity';if(op==='contact'&&actionIntent==='activity_contact')return 'absorbed:contact';",'activity absorption');
 source=replaceOne(source,"}else if(action.has(op)){if(!actionIntent)","}else if(op==='next_action'&&actionIntent==='message_reminder'){payload={...payload,intent:'message_reminder'};}else if(action.has(op)){if(!actionIntent)",'intent normalization');
 source=replaceOne(source,"  wrap('spSaveNext','next_action');",`  wrap('spSaveNext','next_action');
  wrap('relationshipSchedule','message_reminder');
  wrap('rmScheduleM','message_reminder');`,'named handlers');
 return source;
}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-expansion-note.sql':applySql(),'rollback-before-expansion-note.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':base.transport()};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md',...Object.keys(generated)],sources=['sql/expansion-note-context/20260906/manifest.json','crm.html','mobile.html','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operation:'next_action',intent:'message_reminder',ui_coverage_candidate:['M04'],prerequisite:'expansion-note-context/20260906',surface:'pc_mobile',meaning:'staff execution reminder, never provider auto-send',payload:['type','text','due_at','scheduled_at','channel','template_key','draft_body'],server_rules:{scope:'crm_security.can_deal(deal_id,true)',assignee:'approved current Deal owner UUID',schedule:'future instant; due_at equals Asia/Seoul date',replacement:'cancel all current open Deal Next Actions',transaction:'Next Action + private reminder + non-meaningful Activity + Deal version + audit + receipt'},read_additions:['next_action.scheduled_at','next_action.channel','next_action.template_key','next_action.draft_body'],blocked:['provider delivery claim','campaign queue','client actor/time','standalone derived Activity'],rollback:'metadata/audit/receipt archived; business Next Action and Activity retained; X02 remains active',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,applySql,rollbackSql,build};
