'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const create=require('../../pipeline-opportunity-create/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const read=name=>fs.readFileSync(path.join(dir,name),'utf8').replace(/\r\n?/g,'\n');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function applySql(){return tx(read('helper.sql'));}
function rollbackSql(){return tx(read('rollback-fragment.sql'));}
function replaceOne(source,pattern,replacement,label){const next=source.replace(pattern,replacement);if(next===source)throw Error('response build anchor missing: '+label);return next;}
function adapter(){let source=create.adapter();
 source=replaceOne(source,/ function normalizeAssign\(payload\)\{.*?\}\n function normalizeUnassign/s,` function normalizeAssign(payload){const allowed=['inquiry_id','inquiry_row','from','to','status','reason','changed_by','actor_name','at','assignment_group','owner_group','branch_code','reporting_group','consultant_name','response','intent','to_name'];if(Object.keys(payload).some(k=>!allowed.includes(k)))fail('INVALID_ASSIGNMENT_PAYLOAD');const branch=payload.to==='경남지사'||payload.branch_code==='gyeongnam'||payload.assignment_group==='gyeongnam'||payload.owner_group==='gyeongnam';if(branch)fail('INQUIRY_INTENT_NOT_CONNECTED');if(payload.response!==undefined){const outcomes={'진행됨 — 다음 잡음':{intent:'response_progress',status:'전화응대 완료'},'다음주 다시':{intent:'response_next_week_retry',status:'응대중'},'못 받으심 (내일 재시도)':{intent:'response_missed_retry',status:'배정완료'}},outcome=outcomes[payload.response];if(!outcome||(payload.intent!==undefined&&payload.intent!==outcome.intent)||payload.status!==outcome.status||payload.reason!==undefined||payload.to_name!==undefined||typeof payload.from!=='string'||typeof payload.to!=='string'||!payload.from.trim()||payload.from.trim()!==payload.to.trim())fail('INQUIRY_RESPONSE_INTENT_NOT_CONNECTED');return {intent:outcome.intent,response:payload.response};}if(payload.to!==undefined&&payload.to_name!==undefined&&payload.to.trim()!==payload.to_name.trim())fail('ASSIGNMENT_TARGET_CONFLICT');const target=text(payload.to_name===undefined?payload.to:payload.to_name,1,100,'INVALID_ASSIGNMENT_TARGET');if(payload.intent!==undefined&&payload.intent!=='direct_assign')fail('INQUIRY_INTENT_NOT_CONNECTED');const result={intent:'direct_assign',to_name:target};if(payload.reason!==undefined)result.reason=text(payload.reason,1,2000,'INVALID_ASSIGNMENT_REASON');return result;}\n function normalizeUnassign`,'normalizeAssign');
 source=replaceOne(source,/  if\(command\.operation==='inquiry_assign'.*?\n/,`  if(command.operation==='inquiry_assign'){const responseStatuses={response_progress:'전화응대 완료',response_next_week_retry:'응대중',response_missed_retry:'배정완료'};if(responseStatuses[command.payload.intent]){const timestamp=x=>x===null||typeof x==='string',needsResponse=command.payload.intent!=='response_missed_retry',needsDue=command.payload.intent!=='response_progress';if(ack.intent!==command.payload.intent||ack.response!==command.payload.response||ack.status!==responseStatuses[command.payload.intent]||ack.changed!==true||!timestamp(ack.first_response_at)||!timestamp(ack.responded_at)||(needsResponse&&(typeof ack.first_response_at!=='string'||typeof ack.responded_at!=='string'))||(needsDue&&!/^\\d{4}-\\d{2}-\\d{2}$/.test(ack.next_action_date))||typeof ack.updated_at!=='string'||!UUID.test(ack.inquiry_audit_event_id))fail('ACK_CONTRACT_MISMATCH');}else if(ack.intent!=='direct_assign'||!UUID.test(ack.assigned_to)||typeof ack.status!=='string'||typeof ack.changed!=='boolean'||(ack.changed?!UUID.test(ack.inquiry_audit_event_id):ack.inquiry_audit_event_id!=null))fail('ACK_CONTRACT_MISMATCH');}\n`,'validate inquiry ACK');
 return source;
}
function overlay(){let source=create.overlay();
 source=replaceOne(source,'purgeIntent=false,followupIntent=false,createSurface=null','purgeIntent=false,followupIntent=false,responseIntent=false,createSurface=null','overlay response state');
 source=replaceOne(source,"  function applyFollowupAck(q){",`  function applyResponseAck(q){const a=q.ack;for(const rows of inquiryRows())for(const i of rows)if(String(i.id||i.inquiry_id||i.key)===String(q.object_id)){for(const x of [i,i.raw].filter(Boolean)){x.status=a.status;x.first_response_at=a.first_response_at;x.responded_at=a.responded_at;x.next_action_date=a.next_action_date;x.updated_at=a.updated_at;}i.ps=String(a.updated_at).slice(0,10)+' · '+a.status;i.response_history=Array.isArray(i.response_history)?i.response_history:[];if(!i.response_history.some(x=>x.id===a.inquiry_audit_event_id))i.response_history.push({id:a.inquiry_audit_event_id,response:a.response,status:a.status,first_response_at:a.first_response_at,responded_at:a.responded_at,next_action_date:a.next_action_date,at:a.updated_at});}}\n  function applyFollowupAck(q){`,'apply response ACK');
 source=replaceOne(source,"if(q.operation==='inquiry_followup')applyFollowupAck(q);", "if(q.operation==='inquiry_followup')applyFollowupAck(q);if(q.operation==='inquiry_assign'&&q.payload&&/^response_/.test(q.payload.intent||''))applyResponseAck(q);",'sync response ACK');
 source=replaceOne(source,"root.pushWrite=function(op,payload){if(createSurface==='mobile'", "root.pushWrite=function(op,payload){if(op==='inquiry_assign'&&payload&&payload.response!==undefined&&!responseIntent)throw error('INQUIRY_RESPONSE_INTENT_NOT_CONNECTED');if(createSurface==='mobile'",'push response guard');
 source=replaceOne(source,"  if(typeof root.applyTodayPostponeM==='function')",`  const RESPONSE_OUTCOMES=new Set(['진행됨 — 다음 잡음','다음주 다시','못 받으심 (내일 재시도)']);\n  if(typeof root.pickToday==='function'){const original=root.pickToday;root.pickToday=function(i,label){const q=root.todayInquiry&&root.todayInquiry(i);if(q&&!RESPONSE_OUTCOMES.has(label)){if(typeof root.toast==='function')root.toast('지원하지 않는 문의 응대 결과입니다.');return false;}const previous=responseIntent;responseIntent=!!q&&RESPONSE_OUTCOMES.has(label);try{return original.apply(this,arguments);}finally{responseIntent=previous;}};}\n  if(typeof root.recordInquiryResponse==='function'){const original=root.recordInquiryResponse;root.recordInquiryResponse=function(key,label){if(!RESPONSE_OUTCOMES.has(label)){if(typeof root.toast==='function')root.toast('지원하지 않는 문의 응대 결과입니다.');return false;}const previous=responseIntent;responseIntent=true;try{return original.apply(this,arguments);}finally{responseIntent=previous;}};}\n  if(typeof root.applyTodayPostponeM==='function')`,'named response handlers');
 return source;
}
function build(){const files={'staging-apply-after-operational-cutover.sql':applySql(),'rollback-before-operational-cutover.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay()};for(const [name,value] of Object.entries(files))fs.writeFileSync(path.join(dir,name),value);
 const own=['build.cjs','helper.sql','rollback-fragment.sql','review.md','contract.test.cjs','db.test.cjs','ui.test.cjs',...Object.keys(files)];
 const sources=['sql/pipeline-opportunity-create/20260906/manifest.json','mobile.html','sql/business-v2/functions.sql'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',operation:'inquiry_assign',intents:['response_progress','response_next_week_retry','response_missed_retry'],status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',allowed_responses:['진행됨 — 다음 잡음','다음주 다시','못 받으심 (내일 재시도)'],blocked_responses:[],roles:['rep','consultation'],server_rules:{response_progress:{status:'전화응대 완료',response_timestamps:'first_once_last_now',followup_days:null},response_next_week_retry:{status:'응대중',response_timestamps:'first_once_last_now',followup_days:7},response_missed_retry:{status:'배정완료',response_timestamps:'preserve',followup_days:1}},frozen_direct_assign_changed_semantically:false,staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={applySql,rollbackSql,adapter,overlay,build,dir};
