'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{createRequire}=require('node:module');
const req=createRequire(path.resolve(__dirname,'../../../../crm-security-lab/package.json')),acorn=req('acorn');
const operationalUi=require('../../operational-ui/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function replaceFunction(source,name,replacement){const ast=acorn.parse(source,{ecmaVersion:'latest'});let target;function walk(node){if(!node||typeof node!=='object')return;if(node.type==='FunctionDeclaration'&&node.id?.name===name){if(target)throw Error('duplicate '+name);target=node;}for(const value of Object.values(node))if(value&&typeof value==='object'){if(Array.isArray(value))value.forEach(walk);else if(value.type)walk(value);}}walk(ast);if(!target)throw Error('missing '+name);return source.slice(0,target.start)+replacement+source.slice(target.end);}
function replaceAssignedFunction(source,objectName,propertyName,replacement){const ast=acorn.parse(source,{ecmaVersion:'latest'});let target;function walk(node){if(!node||typeof node!=='object')return;if(node.type==='AssignmentExpression'&&node.left?.type==='MemberExpression'&&!node.left.computed&&node.left.object?.type==='Identifier'&&node.left.object.name===objectName&&node.left.property?.name===propertyName){if(target)throw Error('duplicate '+objectName+'.'+propertyName);target=node.right;}for(const value of Object.values(node))if(value&&typeof value==='object'){if(Array.isArray(value))value.forEach(walk);else if(value.type)walk(value);}}walk(ast);if(!target)throw Error('missing '+objectName+'.'+propertyName);return source.slice(0,target.start)+replacement+source.slice(target.end);}
function transport(){let text=operationalUi.transport();
 one(text,"'crm_contacts_scoped_v2','crm_write_command_v2'",'rpc allow');text=text.replace("'crm_contacts_scoped_v2','crm_write_command_v2'","'crm_contacts_scoped_v2','crm_write_command_v2','crm_operational_source_v1'");
 return replaceFunction(text,'read',`async function read(resource,args={}){
  if(!profile)throw Error('AUTH_REQUIRED');
  if(resource==='profile')return {contract_version:1,resource,coverage:'complete',scope:'self',data:profile};
  if(resource==='operational'){
   const limit=args.limit===undefined?100:args.limit;if(!Number.isInteger(limit)||limit<1||limit>100)throw Error('INVALID_LIMIT');
   async function collect(domain){const items=[],seen=new Set();let after=null;for(let pageNo=0;pageNo<500;pageNo++){const result=await rpc('crm_operational_source_v1',{p_domain:domain,p_after:after,p_limit:limit}),p=result?.pagination;if(result?.contract_version!==1||result.resource!=='operational_source'||result.domain!==domain||result.scope_completeness!=='actor_authorized_rows_only'||!Array.isArray(result.items)||!p||!['complete','partial'].includes(p.completeness)||typeof p.has_more!=='boolean'||p.has_more!==(p.completeness==='partial')||p.has_more!==(typeof p.next_cursor==='string'))throw Error('READ_CONTRACT_MISMATCH');for(const item of result.items){if(!item?.id||seen.has(item.id))throw Error('READ_CONTRACT_MISMATCH');seen.add(item.id);items.push(item);}if(!p.has_more)return items;if(p.next_cursor===after)throw Error('READ_CURSOR_STALLED');after=p.next_cursor;}throw Error('READ_INCOMPLETE');}
   const [deals,inquiries]=await Promise.all([collect('deal_core'),collect('inquiry_core')]);
   return {contract_version:1,resource,coverage:'complete_for_actor_scope',scope:'actor_authorized_rows_only',data:{contract_version:3,deals,inquiries}};
  }
  if(resource!=='work_items')return {contract_version:1,resource,coverage:'unavailable',scope:'authorized_only',data:null,reason:'CONTRACT_MISSING'};
  if(!args.opportunity_id)throw Error('TARGET_REQUIRED');
  const result=await rpc('crm_read_scoped_v2',{p_deal_id:args.opportunity_id,p_limit:1});
  if(result.contract_version!==2||!Array.isArray(result.deals)||result.deals.length!==1||result.deals[0].id!==args.opportunity_id)throw Error('READ_CONTRACT_MISMATCH');
  return {contract_version:1,resource,coverage:'complete',scope:'single_authorized_opportunity',data:result.deals[0]};
 }`);
}
function overlay(){let text=fs.readFileSync(path.join(root,'sql/pipeline-quote-version/20260906/operational-overlay.candidate.js'),'utf8');
 one(text,"coverage:'scoped_partial'",'overlay coverage');text=text.replace("coverage:'scoped_partial'","coverage:'complete_for_actor_scope'");
 const shell="deals:(scoped.deals||[]).map(d=>({...d,opportunity_id:d.id,code:d.stage_code,currentBusiness:d.brand,current_business:d.brand}))";
 const shellNext="deals:(scoped.deals||[]).map(d=>{const n=d.next_action?{id:d.next_action.id,type:d.next_action.type,text:d.next_action.text,due:String(d.next_action.due_at||'').slice(0,10),due_at:d.next_action.due_at,assignee:d.next_action.assignee_name,status:d.next_action.status}:null;return {...d,opportunity_id:d.id,code:d.stage_code,currentBusiness:d.brand,current_business:d.brand,nextActionObj:n,nextAction:n};})";
 one(text,shell,'overlay next-action alias');text=text.replace(shell,shellNext);
 const identity="version:d.version,favorite:!!d.favorite";
 const identityMapped="version:d.version,nm:d.site||d.site_name||'현장명 미제공',rep:d.assignee||d.owner_name||'미배정',amt:Number(d.amt||d.amount||0),quote_amount:d.quote_amount==null?0:Number(d.quote_amount),quote_versions:d.quote_versions||[],won_amount:d.outcome==='won'?Number(d.amount||0):0,outcome:d.outcome||null,originBusiness:d.origin_business||d.brand||'',currentBusiness:d.current_business||d.brand||'',businessHistory:d.business_history||[],activities:d.activity_signals||[],contact:Array.isArray(d.contacts)&&d.contacts.length?d.contacts[0]:null,contacts:Array.isArray(d.contacts)?d.contacts:[],office_phone:d.office_phone||'',office_email:d.office_email||'',manager_name:d.manager_name||'',manager_mobile:d.manager_mobile||'',manager_role:d.manager_role||'',person_key:d.person_key||'',manager_current_site:d.manager_current_site||'',manager_started_at:d.manager_started_at||'',manager_status:d.manager_status||'',manager_left_at:d.manager_left_at||'',address:d.address||'',lastAt:d.lastActivity||d.last_activity_at||d.updated||d.created||null,stageAt:d.stageAt||d.stage_entered_at||d.updated||d.created||null,stageHistory:d.stage_history||[],created:d.created||d.created_at||null,updated:d.updated||d.updated_at||null,closed:d.closed||d.closed_at||null,favorite:!!d.favorite";
 one(text,identity,'mobile identity mapping');text=text.replace(identity,identityMapped);
 const mobile="view_count:Number(d.view_count||0),tl:[]";
 one(text,mobile,'mobile next-action mapping');text=text.replace(mobile,"view_count:Number(d.view_count||0),nextAction:d.nextAction||d.next_action||d.nextActionObj||null,tl:[]");
 const personalAck="  function applyPersonalAck(q){const a=q.ack,lists=[root.B&&root.B.deals,root.DEALS];for(const rows of lists)if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.favorite=a.favorite;d.last_viewed_at=a.last_viewed_at;d.last_worked_at=a.last_worked_at;d.view_count=a.view_count;}}";
 one(text,personalAck,'next-action ACK alias');text=text.replace(personalAck,personalAck+"\n  function applyNextAck(q){const id=q.ack&&q.ack.next_action_id;if(!id)return;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){if(d.nextActionObj)d.nextActionObj.id=id;if(d.nextAction&&typeof d.nextAction==='object')d.nextAction.id=id;}}");
 const sync="if(personal.has(q.operation))applyPersonalAck(q);";
 one(text,sync,'next-action ACK sync');text=text.replace(sync,sync+"if(q.operation==='next_action')applyNextAck(q);");
 return text;}
function build(){const transportBase=operationalUi.transport();fs.writeFileSync(path.join(dir,'transport.candidate.js'),transport());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['candidate.sql','rollback.sql','read-contract.js','contract.test.cjs','db.test.cjs','review.md','transport.candidate.js','operational-overlay.candidate.js','ui.test.cjs'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_QUOTE_NOT_APPLIED',prerequisites:['personal-state-compat/20260906','pipeline-action-bundle/20260906','pipeline-quote-version/20260906'],public_function_candidate:'crm_operational_source_v1(text,uuid,integer)',existing_public_read_changed:false,connected_reads_candidate:['O07S','O08M','O08S'],scope_completeness:'actor_authorized_rows_only',still_blocked:['O07D','O07P','O07R','O07G','O08T','O08C','O08A','C03_FULL'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),golden_mobile:sha(fs.readFileSync(path.join(root,'mobile.html'))),transport_base:sha(transportBase),quote_overlay:sha(fs.readFileSync(path.join(root,'sql/pipeline-quote-version/20260906/operational-overlay.candidate.js'))),quote_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-quote-version/20260906/manifest.json')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={transport,overlay,build};
