'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const approval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n";
const candidate=fs.readFileSync(path.join(__dirname,'candidate.sql'),'utf8'),rollback=fs.readFileSync(path.join(__dirname,'rollback.sql'),'utf8');
const deal=n=>s.uid(6,n),inquiry=n=>s.uid(5,n);
async function setup(){const db=await personal.setup();await db.exec(personal.approval+fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'));await db.exec(action.applySql());await db.exec(quote.applySql());return db;}
async function meta(db,signature){return (await db.query("SELECT oid,prosrc,proconfig,proacl::text acl FROM pg_proc WHERE oid=$1::regprocedure",[signature])).rows[0];}
async function call(db,account,domain,after=null,limit=100){await db.exec(`RESET ROLE; SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}'; SET ROLE authenticated;`);try{return (await db.query('SELECT public.crm_operational_source_v1($1,$2,$3) value',[domain,after,limit])).rows[0].value;}finally{await db.exec('RESET ROLE');}}
test('public operational source is actor-scoped, independently paged and non-invasive',async t=>{
 const db=await setup();try{
  const before={read:await meta(db,'public.crm_read_scoped_v2(uuid,integer,uuid,uuid)'),write:await meta(db,'public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)')};
  await db.exec(approval+candidate);
  await t.test('existing public read/write functions are byte-identical',async()=>{assert.deepEqual(await meta(db,'public.crm_read_scoped_v2(uuid,integer,uuid,uuid)'),before.read);assert.deepEqual(await meta(db,'public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)'),before.write);});
  await t.test('rep receives only owned deal with complete Golden list identity and scoped contact projection',async()=>{const value=await call(db,0,'deal_core'),item=value.items[0];assert.deepEqual(value.items.map(x=>x.id),[deal(1)]);assert.equal(value.scope_completeness,'actor_authorized_rows_only');assert.equal(item.favorite,false);assert.deepEqual(item.quote_versions,[]);assert.equal(item.quote_amount,null);for(const key of ['site_name','owner_name','amount','created_at','updated_at','stage_entered_at','last_activity_at','contacts'])assert.ok(Object.hasOwn(item,key),key);assert.ok(Array.isArray(item.contacts));for(const contact of item.contacts){assert.equal(Object.hasOwn(contact,'emails'),false);assert.equal(Object.hasOwn(contact,'custom_fields'),false);}assert.equal(value.pagination.has_more,false);assert.equal(value.pagination.completeness,'complete');});
  await t.test('a quote command is visible through the same scoped operational source',async()=>{await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[0].auth_uid}';`);await db.query("SELECT public.crm_write_command_v2($1,'quote_version',$2,1,$3)",[s.uid(15,1),deal(1),JSON.stringify({amount:123000000,reason:'범위 확정'})]);const value=await call(db,0,'deal_core');assert.equal(Number(value.items[0].quote_amount),123000000);assert.deepEqual(value.items[0].quote_versions.map(x=>Number(x.amount)),[123000000]);assert.equal(value.items[0].version,2);});
  await t.test('limit plus one makes has_more truthful and cursor domain-local',async()=>{const first=await call(db,1,'deal_core',null,1);assert.deepEqual(first.items.map(x=>x.id),[deal(2)]);assert.equal(first.pagination.has_more,true);assert.equal(first.pagination.next_cursor,deal(2));const second=await call(db,1,'deal_core',first.pagination.next_cursor,1);assert.deepEqual(second.items.map(x=>x.id),[deal(3)]);assert.equal(second.pagination.has_more,false);assert.equal(second.pagination.next_cursor,null);});
  await t.test('inquiry source follows inquiry scope and omits raw/address',async()=>{const value=await call(db,2,'inquiry_core');assert.deepEqual(value.items.map(x=>x.id),[inquiry(3)]);assert.equal(Object.hasOwn(value.items[0],'raw'),false);assert.equal(Object.hasOwn(value.items[0],'address'),false);});
  await t.test('private helper and anonymous public access are denied',async()=>{await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[0].auth_uid}'; SET ROLE authenticated;`);try{await assert.rejects(db.query("SELECT crm_security.crm_operational_source_fragment_v1('deal_core',NULL,10)"),e=>e.code==='42501');}finally{await db.exec('RESET ROLE');}await db.exec('SET ROLE anon;');try{await assert.rejects(db.query("SELECT public.crm_operational_source_v1('deal_core',NULL,10)"),e=>e.code==='42501');}finally{await db.exec('RESET ROLE');}});
  await t.test('unapproved domains fail closed',async()=>{await assert.rejects(call(db,0,'company_report'),e=>e.code==='22023');});
 }finally{await db.close();}
});
test('rollback removes only the new source pair',async()=>{const db=await setup();try{const before=await meta(db,'public.crm_read_scoped_v2(uuid,integer,uuid,uuid)');await db.exec(approval+candidate);await db.exec(approval+rollback);assert.equal((await db.query("SELECT to_regprocedure('public.crm_operational_source_v1(text,uuid,integer)') IS NULL gone")).rows[0].gone,true);assert.deepEqual(await meta(db,'public.crm_read_scoped_v2(uuid,integer,uuid,uuid)'),before);}finally{await db.close();}});
