import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {fixture} from './aligo-database-fixture.mjs';
const read=f=>readFileSync(new URL('../sql/'+f,import.meta.url),'utf8');
test('coaching batches preserve recipient, cohort and atomic receipts across reassignment and failures',async()=>{
 const db=new PGlite(),A='11111111-1111-4111-8111-111111111111',AA='22222222-2222-4222-8222-222222222222',B='33333333-3333-4333-8333-333333333333',BB='44444444-4444-4444-8444-444444444444',C='55555555-5555-4555-8555-555555555555';
 const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
 const as=async uid=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role authenticated');};
 const call=async p=>(await db.query('select public.crm_kpi_request_send_v2($1::jsonb) r',[JSON.stringify(p)])).rows[0].r;
 try{
  await db.exec(fixture);await db.exec(read('ops-store-v1-20261002.sql'));
  await db.exec(`alter table public.deals add owner_id uuid,add assignee_name text;
   create table public.inquiries(id uuid primary key,assigned_to uuid,assignee_name text);
   create table crm_security.rep_manager_comments(rep_user_id uuid,week_start date,comment text,status text,created_by_auth_uid uuid,created_by_user_id uuid,completed_at timestamptz,created_at timestamptz,updated_at timestamptz,primary key(rep_user_id,week_start));`);
  await db.exec(read('20261009171018_kpi_request_history_and_ack.sql'));
  await db.exec(read('20261009203001_coaching_target_receipts.sql'));await db.exec(read('20261009203001_coaching_target_receipts.sql'));
  await db.query("insert into public.users values($1,$2,'Admin','admin',true),($3,$4,'Rep','rep',true),($5,null,'Other','rep',true)",[A,AA,B,BB,C]);
  await db.query("insert into crm_security.access_review values($1,$2,'admin','admin',true,now()+interval '1 day'),($3,$4,'rep','rep',true,now()+interval '1 day')",[A,AA,B,BB]);
  const targets=Array.from({length:203},(_,i)=>({target_type:i===202?'inquiry':'deal',target_id:id(i+1),action:'확인 요청'}));
  for(const t of targets)await db.query(t.target_type==='deal'?'insert into public.deals(id,owner_id,assignee_name) values($1,$2,$3)':'insert into public.inquiries values($1,$2,$3)',[t.target_id,B,'Rep']);
  const week=(await db.query("select date_trunc('week',now() at time zone 'Asia/Seoul')::date::text d")).rows[0].d;
  const snapshot={recipient_user_id:B,rep_name:'Rep',week_start:week,promise_key:'kpi:3',rule_version:'coaching-targets-v1',targets};
  const p={request_id:id(501),group_id:id(601),recipient_user_id:B,rep_name:'Rep',week_start:week,promise_key:'kpi:3',line:'대상별 요청',snapshot,batch_index:0,targets:targets.slice(0,200)};
  await as(BB);await assert.rejects(call(p),/forbidden/);await as(AA);
  const ack=await call(p);assert.equal(ack.contract_version,2);assert.equal(ack.actions.length,200);
  assert.ok(ack.actions.every(x=>x.recipient_user_id===B&&x.actor===A&&x.request_group_id===p.group_id&&x.request_week===week));
  await db.exec('reset role');await db.query('update public.deals set owner_id=$1,assignee_name=$2 where id=$3',[C,'Other',id(1)]);await as(AA);
  assert.deepEqual(await call(p),ack,'lost ACK after reassignment returns original recipient');
  await assert.rejects(call({...p,request_id:id(502)}),/batch already accepted/);
  await assert.rejects(call({...p,line:'changed'}),/payload mismatch/);
  const tail={...p,request_id:id(503),batch_index:1,targets:targets.slice(200)};
  await assert.rejects(call({...tail,snapshot:{...snapshot,targets:targets.slice(1)}}),/batch snapshot mismatch/);
  await db.exec('reset role');await db.query('update public.inquiries set assigned_to=$1,assignee_name=$2',[C,'Other']);await as(AA);
  await assert.rejects(call(tail),/담당자 변경/);
  await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from public.kpi_actions')).rows[0].n,200,'failed batch makes no partial writes');
  await db.query('update public.inquiries set assigned_to=$1,assignee_name=$2',[B,'Rep']);
  await db.exec(`create function public.fail_coaching_action() returns trigger language plpgsql as $$ begin raise exception 'forced failure'; end $$;create trigger test_coaching_failure before insert on public.kpi_actions for each row execute function public.fail_coaching_action();`);
  await as(AA);await assert.rejects(call(tail),/forced failure/);await db.exec('reset role');
  assert.equal((await db.query('select count(*)::int n from crm_security.kpi_request_receipts')).rows[0].n,1);
  assert.equal((await db.query('select comment from crm_security.rep_manager_comments')).rows[0].comment,ack.comment.comment);
  await db.exec('drop trigger test_coaching_failure on public.kpi_actions');await as(AA);
  const tailAck=await call(tail);assert.equal(tailAck.actions.length,3);assert.deepEqual(await call(tail),tailAck);
  const otherSnapshot={...snapshot,recipient_user_id:C,rep_name:'Other',targets:[targets[0]]};
  const other=await call({...p,request_id:id(504),group_id:id(602),recipient_user_id:C,rep_name:'Other',snapshot:otherSnapshot,targets:[targets[0]]});
  assert.equal(other.actions[0].recipient_user_id,C,'new recipient can receive a separate request');
  await assert.rejects(call({...tail,request_id:id(505),snapshot:{...snapshot,source_scope:'changed'}}),/group snapshot mismatch/);
  await assert.rejects(db.exec('select * from crm_security.coaching_request_groups'),/permission denied/);
  await db.exec('reset role;set role anon');await assert.rejects(call(p),/permission denied/);
 }finally{await db.close();}
});
