import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {fixture} from './aligo-database-fixture.mjs';
const read=p=>readFileSync(new URL(p,import.meta.url),'utf8');
test('contract corrections require independent approval, append once and roll back the decision on any ledger failure',async()=>{
 const db=new PGlite(),u='11111111-1111-4111-8111-111111111111',au='22222222-2222-4222-8222-222222222222',
 v='33333333-3333-4333-8333-333333333333',av='44444444-4444-4444-8444-444444444444',d='55555555-5555-4555-8555-555555555555';
 try{
  await db.exec(fixture+`alter table public.deals add column owner_id uuid;alter table public.deals add column site_id uuid;alter table public.deals add column list_fields jsonb default '{}'::jsonb;alter table public.deals add column brand text;alter table public.deals add column stage_contexts jsonb default '{}'::jsonb;create table public.sites(site_id uuid primary key,site_name text);create table public.organizations(id uuid primary key,name text);
   create function crm_security.approval_approver(uuid) returns boolean language sql as $$select true$$;`);
  await db.exec(read('../supabase/migrations/20260920160000_contract_sales_ledger.sql'));
  await db.exec(read('../sql/approval-inbox-v1-20261004.sql'));
  await db.exec(read('../sql/contract-correction-approval-20261007.sql'));
  await db.query("insert into public.users values($1,$2,'요청자','admin',true),($3,$4,'승인자','admin',true)",[u,au,v,av]);
  await db.query("insert into crm_security.access_review values($1,$2,'admin','admin',true,now()+interval '1 day'),($3,$4,'admin','admin',true,now()+interval '1 day')",[u,au,v,av]);
  await db.query('insert into public.deals(id,owner_id) values($1,$2)',[d,u]);
  const as=async uid=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role authenticated');};
  const rpc=async(n,p)=>(await db.query(`select public.${n}($1::jsonb) r`,[JSON.stringify(p)])).rows[0].r;
  const preview=()=>rpc('crm_contract_correction_preview_v1',{deal_id:d});
  const request=p=>rpc('crm_contract_correction_request_v1',p);
  const decide=(id,decision='approve')=>rpc('crm_approval_decide_v1',{id,decision,reason:'검토 완료'});
  const proposal=async target=>{const x=await preview();return {deal_id:d,request_id:crypto.randomUUID(),source_event_id:x.source_event_id,expected_version:x.expected_version,target_balance:target,effective_date:'2020-10-02',reason:'계약 증빙 정정'};};
  await as(au);
  await rpc('crm_contract_sales_write_v1',{deal_id:d,request_id:crypto.randomUUID(),kind:'signed',effective_date:'2020-09-01',expected_version:0,amount_delta:300,reason:'합성 계약'});
  const first=await preview();assert.equal(first.balance,300);assert.equal(first.previous_balance,null);
  const p=await proposal(250);
  await assert.rejects(request({...p,effective_date:undefined}),/explicit/);
  await assert.rejects(request({...p,target_balance:0}),/explicit/);
  await assert.rejects(request({...p,source_event_id:crypto.randomUUID()}),/VERSION_CONFLICT/);
  await assert.rejects(rpc('crm_approval_request_v1',{type:'contract_amount',deal_id:d,title:'우회',reason:'우회',payload:p}),/요청 종류/);
  const q=await request(p),id=q.request.id;
  assert.equal(q.request.status,'pending');assert.equal((await preview()).balance,300,'request cannot change money');
  assert.equal((await request(p)).request.id,id,'exact retry returns same approval');
  await assert.rejects(request({...p,target_balance:240}),/REQUEST_ID_REUSE/);
  await assert.rejects(request({...p,request_id:crypto.randomUUID()}),/unique constraint/);
  await assert.rejects(decide(id),/본인이 올린/);
  await as(av);
  await db.exec('reset role');await db.query("update crm_security.access_review set permission_role='rep' where user_id=$1",[v]);await db.exec('set role authenticated');
  await assert.rejects(preview(),/forbidden/);await assert.rejects(decide(id),/forbidden/);
  await db.exec('reset role');await db.query("update crm_security.access_review set permission_role='admin' where user_id=$1",[v]);await db.exec('set role authenticated');
  await db.exec('reset role');await db.exec(`create function public.fail_correction_test() returns trigger language plpgsql as $$begin if new.kind='amended' then raise exception 'synthetic ledger failure';end if;return new;end$$;create trigger fail_correction_test before insert on crm_security.contract_sales_events for each row execute function public.fail_correction_test();set role authenticated;`);
  await assert.rejects(decide(id),/synthetic ledger failure/);
  let rows=(await rpc('crm_approval_list_v1',{})).rows;assert.equal(rows.find(x=>x.id===id).status,'pending');assert.equal((await preview()).balance,300);
  await db.exec('reset role;drop trigger fail_correction_test on crm_security.contract_sales_events;set role authenticated');
  assert.equal((await decide(id)).request.status,'approved');
  let current=await preview();assert.equal(current.balance,250);assert.equal(current.expected_version,2);assert.equal(current.previous_balance,300);
  assert.equal(current.contract_amount,300);assert.equal(current.contract_date,'2020-09-01');assert.equal(current.sales_owner,u);
  await assert.rejects(decide(id),/이미 처리/);
  await as(au);assert.equal((await request(p)).request.status,'approved','lost response retry still returns existing decision');
  const stale=await request(await proposal(200));
  await rpc('crm_contract_sales_write_v1',{deal_id:d,request_id:crypto.randomUUID(),kind:'amended',effective_date:'2020-10-03',expected_version:2,amount_delta:20,reason:'후속 변경'});
  await as(av);await assert.rejects(decide(stale.request.id),/VERSION_CONFLICT/);
  assert.equal((await decide(stale.request.id,'reject')).request.status,'rejected');assert.equal((await preview()).balance,270);
  await as(au);const cancelled=await request({...await proposal(260),effective_date:'2020-10-04'});
  await rpc('crm_approval_request_v1',{id:cancelled.request.id,cancel:true});
  await as(av);await assert.rejects(decide(cancelled.request.id),/이미 처리/);
  await db.exec('reset role');
  const events=(await db.query('select * from crm_security.contract_sales_events order by sequence')).rows;
  assert.deepEqual(events.map(x=>Number(x.amount_delta)),[300,-50,20]);
  assert.deepEqual(events.map(x=>x.effective_date.toISOString().slice(0,10)),['2020-09-01','2020-10-02','2020-10-03']);
  assert.equal((await db.query('select count(*)::int n from crm_security.contract_correction_requests where applied is not null')).rows[0].n,1);
  await db.query('update public.users set active=false where user_id=$1',[u]);await as(au);await assert.rejects(preview(),/forbidden/);
  await db.exec('reset role;set role anon');await assert.rejects(preview(),/permission denied/);
  await db.exec('reset role;set role authenticated');await assert.rejects(db.exec('select * from crm_security.contract_correction_requests'),/permission denied/);
 }finally{await db.close();}
});
