'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const s=require('../scripts/crm-phase1.cjs'),bridge=require('../staging-write/compat-adapter.js'),WriteAck=require('../write-ack.js');
const compatibilityMigration=fs.readFileSync(path.resolve(__dirname,'../supabase/migrations/20260905220648_crm_work_compat_dispatcher.sql'),'utf8');
const readProjectionMigration=fs.readFileSync(path.resolve(__dirname,'../supabase/migrations/20260906073500_crm_work_read_projection.sql'),'utf8');
test('work read projection adds only persisted scope/summary fields',async()=>{const db=await s.setup();try{await db.exec(s.approval+s.migration);await db.exec("SET crm.work_read_ref='rprechiaglyjaydkmxsu';\n"+readProjectionMigration);await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub='${s.mapping.accounts[0].auth_uid}';`);const row=(await db.query('SELECT public.crm_read_scoped_v2(NULL,1,$1,NULL) a',[s.uid(6,1)])).rows[0].a.deals[0];assert.deepEqual(Object.keys(row).sort(),['brand','id','owner_id','primary_work','site_id','stage_code','version','work_items','work_scope_type','work_summary']);assert.equal(row.work_scope_type,null);assert.equal(row.work_summary,null);}finally{await db.close();}});
test('generated work compatibility apply and rollback execute with exact catalog guards',async()=>{
 const work=require('../scripts/crm-work-compat.cjs');await work.build();const db=await work.setup();try{
  const before=await work.capture(db),apply=fs.readFileSync(path.join(work.dir,'staging-apply.sql'),'utf8'),rollback=fs.readFileSync(path.join(work.dir,'rollback.sql'),'utf8');
  await db.exec(apply);await db.exec(rollback);assert.deepEqual(await work.capture(db),before);
 }finally{await db.close();}
});
test('compatibility bridge against actual SQL handler in isolated local PostgreSQL engine',async t=>{
 const db=await s.setup();try{await db.exec(s.approval+s.migration);await db.exec("SET crm.work_compat_ref='rprechiaglyjaydkmxsu';\n"+compatibilityMigration);let actor=0,calls=0;
 const identity={project_ref:bridge.project_ref,auth_uid:s.mapping.accounts[0].auth_uid,user_id:s.uid(1,1),expected_version:1};
 const w={write_id:'PC-COMPAT-TEST-1',op:'opportunity_work_set',actor_id:'FORGED',payload:{opportunity_id:s.uid(6,1),primary_work:'TEST A',work_items:['TEST A'],work_summary:'TEST A',reason:'TEST compatibility proof',actor_name:'FORGED'}};
 const o={project_ref:bridge.project_ref,url:'https://'+bridge.project_ref+'.supabase.co',publishable_key:'sb_publishable_TEST_LOCAL',auth:{getSession:async()=>({data:{session:{user:{id:s.mapping.accounts[actor].auth_uid},access_token:'LOCAL_ONLY'}}})},fetch:async(url,init)=>{
  calls++;assert.equal(new URL(url).hostname,bridge.project_ref+'.supabase.co');const r=JSON.parse(init.body);
  await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub='${s.mapping.accounts[actor].auth_uid}';`);
  try{const a=(await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[r.p_request_id,r.p_operation,r.p_object_id,r.p_expected_version,JSON.stringify(r.p_payload)])).rows[0].a;return Response.json(a);}
  catch(e){return Response.json({code:e.code},{status:e.code==='PT409'?409:e.code==='42501'?403:400});}finally{await db.exec('RESET ROLE');}
 }};
 const client=bridge.create(o),q=await bridge.prepare(w,identity);
 const initialActivities=(await db.query('SELECT count(*)::int n FROM public.activities WHERE deal_id=$1',[s.uid(6,1)])).rows[0].n;
 await t.test('original WriteAck consumes server ACK and legacy persistence order is retained',async()=>{const a=await WriteAck.read(await client.response(q),w);assert.equal(a.write_id,w.write_id);assert.equal(a.actor_auth_uid,identity.auth_uid);assert.equal(a.version,2);assert.equal(a.work_contract,'legacy_work_v1');const row=(await db.query('SELECT actor_auth_uid,actor_user_id FROM crm_security.audit_events')).rows[0];assert.equal(row.actor_auth_uid,identity.auth_uid);assert.equal(row.actor_user_id,identity.user_id);const dealRow=(await db.query('SELECT primary_work,work_items,work_summary,version FROM public.deals WHERE id=$1',[s.uid(6,1)])).rows[0];assert.deepEqual(dealRow,{primary_work:'TEST A',work_items:['TEST A'],work_summary:'TEST A',version:2});assert.equal((await db.query('SELECT count(*)::int n FROM public.activities WHERE deal_id=$1',[s.uid(6,1)])).rows[0].n,initialActivities+1);const legacyAudit=(await db.query("SELECT actor_id,actor_name,after FROM public.audit_logs WHERE entity_id=$1 AND action='opportunity_work_set'",[s.uid(6,1)])).rows[0];assert.equal(legacyAudit.actor_id,identity.user_id);assert.equal(legacyAudit.after.work_summary,'TEST A');});
 await t.test('same original write_id after adapter recreation produces one receipt/audit only',async()=>{const replay=await bridge.create(o).send(await bridge.prepare(w,identity));assert.equal(replay.replayed,true);for(const table of ['command_receipts','audit_events'])assert.equal((await db.query(`SELECT count(*)::int n FROM crm_security.${table}`)).rows[0].n,1);});
 await t.test('same ID with different work data is rejected by server',async()=>{const changed=await bridge.prepare({...w,payload:{...w.payload,reason:'TEST changed intent'}},identity);await assert.rejects(client.send(changed),{status:409});});
 await t.test('stale different request rejected; no automatic version refresh',async()=>{const changed=await bridge.prepare({...w,write_id:'PC-COMPAT-TEST-2'},identity);await assert.rejects(client.send(changed),{status:409});});
 await t.test('other rep valid session cannot write first rep Deal',async()=>{actor=1;const other=await bridge.prepare({...w,write_id:'OTHER'}, {...identity,auth_uid:s.mapping.accounts[1].auth_uid,user_id:s.uid(1,2),expected_version:2});await assert.rejects(client.send(other),{status:403});});
 await t.test('legacy UI display summaries are persisted instead of rebuilt from keys',async()=>{const fresh=await s.setup();try{await fresh.exec(s.approval+s.migration);await fresh.exec("SET crm.work_compat_ref='rprechiaglyjaydkmxsu';\n"+compatibilityMigration);const changed=await bridge.prepare({...w,write_id:'DISPLAY-SUMMARY',payload:{...w.payload,work_summary:'TEST 표시명 (서버 key와 다름)'}},identity);const r=changed.rpc;await fresh.exec(`SET ROLE authenticated; SET request.jwt.claim.sub='${identity.auth_uid}';`);const a=(await fresh.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[r.p_request_id,r.p_operation,r.p_object_id,r.p_expected_version,JSON.stringify(r.p_payload)])).rows[0].a;await fresh.exec('RESET ROLE');assert.equal(a.work.work_summary,'TEST 표시명 (서버 key와 다름)');assert.equal((await fresh.query('SELECT work_summary FROM public.deals WHERE id=$1',[s.uid(6,1)])).rows[0].work_summary,'TEST 표시명 (서버 key와 다름)');}finally{await fresh.close();}});
 assert.equal(calls,5);
 }finally{await db.close();}
});
