const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const C=require('../data-cleanup.js');
const row=(id,extra={})=>({ref:{type:'deal',id},name:'검증용 한빛아파트',address:'수원시 테스트로 12',mobile:'',office:'0311112222',siteId:'',works:['옥상>금속기와'],brand:'POUR',at:'2026-09-01',...extra});
test('같은 현장 다른 공종은 Deal 병합이 아닌 Site 연결',()=>assert.equal(C.classify(row('1'),row('2',{works:['재도장>외부']})).action,'site_link'));
test('ASQ와 POUR는 다른 영업기회로 보존',()=>assert.equal(C.classify(row('1'),row('2',{brand:'아파트스퀘어'})).action,'site_link'));
test('동일 공종 가까운 시기는 검토만',()=>assert.equal(C.classify(row('1'),row('2')).action,'deal_review'));
test('같은 번호 다른 현장은 사람 이동 검토',()=>assert.equal(C.classify(row('1',{mobile:'010-1234-5678'}),row('2',{name:'다른 단지',address:'창원시 테스트로 3',mobile:'01012345678'})).action,'contact_move'));
test('이름 동일 주소 다름은 별도 현장',()=>assert.equal(C.classify(row('1'),row('2',{address:'서울시 테스트로 5'})).action,'separate'));
test('상담담당과 영업담당 차이는 판단 근거 아님',()=>assert.equal(C.classify(row('1',{owner:'황윤선',consultant:'조재연'}),row('2',{owner:'김성민'})).action,'deal_review'));
test('빈 주소/전화번호로 같은 현장 판정하지 않음',()=>assert.equal(C.classify(row('1',{name:'가람',address:'',office:''}),row('2',{name:'새빛',address:'',office:''})),null));
test('이름만 비슷하면 보류 추천',()=>assert.equal(C.classify(row('1',{address:'',office:''}),row('2',{address:'',office:'',works:[]})).action,'defer'));
test('중복 문의는 1일 이내 + 확인 가능한 식별정보 필요',()=>{const a=row('1',{ref:{type:'inquiry',id:'i1'}}),b=row('2',{ref:{type:'inquiry',id:'i2'},at:'2026-09-02'});assert.equal(C.classify(a,b).action,'inquiry_merge');assert.notEqual(C.classify(a,{...b,at:'2026-09-05'}).action,'inquiry_merge')});
test('과거 수주와 올해 영업은 각각 유지',()=>assert.equal(C.classify(row('1',{at:'2024-09-01'}),row('2')).action,'site_link'));
test('같은 record ID 자기 자신 제외',()=>assert.equal(C.classify(row('1'),row('1')),null));
test('Site와 이미 귀속된 자식 Deal을 중복 후보로 만들지 않음',()=>assert.equal(C.classify(row('o1',{ref:{type:'organization',id:'o1'}}),row('d1',{siteId:'o1'})),null));
test('문의 → 이미 전환된 Deal은 중복 아님',()=>assert.equal(C.classify(row('i1',{ref:{type:'inquiry',id:'i1'},linkedDealId:'d1'}),row('d1')),null));
test('후보 pair key는 순서와 무관',()=>assert.equal(C.pairKey(row('1'),row('2')),C.pairKey(row('2'),row('1'))));
test('미확인 날짜로 중복 Deal 확정 안 함',()=>assert.notEqual(C.classify(row('1',{at:''}),row('2',{at:''})).action,'deal_review'));
test('CRM inline JS / modules parse',()=>{const html=fs.readFileSync(path.join(__dirname,'../crm.html'),'utf8');for(const s of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(s[1]);new vm.Script(fs.readFileSync(path.join(__dirname,'../data-cleanup-ui.js'),'utf8'))});
test('SQL: 원본 삭제 없음, 인증/충돌검사/감사 기록 있음',()=>{const sql=fs.readFileSync(path.join(__dirname,'../sql/20260905_data_cleanup.sql'),'utf8');assert.doesNotMatch(sql,/delete\s+from\s+public\.(deals|inquiries|organizations|contacts)/i);assert.match(sql,/auth\.uid\(\)/);assert.match(sql,/fingerprint' is distinct from/);assert.match(sql,/crm_cleanup_audit/);assert.match(sql,/revoke all on function/)});
