const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(mode){
 const els=new Map(),calls=[],node=id=>{if(!els.has(id))els.set(id,{innerHTML:'',textContent:'',value:'',checked:false,disabled:false,hidden:false,className:'',isConnected:true,appendChild(d){els.set(d.id,d)},remove(){els.delete(this.id)},setAttribute(){},addEventListener(){},showModal(){},focus(){}});return els.get(id)};
 node('dups');node('dupBadge');node('cleanup-action').value='site_link';node('cleanup-target').value='b';node('cleanup-note').value='서로 다른 공종의 같은 단지 확인';node('cleanup-move-date');
 const ctx={console,setTimeout(){},document:{getElementById(id){return els.get(id)||null},createElement(){const d=node('new-dialog');d.remove=function(){els.delete(d.id)};return d},activeElement:{isConnected:true,focus(){}}},B:{deals:[{id:'a',site:'한빛',address:'수원 테스트로',workItems:['옥상'],created:'2026-09-01'},{id:'b',site:'한빛',address:'수원 테스트로',workItems:['도장'],created:'2026-09-01'}],inquiries:[],dups:[]},TOKEN:'test',itemPatch(){return {}},contactInfo(){return {}},detailAddress:x=>x.address||'',workItemsOf:x=>x.workItems.map(key=>({key})),inqCtlPartition(){},paint(){},SB:{async rpc(n,arg){calls.push({n,arg});if(n==='crm_cleanup_state')return {data:{ok:true,reviews:[],links:[],sites:[]}};if(n==='crm_cleanup_preview')return {data:{ok:true,fingerprint:'hash',request_id:'id',source_counts:{deal:1},target_counts:{deal:1},counts:{deal:2},summary:'2개 유지'}};if(mode==='error')return {error:{message:'write failed'}};if(mode==='noack')return {data:{status:'unknown'}};return {data:{ok:true}}}}};
 ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);for(const f of ['data-cleanup.js','data-cleanup-ui.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),ctx);
 return {ctx,calls,node,async prepare(){await ctx.DataCleanupUI.refresh();ctx.DataCleanupUI.open(0);for(const id of ['cleanup-proof','cleanup-error','cleanup-save','cleanup-confirm','cleanup-preview-btn'])node(id);await ctx.DataCleanupUI.preview();node('cleanup-confirm').checked=true}};
}
test('서버 ACK 없이 원본을 수정하지 않는다',async()=>{const h=harness('noack');await h.prepare();const before=JSON.stringify(h.ctx.B);await h.ctx.DataCleanupUI.save();assert.equal(JSON.stringify(h.ctx.B),before);assert.match(h.node('cleanup-error').textContent,/명시적인 완료/);assert.equal(h.node('cleanup-save').disabled,true)});
test('저장 실패는 완료 이력이나 사이트 연결을 만들지 않는다',async()=>{const h=harness('error');await h.prepare();await h.ctx.DataCleanupUI.save();assert.match(h.node('cleanup-error').textContent,/write failed/);assert.equal(h.ctx.B.deals[0].cleanup_site_id,undefined)});
test('미리보기 후 사유 수정은 저장을 차단한다',async()=>{const h=harness('ok');await h.prepare();h.node('cleanup-note').value='변경';await h.ctx.DataCleanupUI.save();assert.equal(h.calls.filter(x=>x.n==='crm_cleanup_apply').length,0)});
test('확인 체크 없이 저장하지 않는다',async()=>{const h=harness('ok');await h.prepare();h.node('cleanup-confirm').checked=false;await h.ctx.DataCleanupUI.save();assert.equal(h.calls.filter(x=>x.n==='crm_cleanup_apply').length,0)});
test('정상 저장 요청은 서버 fingerprint와 idempotency key를 보낸다',async()=>{const h=harness('ok');await h.prepare();await h.ctx.DataCleanupUI.save();const apply=h.calls.find(x=>x.n==='crm_cleanup_apply');assert.equal(apply.arg.p.fingerprint,'hash');assert.equal(apply.arg.p.request_id,'id');assert.equal(apply.arg.p.action,'site_link')});
