const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const F=require('../expansion-flow.js');
const Adapter=require('../operational-adapter.js');
const source={id:'pool-1',sourceOpportunityId:'old-won',siteId:'site',status:'니즈확인'};
const deal={name:'테스트 현장',amount:160000000,work_items:['재도장>외부'],primary_work:'재도장>외부',owner:'담당자'};
const request=()=>F.request(source,deal,{dispatch_id:'receipt'});
const ack=()=>({ok:true,operation:'expansion_quote_convert',source_opportunity_id:'old-won',new_opportunity_id:'new-deal',quote_dispatch_id:'receipt',origin:'expansion',stage_code:'sent',expansion_status:'Pipeline 전환'});
test('확장 상태는 6개이며 과거 상태를 읽을 수 있다',()=>{assert.equal(F.statuses.length,6);assert.equal(F.status({status:'추가 니즈 확인'}),'니즈확인');assert.equal(F.legacy('접촉예정'),'접촉 예정')});
test('연도는 준공·종료·생성일 순서이며 이전 탭은 현재 연도에 따라 이동한다',()=>{
 assert.equal(F.recordYear({completionDate:'2025-12-20'},{updated:'2026-09-07'}),2025);
 assert.equal(F.recordYear({}, {closed_at:'2024-03-01',updated:'2026-09-07'}),2024);
 assert.equal(F.recordYear({}, {created_at:'2023-01-01',updated:'2026-09-07'}),2023);
 assert.equal(F.yearMatch({completionDate:'2024-01-01'}, {}, '이전', 2027),true);
 assert.equal(F.yearMatch({completionDate:'2025-01-01'}, {}, '이전', 2027),false);
});
test('견적 발송 증거 없이 새 Deal을 요청하지 못한다',()=>{assert.throws(()=>F.request(source,deal,{}));assert.throws(()=>F.request(source,deal,null))});
test('새 Deal은 sent / expansion / 원 Deal ID를 갖고 원본을 변경하지 않는다',()=>{const before=JSON.stringify(source);const r=request();assert.equal(r.opportunity.code,'sent');assert.equal(r.opportunity.origin,'expansion');assert.equal(r.opportunity.source_opportunity_id,'old-won');assert.equal(JSON.stringify(source),before);assert.equal(deal.code,undefined)});
test('반복 요청은 동일 idempotency key',()=>assert.equal(request().idempotency_key,request().idempotency_key));
test('완료 상태 또는 연결된 Deal이 있으면 재전환 불가',()=>{for(const s of [{status:'신규 영업기회 생성'},{status:'Pipeline 전환'},{created_opportunity_id:'child'}])assert.throws(()=>F.request({...source,...s},deal,{dispatch_id:'x'}))});
test('금액·대표 공종 누락은 차단',()=>{assert.throws(()=>F.request(source,{...deal,amount:0},{dispatch_id:'x'}));assert.throws(()=>F.request(source,{...deal,primary_work:'옥상>싱글'},{dispatch_id:'x'}))});
test('일반 ok, 빈 응답, 다른 source 또는 receipt ACK를 완료로 처리하지 않는다',()=>{for(const a of [{},null,{ok:true},{...ack(),source_opportunity_id:'wrong'},{...ack(),quote_dispatch_id:'wrong'},{...ack(),stage_code:'first_contact'},{...ack(),new_opportunity_id:'old-won'}])assert.throws(()=>F.acknowledged(a,request()))});
test('정확한 전환 ACK만 수락',()=>assert.equal(F.acknowledged(ack(),request()).new_opportunity_id,'new-deal'));
test('확장 전환은 기존 수주 UUID·발송 증거·공종·금액을 고정한다',()=>{
 const sourceId='11111111-1111-4111-8111-111111111111',dispatchId='22222222-2222-4222-8222-222222222222';
 const payload={source_opportunity_id:sourceId,quote_dispatch_id:dispatchId,idempotency_key:'expansion:'+sourceId,opportunity:{name:'[서울 마포] 테스트아파트',work_name:'옥상 방수',brand:'POUR솔루션',owner:'테스트',amount:1000000,reason:'실제 견적 발송 확인',primary_work:'옥상>싱글',work_items:['옥상>싱글'],work_scope_type:'single',work_summary:'옥상 싱글',office_phone:'02-1234-5678',manager_name:'김관리',manager_mobile:'010-1234-5678',person_key:'mobile:01012345678',origin:'expansion',origin_source:'expansion',source_opportunity_id:sourceId,stage_code:'sent',code:'sent',stage:'컨설팅 자료 발송완료'}};
 const normalized=Adapter.normalize('expansion_quote_convert',sourceId,1,payload);
 assert.equal(normalized.payload.quote_dispatch_id,dispatchId);assert.equal(normalized.payload.opportunity.office_phone,'0212345678');
 assert.throws(()=>Adapter.normalize('expansion_quote_convert',sourceId,1,{...payload,quote_dispatch_id:'draft'}),/EXPANSION_CONVERT_INTENT_NOT_CONNECTED/);
});
test('실패 응답 때 mutation 이전에 검증하고 일반 생성 경로로 빠지지 않는다',()=>{const ui=fs.readFileSync(require.resolve('../expansion-pool.js'),'utf8');assert.ok(ui.indexOf('F.acknowledged(')<ui.indexOf('local.local.createdOpportunityId='));assert.match(ui,/pending.has/);const crm=fs.readFileSync(require.resolve('../crm.html'),'utf8');assert.match(crm,/if\(expansionSource\)\{ExpansionPool.convert[\s\S]*?return;\}/);assert.doesNotMatch(crm,/if\(expansionSource\)expansionSave/);new vm.Script(ui)});
test('확장 전환은 차단된 legacy WRITE_API 대신 멱등 queue를 사용한다',()=>{const ui=fs.readFileSync(require.resolve('../expansion-pool.js'),'utf8');assert.match(ui,/queue\.enqueue\('expansion_quote_convert'/);assert.doesNotMatch(ui,/fetch\(WRITE_API/);});
test('확장 목록은 독립 복합필터·전체연도 기한배지·고정 페이지를 사용한다',()=>{
 const ui=fs.readFileSync(require.resolve('../expansion-pool.js'),'utf8');
 assert.match(ui,/expansionStatusFilter/);
 assert.match(ui,/expansionDueFilter/);
 assert.match(ui,/globalDue/);
 assert.match(ui,/전체연도 기한도래/);
 assert.match(ui,/start=\(page-1\)\*pageSize/);
 assert.match(ui,/← 이전 20건/);
 assert.match(ui,/Pipeline 전환','보류'/);
 assert.doesNotMatch(ui,/y<2024/);
 assert.doesNotMatch(ui,/slice\(0,page\*20\)/);
});
test('확장관리는 상태 보드를 기본으로 하고 상세 목록을 보조 보기로 유지한다',()=>{
 const ui=fs.readFileSync(require.resolve('../expansion-pool.js'),'utf8');
 const css=fs.readFileSync(require.resolve('../expansion-pool.css'),'utf8');
 assert.match(ui,/expansionView\|\|'board'/);
 assert.match(ui,/상태 보드/);
 assert.match(ui,/상세 목록/);
 for(const status of F.statuses)assert.ok(ui.includes(status)||ui.includes('F.statuses'),status);
 assert.match(ui,/cardActions\(r,done\)/);
 assert.match(css,/\.exp-board\{/);
 assert.match(css,/scroll-snap-type/);
});
test('상태 보드와 상세 목록은 같은 확장관리 데이터로 실제 렌더링된다',()=>{
 const root={innerHTML:''},badge={textContent:'',style:{}},rows=F.statuses.map((status,index)=>({id:'pool-'+index,sourceOpportunityId:'source-'+index,site:'검수 현장 '+index,owner:'황윤선',sourceWorkSummary:'옥상 방수',wonAmount:10000000,completionDate:'2026-03-01',nextContactAt:'2026-09-08',status,candidates:['재도장']}));
 const context={console,window:null,document:{getElementById:id=>id==='expansion-root'?root:id==='expansionBadge'?badge:null},ExpansionFlow:F,B:{expansion_events:[],expansion_quote_dispatches:[],deals:[]},G:{expansionOwner:'전체',expansionYear:'전체'},expansionRecords:()=>rows,expansionSourceDeal:()=>({assignee:'황윤선',contract_date:'2026-01-01'}),daysTo:()=>0,repN:x=>x,fmtAmt:x=>Math.round(x/10000)+'만',fmtD:x=>String(x).slice(0,10),paintExpansion:()=>{}};
 context.window=context;vm.createContext(context);new vm.Script(fs.readFileSync(require.resolve('../expansion-pool.js'),'utf8')).runInContext(context);
 context.ExpansionPool.render();assert.equal((root.innerHTML.match(/class="exp-board-column"/g)||[]).length,6);assert.match(root.innerHTML,/검수 현장 0/);assert.match(root.innerHTML,/오늘 접촉/);
 context.G.expansionView='list';context.ExpansionPool.render();assert.match(root.innerHTML,/class="exp-pool-list"/);assert.doesNotMatch(root.innerHTML,/class="exp-board"/);
});
test('서버 migration: 발송증명·트랜잭션 잠금·읽기전용·권한',()=>{const sql=fs.readFileSync(require.resolve('../sql/20260905_expansion_quote_handoff.sql'),'utf8');for(const s of ['for update',"q.status<>'sent'",'provider_receipt_id','crm_expansion_readonly_guard',"'origin','expansion'",'from public,anon,authenticated'])assert.ok(sql.includes(s),s)});
