'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const direct=require('../scripts/crm-inquiry-direct-assign.cjs'),bridge=require('../staging-write/compat-adapter.js'),WriteAck=require('../write-ack.js');
const s=require('../scripts/crm-phase1.cjs');
const inquiry=s.uid(5,5),internal=s.uid(1,1),other=s.uid(1,2),admin=s.uid(1,5),adminAuth=s.mapping.accounts[4].auth_uid;
function envelope(id='DIRECT-ASSIGN-1',patch={}){return {write_id:id,op:'inquiry_assign',actor_id:'FORGED',version:1,payload:{inquiry_id:inquiry,inquiry_row:55,from:'FORGED',to:'TEST INTERNAL_REP',status:'FORGED',changed_by:'FORGED',at:'FORGED',...patch}};}
async function rpc(db,q,account=4){await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);try{return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[q.rpc.p_request_id,q.rpc.p_operation,q.rpc.p_object_id,q.rpc.p_expected_version,JSON.stringify(q.rpc.p_payload)])).rows[0].a;}finally{await db.exec('RESET ROLE');}}
test('direct_assign contract against isolated local PostgreSQL engine',async t=>{const db=await direct.setup();try{await db.exec(direct.approval+direct.candidate);await db.query("UPDATE public.inquiries SET assigned_to=NULL,assigned_at=NULL,status='접수' WHERE id=$1",[inquiry]);
 const identity={project_ref:bridge.project_ref,auth_uid:adminAuth,user_id:admin};
 const first=await bridge.prepare(envelope(),identity);
 await t.test('first assignment resolves approved rep UUID and writes server-owned state/history/audit',async()=>{const a=await rpc(db,first),ui=WriteAck.validate(bridge.validateAck(a,first),envelope());assert.equal(ui.write_id,'DIRECT-ASSIGN-1');assert.equal(ui.intent,'direct_assign');assert.equal(ui.assigned_to,internal);const row=(await db.query('SELECT assigned_to,status FROM public.inquiries WHERE id=$1',[inquiry])).rows[0];assert.deepEqual(row,{assigned_to:internal,status:'배정완료'});const h=(await db.query('SELECT from_owner,to_owner,reason,actor_name FROM public.assignment_history WHERE inquiry_id=$1',[inquiry])).rows[0];assert.deepEqual(h,{from_owner:'미배정',to_owner:'TEST INTERNAL_REP',reason:null,actor_name:'TEST ADMIN'});const audit=(await db.query('SELECT actor_auth_uid,actor_user_id,action,reason FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1',[inquiry])).rows[0];assert.deepEqual(audit,{actor_auth_uid:adminAuth,actor_user_id:admin,action:'direct_assign',reason:null});});
 await t.test('same request replays without duplicate business rows',async()=>{const a=await rpc(db,first);assert.equal(a.replayed,true);assert.equal((await db.query('SELECT count(*)::int n FROM public.assignment_history WHERE inquiry_id=$1',[inquiry])).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1',[inquiry])).rows[0].n,1);});
 await t.test('same request id with another target is 409',async()=>{const changed=await bridge.prepare(envelope('DIRECT-ASSIGN-1',{to:'TEST OTHER_REP',reason:'담당 구역 변경'}),identity);await assert.rejects(rpc(db,changed),e=>e.code==='PT409');});
 await t.test('reassignment without reason is rejected before mutation',async()=>{const q=await bridge.prepare(envelope('DIRECT-ASSIGN-2',{to:'TEST OTHER_REP'}),identity);await assert.rejects(rpc(db,q),e=>e.code==='22023');assert.equal((await db.query('SELECT assigned_to FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].assigned_to,internal);});
 await t.test('reasoned reassignment preserves status and records real server actor',async()=>{await db.query("UPDATE public.inquiries SET status='응대중' WHERE id=$1",[inquiry]);const q=await bridge.prepare(envelope('DIRECT-ASSIGN-3',{to:'TEST OTHER_REP',reason:'  담당 권역 조정  '}),identity),a=await rpc(db,q);assert.equal(a.assigned_to,other);assert.equal(a.status,'응대중');const h=(await db.query('SELECT from_owner,to_owner,reason,actor_name FROM public.assignment_history WHERE inquiry_id=$1 ORDER BY changed_at DESC LIMIT 1',[inquiry])).rows[0];assert.deepEqual(h,{from_owner:'TEST INTERNAL_REP',to_owner:'TEST OTHER_REP',reason:'담당 권역 조정',actor_name:'TEST ADMIN'});});
 await t.test('branch target and non-admin actor cannot enter direct assignment',async()=>{const branch=await bridge.prepare(envelope('DIRECT-ASSIGN-4',{to:'TEST GYEONGNAM'}),identity);await assert.rejects(rpc(db,branch),e=>e.code==='22023');const denied=await bridge.prepare(envelope('DIRECT-ASSIGN-5',{to:'TEST INTERNAL_REP',reason:'테스트'}),{...identity,auth_uid:s.mapping.accounts[1].auth_uid,user_id:other});await assert.rejects(rpc(db,denied,1),e=>e.code==='42501');});
 }finally{await db.close();}});
test('generated guarded apply and evidence-preserving rollback restore the prior contract',async()=>{await direct.build();const db=await direct.setup();try{const before=await direct.capture(db),apply=fs.readFileSync(path.join(direct.dir,'staging-apply.sql'),'utf8'),rollback=fs.readFileSync(path.join(direct.dir,'rollback.sql'),'utf8');await db.exec(apply);await db.query("UPDATE public.inquiries SET assigned_to=NULL,assigned_at=NULL,status='접수' WHERE id=$1",[inquiry]);const q=await bridge.prepare(envelope('ROLLBACK-EVIDENCE'),{project_ref:bridge.project_ref,auth_uid:adminAuth,user_id:admin});await rpc(db,q);await db.exec(rollback);assert.deepEqual(await direct.capture(db),before);assert.equal((await db.query("SELECT count(*)::int n FROM crm_inquiry_direct_archive.command_receipts WHERE operation='inquiry_assign'")).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM crm_inquiry_direct_archive.inquiry_audit_events')).rows[0].n,1);assert.equal((await db.query('SELECT assigned_to FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].assigned_to,internal);}finally{await db.close();}});
