'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(require.resolve('../mobile.html'),'utf8');
function source(name,next){const start=html.indexOf('function '+name+'('),end=html.indexOf('\nfunction '+next+'(',start);return html.slice(start,end);}
function harness(rep,reason){const writes=[],messages=[],q={key:'f6090500-0005-4000-8000-000000000001',rep,status:'접수',raw:{row:7}},field={value:reason||'',focused:false,focus(){this.focused=true}};const c={ADMIN:{assign:[q]},G:{},document:{getElementById:id=>id==='inq-reassign-reason'?field:null},isoNow:()=> '2026-09-06T12:00:00.000Z',pushWrite:(op,payload)=>writes.push({op,payload}),closeSheet(){},toast:x=>messages.push(x),render(){}};vm.createContext(c);vm.runInContext(source('pickAssign','rOverdue'),c);return {c,q,writes,messages,field};}
test('모바일 최초 배정은 사유 없이 기존 payload로 진행',()=>{const h=harness('미배정');h.c.pickAssign(0,'TEST INTERNAL_REP');assert.equal(h.writes.length,1);assert.equal('reason' in h.writes[0].payload,false);assert.equal(h.q.status,'배정완료');});
test('모바일 재배정은 사유가 없으면 로컬 상태와 큐를 변경하지 않음',()=>{const h=harness('TEST INTERNAL_REP');const before=JSON.stringify(h.q);h.c.pickAssign(0,'TEST OTHER_REP');assert.equal(JSON.stringify(h.q),before);assert.equal(h.writes.length,0);assert.match(h.messages[0],/재배정 사유/);assert.equal(h.field.focused,true);});
test('모바일 재배정 사유를 기존 inquiry_assign payload에 추가',()=>{const h=harness('TEST INTERNAL_REP','  지역 담당 조정  ');h.c.pickAssign(0,'TEST OTHER_REP');assert.equal(h.writes.length,1);assert.deepEqual(JSON.parse(JSON.stringify(h.writes[0])),{op:'inquiry_assign',payload:{inquiry_id:h.q.key,inquiry_row:7,from:'TEST INTERNAL_REP',to:'TEST OTHER_REP',status:'배정완료',at:'2026-09-06T12:00:00.000Z',reason:'지역 담당 조정'}});});
test('재배정 시트에만 필수 사유 입력을 표시',()=>{const code=source('assignSheet','pickAssign');assert.match(code,/reassign\?'[^']*inq-reassign-reason/);assert.match(code,/재배정 사유/);assert.match(code,/maxlength="2000"/);});
test('Staging UI transport도 direct_assign만 연결하고 나머지 intent는 차단',()=>{const built=fs.readFileSync(require.resolve('../staging-phase1/mobile.html'),'utf8'),transport=fs.readFileSync(require.resolve('../staging-phase1/transport.js'),'utf8');assert.match(built,/op==='inquiry_assign'.*Phase1\.queue\.enqueue/);assert.match(built,/inq-reassign-reason/);assert.match(transport,/intent:'direct_assign'/);assert.match(transport,/INQUIRY_INTENT_NOT_CONNECTED/);assert.match(transport,/q\.operation==='inquiry_assign'/);});
