const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const I=require('../issue-modal.js'),M=require('../money-input.js');
test('금액 내림차순, 동액이면 장기정체, 원본 순서 보존',()=>{const a=[{amount:10,days:8},{amount:20,days:7},{amount:20,days:18}];assert.deepEqual(I.sorted(a,'amount').map(x=>x.days),[18,7,8]);assert.equal(a[0].amount,10)});
test('기간 미확인은 0일·14일 이상으로 둔갑하지 않는다',()=>assert.deepEqual(I.buckets([{days:7},{days:13},{days:14},{days:null}]),{week:2,long:1,unknown:1}));
const crm=fs.readFileSync(require.resolve('../crm.html'),'utf8');
test('오늘업무는 산정한 관리 배열을 두 업무함과 상세 열기에 그대로 사용한다',()=>{
 assert.match(crm,/TODAY_ADMIN_INQUIRY=X\.inquiry/);assert.match(crm,/TODAY_ADMIN_PIPELINE=X\.pipeline/);
 assert.match(crm,/todayAdminBoard\('inquiry'.*X\.inquiry/);assert.match(crm,/todayAdminBoard\('pipeline'.*X\.pipeline/);
 assert.match(crm,/group==='admin-inquiry'\?TODAY_ADMIN_INQUIRY\[i\]/);assert.match(crm,/group==='admin-pipeline'\?TODAY_ADMIN_PIPELINE\[i\]/);
 assert.match(crm,/IssueModal.bind\('health:noAmount','noAmount',noAmt\)/);assert.match(crm,/IssueModal.bind\('pipe:quick:'/);
});
function harness(){
 const nodes={},writes=[],events=[],patch={},d={id:'one',site:'테스트 아파트',assignee:'황윤선',code:'bidding',amt:100,days:8},G={page:'dash',rep:'황윤선',period:'month'},focus={focus(){events.push('focus')}};
 function node(id=''){let html='';const n={id,value:'',style:{},textContent:'',focus(){},scrollIntoView(){},remove(){delete nodes[id]},querySelector(){return node()},querySelectorAll(){return []}};Object.defineProperty(n,'innerHTML',{get:()=>html,set:s=>{html=s;for(const m of s.matchAll(/\bid="([^"]+)"/g)){nodes[m[1]]=node(m[1]);const tail=s.slice(m.index).split('>')[0];nodes[m[1]].value=(tail.match(/value="([^"]*)"/)||[])[1]||''}}});return n}
 const body={style:{overflow:'auto'},appendChild(n){nodes[n.id]=n}};const c={MoneyInput:M,document:{body,activeElement:focus,createElement:()=>node(),getElementById:id=>nodes[id],querySelectorAll:()=>[]},G,CUR_DETAIL:{kind:'deal',item:{id:'previous'}},location:{href:''},itemPatch:()=>patch,relationshipMeta:x=>({days:x.days,meaningfulAt:x.days==null?'':'2026-08-28'}),actionObj:(x,p)=>p.nextActionObj||x.nextActionObj||null,daysTo:()=>-8,relDaysSince:()=>8,stageAge:()=>20,dealStage:x=>x.code,stageLabel:x=>x,repN:x=>x,oppAmt:x=>x.amt||0,quoteAmt:()=>0,wonAmt:()=>0,fmtAmt:x=>x+'원',towerActive:()=>true,isoNow:()=> '2026-09-05T10:00:00Z',pushWrite:(op,p)=>writes.push({op,p}),saveLocal(){},NextActionPicker:{html:()=>'',read:()=> '전화'},contactInfo:()=>({mobile:'01012345678'}),phoneN:x=>x,dealKey:x=>x.id,openRelationshipMessage:()=>events.push('sms:'+c.CUR_DETAIL.item.id),closeKakaoModal(){},drwDeal:()=>events.push('detail'),drwInq:()=>events.push('inquiry')};
 c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(require.resolve('../issue-modal.js'),'utf8'),c);return {c,nodes,writes,events,patch,d,G,open(kind,rows=[d]){c.IssueModal.bind('test',kind,rows);c.IssueModal.open('test')}};
}
test('카드 클릭은 조회만, 37건 그대로, 닫아도 페이지·필터 유지',()=>{const h=harness(),rows=Array.from({length:37},(_,i)=>({...h.d,id:i}));h.open('nearIdle',rows);rows.push({...h.d,id:'later'});assert.equal(h.nodes['issue-title'].textContent,'수주임박 무활동 · 37건');assert.equal(h.writes.length,0);h.c.IssueModal.close();assert.deepEqual(h.G,{page:'dash',rep:'황윤선',period:'month'});assert.equal(h.c.document.body.style.overflow,'auto');assert.ok(h.events.includes('focus'))});
test('다음 행동 등록은 모달 내부에서 요청하고 페이지 이동하지 않는다',()=>{const h=harness();h.open('nextMissing');h.c.IssueModal.action(0,'next');h.nodes['issue-text'].value='견적 검토 확인';h.nodes['issue-due'].value='2026-09-08';h.c.IssueModal.save();assert.equal(h.writes[0].op,'next_action');assert.equal(h.writes[0].p.text,'견적 검토 확인');assert.equal(h.G.page,'dash');assert.equal(h.d.nextActionObj.due,'2026-09-08')});
test('금액 쉼표를 숫자로 저장, 잘못된 입력은 차단',()=>{const h=harness();h.open('noAmount');h.c.IssueModal.action(0,'amount');h.nodes['issue-amount'].value='abc';h.c.IssueModal.save();assert.equal(h.writes.length,0);h.nodes['issue-amount'].value='1,043,900,000';h.c.IssueModal.save();assert.equal(h.writes[0].p.amount,1043900000)});
test('기한초과 완료는 결과를 받고 중복완료를 막는다',()=>{const h=harness();h.d.nextActionObj={id:'a',text:'확인전화',due:'2026-08-28',type:'전화'};h.open('overdue');h.c.IssueModal.action(0,'complete');h.c.IssueModal.save();assert.equal(h.writes.length,0);h.nodes['issue-result'].value='통화 완료, 견적 검토중';h.c.IssueModal.save();assert.equal(h.writes[0].op,'next_action_complete');assert.equal(h.d.nextActionObj,null);h.c.IssueModal.action(0,'complete');h.nodes['issue-result'].value='다시';h.c.IssueModal.save();assert.equal(h.writes.length,2)});
test('문자는 기존 Composer 재사용, 닫으면 이전 상세 context 복원',()=>{const h=harness();h.open('nearIdle');h.c.IssueModal.action(0,'sms');assert.ok(h.events.includes('sms:one'));assert.equal(h.G.page,'dash');h.c.closeKakaoModal();assert.equal(h.c.CUR_DETAIL.item.id,'previous');assert.equal(h.nodes['issue-modal'].style.visibility,'')});
test('자세히 보기만 Deal 상세를 연다',()=>{const h=harness();h.open('nearIdle');h.c.IssueModal.action(0,'detail');assert.ok(h.events.includes('detail'));assert.equal(h.writes.length,0)});
