const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const build=require('../scripts/build-production-ui.cjs');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
assert.match(source,/^---\r?\nlayout: null\r?\n---/);
assert.match(source,/var APP_BUILD\s*=\s*'\{\{ site\.github\.build_revision \| default: "source" \}\}';/);
assert.doesNotMatch(source,/var APP_BUILD\s*=\s*'20\d{6}/);
assert.match(source,/loaded !== APP_BUILD\) newBuildBanner\(\)/);
assert.match(source,/addEventListener\('focus', mountCurrentBuild\)/);
assert.match(source,/addEventListener\('pageshow', mountCurrentBuild\)/);
assert.match(source,/visibilityState === 'visible'/);
assert.match(source,/setInterval\(mountCurrentBuild, 300000\)/);
const output=build.productionText(source,'index.html');
assert.match(output,/^<!doctype html>/);
assert.match(output,new RegExp(`var APP_BUILD\\s*=\\s*'${build.buildId}';`));
assert.equal(build.buildId,build.sourceCommit.slice(0,12));
const requestAssets=['pc-manager-transport','pc-error-state','inquiry-flow','work-request'];
const requestHtml=requestAssets.map((name,i)=>`<script data-order="${i}" src="./${name}.js?v=previous"></script>`).join('')+'<script src="./unrelated.js?v=keep"></script>';
const requestBuilt=build.productionText(requestHtml,'crm.html');
assert.equal(requestBuilt,requestHtml.replaceAll('?v=previous',`?v=${build.buildId}`),'all contact/request modules refresh together without changing markup or unrelated assets');
assert.equal(build.productionText(requestHtml,'fixture.js'),requestHtml,'runtime source strings are not rewritten as HTML');
const buildSource=fs.readFileSync(path.join(__dirname,'../scripts/build-production-ui.cjs'),'utf8');
assert.match(buildSource,/\['organization-history-reader\.js', 'organization-history-view\.js'\]/);
assert.match(buildSource,/fs\.unlinkSync\(target\)/);
console.log(`PASS production build version derives from commit ${build.buildId}`);
