const fs = require('fs');

const source='아파트스퀘어_감리업무_로드맵_12단계전수검증완료.html';
let html=fs.readFileSync(source,'utf8');

const css=`<style id="stage-checklist-ui">
.checklist-open{margin-top:14px;border:0;background:#f07b45;color:#fff;padding:11px 15px;font-weight:900;font-size:11px;cursor:pointer;box-shadow:0 4px 0 #b95024}.checklist-open:hover{transform:translateY(-1px)}.checklist-open strong{margin-left:8px;background:rgba(255,255,255,.22);padding:3px 7px;border-radius:999px}
.check-dialog{width:min(680px,calc(100vw - 28px));max-height:min(760px,calc(100vh - 28px));border:0;padding:0;background:#fbfaf7;color:#14231d;box-shadow:0 30px 90px rgba(10,30,22,.35);animation:check-pop .2s ease-out}.check-dialog::backdrop{background:rgba(7,24,18,.62);backdrop-filter:blur(4px)}@keyframes check-pop{from{opacity:0;transform:translateY(18px) scale(.97)}to{opacity:1;transform:none}}
.check-dialog header{position:sticky;top:0;z-index:2;background:#123c31;color:#fff;padding:22px 24px 18px;display:flex;justify-content:space-between;gap:20px;align-items:start}.check-dialog header small{display:block;color:#b9ddcf;font-weight:900;letter-spacing:.08em;margin-bottom:5px}.check-dialog h3{font-size:23px;margin:0}.dialog-close{width:36px;height:36px;border:1px solid rgba(255,255,255,.35);background:transparent;color:#fff;font-size:20px;cursor:pointer}.check-progress{padding:16px 24px 0}.check-progress-line{height:7px;background:#dfe6e2;overflow:hidden}.check-progress-line i{display:block;height:100%;background:#f07b45;transition:width .2s}.check-progress p{display:flex;justify-content:space-between;font-size:11px;font-weight:800}.required-list{list-style:none;margin:0;padding:10px 24px 24px}.required-list li{border-top:1px solid #dfe5e1}.required-list label{display:grid;grid-template-columns:28px 1fr;gap:12px;padding:16px 2px;cursor:pointer;align-items:start}.required-list input{width:20px;height:20px;accent-color:#f07b45}.required-list b{display:block;font-size:13px;margin-bottom:4px}.required-list span{font-size:11px;color:#647069;line-height:1.55}.check-note{margin:0 24px 24px;padding:13px 15px;background:#fff3e9;border-left:4px solid #f07b45;font-size:11px;line-height:1.55}.checklist-ok .check-note{background:#eaf5ef;border-color:#16845f}.checklist-ok .check-progress-line i{background:#16845f}@media(max-width:700px){.check-dialog header{padding:18px}.required-list{padding:8px 18px 20px}.check-progress{padding:14px 18px 0}}
@media print{.check-dialog,.checklist-open{display:none!important}}
</style>`;
html=html.replace('</head>',css+'</head>');

const dialog=`<dialog class="check-dialog" id="checkDialog"><header><div><small id="checkStep"></small><h3 id="checkTitle"></h3></div><button type="button" class="dialog-close" id="checkClose" aria-label="체크리스트 닫기">×</button></header><div class="check-progress"><div class="check-progress-line"><i id="checkBar"></i></div><p><span>필수 확인 진행률</span><strong id="checkCount"></strong></p></div><ul class="required-list" id="requiredList"></ul><p class="check-note" id="checkNote"></p></dialog>`;
html=html.replace('<script>',dialog+'<script>');

const data=`const stageChecklists=[
[{t:'단지와 문의자 확인',d:'아파트명·정확한 주소·문의자 이름·연락처가 확보됐는지 확인합니다.'},{t:'요청공종 확인',d:'누수·도장·방수 등 요청공종과 문제 위치를 구체적으로 적습니다.'},{t:'의결·예산·희망일정 확인',d:'장기수선계획·의결상태·예산범위·희망 착수시기를 확인합니다.'},{t:'기존 자료 확인',d:'도면·하자사진·과거 공사 및 견적 이력이 있는지 확인합니다.'},{t:'담당자와 다음 연락일 지정',d:'CRM 담당자와 다음 연락일을 입력하고 잔디 전송까지 확인합니다.'}],
[{t:'방문 목적 확정',d:'현장진단에서 답해야 할 질문과 확인범위를 먼저 정합니다.'},{t:'출입조건과 동행자 확인',d:'출입방법·주차·옥상키·기계실 등 접근권한과 동행자를 확인합니다.'},{t:'도면·이력 준비',d:'최신 도면과 기존 하자·보수·민원 이력을 준비합니다.'},{t:'사진 촬영계획 준비',d:'전경·중경·근접·위치표시 사진의 필수 촬영목록을 정합니다.'},{t:'사실과 추정 분리 기록',d:'관찰한 사실, 추정 원인, 추가 확인사항을 구분해 남깁니다.'}],
[{t:'진단결과 승인',d:'현장진단 기록과 사진이 검토·승인됐는지 확인합니다.'},{t:'공사범위와 제외범위 확정',d:'포함·제외·별도협의 범위를 문장으로 명확히 고정합니다.'},{t:'산출조건 확인',d:'공종·물량·인원·일수·감리방식과 부가세 조건을 확인합니다.'},{t:'견적서 교차검수',d:'현장명·금액·기간·특약이 산출근거 및 미리보기와 일치하는지 봅니다.'},{t:'발송과 이력 저장',d:'최종 PDF·수신자·발송일·버전과 비교견적 여부를 기록합니다.'}],
[{t:'최종견적 일치 확인',d:'계약금액·범위·기간이 최종 승인 견적과 같은지 확인합니다.'},{t:'계약당사자 정보 확인',d:'발주자·수급자·대표자·주소·사업자정보를 확인합니다.'},{t:'특약과 책임범위 확인',d:'감리범위·보고방식·변경·해지·지체 관련 조건을 확인합니다.'},{t:'날인과 회수 확인',d:'검토승인·쌍방 날인·원본 발송 및 회수상태를 기록합니다.'},{t:'프로젝트 등록',d:'계약서와 최종견적을 현장폴더에 저장하고 다음 담당자에게 공유합니다.'}],
[{t:'최신 도면 고정',d:'현장조건과 대조한 최신 도면에 버전·승인일을 표시합니다.'},{t:'공법·자재기준 확정',d:'공종별 공법, 제품, 규격, 품질기준과 대체 승인절차를 정합니다.'},{t:'물량근거 확보',d:'구간·치수·산식·할증·제외수량의 근거를 남깁니다.'},{t:'상호 간섭 검토',d:'공종 순서와 다른 공종·시설물과의 간섭을 확인합니다.'},{t:'승인본 분리 보관',d:'검토본과 승인본을 구분하고 입찰에 사용할 파일을 고정합니다.'}],
[{t:'입찰조건 고정',d:'참가자격·공사기간·보증·제출서류·평가기준을 확정합니다.'},{t:'동일자료 배포',d:'모든 업체가 같은 도면·시방·수량·현설자료를 받았는지 확인합니다.'},{t:'현설 일정과 장소 확인',d:'일시·장소·출입·안전수칙과 담당 연락처를 공지합니다.'},{t:'참석·질의 기록',d:'참석명부와 업체별 질의, 공식 답변 및 배포일을 남깁니다.'},{t:'변경사항 일괄 통지',d:'정정자료가 있으면 모든 참가업체에 같은 시점에 전달합니다.'}],
[{t:'선정근거 기록',d:'금액·기술·실적·서류 등 업체선정 근거를 남깁니다.'},{t:'도급조건 확인',d:'공사금액·기간·보증·지체상금·범위가 낙찰조건과 일치하는지 확인합니다.'},{t:'착공서류 확보',d:'공정표·안전계획·현장대리인·작업자·승인자재 서류를 받습니다.'},{t:'현장 계정과 권한 확인',d:'아임웹 현장·고객그룹·계정을 만들고 해당 현장만 보이는지 시험합니다.'},{t:'비밀번호 비노출 확인',d:'계정 전달 절차만 기록하고 비밀번호 값은 문서와 화면에서 제외합니다.'}],
[{t:'당일 공정과 HOLD 확인',d:'오늘 작업구역·예정 공정·은폐 전 확인시점을 확정합니다.'},{t:'전회 미종결 재확인',d:'이전 지적의 동일 위치 사진·담당자·약속기한을 준비합니다.'},{t:'안전·자재·품질 점검',d:'안전→자재→품질→공정→보양·민원 순으로 현장을 확인합니다.'},{t:'판정과 책임자 기록',d:'진행·조건부·보류 판정과 조치담당자·기한·재확인일을 남깁니다.'},{t:'현장 종료·보고 확인',d:'현장대리인과 결과를 다시 읽고 일지·사진·다음 방문목적을 확정합니다.'}],
[{t:'실제 공정률 확인',d:'보고 공정률을 현장사진·작업일보·시공수량과 대조합니다.'},{t:'지적사항 상태 확인',d:'신규·진행·완료·보류 지적마다 담당자와 기한을 확인합니다.'},{t:'기성청구 근거 확인',d:'청구수량이 승인범위와 실제 완료수량 안에 있는지 검토합니다.'},{t:'보류·공제항목 분리',d:'미시공·하자·서류미비 항목을 기성 승인에서 분리합니다.'},{t:'승인과 발송 기록',d:'검토의견·승인자·날인본·발송일과 다음 재확인일을 남깁니다.'}],
[{t:'예비검사 완료',d:'전체 구간·취약부·민원구간을 돌고 펀치리스트를 확정합니다.'},{t:'동일 위치 보완확인',d:'전회 지적을 같은 위치에서 완료·재보완·경과관찰로 판정합니다.'},{t:'계약·변경범위 대조',d:'계약범위와 승인변경이 실제 시공 및 준공서류에 반영됐는지 확인합니다.'},{t:'합동검사 서명 확보',d:'입대의·시공사와 최종 결과, 잔여사항, 참석자 서명을 확보합니다.'},{t:'준공계 발송증빙',d:'날인·스캔·제본·우편 또는 이메일 발송증빙까지 확인합니다.'}],
[{t:'공사잔금 조건 확인',d:'준공승인·하자보증·보완종결 후 시공사 잔금 조건을 확인합니다.'},{t:'감리비 별도 산정',d:'공사잔금과 감리비를 구분하고 계약금액·기지급액·잔액을 대조합니다.'},{t:'청구정보 확인',d:'사업자정보·공급가액·세액·청구일을 증빙과 맞춥니다.'},{t:'세금계산서 발행 확인',d:'발행 대상·이메일·작성일·금액을 확인하고 발행이력을 남깁니다.'},{t:'입금과 정산 마감',d:'입금일·금액·미수 여부를 기록하고 현장 정산을 마감합니다.'}],
[{t:'접수내용과 책임선 확인',d:'하자·민원·후속요청의 사실, 계약범위, 담당 주체를 구분합니다.'},{t:'증거와 이력 확보',d:'최초 발생부터 현재까지 사진·문서·협의내용을 시간순으로 모읍니다.'},{t:'회신·조치기한 지정',d:'공문·소명·보완 등 처리방법과 담당자·기한을 확정합니다.'},{t:'종결증빙 확인',d:'보완사진·서명·발송내역 등 제3자가 확인 가능한 증거를 남깁니다.'},{t:'완료현장과 재계약 관리',d:'접근권한·완료메뉴를 정리하고 만족도·추가공사·재계약 기회를 기록합니다.'}]
];`;
html=html.replace('const store=sessionStorage;',data+'\nconst store=sessionStorage;');

html=html.replace("const store=sessionStorage;const stepsEl=document.getElementById('steps'),stageHeadEl=document.getElementById('stageHead'),worksEl=document.getElementById('works'),completeEl=document.getElementById('complete'),fieldJumpEl=document.getElementById('fieldJump'),printBtnEl=document.getElementById('printBtn');", "const store=sessionStorage;const stepsEl=document.getElementById('steps'),stageHeadEl=document.getElementById('stageHead'),worksEl=document.getElementById('works'),completeEl=document.getElementById('complete'),fieldJumpEl=document.getElementById('fieldJump'),printBtnEl=document.getElementById('printBtn'),checkDialogEl=document.getElementById('checkDialog'),requiredListEl=document.getElementById('requiredList'),checkStepEl=document.getElementById('checkStep'),checkTitleEl=document.getElementById('checkTitle'),checkBarEl=document.getElementById('checkBar'),checkCountEl=document.getElementById('checkCount'),checkNoteEl=document.getElementById('checkNote'),checkCloseEl=document.getElementById('checkClose');");

html=html.replace("let state=JSON.parse(store.getItem('integrated-roadmap')||'{}'),current=", "let checklistState=JSON.parse(store.getItem('integrated-required-checks')||'{}'),state=JSON.parse(store.getItem('integrated-roadmap')||'{}'),current=");
html=html.replace('const done=x.works.every((_,w)=>state[k(i,w)]?.done),blocked=', 'const done=x.works.every((_,w)=>state[k(i,w)]?.done)&&stageChecklistDone(i),blocked=');
html=html.replace("<p>주 책임 · ${s.owner}</p></div><div class=\"gates\">", "<p>주 책임 · ${s.owner}</p><button type=\"button\" class=\"checklist-open\" data-open-checklist>필수 체크리스트 <strong>${checklistProgress(current)}</strong></button></div><div class=\"gates\">");
html=html.replace("completeEl.innerHTML=`<b>단계 완료 ${done}/${s.works.length}</b> · 업무를 모두 완료하면", "completeEl.innerHTML=`<b>업무 ${done}/${s.works.length} · 필수체크 ${checklistProgress(current)}</b> · 업무와 필수 체크를 모두 완료하면");

const functions=`function checklistProgress(si){const list=stageChecklists[si]||[],done=list.filter((_,i)=>checklistState['c'+si+'-'+i]).length;return done+'/'+list.length}function stageChecklistDone(si){const list=stageChecklists[si]||[];return list.length>0&&list.every((_,i)=>checklistState['c'+si+'-'+i])}function renderChecklist(){const list=stageChecklists[current]||[],done=list.filter((_,i)=>checklistState['c'+current+'-'+i]).length;checkStepEl.textContent='STEP '+String(current+1).padStart(2,'0')+' · 필수 확인';checkTitleEl.textContent=stages[current].n+' 체크리스트';checkCountEl.textContent=done+' / '+list.length;checkBarEl.style.width=(list.length?done/list.length*100:0)+'%';requiredListEl.innerHTML=list.map((x,i)=>'<li><label><input type="checkbox" data-required="'+i+'" '+(checklistState['c'+current+'-'+i]?'checked':'')+'><span><b>'+x.t+'</b>'+x.d+'</span></label></li>').join('');checkNoteEl.textContent=done===list.length?'필수 확인 완료 · 이 단계의 모든 업무까지 완료하면 다음 단계로 넘길 수 있습니다.':'미확인 '+(list.length-done)+'개 · 필수 항목을 모두 확인해야 단계가 완료로 표시됩니다.';checkDialogEl.classList.toggle('checklist-ok',done===list.length)}function openChecklist(){renderChecklist();checkDialogEl.showModal()}
`;
html=html.replace('function selectStage(i){',functions+'function selectStage(i){');
html=html.replace("stepsEl.addEventListener('click'", "stageHeadEl.addEventListener('click',e=>{if(e.target.closest('[data-open-checklist]'))openChecklist()});requiredListEl.addEventListener('change',e=>{if(!e.target.matches('[data-required]'))return;checklistState['c'+current+'-'+e.target.dataset.required]=e.target.checked;store.setItem('integrated-required-checks',JSON.stringify(checklistState));renderChecklist();render()});checkCloseEl.addEventListener('click',()=>checkDialogEl.close());checkDialogEl.addEventListener('click',e=>{if(e.target===checkDialogEl)checkDialogEl.close()});stepsEl.addEventListener('click'");

for(const marker of ['stageChecklists=[','data-open-checklist','function renderChecklist()','integrated-required-checks','checkDialogEl.showModal()'])if(!html.includes(marker))throw new Error('missing '+marker);
const outputs=['아파트스퀘어_감리업무_실전운영템플릿.html','아파트스퀘어_감리업무_로드맵.html','아파트스퀘어_감리업무_로드맵_12단계전수검증완료.html','아파트스퀘어_감리업무_로드맵_단계별필수체크리스트.html'];
for(const file of outputs){fs.writeFileSync(file,html,'utf8');console.log('updated '+file)}
