'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),purge=require('../../inquiry-purge/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),twenty=purge.twenty,auditBefore=purge.auditAfter;
const twentyOne=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text, 'waiting_context'::text, 'inquiry_reclassify'::text, 'inquiry_status'::text, 'inquiry_trash'::text, 'inquiry_restore'::text, 'inquiry_purge'::text, 'inquiry_followup'::text]))`;
const auditAfter=`CHECK (action = ANY (ARRAY['direct_assign'::text, 'direct_reassign'::text, 'inquiry_unassign'::text, 'inquiry_reclassify'::text, 'inquiry_hold'::text, 'inquiry_trash'::text, 'inquiry_restore'::text, 'inquiry_purge'::text, 'inquiry_followup'::text]))`;
const helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function adapter(){let text=purge.adapter();
 const ops="'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge']";one(text,ops,'operations');text=text.replace(ops,"'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'normalize marker');text=text.replace(marker," function normalizeInquiryFollowup(objectId,payload){if(payload.inquiry_id!==objectId)fail('INVALID_INQUIRY_FOLLOWUP_COMMAND');const allowed=['inquiry_id','due_at','reason'];if(Object.keys(payload).some(k=>!allowed.includes(k))||!/^\\d{4}-\\d{2}-\\d{2}$/.test(payload.due_at)||payload.reason!=='담당자 연기')fail('INQUIRY_FOLLOWUP_INTENT_NOT_CONNECTED');return {due_at:payload.due_at,reason:'담당자 연기'};}\n"+marker);
 const sentinel="['inquiry_assign','inquiry_unassign','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','favorite_set','opportunity_touch'].includes(operation)";one(text,sentinel,'sentinel');text=text.replace(sentinel,"['inquiry_assign','inquiry_unassign','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup','favorite_set','opportunity_touch'].includes(operation)");
 const dispatch="else if(operation==='inquiry_purge')normalized=normalizePurge(objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);";one(text,dispatch,'dispatch');text=text.replace(dispatch,"else if(operation==='inquiry_purge')normalized=normalizePurge(objectId,payload);else if(operation==='inquiry_followup')normalized=normalizeInquiryFollowup(objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);");
 const ack="  if(command.operation==='inquiry_followup'&&(ack.next_action_date!==command.payload.due_at||!(ack.previous_next_action_date===null||/^\\d{4}-\\d{2}-\\d{2}$/.test(ack.previous_next_action_date))||typeof ack.status!=='string'||typeof ack.updated_at!=='string'||!UUID.test(ack.inquiry_audit_event_id)))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','ACK return');return text.replace('  return ack;}',ack+'  return ack;}');}
function overlay(){let text=purge.overlay();
 const connected="'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge']";one(text,connected,'connected');text=text.replace(connected,"'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup']");
 const state='holdIntent=false,trashIntent=false,restoreIntent=false,purgeIntent=false;const versions';one(text,state,'state');text=text.replace(state,'holdIntent=false,trashIntent=false,restoreIntent=false,purgeIntent=false,followupIntent=false;const versions');
 const rows="  function inquiryRows(){return [root.B&&root.B.inquiries,root.B&&root.B.inquiryTrash,root.INQUIRIES,root.ADMIN&&root.ADMIN.inquiries].filter(Array.isArray);}\n";one(text,rows,'rows');text=text.replace(rows,rows+"  function applyFollowupAck(q){for(const rows of inquiryRows())for(const i of rows)if(String(i.id||i.inquiry_id||i.key)===String(q.object_id))for(const x of [i,i.raw].filter(Boolean)){x.next_action_date=x.nextActionDate=x.due=q.ack.next_action_date;x.updated_at=q.ack.updated_at;}}\n");
 const sync="if(q.operation==='inquiry_purge')applyPurgeAck(q);";one(text,sync,'sync');text=text.replace(sync,sync+"if(q.operation==='inquiry_followup')applyFollowupAck(q);");
 const push="root.pushWrite=function(op,payload){if(op==='inquiry_trash'&&!trashIntent)throw error('INQUIRY_TRASH_INTENT_NOT_CONNECTED');if(op==='inquiry_restore'&&!restoreIntent)throw error('INQUIRY_RESTORE_INTENT_NOT_CONNECTED');if(op==='inquiry_purge'&&!purgeIntent)throw error('INQUIRY_PURGE_INTENT_NOT_CONNECTED');";one(text,push,'push');text=text.replace(push,push+"if(op==='inquiry_followup'&&!followupIntent)throw error('INQUIRY_FOLLOWUP_INTENT_NOT_CONNECTED');");
 const wrapper="  if(typeof root.inqCtlHardDelete==='function'){const original=root.inqCtlHardDelete;root.inqCtlHardDelete=function(){const previous=purgeIntent;purgeIntent=true;try{return original.apply(this,arguments);}finally{purgeIntent=previous;}};}";one(text,wrapper,'purge wrapper');text=text.replace(wrapper,wrapper+"\n  if(typeof root.applyTodayPostponeM==='function'){const original=root.applyTodayPostponeM;root.applyTodayPostponeM=function(){const t=root.G&&root.G._today&&root.G._today[root.G.execTask],previous=followupIntent;followupIntent=!!(t&&t.kind==='inquiry');try{return original.apply(this,arguments);}finally{followupIntent=previous;}};}");
 const end='  return Object.freeze({versions,connected,versionFor,get compound(){return compound;},get actionIntent(){return actionIntent;}});';one(text,end,'install end');const compat=`  if(typeof root.inquiryViewM==='function'){const original=root.inquiryViewM;root.inquiryViewM=function(q){const v=original.apply(this,arguments),due=q&&(q.next_action_date||q.nextActionDate||q.due)||null;v.next_action_date=v.nextActionDate=v.due=due;return v;};}
  if(typeof root.buildToday==='function'&&typeof root.myInquiriesM==='function'){const originalBuild=root.buildToday;root.buildToday=function(){const originalMine=root.myInquiriesM,today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),all=originalMine.call(root);root.myInquiriesM=function(){return all.filter(q=>!String(q.next_action_date||q.nextActionDate||q.due||'').slice(0,10)||String(q.next_action_date||q.nextActionDate||q.due).slice(0,10)<=today);};try{return originalBuild.apply(this,arguments).map(t=>{if(t.kind!=='inquiry')return t;const q=all.find(x=>String(x.key||x.id||x.inquiry_id)===String(t.ref)),due=String(q&&(q.next_action_date||q.nextActionDate||q.due)||'').slice(0,10);if(!due)return t;const days=Math.floor((Date.parse(today+'T00:00:00Z')-Date.parse(due+'T00:00:00Z'))/86400000);return {...t,due_at:due,bucket:days>0?'overdue':'today',p:days>0?1:2,why:days>0?'문의 후속 · '+days+'일 초과':'문의 후속 · 오늘'};}).sort((a,b)=>a.p-b.p).slice(0,12);}finally{root.myInquiriesM=originalMine;}};}
`;
 return text.replace(end,compat+end);}
function applySql(){return `SET crm.inquiry_followup_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.inquiry_followup_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_purge_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_purge_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_followup_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twenty}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry followup prerequisite drift';END IF;END $guard$;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_inquiry_purge_20260906;ALTER FUNCTION public.crm_write_command_v2_inquiry_purge_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_inquiry_purge_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign','inquiry_reclassify','inquiry_hold','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup'));
${helper()}
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN IF p_operation='inquiry_followup' THEN IF p_expected_version IS DISTINCT FROM 0 THEN RAISE EXCEPTION 'invalid inquiry management version sentinel' USING ERRCODE='22023';END IF;RETURN crm_security.crm_inquiry_followup_command_v1(p_request_id,p_object_id,p_payload);END IF;RETURN crm_security.crm_write_command_v2_inquiry_purge_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ BEGIN IF has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_inquiry_followup_command_v1(uuid,uuid,jsonb)','EXECUTE') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twentyOne}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry followup post-apply drift';END IF;END $post$;COMMIT;`;}
function rollbackSql(){return `SET crm.inquiry_followup_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.inquiry_followup_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_purge_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_followup_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regnamespace('crm_inquiry_followup_archive') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twentyOne}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry followup rollback drift';END IF;END $guard$;
CREATE SCHEMA crm_inquiry_followup_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_inquiry_followup_archive FROM PUBLIC,anon,authenticated,service_role;CREATE TABLE crm_inquiry_followup_archive.audit_events AS SELECT * FROM crm_security.inquiry_audit_events WHERE action='inquiry_followup';CREATE TABLE crm_inquiry_followup_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation='inquiry_followup';REVOKE ALL ON crm_inquiry_followup_archive.audit_events,crm_inquiry_followup_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;DELETE FROM crm_security.command_receipts WHERE operation='inquiry_followup';DELETE FROM crm_security.inquiry_audit_events WHERE action='inquiry_followup';
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_inquiry_followup_command_v1(uuid,uuid,jsonb);ALTER FUNCTION crm_security.crm_write_command_v2_inquiry_purge_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign','inquiry_reclassify','inquiry_hold','inquiry_trash','inquiry_restore','inquiry_purge'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_inquiry_purge_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_followup_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twenty}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry followup rollback verification drift';END IF;END $post$;COMMIT;`;}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-purge.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-purge.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-purge.sql','rollback-after-purge.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_PURGE_NOT_APPLIED',prerequisites:['inquiry-purge/20260906'],operations:['inquiry_followup'],ui_coverage_candidate:['I08','O08T'],intent:'assigned_inquiry_scalar_followup_date',blocked_meanings:['generic_next_action_create','automatic_notification','response_update'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_mobile:sha(fs.readFileSync(path.join(root,'mobile.html'))),purge_manifest:sha(fs.readFileSync(path.join(root,'sql/inquiry-purge/20260906/manifest.json'))),inquiry_contracts:sha(fs.readFileSync(path.join(root,'docs/operational-cutover-20260906/inquiry-management-contracts.md')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,build,twenty,twentyOne,auditBefore,auditAfter};
