/* Loaded last: replaces only transport/read entry points reached by the final UI handlers. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.OperationalUI=api;api.install(root);}})(typeof window==='undefined'?globalThis:window,function(){
 'use strict';
 const connected=new Set(['opportunity_work_set','inquiry_assign','inquiry_unassign','service_change']);
 const companion=new Set(['activity','next_action','next_action_complete']);
 function error(code){const e=Error(code);e.code=code;return e;}
 function idFor(op,p){return op.startsWith('inquiry_')?p?.inquiry_id:p?.opportunity_id;}
 function shell(scoped){return {contract_version:2,generated_at:new Date().toISOString(),deals:(scoped.deals||[]).map(d=>({...d,opportunity_id:d.id,code:d.stage_code,currentBusiness:d.brand,current_business:d.brand})),inquiries:scoped.inquiries||[],dups:[],users:[],sales_people:[],activities:[],sites:[],contacts:[],leads:[],asq_projects:[],_operationalRead:{coverage:'scoped_partial',n8n_requests:0}};}
 function install(root){if(!root.Phase1||!root.OperationalAdapter)throw error('OPERATIONAL_LOAD_ORDER');let compound=null;const versions=new Map(),seenAcks=new Set();
  function versionFor(id,payload){if(Number.isSafeInteger(payload?.expected_version)&&payload.expected_version>=0)return payload.expected_version;const value=versions.get(id);if(!Number.isSafeInteger(value))throw error('READ_VERSION_REQUIRED');return value;}
  function syncQueue(){root.WRITE_Q=root.Phase1.queue.list();for(const q of root.WRITE_Q){if(q.status==='done'&&q.ack&&!seenAcks.has(q.request_id)){seenAcks.add(q.request_id);if(Number.isSafeInteger(q.ack.version))versions.set(q.object_id,q.ack.version);}}if(typeof root.updateSyncBadge==='function')root.updateSyncBadge();if(typeof root.updatePendingBadge==='function')root.updatePendingBadge();}
  root.pushWrite=function(op,payload){if(compound==='service_change'&&companion.has(op))return 'absorbed:'+op;if(!connected.has(op))throw error('OP_NOT_CONNECTED:'+op);const id=idFor(op,payload);const expected=op.startsWith('inquiry_')?0:versionFor(id,payload);const q=root.Phase1.queue.enqueue(op,id,expected,payload);syncQueue();root.Phase1.queue.flush().catch(e=>{if(root.console?.warn)root.console.warn('Operational queue: '+e.message);}).finally(syncQueue);return q.request_id;};
  if(typeof root.commitBiz==='function'){const original=root.commitBiz;root.commitBiz=function(){compound='service_change';try{return original.apply(this,arguments);}finally{compound=null;}};}
  async function scoped(){const response=await root.Phase1.read('operational',{limit:100});for(const d of response.data.deals||[])if(Number.isSafeInteger(d.version))versions.set(d.id,d.version);return response.data;}
  root.loadData=async function(){if(!root.TOKEN||!root.ME)return;try{const data=await scoped(),bundle=shell(data);if(typeof root.applyBundle==='function')root.applyBundle(bundle);if(root.document){const load=root.document.getElementById('load'),live=root.document.getElementById('live'),err=root.document.getElementById('err');if(load)load.style.display='none';if(live){live.className='live on';live.textContent='Staging · 문의 scoped read · Pipeline 필드 제한';live.title='Supabase crm_read_scoped_v2 · n8n 미사용';}if(err){err.textContent='문의 조회와 승인된 4개 저장 op만 연결됨 · 나머지 기능은 fail-closed';err.style.display='block';}}return bundle;}catch(e){if(root.document){const err=root.document.getElementById('err');if(err){err.textContent=e.message;err.style.display='block';}}throw e;}};
  root.loadLive=async function(){if(!root.TOKEN)return;try{const data=await scoped(),bundle=shell(data);root.BUNDLE=bundle;root.DEALS=(bundle.deals||[]).map(d=>typeof root.normalizeDeal==='function'?root.normalizeDeal({id:d.id,server_id:d.id,site_id:d.site_id,owner_id:d.owner_id,nm:'현장명 미제공',rep:'',code:d.stage_code||'first_contact',sub:d.brand||'',currentBusiness:d.brand||'',originBusiness:d.brand||'',primaryWork:d.primary_work||'',workItems:d.work_items||[],workScopeType:d.work_scope_type||'',workSummary:d.work_summary||'',version:d.version,tl:[]}):d);root.LIVE=true;root.LOAD_ERR='문의 scoped read 연결 · Pipeline 상세 projection은 아직 제한됨';if(typeof root.rebuildAdmin==='function')root.rebuildAdmin();if(typeof root.render==='function'&&root.CUR!=='flow'&&root.CUR!=='login')root.render();return bundle;}catch(e){root.LIVE=false;root.LOAD_ERR=e.message;if(typeof root.render==='function')root.render();throw e;}};
  root.addEventListener('phase1:queue',syncQueue);root.addEventListener('phase1:identity-cleared',()=>{versions.clear();seenAcks.clear();});syncQueue();
  return Object.freeze({versions,connected,versionFor,get compound(){return compound;}});
 }
 return Object.freeze({install,connected:Object.freeze([...connected]),companion:Object.freeze([...companion])});
});

