'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname,root=path.resolve(dir,'../../..'),base=require('../../message-log-compat/20260906/build.cjs');
const read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function one(source,from,to,label){if(!source.includes(from))throw Error('relationship cadence build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=base.adapter();
 source=one(source,"'expansion_pool_update','customer_support_action','message_log'])","'expansion_pool_update','customer_support_action','message_log','relationship_hold','relationship_response'])",'operations');
 source=one(source,' function normalizeMessageLog(objectId,payload){',` function normalizeRelationship(operation,objectId,payload){
  if(operation==='relationship_hold'){const allowed=['opportunity_id','person_key','hold_until','reason','next_action_type','next_action_text','next_due_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(String(payload.hold_until||''))||payload.next_due_at!==payload.hold_until)fail('RELATIONSHIP_HOLD_INTENT_NOT_CONNECTED');return {person_key:payload.person_key==null||String(payload.person_key).trim()===''?null:text(String(payload.person_key),1,200,'INVALID_PERSON_KEY'),hold_until:date(payload.hold_until),reason:text(payload.reason,1,1000,'INVALID_RELATIONSHIP_REASON'),next_action_type:text(payload.next_action_type,1,100,'INVALID_NEXT_TYPE'),next_action_text:text(payload.next_action_text,1,500,'INVALID_NEXT_TEXT'),next_due_at:date(payload.next_due_at)};}
  const allowed=['opportunity_id','person_key','response_at','response_kind','cancel_pending_cadence','activity_type','activity_note','activity_result','activity_occurred_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||payload.cancel_pending_cadence!==true||payload.activity_type!==payload.response_kind||payload.activity_occurred_at!==payload.response_at||typeof payload.response_at!=='string'||!/^\\d{4}-\\d{2}-\\d{2}T/.test(payload.response_at))fail('RELATIONSHIP_RESPONSE_INTENT_NOT_CONNECTED');return {person_key:payload.person_key==null||String(payload.person_key).trim()===''?null:text(String(payload.person_key),1,200,'INVALID_PERSON_KEY'),response_kind:text(payload.response_kind,1,100,'INVALID_RESPONSE_KIND'),activity_type:text(payload.activity_type,1,100,'INVALID_ACTIVITY_TYPE'),activity_note:text(payload.activity_note,1,4000,'INVALID_ACTIVITY_NOTE'),activity_result:text(payload.activity_result,1,8000,'INVALID_ACTIVITY_RESULT'),activity_occurred_at:payload.activity_occurred_at,cancel_pending_cadence:true};
 }
 function normalizeMessageLog(objectId,payload){`,'normalizer');
 source=one(source,"else if(operation==='message_log')normalized=normalizeMessageLog(objectId,payload);else normalized=normalizeTrash", "else if(operation==='message_log')normalized=normalizeMessageLog(objectId,payload);else if(operation==='relationship_hold'||operation==='relationship_response')normalized=normalizeRelationship(operation,objectId,payload);else normalized=normalizeTrash",'normalize route');
 source=one(source,"  if(command.operation==='message_log'&&",`  if(command.operation==='relationship_hold'&&(ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||ack.hold_until!==command.payload.hold_until||!UUID.test(ack.relationship_event_id)||!UUID.test(ack.next_action_id)||!Array.isArray(ack.cancelled_action_ids)||!UUID.test(ack.audit_event_id)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='relationship_response'&&(ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||!UUID.test(ack.relationship_event_id)||!UUID.test(ack.message_log_id)||!UUID.test(ack.activity_id)||(ack.next_action_id!==null&&!UUID.test(ack.next_action_id))||typeof ack.linked_next_cancelled!=='boolean'||!Array.isArray(ack.cancelled_action_ids)||!UUID.test(ack.audit_event_id)||typeof ack.business_at!=='string'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='message_log'&&`,'ACK');
 return source;
}
function overlay(){let source=base.overlay();
 source=one(source,"'expansion_pool_update','customer_support_action','message_log'])","'expansion_pool_update','customer_support_action','message_log','relationship_hold','relationship_response'])",'connected');
 source=one(source,'messageOutcome=null,messageIntent=false;','messageOutcome=null,messageIntent=false,holdOutcome=null,cadenceHoldIntent=false,responseCapture=null,cadenceResponseIntent=false,suppressedResponseActivity=null;','state');
 source=one(source,'  function applyMessageAck(q){',`  function applyRelationshipAck(q){const a=q.ack;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.version=a.version;if(q.operation==='relationship_hold'){d.wakeUpAt=d.wake_up_at=d.relationshipHoldUntil=d.relationship_hold_until=a.hold_until;d.waitingReason=d.waiting_reason=q.payload.reason;d.relationshipState=d.relationship_state='hold';d.nextAction=d.nextActionObj={id:a.next_action_id,type:q.payload.next_action_type,text:q.payload.next_action_text,due:q.payload.next_due_at,due_at:q.payload.next_due_at,status:'open'};}else{d.lastCustomerResponseAt=d.last_customer_response_at=a.business_at;d.outboundAttempts=d.outbound_attempts=0;d.relationshipState=d.relationship_state='active';for(const logs of [d.messageLogs,d.message_logs,root.B&&root.B.messageLogs,root.B&&root.B.message_logs])if(Array.isArray(logs))for(const m of logs)if(String(m.id||m.message_log_id)===String(a.message_log_id)){m.responseAt=m.response_at=a.business_at;m.responseKind=m.response_kind=q.payload.response_kind;m.responseActivityId=m.response_activity_id=a.activity_id;}if(a.linked_next_cancelled&&d.nextAction&&String(d.nextAction.id)===String(a.next_action_id))d.nextAction.status='cancelled';}}}
  function applyMessageAck(q){`,'ACK hydrator');
 source=one(source,"if(q.operation==='message_log')applyMessageAck(q);}","if(q.operation==='message_log')applyMessageAck(q);if(q.operation==='relationship_hold'||q.operation==='relationship_response')applyRelationshipAck(q);}",'ACK route');
 source=one(source,'root.pushWrite=function(op,payload){if(messageOutcome',`root.pushWrite=function(op,payload){if(holdOutcome&&op==='relationship_hold'){holdOutcome.parent=payload;return 'absorbed:relationship_hold';}if(holdOutcome&&op==='next_action'){holdOutcome.next=payload;return 'absorbed:next_action';}if(responseCapture&&op==='relationship_response'){responseCapture.parent=payload;return 'absorbed:relationship_response';}if(responseCapture&&op==='activity'){responseCapture.activity=payload;return 'absorbed:activity';}if(suppressedResponseActivity&&op==='activity'&&String(payload&&payload.opportunity_id)===suppressedResponseActivity.opportunity_id&&String(payload&&payload.type)===suppressedResponseActivity.type&&String(payload&&payload.occurred_at)===suppressedResponseActivity.occurred_at){suppressedResponseActivity=null;return 'absorbed:activity';}if(op==='relationship_hold'&&!cadenceHoldIntent)throw error('RELATIONSHIP_HOLD_INTENT_NOT_CONNECTED');if(op==='relationship_response'&&!cadenceResponseIntent)throw error('RELATIONSHIP_RESPONSE_INTENT_NOT_CONNECTED');if(messageOutcome`,'compound capture');
 source=one(source,"  if(typeof root.pickToday==='function')",`  function queueRelationship(operation,payload){const prior=operation==='relationship_hold'?cadenceHoldIntent:cadenceResponseIntent;if(operation==='relationship_hold')cadenceHoldIntent=true;else cadenceResponseIntent=true;try{return root.pushWrite(operation,payload);}finally{if(operation==='relationship_hold')cadenceHoldIntent=prior;else cadenceResponseIntent=prior;}}
  function wrapRelationshipHold(name){if(typeof root[name]!=='function')return;const original=root[name];root[name]=function(){if(holdOutcome)throw error('RELATIONSHIP_HOLD_NESTED_INTENT');holdOutcome={parent:null,next:null};try{const result=original.apply(this,arguments),c=holdOutcome;if(!c.parent||!c.next)throw error('RELATIONSHIP_HOLD_COMPOUND_REQUIRED');const payload={...c.parent,next_action_type:c.next.type,next_action_text:c.next.text,next_due_at:String(c.next.due_at||c.next.due||'').slice(0,10)};holdOutcome=null;queueRelationship('relationship_hold',payload);return result;}finally{holdOutcome=null;}};}
  wrapRelationshipHold('relV8Hold');wrapRelationshipHold('relHoldM');
  function queueResponse(c,activity){const p=c&&c.parent;if(!p||!activity)throw error('RELATIONSHIP_RESPONSE_COMPOUND_REQUIRED');const at=String(activity.occurred_at||activity.at||p.response_at||'');queueRelationship('relationship_response',{...p,response_at:at,response_kind:activity.type,activity_type:activity.type,activity_note:String(activity.note||''),activity_result:String(activity.result||''),activity_occurred_at:at,cancel_pending_cadence:true});}
  if(typeof root.addActivity==='function'){const original=root.addActivity;root.addActivity=function(){if(arguments[4]!==true)return original.apply(this,arguments);if(responseCapture)throw error('RELATIONSHIP_RESPONSE_NESTED_INTENT');const prior=responseCapture;responseCapture={parent:null,activity:null};try{const row=original.apply(this,arguments),c=responseCapture;if(!c.parent){responseCapture=prior;if(c.activity)root.pushWrite('activity',c.activity);return row;}queueResponse(c,c.activity||row);return row;}finally{responseCapture=prior;}};}
  if(typeof root.logActivity==='function'){const original=root.logActivity;root.logActivity=function(){if(responseCapture)throw error('RELATIONSHIP_RESPONSE_NESTED_INTENT');const prior=responseCapture;responseCapture={parent:null,activity:null};try{const row=original.apply(this,arguments),c=responseCapture;if(c.parent){const d=root.CUR_DETAIL&&root.CUR_DETAIL.item,activity={opportunity_id:d&&d.id,type:row.type,note:row.note,result:row.result,occurred_at:row.at,meaningful_contact:true};queueResponse(c,activity);suppressedResponseActivity={opportunity_id:String(activity.opportunity_id),type:String(activity.type),occurred_at:String(activity.occurred_at)};}return row;}finally{responseCapture=prior;}};}
  if(typeof root.pickToday==='function')`,'relationship handlers');
 return source;
}
function transport(){return base.transport();}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-message-log.sql':applySql(),'rollback-before-message-log.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':transport()};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md',...Object.keys(generated)],sources=['sql/message-log-compat/20260906/manifest.json','crm.html','mobile.html','sql/20260905_relationship_messaging.sql','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operations:['relationship_hold','relationship_response'],ui_coverage_candidate:['M05'],prerequisite:'message-log-compat/20260906',surface:'pc_mobile',contracts:{hold:{absorbed_child:'next_action',effects:['private hold event','Deal wake_up_at/version','replacement open Next Action','audit','receipt'],activity:'none; preserve current UI'},response:{absorbed_child:'meaningful activity',outbound_link:'latest same Deal/person sent and unresponded user-attested message outcome at or before activity',next_cancel:'only linked outcome open next_action_id',effects:['message response marker','meaningful Activity','private response event','Deal activity/contact timestamps/version','audit','receipt']}},authority:'server UUID actor/contact/time; bounded Activity business occurrence only',read_derivations:['last_outbound_at','outbound_attempts','last_customer_response_at','relationship hold aliases','message response_at/response_kind'],blocked:['direct unwrapped relationship writes','provider delivery inference','unrelated Next Action cancellation','synthetic hold Activity'],implementation_present:true,rollback:'relationship events/responses/receipts archived; M02 write/read layer restored',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,transport,applySql,rollbackSql,build};
