-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.
BEGIN;
SET LOCAL crm.relationship_cadence_ref='rprechiaglyjaydkmxsu';SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='90s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.relationship_cadence_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regclass('crm_security.relationship_events') IS NULL OR to_regprocedure('crm_security.crm_relationship_cadence_command_v1(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_pre_relationship_cadence_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_operational_source_v1_pre_relationship_cadence_20260906(text,uuid,integer)') IS NULL OR to_regnamespace('crm_relationship_cadence_archive') IS NOT NULL THEN RAISE EXCEPTION 'relationship cadence rollback drift';END IF;END $guard$;
LOCK TABLE crm_security.command_receipts IN ACCESS EXCLUSIVE MODE;
CREATE SCHEMA crm_relationship_cadence_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_relationship_cadence_archive FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE crm_relationship_cadence_archive.events AS TABLE crm_security.relationship_events;
CREATE TABLE crm_relationship_cadence_archive.message_responses AS SELECT id,response_at,response_kind,response_activity_id FROM crm_security.message_outcomes WHERE response_at IS NOT NULL;
CREATE TABLE crm_relationship_cadence_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation IN ('relationship_hold','relationship_response');
REVOKE ALL ON crm_relationship_cadence_archive.events,crm_relationship_cadence_archive.message_responses,crm_relationship_cadence_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;
DELETE FROM crm_security.command_receipts WHERE operation IN ('relationship_hold','relationship_response');
DROP FUNCTION public.crm_operational_source_v1(text,uuid,integer);DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_relationship_cadence_command_v1(uuid,text,uuid,integer,jsonb);DROP TABLE crm_security.relationship_events;
ALTER TABLE crm_security.message_outcomes DROP COLUMN response_activity_id,DROP COLUMN response_kind,DROP COLUMN response_at;
ALTER FUNCTION crm_security.crm_operational_source_v1_pre_relationship_cadence_20260906(text,uuid,integer) SET SCHEMA public;ALTER FUNCTION public.crm_operational_source_v1_pre_relationship_cadence_20260906(text,uuid,integer) RENAME TO crm_operational_source_v1;
ALTER FUNCTION crm_security.crm_write_command_v2_pre_relationship_cadence_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA public;ALTER FUNCTION public.crm_write_command_v2_pre_relationship_cadence_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;
REVOKE EXECUTE ON FUNCTION public.crm_operational_source_v1(text,uuid,integer) FROM PUBLIC,anon,service_role;GRANT EXECUTE ON FUNCTION public.crm_operational_source_v1(text,uuid,integer) TO authenticated;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation=ANY(ARRAY['opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup','opportunity_create','lineage_link','attachment_prepare','attachment_complete','expansion_pool_update','expansion_note','customer_support_action','message_log']::text[]));
DO $post$ BEGIN IF to_regclass('crm_security.relationship_events') IS NOT NULL OR to_regprocedure('crm_security.crm_relationship_cadence_command_v1(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='crm_security' AND table_name='message_outcomes' AND column_name IN ('response_at','response_kind','response_activity_id')) OR EXISTS(SELECT 1 FROM crm_security.command_receipts WHERE operation IN ('relationship_hold','relationship_response')) THEN RAISE EXCEPTION 'relationship cadence rollback verification drift';END IF;END $post$;
COMMIT;
