-- STAGING ONLY rollback. Archives candidate data; does not touch frozen commands.
BEGIN;
SET LOCAL search_path=pg_catalog;
SET LOCAL crm.operational_go_ref='rprechiaglyjaydkmxsu';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.operational_go_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('crm_security.crm_write_command_v2_pre_go_20260907(uuid,text,uuid,integer,jsonb)') IS NULL THEN RAISE EXCEPTION 'operational GO rollback drift';END IF;END $guard$;
CREATE SCHEMA crm_operational_go_archive AUTHORIZATION postgres;
REVOKE ALL ON SCHEMA crm_operational_go_archive FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE crm_operational_go_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation IN('inquiry_consultant','assign','contact_upsert','contact_relationship','contact_move','rep_manager_comment');
CREATE TABLE crm_operational_go_archive.user_capabilities AS TABLE crm_security.user_capabilities;
CREATE TABLE crm_operational_go_archive.inquiry_routing AS TABLE crm_security.inquiry_routing;
CREATE TABLE crm_operational_go_archive.contact_compat_state AS TABLE crm_security.contact_compat_state;
CREATE TABLE crm_operational_go_archive.rep_manager_comments AS TABLE crm_security.rep_manager_comments;
REVOKE ALL ON ALL TABLES IN SCHEMA crm_operational_go_archive FROM PUBLIC,anon,authenticated,service_role;
DELETE FROM crm_security.command_receipts WHERE operation IN('inquiry_consultant','assign','contact_upsert','contact_relationship','contact_move','rep_manager_comment');
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);
ALTER FUNCTION crm_security.crm_write_command_v2_pre_go_20260907(uuid,text,uuid,integer,jsonb) SET SCHEMA public;
ALTER FUNCTION public.crm_write_command_v2_pre_go_20260907(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;
DROP FUNCTION public.crm_operational_source_v1(text,uuid,integer);
ALTER FUNCTION crm_security.crm_operational_source_v1_pre_go_20260907(text,uuid,integer) SET SCHEMA public;
ALTER FUNCTION public.crm_operational_source_v1_pre_go_20260907(text,uuid,integer) RENAME TO crm_operational_source_v1;
DROP FUNCTION crm_security.crm_operational_go_command_v1(uuid,text,uuid,integer,jsonb);
DROP TABLE crm_security.rep_manager_comments;
DROP TABLE crm_security.contact_compat_state;
DROP TABLE crm_security.inquiry_routing;
DROP TABLE crm_security.user_capabilities;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;
ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation=ANY(ARRAY['opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup','opportunity_create','lineage_link','attachment_prepare','attachment_complete','expansion_pool_update','expansion_note','customer_support_action','message_log','relationship_hold','relationship_response']::text[]));
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.crm_operational_source_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.crm_operational_source_v1(text,uuid,integer) TO authenticated;
COMMIT;
