'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const reachable=require('../../reachable-operations-bundle/20260906/build.cjs');
const create=require('../../pipeline-opportunity-create/20260906/build.cjs');
const response=require('../../inquiry-response-progress/20260906/build.cjs');
const inquiryPipeline=require('../../inquiry-pipeline-lineage/20260906/build.cjs');
const inquiryProgress=require('../../inquiry-stage-progress/20260906/build.cjs');
const inquiryAction=require('../../inquiry-action-check/20260906/build.cjs');
const technicalTransfer=require('../../technical-inquiry-transfer/20260906/build.cjs');
const attachment=require('../../attachment-compat/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const read=p=>fs.readFileSync(path.join(root,p),'utf8').replace(/\r\n?/g,'\n');
const customerApply='sql/customer-asset-bundle/20260906/candidate.sql',customerRollback='sql/customer-asset-bundle/20260906/rollback.sql';
function unwrap(sql,label){return reachable.unwrap(sql.replace(/\r\n?/g,'\n'),label);}
const twentyFive=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text, 'waiting_context'::text, 'inquiry_reclassify'::text, 'inquiry_status'::text, 'inquiry_trash'::text, 'inquiry_restore'::text, 'inquiry_purge'::text, 'inquiry_followup'::text, 'opportunity_create'::text, 'lineage_link'::text, 'attachment_prepare'::text, 'attachment_complete'::text]))`;
function post(mode,options={}){if(mode==='apply')return `DO $cutover_candidate_post$ BEGIN
 IF to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL
  OR to_regprocedure('public.crm_operational_source_v1(text,uuid,integer)') IS NULL
  OR to_regprocedure('crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)') IS NULL
  ${options.skipResponse?'':'OR to_regprocedure(\'crm_security.crm_inquiry_response_command_v1(uuid,uuid,jsonb)\') IS NULL'}
  ${options.skipInquiryPipeline?'':"OR to_regprocedure('crm_security.crm_inquiry_pipeline_promote_command_v1(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_lineage_link_command_v1(uuid,uuid,integer,jsonb)') IS NULL"}
  ${options.skipInquiryProgress||options.skipInquiryPipeline?'':"OR to_regprocedure('crm_security.crm_inquiry_stage_progress_command_v1(uuid,uuid,jsonb)') IS NULL"}
  ${options.skipInquiryAction||options.skipInquiryProgress||options.skipInquiryPipeline?'':"OR to_regprocedure('crm_security.crm_inquiry_action_command_v1(uuid,text,uuid,jsonb)') IS NULL"}
  ${options.skipTechnical||options.skipInquiryAction||options.skipInquiryProgress||options.skipInquiryPipeline?'':"OR to_regprocedure('crm_security.crm_technical_inquiry_transfer_command_v1(uuid,uuid,jsonb)') IS NULL"}
  ${options.skipAttachment||options.skipTechnical||options.skipInquiryAction||options.skipInquiryProgress||options.skipInquiryPipeline?'':"OR to_regprocedure('crm_security.crm_attachment_command_v1(uuid,text,uuid,jsonb)') IS NULL OR to_regclass('crm_security.deal_attachments') IS NULL"}
  OR to_regprocedure('public.crm_contacts_scoped_v2(uuid)') IS NULL
  OR md5(pg_get_functiondef('public.crm_contacts_scoped_v2(uuid)'::regprocedure))<>'7e811c93e73ba945a0dfea164da55fcd'
  OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${options.skipInquiryPipeline?create.twentyTwo:options.skipAttachment||options.skipTechnical?inquiryPipeline.twentyThree:twentyFive}$expected$
  OR has_function_privilege('authenticated','crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)','EXECUTE')
  OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE')
 THEN RAISE EXCEPTION 'operational cutover cumulative apply drift'; END IF;
END $cutover_candidate_post$;`;
 return `DO $cutover_candidate_rollback_post$ BEGIN
 IF to_regprocedure('crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_inquiry_response_command_v1(uuid,uuid,jsonb)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_inquiry_pipeline_promote_command_v1(uuid,text,uuid,integer,jsonb)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_inquiry_stage_progress_command_v1(uuid,uuid,jsonb)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_inquiry_action_command_v1(uuid,text,uuid,jsonb)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_technical_inquiry_transfer_command_v1(uuid,uuid,jsonb)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_attachment_command_v1(uuid,text,uuid,jsonb)') IS NOT NULL
  OR to_regprocedure('public.crm_operational_source_v1(text,uuid,integer)') IS NOT NULL
  OR md5(replace(replace(pg_get_functiondef('public.crm_contacts_scoped_v2(uuid)'::regprocedure),chr(13)||chr(10),chr(10)),chr(13),chr(10)))<>'1a58be86503cb53bdc3a9a784eb4add2'
 THEN RAISE EXCEPTION 'operational cutover cumulative rollback drift'; END IF;
END $cutover_candidate_rollback_post$;`;
}
function compose(mode,options={}){const parts=['-- LOCAL CUMULATIVE REVIEW CANDIDATE ONLY. Separate Staging approval is required.','-- Target: netform-crm-staging / rprechiaglyjaydkmxsu. Production and external workflow endpoints are forbidden.','BEGIN;','SET LOCAL search_path=pg_catalog;',"SET LOCAL lock_timeout='3s';","SET LOCAL statement_timeout='240s';","SET LOCAL crm.customer_asset_ref='rprechiaglyjaydkmxsu';"];
 if(mode==='apply'){parts.push('-- ===== APPLY REACHABLE 21-OP BUNDLE =====',unwrap(reachable.compose('apply',{localPersonalCandidate:options.localPersonalCandidate}),'reachable apply'),'-- ===== APPLY DIRECT OPPORTUNITY CREATE =====',unwrap(create.applySql(),'opportunity create apply'),'-- ===== APPLY DEAL CONTACT READ =====',unwrap(read(customerApply),'customer read apply'));if(!options.skipResponse)parts.push('-- ===== APPLY INQUIRY RESPONSE PROGRESS =====',unwrap(response.applySql(),'inquiry response apply'));if(!options.skipInquiryPipeline)parts.push('-- ===== APPLY INQUIRY PIPELINE + LINEAGE =====',unwrap(inquiryPipeline.applySql(),'inquiry pipeline apply'));if(!options.skipInquiryPipeline&&!options.skipInquiryProgress)parts.push('-- ===== APPLY PC INQUIRY STAGE PROGRESS =====',unwrap(inquiryProgress.applySql(),'inquiry progress apply'));if(!options.skipInquiryPipeline&&!options.skipInquiryProgress&&!options.skipInquiryAction)parts.push('-- ===== APPLY PC INQUIRY NEXT + COMPLETE + CHECK =====',unwrap(inquiryAction.applySql(),'inquiry action/check apply'));if(!options.skipInquiryPipeline&&!options.skipInquiryProgress&&!options.skipInquiryAction&&!options.skipTechnical)parts.push('-- ===== APPLY TECHNICAL INQUIRY TRANSFER =====',unwrap(technicalTransfer.applySql(),'technical inquiry transfer apply'));
  if(!options.skipInquiryPipeline&&!options.skipInquiryProgress&&!options.skipInquiryAction&&!options.skipTechnical&&!options.skipAttachment)parts.push('-- ===== APPLY ATTACHMENT PREPARE COMPLETE + READY READ =====',unwrap(attachment.applySql(),'attachment compatibility apply'));
 }else if(mode==='rollback'){if(!options.skipInquiryPipeline&&!options.skipInquiryProgress&&!options.skipInquiryAction&&!options.skipTechnical&&!options.skipAttachment)parts.push('-- ===== ROLLBACK ATTACHMENT PREPARE COMPLETE + READY READ =====',unwrap(attachment.rollbackSql(),'attachment compatibility rollback'));if(!options.skipInquiryPipeline&&!options.skipInquiryProgress&&!options.skipInquiryAction&&!options.skipTechnical)parts.push('-- ===== ROLLBACK TECHNICAL INQUIRY TRANSFER =====',unwrap(technicalTransfer.rollbackSql(),'technical inquiry transfer rollback'));if(!options.skipInquiryPipeline&&!options.skipInquiryProgress&&!options.skipInquiryAction)parts.push('-- ===== ROLLBACK PC INQUIRY NEXT + COMPLETE + CHECK =====',unwrap(inquiryAction.rollbackSql(),'inquiry action/check rollback'));if(!options.skipInquiryPipeline&&!options.skipInquiryProgress)parts.push('-- ===== ROLLBACK PC INQUIRY STAGE PROGRESS =====',unwrap(inquiryProgress.rollbackSql(),'inquiry progress rollback'));if(!options.skipInquiryPipeline)parts.push('-- ===== ROLLBACK INQUIRY PIPELINE + LINEAGE =====',unwrap(inquiryPipeline.rollbackSql(),'inquiry pipeline rollback'));parts.push('-- ===== ROLLBACK INQUIRY RESPONSE PROGRESS =====',unwrap(response.rollbackSql(),'inquiry response rollback'),'-- ===== ROLLBACK DEAL CONTACT READ =====',unwrap(read(customerRollback),'customer read rollback'),'-- ===== ROLLBACK DIRECT OPPORTUNITY CREATE =====',unwrap(create.rollbackSql(),'opportunity create rollback'),'-- ===== ROLLBACK REACHABLE 21-OP BUNDLE =====',unwrap(reachable.compose('rollback',{localPersonalRollback:options.localPersonalRollback}),'reachable rollback'));
 }else throw Error('mode must be apply or rollback');
 parts.push(post(mode,options),'COMMIT;','');return parts.join('\n');}
function build(){const apply=compose('apply'),rollback=compose('rollback'),adapter=attachment.adapter(),overlay=attachment.overlay(),transport=attachment.transport();
 fs.mkdirSync(dir,{recursive:true});for(const [name,value] of Object.entries({'staging-apply.sql':apply,'rollback.sql':rollback,'operational-adapter.candidate.js':adapter,'operational-overlay.candidate.js':overlay,'transport.candidate.js':transport}))fs.writeFileSync(path.join(dir,name),value);
 const files=['build.cjs','db.test.cjs','review.md','staging-readonly-preflight-20260906.json','staging-apply.sql','rollback.sql','operational-adapter.candidate.js','operational-overlay.candidate.js','transport.candidate.js'];
 const sources=['sql/reachable-operations-bundle/20260906/manifest.json','sql/pipeline-opportunity-create/20260906/manifest.json','sql/inquiry-response-progress/20260906/manifest.json','sql/inquiry-pipeline-lineage/20260906/manifest.json','sql/inquiry-stage-progress/20260906/manifest.json','sql/inquiry-action-check/20260906/manifest.json','sql/technical-inquiry-transfer/20260906/manifest.json','sql/attachment-compat/20260906/manifest.json','sql/customer-asset-bundle/20260906/manifest.json','sql/customer-asset-bundle/20260906/candidate.sql','sql/customer-asset-bundle/20260906/rollback.sql'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CUMULATIVE_25_OP_PLUS_INQUIRY_RESPONSES_PIPELINE_LINEAGE_PC_PROGRESS_ACTION_CHECK_TECHNICAL_TRANSFER_ATTACHMENTS_AND_CONTACT_READ_NOT_APPLIED',classification:'DERIVED_SAFE_COMPONENTS_REQUIRING_STAGING_JWT_E2E',staging_readonly_preflight:'PASS',staging_readonly_preflight_file:'staging-readonly-preflight-20260906.json',operations:[...reachable.finalOperations,'opportunity_create','lineage_link','attachment_prepare','attachment_complete'],internal_intents:['inquiry_assign/response_progress','inquiry_assign/response_next_week_retry','inquiry_assign/response_missed_retry','opportunity_create/inquiry_promote_create','opportunity_create/technical_inquiry_transfer','transition/inquiry_promote_existing','inquiry_status/progress','next_action/inquiry_next_set','next_action_complete/inquiry_next_complete','stage_check/inquiry_check'],read_additions:['deal_contact_timeline','inquiry_response_history','lineage_first_deal_resolution','inquiry_stage_history_activity_next_action','inquiry_checklist_and_action_history','deal_ready_attachments'],transactionality:{apply:'single_transaction',rollback:'single_transaction_reverse_order',rollback_runtime_limit:'PRE_OPPORTUNITY_CREATE_OR_INQUIRY_PURGE_USE;_INQUIRY_PROGRESS_ACTION_TECHNICAL_TRANSFER_AND_ATTACHMENT_EVIDENCE_PRESERVED;_STORAGE_BYTES_NEVER_SQL_DELETED'},frozen_operations_changed_semantically:false,blocked_meanings:['branch_inquiry_promote','inquiry_terminal_or_hold_from_pc_progress','expansion_convert','contact_upsert','contact_relationship','contact_move','site_1n_timeline','attachment_expired_pending_storage_api_cleanup'],staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(files.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};
 fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={compose,build,unwrap};
