'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname,root=path.resolve(dir,'../../..'),baseDir=path.join(root,'sql','operational-cutover-candidate','20260906');
const read=file=>fs.readFileSync(file,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function replaceOne(source,from,to,label){if(!source.includes(from))throw Error('closed-won build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=read(path.join(baseDir,'operational-adapter.candidate.js'));
 source=replaceOne(source,' function normalizeClose(objectId,payload){',' function normalizeCloseNonwon(objectId,payload){','nonwon rename');
 source=replaceOne(source,' function normalize(operation,objectId,expectedVersion,payload){',` function normalizeClose(objectId,payload){if(payload&&payload.outcome!=='won')return normalizeCloseNonwon(objectId,payload);const allowed=['opportunity_id','from','to','stage_code','at','transition_date','note','reason','stage_context','stage_contexts','contract_amount','completion_date','outcome','closed_at','won_amount'],s=payload&&payload.stage_context,f=s&&s.fields;if(!object(payload)||Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||payload.from!=='completion'||payload.to!=='won'||payload.stage_code!=='completion'||payload.outcome!=='won'||payload.won_amount!==payload.contract_amount||payload.won_amount!==f?.contract_amount||payload.completion_date!==f?.completion_date||s.from!=='completion'||s.to!=='won'||s.transition_date!==payload.transition_date||s.terminal!==true||!object(f)||Object.keys(f).some(k=>!['completion_date','completion_checks','contract_amount'].includes(k))||!/^\\d{4}-\\d{2}-\\d{2}$/.test(payload.transition_date)||!/^\\d{4}-\\d{2}-\\d{2}$/.test(f.completion_date)||!Array.isArray(f.completion_checks)||f.completion_checks.length!==2||!['공사 완료','준공검사 완료'].every(x=>f.completion_checks.includes(x))||!Number.isSafeInteger(f.contract_amount)||f.contract_amount<=0||typeof payload.note!=='string'||!payload.note.trim()||payload.note.length>16000||s.memo!=null&&(typeof s.memo!=='string'||s.memo.length>8000))fail('CLOSE_INTENT_NOT_CONNECTED');return {from:'completion',outcome:'won',transition_date:payload.transition_date,completion_date:f.completion_date,completion_checks:f.completion_checks.slice(),won_amount:f.contract_amount,note:payload.note.trim(),memo:String(s.memo||'').trim()||null};}
 function normalize(operation,objectId,expectedVersion,payload){`,'won normalizer');
 source=replaceOne(source,"  if(command.operation==='close'&&(ack.previous_version",`  if(command.operation==='close'&&command.payload.outcome==='won'&&(ack.stage_code!=='won'||ack.won_amount!==command.payload.won_amount||ack.completion_date!==command.payload.completion_date||ack.expansion_source_deal_id!==command.object_id||typeof ack.expansion_next_contact_at!=='string'||!UUID.test(ack.won_event_id)))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='close'&&(ack.previous_version`,'won ACK');
 return source;
}
function overlay(){let source=read(path.join(baseDir,'operational-overlay.candidate.js'));
 source=replaceOne(source,"if(closeCompound&&op==='activity')return 'absorbed:'+op;","if(closeCompound&&(op==='activity'||op==='expansion_pool_upsert'))return 'absorbed:'+op;",'close children');
 source=replaceOne(source,"d.badfit_type=a.badfit_type;d.nextAction", "d.badfit_type=a.badfit_type;if(a.outcome==='won'){d.stage_code=d.code='won';d.won_amount=d.wonAmount=a.won_amount;d.completion_date=a.completion_date;}d.nextAction",'close ACK hydration');
 source=replaceOne(source,"inquiries:scoped.inquiries||[],dups:[]", "inquiries:scoped.inquiries||[],expansion_pool:scoped.expansion_pool||[],expansionPool:scoped.expansion_pool||[],dups:[]",'shell expansion');
 source=replaceOne(source,"won_amount:d.outcome==='won'?Number(d.amount||0):0,outcome:", "won_amount:d.won_amount==null?(d.outcome==='won'?Number(d.amount||0):0):Number(d.won_amount),completion_date:d.completion_date||null,outcome:",'mobile won hydration');
 return source;
}
function transport(){let source=read(path.join(baseDir,'transport.candidate.js'));
 source=replaceOne(source,"const [deals,inquiries]=await Promise.all([collect('deal_core'),collect('inquiry_core')]);\n   return {contract_version:1,resource,coverage:'complete_for_actor_scope',scope:'actor_authorized_rows_only',data:{contract_version:3,deals,inquiries}};", "const [deals,inquiries,expansion_pool]=await Promise.all([collect('deal_core'),collect('inquiry_core'),collect('expansion_pool')]);\n   return {contract_version:1,resource,coverage:'complete_for_actor_scope',scope:'actor_authorized_rows_only',data:{contract_version:4,deals,inquiries,expansion_pool}};",'transport domains');
 return source;
}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-operational-cutover.sql':applySql(),'rollback-before-operational-cutover.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':transport()};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);
 const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','ui.test.cjs','db.test.cjs','review.md','staging-readonly-preflight-20260906.json',...Object.keys(generated)];
 const sources=['sql/operational-cutover-candidate/20260906/manifest.json','stage-transition.js','stage-transition-ui.js','crm.html','mobile.html','sql/20260905_expansion_management.sql','docs/operational-cutover-20260906/pipeline-lifecycle-contracts.md'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operation:'close',intent:'won',ui_coverage_candidate:['P04W','P16'],prerequisite:'operational-cutover-candidate/20260906',absorbed_children:['activity','expansion_pool_upsert'],server_rules:{from_stage:'completion',required_checks:['공사 완료','준공검사 완료'],won_amount:'positive bigint separate from expected amount',completion_date:'required and not after transition date',next_contact_days:30,pool_fields:'server-derived from Deal UUID/site/owner/work'},private_relations:['crm_security.deal_won_events','crm_security.expansion_pool'],read_additions:['deal_core.won_amount','deal_core.completion_date','expansion_pool actor-scoped domain'],rollback_runtime_limit:'BEFORE_ANY_DEAL_WON_EVENT',staging_readonly_preflight:'PASS',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};
 fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,transport,applySql,rollbackSql,build};
