'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),personal=require('../../personal-state-compat/20260906/build.cjs'),cutover=require('../../operational-cutover-candidate/20260906/build.cjs'),won=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
async function scalar(db,sql,params=[]){return (await db.query(sql,params)).rows[0];}
async function storage(db){await db.exec(`CREATE SCHEMA IF NOT EXISTS storage;CREATE TABLE IF NOT EXISTS storage.buckets(id text PRIMARY KEY,name text NOT NULL,public boolean NOT NULL DEFAULT false,file_size_limit bigint,allowed_mime_types text[]);CREATE TABLE IF NOT EXISTS storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text NOT NULL REFERENCES storage.buckets(id),name text NOT NULL,owner_id text,metadata jsonb,UNIQUE(bucket_id,name));GRANT USAGE ON SCHEMA storage TO authenticated;GRANT INSERT ON storage.objects TO authenticated;`);}
async function setup(){const db=await personal.setup();await storage(db);await db.exec(cutover.compose('apply',{localPersonalCandidate:true}));await db.exec(won.applySql());return db;}
async function actorDeal(db,index=0){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[index].auth_uid}'`);return scalar(db,"SELECT d.id,d.version FROM public.deals d JOIN public.users u ON u.user_id=d.owner_id WHERE u.auth_uid=current_setting('request.jwt.claim.sub')::uuid ORDER BY d.id LIMIT 1");}
function payload(){return {from:'completion',outcome:'won',transition_date:'2026-09-06',completion_date:'2026-09-05',completion_checks:['공사 완료','준공검사 완료'],won_amount:123000000,note:'준공과 최종 계약금액 확인',memo:null};}
test('won closes Deal and creates exactly one history/activity/audit/pool/receipt',async()=>{const db=await setup();try{const d=await actorDeal(db);await db.query("UPDATE public.deals SET stage_code='completion',lifecycle_status='active',outcome=NULL,stage_contexts=jsonb_build_object('completion',jsonb_build_object('fields',jsonb_build_object('completion_date','2026-09-05','completion_checks',jsonb_build_array('공사 완료','준공검사 완료')))) WHERE id=$1",[d.id]);const req='f6090600-0404-4000-8000-000000000011',ack=(await db.query("SELECT public.crm_write_command_v2($1,'close',$2,$3,$4) ack",[req,d.id,d.version,JSON.stringify(payload())])).rows[0].ack;assert.equal(ack.outcome,'won');assert.equal(ack.won_amount,123000000);assert.equal(ack.completion_date,'2026-09-05');assert.equal((await scalar(db,'SELECT count(*)::int n FROM crm_security.expansion_pool WHERE source_deal_id=$1',[d.id])).n,1);assert.equal((await scalar(db,'SELECT count(*)::int n FROM crm_security.deal_won_events WHERE deal_id=$1',[d.id])).n,1);assert.equal((await scalar(db,"SELECT count(*)::int n FROM public.stage_history WHERE opportunity_id=$1 AND to_stage='won'",[d.id])).n,1);assert.equal((await scalar(db,"SELECT count(*)::int n FROM public.activities WHERE deal_id=$1 AND detail->>'note'='Closed Won · 준공 완료'",[d.id])).n,1);const replay=(await db.query("SELECT public.crm_write_command_v2($1,'close',$2,$3,$4) ack",[req,d.id,d.version,JSON.stringify(payload())])).rows[0].ack;assert.equal(replay.replayed,true);assert.equal((await scalar(db,'SELECT count(*)::int n FROM crm_security.deal_won_events WHERE deal_id=$1',[d.id])).n,1);const changed=payload();changed.won_amount++;await assert.rejects(db.query("SELECT public.crm_write_command_v2($1,'close',$2,$3,$4)",[req,d.id,d.version,JSON.stringify(changed)]),e=>e.code==='PT409');}finally{await db.close();}});
test('wrong stage, stale version, and foreign scope fail without side effects',async()=>{const db=await setup();try{const d=await actorDeal(db);await assert.rejects(db.query("SELECT public.crm_write_command_v2($1,'close',$2,$3,$4)",['f6090600-0404-4000-8000-000000000021',d.id,d.version,JSON.stringify(payload())]),e=>e.code==='PT409');await db.query("UPDATE public.deals SET stage_code='completion',stage_contexts=jsonb_build_object('completion',jsonb_build_object('fields','{}'::jsonb)) WHERE id=$1",[d.id]);await assert.rejects(db.query("SELECT public.crm_write_command_v2($1,'close',$2,$3,$4)",['f6090600-0404-4000-8000-000000000022',d.id,d.version+1,JSON.stringify(payload())]),e=>e.code==='PT409');await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[1].auth_uid}'`);await assert.rejects(db.query("SELECT public.crm_write_command_v2($1,'close',$2,$3,$4)",['f6090600-0404-4000-8000-000000000023',d.id,d.version,JSON.stringify(payload())]),e=>e.code==='42501');assert.equal((await scalar(db,'SELECT count(*)::int n FROM crm_security.deal_won_events')).n,0);}finally{await db.close();}});
test('empty expansion pool returns explicit complete pagination',async()=>{const db=await setup();try{await actorDeal(db);const value=(await db.query("SELECT public.crm_operational_source_v1('expansion_pool',NULL,100) value")).rows[0].value;assert.deepEqual(value.items,[]);assert.equal(value.pagination.completeness,'complete');assert.equal(value.pagination.has_more,false);assert.equal(value.pagination.next_cursor,null);}finally{await db.close();}});
test('rollback works before use and refuses after irreversible won evidence',async()=>{
 let db=await setup();
 try{
  await db.exec(won.rollbackSql());
  assert.equal((await scalar(db,"SELECT to_regclass('crm_security.expansion_pool') IS NULL gone")).gone,true);
  assert.equal((await scalar(db,`SELECT count(*)::int n FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name IN ('won_amount','completion_date')`)).n,0);
 }finally{await db.close();}
 db=await setup();
 try{
  const d=await actorDeal(db);
  await db.query("UPDATE public.deals SET stage_code='completion',stage_contexts=jsonb_build_object('completion',jsonb_build_object('fields','{}'::jsonb)) WHERE id=$1",[d.id]);
  await db.query("SELECT public.crm_write_command_v2($1,'close',$2,$3,$4)",['f6090600-0404-4000-8000-000000000031',d.id,d.version,JSON.stringify(payload())]);
  await assert.rejects(db.exec(won.rollbackSql()),/runtime closed-won evidence exists/);
  await db.exec('ROLLBACK');
  assert.equal((await scalar(db,"SELECT to_regclass('crm_security.expansion_pool') IS NOT NULL present")).present,true);
 }finally{await db.close();}
});
