'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=require('../../inquiry-action-check/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const read=name=>fs.readFileSync(path.join(dir,name),'utf8').replace(/\r\n?/g,'\n');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function replaceOne(source,pattern,replacement,label){const next=source.replace(pattern,replacement);if(next===source)throw Error('technical inquiry transfer build anchor missing: '+label);return next;}
function adapter(){let source=base.adapter();
 source=replaceOne(source,"function normalizeCreate(objectId,payload){if(payload.intent==='inquiry_promote_create')",`function normalizeCreate(objectId,payload){if(payload.intent==='technical_inquiry_transfer'){const allowed=['intent','inquiry_id','client_ref'];if(Object.keys(payload).some(k=>!allowed.includes(k))||!UUID.test(payload.inquiry_id)||typeof payload.client_ref!=='string'||!/^local-tech-[A-Za-z0-9._:-]+$/.test(payload.client_ref))fail('TECHNICAL_INQUIRY_TRANSFER_INTENT_NOT_CONNECTED');return {intent:'technical_inquiry_transfer',inquiry_id:payload.inquiry_id,client_ref:payload.client_ref};}if(payload.intent==='inquiry_promote_create')`,'normalize create');
 source=replaceOne(source,"  if(command.operation==='opportunity_create'&&command.payload.intent==='inquiry_promote_create'",`  if(command.operation==='opportunity_create'&&command.payload.intent==='technical_inquiry_transfer'&&(ack.intent!=='technical_inquiry_transfer'||ack.inquiry_id!==command.payload.inquiry_id||!UUID.test(ack.new_opportunity_id)||ack.opportunity_id!==ack.new_opportunity_id||ack.to_stage!=='first_contact'||ack.version!==1||!UUID.test(ack.stage_history_id)||!UUID.test(ack.activity_id)||!UUID.test(ack.audit_event_id)||!UUID.test(ack.inquiry_audit_event_id)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='opportunity_create'&&command.payload.intent==='inquiry_promote_create'`,'technical ACK');
 source=replaceOne(source,"command.payload.intent!=='inquiry_promote_create'&&(!UUID.test(ack.new_opportunity_id)","!['inquiry_promote_create','technical_inquiry_transfer'].includes(command.payload.intent)&&(!UUID.test(ack.new_opportunity_id)",'generic create ACK guard');
 return source;
}
function overlay(){let source=base.overlay();
 source=replaceOne(source,'promotionContext=null,createSurface=null','promotionContext=null,technicalTransfer=null,createSurface=null','technical state');
 source=replaceOne(source,"  function applyLineageAck(q){",`  function applyTechnicalTransferAck(q){const a=q.ack;versions.set(a.opportunity_id,a.version);for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.payload.client_ref)){d.id=d.opportunity_id=d.server_id=a.opportunity_id;d.origin_inquiry_id=d.originInquiryId=a.inquiry_id;d.site_id=a.site_id==null?null:a.site_id;d.owner_id=a.owner_id==null?null:a.owner_id;d.code=d.stage_code=a.to_stage;d.version=a.version;}for(const rows of inquiryRows())for(const i of rows)if(String(i.id||i.inquiry_id||i.key)===String(a.inquiry_id)){i.originOpportunityId=i.opportunity_id=a.opportunity_id;i.status='영업전환';i.qualified_at=i.qualifiedAt=a.server_at;i.legacy_review_status='promoted';}}
  function applyLineageAck(q){`,'technical ACK apply');
 source=replaceOne(source,"if(q.operation==='opportunity_create'&&q.payload.intent==='inquiry_promote_create')applyPromotionAck(q);else if(q.operation==='opportunity_create')applyCreateAck(q);", "if(q.operation==='opportunity_create'&&q.payload.intent==='technical_inquiry_transfer')applyTechnicalTransferAck(q);else if(q.operation==='opportunity_create'&&q.payload.intent==='inquiry_promote_create')applyPromotionAck(q);else if(q.operation==='opportunity_create')applyCreateAck(q);",'technical ACK sync');
 source=replaceOne(source,"root.pushWrite=function(op,payload){if(promotionContext",`root.pushWrite=function(op,payload){if(technicalTransfer&&op==='inquiry_status')return 'absorbed:inquiry_status';if(technicalTransfer&&op==='opportunity_create'){const q=technicalTransfer.q,inquiryId=String(q&&(q.id||q.inquiry_id||(root.inqKey&&root.inqKey(q)))||''),clientRef=String(payload&&payload.client_ref||'');if(!inquiryId||!clientRef)throw error('TECHNICAL_INQUIRY_TRANSFER_INTENT_NOT_CONNECTED');payload={intent:'technical_inquiry_transfer',inquiry_id:inquiryId,client_ref:clientRef};}if(promotionContext`,'technical push transform');
 source=replaceOne(source,"if(op==='opportunity_create'&&!createSurface&&!promotionContext)","if(op==='opportunity_create'&&!createSurface&&!promotionContext&&!technicalTransfer)",'create guard');
 source=replaceOne(source,"payload=promotionContext?{...payload,client_ref:String(clientRef)}:{...payload,surface:createSurface,client_ref:String(clientRef),...(createOwnerOverride?{owner:createOwnerOverride}:{})};", "payload=technicalTransfer?payload:promotionContext?{...payload,client_ref:String(clientRef)}:{...payload,surface:createSurface,client_ref:String(clientRef),...(createOwnerOverride?{owner:createOwnerOverride}:{})};",'create payload');
 source=replaceOne(source,"  if(typeof root.inqCtlConfirmReason==='function')",`  if(typeof root.inqTechPromote==='function'){const original=root.inqTechPromote;root.inqTechPromote=function(){const modal=root.INQ_CTL_MODAL,q=modal&&typeof root.inqCtlFind==='function'?root.inqCtlFind(modal.key,false):null;if(!q)return original.apply(this,arguments);const prior=technicalTransfer;technicalTransfer={q};try{return original.apply(this,arguments);}finally{technicalTransfer=prior;}};}
  if(typeof root.inqCtlConfirmReason==='function')`,'technical handler wrapper');
 return source;
}
function applySql(){return tx(read('helper.sql'));}
function rollbackSql(){return tx(read('rollback-fragment.sql'));}
function build(){const files={'staging-apply-after-inquiry-action-check.sql':applySql(),'rollback-before-inquiry-action-check.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay()};for(const [name,value] of Object.entries(files))fs.writeFileSync(path.join(dir,name),value);
 const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs',...Object.keys(files)];
 const sources=['sql/inquiry-action-check/20260906/manifest.json','crm.html','docs/operational-cutover-20260906/technical-inquiry-transfer-resolution.md'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',operations:['opportunity_create'],intents:['technical_inquiry_transfer'],ui_coverage_candidate:['I15'],status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',surface:'pc_only',handlers:['inqTechPromote'],absorbed_child_operations:['inquiry_status'],server_helper_implemented:true,transaction:['technical Deal create','inquiry conversion/backlink','stage history','activity','Deal/private inquiry audit','admin object scope','command receipt'],staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={applySql,rollbackSql,adapter,overlay,build,dir};
