'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const personal=require('../../personal-state-compat/20260906/build.cjs'),cutover=require('../../operational-cutover-candidate/20260906/build.cjs'),response=require('../../inquiry-response-progress/20260906/build.cjs'),pipeline=require('../../inquiry-pipeline-lineage/20260906/build.cjs'),progress=require('../../inquiry-stage-progress/20260906/build.cjs'),actions=require('../../inquiry-action-check/20260906/build.cjs'),build=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const inq=n=>s.uid(5,n),deal=n=>s.uid(6,n),user=n=>s.uid(1,n),site=n=>s.uid(2,n),request=n=>`f6090600-0118-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(cutover.compose('apply',{localPersonalCandidate:true,skipResponse:true,skipInquiryPipeline:true,skipTechnical:true}));await db.exec(response.applySql());await db.exec(pipeline.applySql());await db.exec(progress.applySql());await db.exec(actions.applySql());await db.exec(build.applySql());return db;}
async function actor(db,index=4){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[s.mapping.accounts[index].auth_uid]);await db.exec('SET ROLE authenticated');}
async function rpc(db,requestId,inquiryId=inq(5),payload={},index=4){await actor(db,index);try{return (await db.query('SELECT public.crm_write_command_v2($1,$2,$1,0,$3) a',[requestId,'opportunity_create',JSON.stringify({intent:'technical_inquiry_transfer',inquiry_id:inquiryId,client_ref:'local-tech-'+requestId.slice(-4),...payload})])).rows[0].a;}finally{await db.exec('RESET ROLE');}}
async function one(db,sql,params=[]){return (await db.query(sql,params)).rows[0];}
async function prepare(db,{assigned=user(1),withSite=true}={}){await db.query('UPDATE public.deals SET origin_inquiry_id=NULL WHERE origin_inquiry_id=$1',[inq(5)]);await db.query("UPDATE public.inquiries SET brand='기술자문',inquiry_type='기술자문',assigned_to=$1,assignee_name=NULL,status='접수',site_id=$2,deal_id=NULL,opportunity_id=NULL,qualified_at=NULL WHERE id=$3",[assigned,withSite?site(5):null,inq(5)]);}

test('admin transfer creates one canonical Deal, lineage and evidence atomically',async()=>{const db=await setup();try{await prepare(db);const a=await rpc(db,request(1));assert.equal(a.intent,'technical_inquiry_transfer');assert.equal(a.to_stage,'first_contact');assert.equal(a.version,1);assert.equal(a.owner_id,user(1));assert.equal(a.site_id,site(5));assert.deepEqual(await one(db,'SELECT brand,list_name,stage_code,amount,owner_id,site_id,origin_inquiry_id,version FROM public.deals WHERE id=$1',[a.opportunity_id]),{brand:'기술자문',list_name:'기술자문',stage_code:'first_contact',amount:null,owner_id:user(1),site_id:site(5),origin_inquiry_id:inq(5),version:1});assert.deepEqual(await one(db,'SELECT status,deal_id,opportunity_id FROM public.inquiries WHERE id=$1',[inq(5)]),{status:'영업전환',deal_id:a.opportunity_id,opportunity_id:a.opportunity_id});for(const [table,key] of [['stage_history','opportunity_id'],['activities','deal_id']])assert.equal((await one(db,`SELECT count(*)::int n FROM public.${table} WHERE ${key}=$1`,[a.opportunity_id])).n,1);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='technical_inquiry_transfer'",[inq(5)])).n,1);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='technical_inquiry_transfer'",[a.opportunity_id])).n,1);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_security.object_scope WHERE deal_id=$1 AND user_id=$2 AND can_write',[a.opportunity_id,user(5)])).n,1);}finally{await db.close();}});
test('invalid rep and absent site remain NULL; no Site or fake user is created',async()=>{const db=await setup();try{await prepare(db,{assigned:user(5),withSite:false});const users=(await one(db,'SELECT count(*)::int n FROM public.users')).n,sites=(await one(db,'SELECT count(*)::int n FROM public.sites')).n,a=await rpc(db,request(2));assert.equal(a.owner_id,null);assert.equal(a.site_id,null);assert.equal((await one(db,'SELECT count(*)::int n FROM public.users')).n,users);assert.equal((await one(db,'SELECT count(*)::int n FROM public.sites')).n,sites);}finally{await db.close();}});
test('replay is duplicate-free; reuse, duplicate lineage and non-admin are rejected',async()=>{const db=await setup();try{await prepare(db);const p={client_ref:'local-tech-fixed'},a=await rpc(db,request(3),inq(5),p),replay=await rpc(db,request(3),inq(5),p);assert.equal(replay.replayed,true);assert.equal(replay.opportunity_id,a.opportunity_id);assert.equal((await one(db,'SELECT count(*)::int n FROM public.deals WHERE origin_inquiry_id=$1',[inq(5)])).n,1);await assert.rejects(rpc(db,request(3),inq(5),{client_ref:'local-tech-other'}),e=>e.code==='PT409');await assert.rejects(rpc(db,request(4)),e=>e.code==='PT409');await prepare(db);await assert.rejects(rpc(db,request(5),inq(5),{},0),e=>e.code==='42501');}finally{await db.close();}});
test('late audit failure rolls Deal, inquiry linkage, history, activity and receipt back',async()=>{const db=await setup();try{await prepare(db);const before=await one(db,'SELECT status,deal_id,opportunity_id,qualified_at FROM public.inquiries WHERE id=$1',[inq(5)]);await db.exec("CREATE FUNCTION crm_security.reject_technical_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='technical_inquiry_transfer' THEN RAISE EXCEPTION 'injected technical audit failure';END IF;RETURN NEW;END$$;CREATE TRIGGER reject_technical_audit BEFORE INSERT ON crm_security.audit_events FOR EACH ROW EXECUTE FUNCTION crm_security.reject_technical_audit();");await assert.rejects(rpc(db,request(6)),/injected technical audit failure/);assert.equal((await one(db,'SELECT count(*)::int n FROM public.deals WHERE origin_inquiry_id=$1',[inq(5)])).n,0);assert.deepEqual(await one(db,'SELECT status,deal_id,opportunity_id,qualified_at FROM public.inquiries WHERE id=$1',[inq(5)]),before);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_security.command_receipts WHERE request_id=$1',[request(6)])).n,0);}finally{await db.close();}});
test('rollback restores previous dispatcher and archives candidate evidence',async()=>{const db=await setup();try{await prepare(db);const before=(await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_write_command_v2_inquiry_action_check_20260906(uuid,text,uuid,integer,jsonb)'::regprocedure")).d;await rpc(db,request(7));await db.exec(build.rollbackSql());assert.equal((await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)'::regprocedure")).d,before);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_technical_inquiry_transfer_archive.command_receipts')).n,1);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_technical_inquiry_transfer_archive.inquiry_audit_events')).n,1);}finally{await db.close();}});
