'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=require('../../inquiry-pipeline-lineage/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const read=name=>fs.readFileSync(path.join(dir,name),'utf8').replace(/\r\n?/g,'\n');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function replaceOne(source,pattern,replacement,label){const next=source.replace(pattern,replacement);if(next===source)throw Error('inquiry stage progress build anchor missing: '+label);return next;}
function applySql(){return tx(read('helper.sql'));}
function rollbackSql(){return tx(read('rollback-fragment.sql'));}
function adapter(){let source=base.adapter();
 source=replaceOne(source,/ function normalizeHold\(objectId,payload\)\{.*?\}\n function normalizeTrash/s,` function normalizeHold(objectId,payload){if(payload&&payload.intent==='progress'){const allowed=['inquiry_id','intent','from_status','target','did','result','next','due'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.inquiry_id!==objectId||typeof payload.from_status!=='string'||!payload.from_status.trim()||payload.from_status.length>200||!/^step:[0-5]$/.test(payload.target)||typeof payload.did!=='string'||!payload.did.trim()||payload.did.length>8000||typeof payload.result!=='string'||!payload.result.trim()||payload.result.length>8000||typeof payload.next!=='string'||!payload.next.trim()||payload.next.length>500||!/^\\d{4}-\\d{2}-\\d{2}$/.test(payload.due))fail('INQUIRY_PROGRESS_INTENT_NOT_CONNECTED');return {intent:'progress',from_status:payload.from_status.trim(),target:payload.target,did:payload.did.trim(),result:payload.result.trim(),next:payload.next.trim(),due:payload.due};}const allowed=['inquiry_id','from_status','to_status','reason','changed_by','at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.inquiry_id!==objectId||payload.to_status!=='보류'||typeof payload.reason!=='string'||!payload.reason.trim()||payload.reason.length>2000)fail('INQUIRY_STATUS_INTENT_NOT_CONNECTED');return {intent:'hold',reason:payload.reason.trim()};}\n function normalizeTrash`,'normalize inquiry status');
 source=replaceOne(source,"if(command.operation==='inquiry_status'&&(ack.intent!=='hold'","if(command.operation==='inquiry_status'&&command.payload.intent==='hold'&&(ack.intent!=='hold'",'hold ACK intent guard');
 source=replaceOne(source,"  if(command.operation==='lineage_link'",`  if(command.operation==='inquiry_status'&&command.payload.intent==='progress'){const n=Number(command.payload.target.slice(5)),statuses=['접수','전화응대 완료','견적서 발송완료','초기 집중관리','경쟁·임박·입찰','계약·공사 예정'],stages=['견적문의 접수','응대·컨설팅','견적서 발송','영업·관리 (유대·대기)','경쟁·임박','계약·시공'];if(ack.intent!=='progress'||ack.from_status!==command.payload.from_status||ack.to_status!==statuses[n]||typeof ack.from_stage!=='string'||!ack.from_stage||ack.to_stage!==stages[n]||typeof ack.first_response_at!=='string'||typeof ack.responded_at!=='string'||ack.next_action_date!==command.payload.due||!UUID.test(ack.stage_history_id)||!UUID.test(ack.next_action_id)||!Array.isArray(ack.cancelled_action_ids)||!UUID.test(ack.inquiry_audit_event_id)||typeof ack.server_at!=='string')fail('ACK_CONTRACT_MISMATCH');}\n  if(command.operation==='lineage_link'`,'progress ACK');
 return source;
}
function overlay(){let source=base.overlay();
 source=replaceOne(source,'holdIntent=false,trashIntent=false','holdIntent=false,progressIntent=false,trashIntent=false','progress state');
 source=replaceOne(source,"  function applyHoldAck(q){",`  function applyProgressAck(q){const a=q.ack;for(const rows of inquiryRows())for(const i of rows)if(String(i.id||i.inquiry_id||i.key)===String(q.object_id)){i.status=a.to_status;i.first_response_at=i.firstResponseAt=a.first_response_at;i.responded_at=i.respondedAt=a.responded_at;i.next_action_date=i.due=a.next_action_date;i.updated_at=a.server_at;i.stageHistory=Array.isArray(i.stageHistory)?i.stageHistory:[];if(!i.stageHistory.some(x=>x.id===a.stage_history_id))i.stageHistory.push({id:a.stage_history_id,from:a.from_stage,to:a.to_stage,reason:q.payload.result,actor:a.actor_name,at:a.server_at});i.activities=Array.isArray(i.activities)?i.activities:[];if(!i.activities.some(x=>x.id===a.inquiry_audit_event_id))i.activities.push({id:a.inquiry_audit_event_id,type:'단계전환',note:q.payload.did,result:q.payload.result,actor:a.actor_name,stage:a.to_stage,at:a.server_at});i.nextActionObj=i.nextAction={id:a.next_action_id,type:'전화',text:q.payload.next,due:a.next_action_date,due_at:a.next_action_date,status:'open'};}}\n  function applyHoldAck(q){`,'apply progress ACK');
 source=replaceOne(source,"if(q.operation==='inquiry_status')applyHoldAck(q);", "if(q.operation==='inquiry_status'&&q.payload.intent==='progress')applyProgressAck(q);else if(q.operation==='inquiry_status')applyHoldAck(q);",'sync progress ACK');
 source=replaceOne(source,"if(op==='inquiry_status'&&!holdIntent)","if(op==='inquiry_status'&&!holdIntent&&!progressIntent)",'progress push guard');
 source=replaceOne(source,"  if(typeof root.inqCtlConfirmReason==='function')",`  if(typeof root.iqApply==='function'){const original=root.iqApply;root.iqApply=function(q,target){if(!/^step:[0-5]$/.test(String(target||''))){if(typeof root.iqMsg==='function')root.iqMsg('종료·보류는 전용 처리에서 저장해 주세요.');return false;}const get=id=>root.document&&root.document.getElementById?root.document.getElementById(id):null,from=String(q&&q.status||''),payload={inquiry_id:String(q&&(q.id||q.inquiry_id||(root.inqKey&&root.inqKey(q)))||''),intent:'progress',from_status:from,target:String(target),did:String(get('iq-did')?.value||'').trim(),result:String(get('iq-res')?.value||'').trim(),next:String(get('iq-next')?.value||'').trim(),due:String(get('iq-due')?.value||'')};const previous=progressIntent;progressIntent=true;try{root.OperationalAdapter.normalize('inquiry_status',payload.inquiry_id,0,payload);const out=original.apply(this,arguments);if(out===true)root.pushWrite('inquiry_status',payload);return out;}finally{progressIntent=previous;}};}\n  if(typeof root.inqCtlConfirmReason==='function')`,'named iqApply wrapper');
 return source;
}
function build(){const files={'staging-apply-after-inquiry-pipeline.sql':applySql(),'rollback-before-inquiry-pipeline.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay()};for(const [name,value] of Object.entries(files))fs.writeFileSync(path.join(dir,name),value);
 const own=['build.cjs','helper.sql','rollback-fragment.sql','review.md','contract.test.cjs','db.test.cjs','ui.test.cjs',...Object.keys(files)];
 const sources=['sql/inquiry-pipeline-lineage/20260906/manifest.json','crm.html','sql/operational-bundle/20260906/after.json'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',operation:'inquiry_status',intent:'progress',ui_coverage_candidate:['I04'],status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',surface:'pc_only',allowed_targets:['step:0','step:1','step:2','step:3','step:4','step:5'],blocked_targets:['hold','lost','badfit_lead','nocontact'],roles:['assigned_rep','assigned_consultation','scoped_admin'],transaction:['inquiries status/response timestamps/next_action_date','cancel prior open inquiry next actions','insert open inquiry next action','stage_history','private inquiry audit','command receipt'],staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={applySql,rollbackSql,adapter,overlay,build,dir};
