'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const personal=require('../../personal-state-compat/20260906/build.cjs'),cutover=require('../../operational-cutover-candidate/20260906/build.cjs'),response=require('../../inquiry-response-progress/20260906/build.cjs'),pipeline=require('../../inquiry-pipeline-lineage/20260906/build.cjs'),build=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const inq=n=>s.uid(5,n),user=n=>s.uid(1,n),request=n=>`f6090600-0116-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(cutover.compose('apply',{localPersonalCandidate:true,skipResponse:true,skipInquiryPipeline:true}));await db.exec(response.applySql());await db.exec(pipeline.applySql());await db.exec(build.applySql());return db;}
async function actor(db,index=0){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[s.mapping.accounts[index].auth_uid]);await db.exec('SET ROLE authenticated');}
async function rpc(db,requestId,payload,index=0,id=inq(1)){await actor(db,index);try{return (await db.query("SELECT public.crm_write_command_v2($1,'inquiry_status',$2,0,$3) a",[requestId,id,JSON.stringify(payload)])).rows[0].a;}finally{await db.exec('RESET ROLE');}}
async function one(db,sql,params=[]){return (await db.query(sql,params)).rows[0];}
async function payload(db,patch={}){const due=(await one(db,"SELECT ((clock_timestamp() AT TIME ZONE 'Asia/Seoul')::date+2)::text d")).d;return {intent:'progress',from_status:'배정완료',target:'step:1',did:'관리소장 통화',result:'현장 확인 완료',next:'도면 요청',due,...patch};}

test('PC progress atomically updates inquiry, replaces Next Action and records scoped evidence',async()=>{const db=await setup();try{
 await db.query("UPDATE public.inquiries SET assigned_to=$1,assignee_name='TEST INTERNAL_REP',status='배정완료',first_response_at=NULL,responded_at=NULL,next_action_date=NULL WHERE id=$2",[user(1),inq(1)]);
 await db.query("INSERT INTO public.next_actions(inquiry_id,title,due_at,assignee_name) VALUES($1,'기존 후속',now()+'1 day'::interval,'TEST INTERNAL_REP')",[inq(1)]);
 const p=await payload(db),a=await rpc(db,request(1),p);assert.equal(a.intent,'progress');assert.equal(a.to_status,'전화응대 완료');assert.equal(a.actor_user_id,user(1));assert.equal(a.cancelled_action_ids.length,1);
 const row=await one(db,'SELECT status,first_response_at,responded_at,next_action_date::text FROM public.inquiries WHERE id=$1',[inq(1)]);assert.equal(row.status,'전화응대 완료');assert.equal(row.first_response_at.getTime(),row.responded_at.getTime());assert.equal(row.next_action_date,p.due);
 assert.equal((await one(db,"SELECT count(*)::int n FROM public.next_actions WHERE inquiry_id=$1 AND status='open'",[inq(1)])).n,1);assert.equal((await one(db,"SELECT count(*)::int n FROM public.next_actions WHERE inquiry_id=$1 AND status='cancelled'",[inq(1)])).n,1);assert.equal((await one(db,'SELECT count(*)::int n FROM public.stage_history WHERE inquiry_id=$1',[inq(1)])).n,1);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_stage_progress'",[inq(1)])).n,1);
 await actor(db,0);const read=(await db.query("SELECT public.crm_operational_source_v1('inquiry_core',NULL,100) a")).rows[0].a;await db.exec('RESET ROLE');const item=read.items.find(x=>x.id===inq(1));assert.equal(item.stage_history.length,1);assert.equal(item.activities[0].note,'관리소장 통화');assert.equal(item.next_action.id,a.next_action_id);assert.equal('actor_auth_uid' in item.activities[0],false);
 const replay=await rpc(db,request(1),p);assert.equal(replay.replayed,true);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_stage_progress'",[inq(1)])).n,1);
 }finally{await db.close();}});

test('stale status, terminal/technical meaning, foreign actor and request reuse fail closed',async()=>{const db=await setup();try{
 await db.query("UPDATE public.inquiries SET assigned_to=$1,status='배정완료',inquiry_type=NULL,brand='TEST' WHERE id=$2",[user(1),inq(1)]);const p=await payload(db);
 await assert.rejects(rpc(db,request(10),{...p,from_status:'접수'}),e=>e.code==='PT409');await assert.rejects(rpc(db,request(11),{...p,target:'lost'}),e=>e.code==='22023');await assert.rejects(rpc(db,request(12),p,1),e=>e.code==='42501');
 await db.query("UPDATE public.inquiries SET inquiry_type='기술자문' WHERE id=$1",[inq(1)]);await assert.rejects(rpc(db,request(13),p),e=>e.code==='42501');await db.query("UPDATE public.inquiries SET inquiry_type=NULL WHERE id=$1",[inq(1)]);await rpc(db,request(14),p);await assert.rejects(rpc(db,request(14),{...p,next:'다른 후속'}),e=>e.code==='PT409');
 }finally{await db.close();}});

test('late audit failure rolls public status, history, action replacement and receipt back',async()=>{const db=await setup();try{
 await db.query("UPDATE public.inquiries SET assigned_to=$1,status='배정완료',first_response_at=NULL,responded_at=NULL,next_action_date=NULL WHERE id=$2",[user(1),inq(1)]);await db.query("INSERT INTO public.next_actions(inquiry_id,title,due_at,assignee_name) VALUES($1,'기존 후속',now()+'1 day'::interval,'TEST INTERNAL_REP')",[inq(1)]);const before=await one(db,'SELECT status,first_response_at,responded_at,next_action_date FROM public.inquiries WHERE id=$1',[inq(1)]);
 await db.exec("CREATE FUNCTION crm_security.reject_progress_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='inquiry_stage_progress' THEN RAISE EXCEPTION 'injected progress audit failure';END IF;RETURN NEW;END$$;CREATE TRIGGER reject_progress_audit BEFORE INSERT ON crm_security.inquiry_audit_events FOR EACH ROW EXECUTE FUNCTION crm_security.reject_progress_audit();");await assert.rejects(rpc(db,request(20),await payload(db)),/injected progress audit failure/);assert.deepEqual(await one(db,'SELECT status,first_response_at,responded_at,next_action_date FROM public.inquiries WHERE id=$1',[inq(1)]),before);assert.equal((await one(db,"SELECT count(*)::int n FROM public.next_actions WHERE inquiry_id=$1 AND status='open'",[inq(1)])).n,1);assert.equal((await one(db,'SELECT count(*)::int n FROM public.stage_history WHERE inquiry_id=$1',[inq(1)])).n,0);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_security.command_receipts WHERE request_id=$1',[request(20)])).n,0);
 }finally{await db.close();}});

test('rollback restores prior dispatcher/read bodies and archives only progress evidence',async()=>{const db=await setup();try{const beforeWrite=(await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_write_command_v2_inquiry_pipeline_20260906(uuid,text,uuid,integer,jsonb)'::regprocedure")).d,beforeRead=(await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_operational_source_fragment_pre_inquiry_stage_progress_20260906(text,uuid,integer)'::regprocedure")).d;await db.query("UPDATE public.inquiries SET assigned_to=$1,status='배정완료' WHERE id=$2",[user(1),inq(1)]);await rpc(db,request(30),await payload(db));const persisted=await one(db,'SELECT status,next_action_date FROM public.inquiries WHERE id=$1',[inq(1)]);await db.exec(build.rollbackSql());assert.equal((await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)'::regprocedure")).d,beforeWrite);assert.equal((await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_operational_source_fragment_v1(text,uuid,integer)'::regprocedure")).d,beforeRead);assert.deepEqual(await one(db,'SELECT status,next_action_date FROM public.inquiries WHERE id=$1',[inq(1)]),persisted);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_inquiry_stage_progress_archive.command_receipts")).n,1);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_inquiry_stage_progress_archive.inquiry_audit_events")).n,1);}finally{await db.close();}});
