'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname,root=path.resolve(dir,'../../..'),baseDir=path.resolve(dir,'../../queue-retry-compat/20260906');
const read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function one(source,from,to,label){if(!source.includes(from))throw Error('message log build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=read(path.join(baseDir,'operational-adapter.candidate.js'));
 source=one(source,"'expansion_pool_update','customer_support_action'])","'expansion_pool_update','customer_support_action','message_log'])",'operation');
 source=one(source,' function normalizeSupport(objectId,payload){',` function normalizeMessageLog(objectId,payload){const allowed=['opportunity_id','site_id','person_key','channel','sender','recipient_phone','template_key','template_title','template_kind','template_grade','purpose','body','stage_code','message_context','quote_version_no','quote_attachment_id','attachment_refs','status','success','next_action_created','sent_at','failed_at','next_action_requested','next_action_type','next_action_text','next_due_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||!['sms','kakao'].includes(payload.channel)||!['info','promo','mixed'].includes(payload.template_kind)||!['sent','failed','cancelled'].includes(payload.status)||payload.message_context!=='deal'||typeof payload.next_action_requested!=='boolean')fail('MESSAGE_LOG_INTENT_NOT_CONNECTED');const refs=payload.attachment_refs;if(!Array.isArray(refs)||refs.length>10||refs.some(x=>!UUID.test(String(x)))||new Set(refs).size!==refs.length)fail('INVALID_MESSAGE_ATTACHMENTS');const quote=payload.quote_version_no==null?null:Number(payload.quote_version_no),quoteAttachment=payload.quote_attachment_id==null?null:String(payload.quote_attachment_id);if((quote!==null&&(!Number.isSafeInteger(quote)||quote<1))||(quoteAttachment!==null&&(!UUID.test(quoteAttachment)||!refs.includes(quoteAttachment))))fail('INVALID_MESSAGE_ATTACHMENTS');const optional=(value,max,code)=>value==null||String(value).trim()===''?null:text(String(value),1,max,code),out={person_key:optional(payload.person_key,200,'INVALID_PERSON_KEY'),channel:payload.channel,template_key:text(payload.template_key,1,200,'INVALID_TEMPLATE_KEY'),template_title:text(payload.template_title,1,300,'INVALID_TEMPLATE_TITLE'),template_kind:payload.template_kind,template_grade:optional(payload.template_grade,100,'INVALID_TEMPLATE_GRADE'),purpose:optional(payload.purpose,500,'INVALID_MESSAGE_PURPOSE'),body:text(payload.body,1,5000,'INVALID_MESSAGE_BODY'),message_context:'deal',quote_version_no:quote,quote_attachment_id:quoteAttachment,attachment_refs:refs.slice(),status:payload.status,next_action_requested:payload.next_action_requested,next_action_type:null,next_action_text:null,next_due_at:null};if(payload.status!=='sent'&&payload.next_action_requested)fail('MESSAGE_LOG_INTENT_NOT_CONNECTED');if(payload.next_action_requested){out.next_action_type=text(payload.next_action_type,1,100,'INVALID_NEXT_TYPE');out.next_action_text=text(payload.next_action_text,1,500,'INVALID_NEXT_TEXT');out.next_due_at=date(payload.next_due_at);}else if(payload.next_action_type!=null||payload.next_action_text!=null||payload.next_due_at!=null)fail('MESSAGE_LOG_INTENT_NOT_CONNECTED');return out;}
 function normalizeSupport(objectId,payload){`,'normalizer');
 source=one(source,"else if(operation==='customer_support_action')normalized=normalizeSupport(objectId,payload);else normalized=normalizeTrash", "else if(operation==='customer_support_action')normalized=normalizeSupport(objectId,payload);else if(operation==='message_log')normalized=normalizeMessageLog(objectId,payload);else normalized=normalizeTrash",'normalize route');
 source=one(source,"  if(command.operation==='customer_support_action'&&",`  if(command.operation==='message_log'&&(ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||!UUID.test(ack.message_log_id)||ack.attestation_kind!=='user_attested'||ack.user_attested!==true||ack.status!==command.payload.status||!UUID.test(ack.contact_id)||typeof ack.recipient_phone!=='string'||(ack.activity_id!==null&&!UUID.test(ack.activity_id))||(ack.next_action_id!==null&&!UUID.test(ack.next_action_id))||!UUID.test(ack.audit_event_id)||typeof ack.actor_name!=='string'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='customer_support_action'&&`,'ACK');
 return source;
}
function overlay(){let source=read(path.join(baseDir,'operational-overlay.candidate.js'));
 source=one(source,"'expansion_pool_update','customer_support_action'])","'expansion_pool_update','customer_support_action','message_log'])",'connected');
 source=one(source,'return {...d,opportunity_id:',"return {...d,messageLogs:(scoped.message_logs||[]).filter(x=>String(x.opportunity_id)===String(d.id)),message_logs:(scoped.message_logs||[]).filter(x=>String(x.opportunity_id)===String(d.id)),opportunity_id:",'deal hydration');
 source=one(source,'customer_support_actions:scoped.customer_support_actions||[],dups:[]','customer_support_actions:scoped.customer_support_actions||[],messageLogs:scoped.message_logs||[],message_logs:scoped.message_logs||[],dups:[]','shell aliases');
 source=one(source,'expansionIntent=false,supportIntent=false;','expansionIntent=false,supportIntent=false,messageOutcome=null,messageIntent=false;','state');
 source=one(source,'  function applySupportAck(q){',`  function applyMessageAck(q){const a=q.ack,row={id:a.message_log_id,message_log_id:a.message_log_id,opportunity_id:q.object_id,contact_id:a.contact_id,person_key:a.person_key,recipient_phone:a.recipient_phone,channel:q.payload.channel,template_key:q.payload.template_key,template_title:q.payload.template_title,template_kind:q.payload.template_kind,template_grade:q.payload.template_grade,purpose:q.payload.purpose,body:q.payload.body,message_context:'deal',quote_version_no:q.payload.quote_version_no,quote_attachment_id:q.payload.quote_attachment_id,attachment_refs:q.payload.attachment_refs,status:a.status,success:a.status==='sent',attestation_kind:'user_attested',user_attested:true,actor_name:a.actor_name,activity_id:a.activity_id,next_action_id:a.next_action_id,occurred_at:a.server_at,sent_at:a.status==='sent'?a.server_at:null,failed_at:a.status==='failed'?a.server_at:null};root.B=root.B||{};const global=Array.isArray(root.B.messageLogs)?root.B.messageLogs:(root.B.messageLogs=[]);if(!global.some(x=>x.id===row.id))global.push(row);root.B.message_logs=global;for(const rows of [root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.version=a.version;let logs=Array.isArray(d.messageLogs)?d.messageLogs:(d.messageLogs=[]),pending=logs.findLast?logs.findLast(x=>!x.id&&x.template_key===q.payload.template_key&&x.status===q.payload.status):null;if(pending)Object.assign(pending,row);else if(!logs.some(x=>x.id===row.id))logs.push(row);d.message_logs=logs;if(a.next_action_id)d.nextAction=d.nextActionObj={id:a.next_action_id,type:q.payload.next_action_type,text:q.payload.next_action_text,due:q.payload.next_due_at,due_at:q.payload.next_due_at,status:'open'};}}
  function applySupportAck(q){`,'ACK hydrator');
 source=one(source,"if(q.operation==='customer_support_action')applySupportAck(q);}","if(q.operation==='customer_support_action')applySupportAck(q);if(q.operation==='message_log')applyMessageAck(q);}",'ACK route');
 source=one(source,"root.pushWrite=function(op,payload){if(op==='customer_support_action'", "root.pushWrite=function(op,payload){if(messageOutcome&&op==='message_log'){messageOutcome.parent=payload;return 'absorbed:message_log';}if(messageOutcome&&op==='activity'){messageOutcome.activity=payload;return 'absorbed:activity';}if(messageOutcome&&op==='next_action'){messageOutcome.next=payload;return 'absorbed:next_action';}if(op==='message_log'&&!messageIntent)throw error('MESSAGE_LOG_INTENT_NOT_CONNECTED');if(op==='customer_support_action'",'compound capture');
 source=one(source,"  if(typeof root.pickToday==='function')",`  function wrapMessageConfirm(name){if(typeof root[name]!=='function')return;const original=root[name];root[name]=function(status){if(messageOutcome)throw error('MESSAGE_LOG_NESTED_INTENT');messageOutcome={parent:null,activity:null,next:null};try{const result=original.apply(this,arguments),c=messageOutcome,p=c.parent;if(!p)throw error('MESSAGE_LOG_PARENT_REQUIRED');if(p.status==='sent'&&!c.activity)throw error('MESSAGE_LOG_ACTIVITY_REQUIRED');if(p.status!=='sent'&&(c.activity||c.next))throw error('MESSAGE_LOG_SIDE_EFFECT_MISMATCH');if(Boolean(p.next_action_created)!==Boolean(c.next))throw error('MESSAGE_LOG_NEXT_ACTION_MISMATCH');const payload={...p,next_action_requested:Boolean(c.next),next_action_type:c.next?c.next.type:null,next_action_text:c.next?c.next.text:null,next_due_at:c.next?String(c.next.due_at||'').slice(0,10):null};messageOutcome=null;const prior=messageIntent;messageIntent=true;try{root.pushWrite('message_log',payload);}finally{messageIntent=prior;}return result;}finally{messageOutcome=null;}};}
  wrapMessageConfirm('relationshipConfirm');wrapMessageConfirm('rmConfirmM');
  if(typeof root.pickToday==='function')`,'named message handlers');
 return source;
}
function transport(){let source=read(path.join(baseDir,'transport.candidate.js'));
 source=one(source,'const [deals,inquiries,expansion_pool,customer_support_actions]=await Promise.all', 'const [deals,inquiries,expansion_pool,customer_support_actions,message_logs]=await Promise.all','collect lhs');
 source=one(source,"collect('customer_support_action')]);", "collect('customer_support_action'),collect('message_log')]);",'collect rhs');
 source=one(source,'customer_support_actions,customerSupportActions:customer_support_actions,expansion_events:', 'customer_support_actions,customerSupportActions:customer_support_actions,message_logs,messageLogs:message_logs,expansion_events:','bundle');
 return source;
}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-customer-support.sql':applySql(),'rollback-before-customer-support.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':transport()};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md',...Object.keys(generated)],sources=['sql/queue-retry-compat/20260906/manifest.json','crm.html','mobile.html','sql/20260905_relationship_messaging.sql','sql/20260905_contextual_message_composer.sql','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operation:'message_log',ui_coverage_candidate:['M02'],prerequisite:'queue-retry-compat/20260906 (DB prerequisite customer-support-action/20260906)',surface:'pc_mobile',meaning:'user-attested external send outcome; never provider delivery evidence',server_rules:{scope:'current can_deal(...,true) and version',contact:'unique current Deal contact and phone resolved server-side',sent:'message outcome + non-meaningful Activity + optional replacement Next Action atomically',failed_cancelled:'message outcome only plus Deal version/audit/receipt',attachments:'referenced quote version and ready Deal attachments only',authority:'server UUID actor/contact/phone/time; client sender/phone/stage/site/time stripped',idempotency:'common receipt and 409 reuse conflict'},read_additions:['message_log actor-scoped operational source','messageLogs/message_logs aliases'],blocked:['provider delivery claim','automatic send','direct unwrapped message_log','unready/cross-Deal attachment'],rollback:'message outcomes/receipts archived; O02 write/read layer restored',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,transport,applySql,rollbackSql,build};
