'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),amount=require('../../pipeline-amount-expected/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),fourteen=amount.fourteen;
const fifteen=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text, 'waiting_context'::text]))`;
const helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function adapter(){let text=amount.adapter();const ops="'transition','close','amount']";one(text,ops,'waiting adapter operations');text=text.replace(ops,"'transition','close','amount','waiting_context']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'waiting normalize marker');const fn=" function normalizeWaiting(objectId,payload){const allowed=['opportunity_id','waiting_reason','waiting_speaker','waiting_customer_statement','wake_up_at','waiting_evidence','expected_resume_at','actor_name','at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId)fail('WAITING_CONTEXT_INTENT_NOT_CONNECTED');const clean=(v,min,max)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)fail('INVALID_WAITING_CONTEXT');return v.trim();},validDate=v=>{if(typeof v!=='string'||!/^\\d{4}-\\d{2}-\\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail('INVALID_WAITING_CONTEXT');return v;};return {waiting_reason:clean(payload.waiting_reason,2,2000),waiting_speaker:clean(payload.waiting_speaker,1,500),waiting_customer_statement:clean(payload.waiting_customer_statement,2,8000),wake_up_at:validDate(payload.wake_up_at),waiting_evidence:clean(payload.waiting_evidence,2,4000),expected_resume_at:validDate(payload.expected_resume_at)};}\n";text=text.replace(marker,fn+marker);
 const dispatch="else if(operation==='close')normalized=normalizeClose(objectId,payload);else normalized=normalizeAmount(objectId,payload);";one(text,dispatch,'waiting dispatch');text=text.replace(dispatch,"else if(operation==='close')normalized=normalizeClose(objectId,payload);else if(operation==='amount')normalized=normalizeAmount(objectId,payload);else normalized=normalizeWaiting(objectId,payload);");
 const ack="  if(command.operation==='waiting_context'&&(ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||ack.wake_up_at!==command.payload.wake_up_at||ack.expected_resume_at!==command.payload.expected_resume_at||!UUID.test(ack.next_action_id)||!UUID.test(ack.activity_id)||!UUID.test(ack.audit_event_id)||!Array.isArray(ack.cancelled_action_ids)||!ack.waiting_context||typeof ack.waiting_context!=='object'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','waiting ACK return');return text.replace('  return ack;}',ack+'  return ack;}');}
function overlay(){let text=amount.overlay();const connected="'transition','close','amount']";one(text,connected,'waiting overlay connected');text=text.replace(connected,"'transition','close','amount','waiting_context']");
 const state='let compound=null,actionIntent=null,completeActionId=null,stageIntent=false,transitionCompound=false,closeCompound=false,preClose=false;const versions=new Map(),seenAcks=new Set();';one(text,state,'waiting state');text=text.replace(state,'let compound=null,actionIntent=null,completeActionId=null,stageIntent=false,transitionCompound=false,closeCompound=false,preClose=false,waitingIntent=false,waitingChild=false;const versions=new Map(),seenAcks=new Set();');
 const amountAck="  function applyAmountAck(q){const a=q.ack;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.amount=d.amt=a.amount;d.quote_amount=d.quoteAmt=a.quote_amount;}} ";one(text,amountAck,'waiting ACK marker');text=text.replace(amountAck,amountAck+"\n  function applyWaitingAck(q){const a=q.ack,f=a.waiting_context&&a.waiting_context.fields||{};for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.stage_contexts=d.stageContexts={...(d.stage_contexts||d.stageContexts||{}),waiting:a.waiting_context};d.wake_up_at=d.wakeUpAt=a.wake_up_at;d.waiting_reason=d.waitingReason=f.reason;d.waiting_speaker=d.waitingSpeaker=f.speaker;d.waiting_customer_statement=d.waitingCustomerStatement=f.statement;d.waiting_evidence=d.waitingEvidence=f.evidence;d.expected_resume_at=d.expectedResumeAt=f.resume_date;d.nextAction=d.nextActionObj={id:a.next_action_id,type:'전화',text:'대기 사유 확인 후 재접촉',due:a.wake_up_at,due_at:a.wake_up_at,status:'open'};}} ");
 const sync="if(q.operation==='amount')applyAmountAck(q);";one(text,sync,'waiting ACK sync');text=text.replace(sync,sync+"if(q.operation==='waiting_context')applyWaitingAck(q);");
 const push="root.pushWrite=function(op,payload){if(preClose";one(text,push,'waiting push marker');text=text.replace(push,"root.pushWrite=function(op,payload){if(waitingChild&&op==='next_action')return 'absorbed:next_action';if(op==='waiting_context'&&!waitingIntent)throw error('WAITING_CONTEXT_INTENT_NOT_CONNECTED');if(preClose");
 const enqueue="if(op==='close'){closeCompound=true;(root.queueMicrotask||queueMicrotask)(()=>{closeCompound=false;});}syncQueue();";one(text,enqueue,'waiting enqueue marker');text=text.replace(enqueue,"if(op==='close'){closeCompound=true;(root.queueMicrotask||queueMicrotask)(()=>{closeCompound=false;});}if(op==='waiting_context'){waitingChild=true;(root.queueMicrotask||queueMicrotask)(()=>{waitingChild=false;});}syncQueue();");
 const wrapper="  if(typeof root.commitClose==='function'){const original=root.commitClose;root.commitClose=function(outcome){if(!['lost','badfit','nocontact'].includes(outcome))return original.apply(this,arguments);const previous=preClose;preClose=true;try{return original.apply(this,arguments);}finally{preClose=previous;}};}";one(text,wrapper,'waiting wrapper marker');text=text.replace(wrapper,wrapper+"\n  if(typeof root.dccSaveWaitingContext==='function'){const original=root.dccSaveWaitingContext;root.dccSaveWaitingContext=function(){const previous=waitingIntent;waitingIntent=true;try{return original.apply(this,arguments);}finally{waitingIntent=previous;}};}");
 const pcMap="map(d=>{const n=d.next_action?{id:d.next_action.id,type:d.next_action.type,text:d.next_action.text,due:String(d.next_action.due_at||'').slice(0,10),due_at:d.next_action.due_at,assignee:d.next_action.assignee_name,status:d.next_action.status}:null;return";one(text,pcMap,'waiting PC map');text=text.replace(pcMap,"map(d=>{const w=d.stage_contexts&&d.stage_contexts.waiting&&d.stage_contexts.waiting.fields||{},n=d.next_action?{id:d.next_action.id,type:d.next_action.type,text:d.next_action.text,due:String((d.stage_code==='waiting'&&w.contact_date)||d.next_action.due_at||'').slice(0,10),due_at:(d.stage_code==='waiting'&&w.contact_date)||d.next_action.due_at,assignee:d.next_action.assignee_name,status:d.next_action.status}:null;return");
 const pc="quoteVersions:d.quote_versions||[],nextActionObj:n";one(text,pc,'waiting PC aliases');text=text.replace(pc,"quoteVersions:d.quote_versions||[],waitingReason:w.reason||'',waiting_reason:w.reason||'',waitingSpeaker:w.speaker||'',waiting_speaker:w.speaker||'',waitingCustomerStatement:w.statement||'',waiting_customer_statement:w.statement||'',waitingEvidence:w.evidence||'',waiting_evidence:w.evidence||'',expectedResumeAt:w.resume_date||'',expected_resume_at:w.resume_date||'',wakeUpAt:w.contact_date||'',wake_up_at:w.contact_date||'',nextActionObj:n");
 const mobile="stage_contexts:d.stage_contexts||{},stageHistory:d.stage_history||[]";one(text,mobile,'waiting mobile aliases');text=text.replace(mobile,"stage_contexts:d.stage_contexts||{},waitingReason:d.stage_contexts?.waiting?.fields?.reason||'',waitingSpeaker:d.stage_contexts?.waiting?.fields?.speaker||'',waitingCustomerStatement:d.stage_contexts?.waiting?.fields?.statement||'',waitingEvidence:d.stage_contexts?.waiting?.fields?.evidence||'',expectedResumeAt:d.stage_contexts?.waiting?.fields?.resume_date||'',wakeUpAt:d.stage_contexts?.waiting?.fields?.contact_date||'',stageHistory:d.stage_history||[]");
 return text;}
function applySql(){return `SET crm.waiting_context_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.waiting_context_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_close_nonwon_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name IN ('stage_contexts','wake_up_at') GROUP BY table_schema,table_name HAVING count(*)=2) OR to_regprocedure('crm_security.crm_write_command_v2_expected_amount_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fourteen}$expected$ THEN RAISE EXCEPTION 'waiting context after-amount prerequisite drift';END IF;END $guard$;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_expected_amount_20260906;ALTER FUNCTION public.crm_write_command_v2_expected_amount_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_expected_amount_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context'));
${helper()}
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN IF p_operation='waiting_context' THEN RETURN crm_security.crm_deal_waiting_context_command_v1(p_request_id,p_object_id,p_expected_version,p_payload);END IF;RETURN crm_security.crm_write_command_v2_expected_amount_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ BEGIN IF has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fifteen}$expected$ THEN RAISE EXCEPTION 'waiting context post-apply drift';END IF;END $post$;COMMIT;`}
function rollbackSql(){return `SET crm.waiting_context_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.waiting_context_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_expected_amount_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)') IS NULL OR to_regnamespace('crm_waiting_context_archive') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fifteen}$expected$ THEN RAISE EXCEPTION 'waiting context rollback drift';END IF;END $guard$;
CREATE SCHEMA crm_waiting_context_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_waiting_context_archive FROM PUBLIC,anon,authenticated,service_role;CREATE TABLE crm_waiting_context_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation='waiting_context';REVOKE ALL ON crm_waiting_context_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;DELETE FROM crm_security.command_receipts WHERE operation='waiting_context';
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb);ALTER FUNCTION crm_security.crm_write_command_v2_expected_amount_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_expected_amount_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fourteen}$expected$ THEN RAISE EXCEPTION 'waiting context rollback verification drift';END IF;END $post$;COMMIT;`}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-amount.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-amount.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-amount.sql','rollback-after-amount.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_AMOUNT_NOT_APPLIED',prerequisites:['pipeline-amount-expected/20260906'],operation:'waiting_context',intent:'existing_waiting_deal_context_only',absorbed_children:['next_action'],blocked_meanings:['transition_into_waiting','non_waiting_deal','mobile_response'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),amount_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-amount-expected/20260906/manifest.json'))),transition_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-transition/20260906/manifest.json')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,build,fourteen,fifteen};
