'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('../../pipeline-stage-check/20260906/build.cjs'),transition=require('../../pipeline-transition/20260906/build.cjs'),close=require('../../pipeline-close-nonwon/20260906/build.cjs'),amount=require('../../pipeline-amount-expected/20260906/build.cjs'),waiting=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),deal=s.uid(6,1),auth=s.mapping.accounts[0].auth_uid;const rid=n=>`f6090600-0092-4000-8000-${String(n).padStart(12,'0')}`;
const p=()=>({waiting_reason:'입대의 의결 대기',waiting_speaker:'김 관리소장',waiting_customer_statement:'10월 회의 후 다시 연락해 주세요.',wake_up_at:'2026-10-01',waiting_evidence:'관리소장 전화 확인',expected_resume_at:'2026-10-15'});
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());await db.exec(transition.applySql());await db.exec(close.applySql());await db.exec(amount.applySql());await db.exec(waiting.applySql());await db.query("UPDATE public.deals SET stage_code='waiting' WHERE id=$1",[deal]);return db;}
async function write(db,account,version,payload,request){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query("SELECT public.crm_write_command_v2($1,'waiting_context',$2,$3,$4) a",[request,deal,version,JSON.stringify(payload)])).rows[0].a;}
test('waiting context is one actor-scoped transaction',async t=>{const db=await setup();try{
 await t.test('context, wake, replacement Next, Activity, audit and receipt are exact',async()=>{const ack=await write(db,0,1,p(),rid(1));assert.equal(ack.actor_auth_uid,auth);assert.equal(ack.version,2);assert.equal(ack.cancelled_action_ids.length,1);const row=(await db.query('SELECT stage_code,wake_up_at,next_action,next_action_date,stage_contexts,version FROM public.deals WHERE id=$1',[deal])).rows[0];assert.equal(row.stage_code,'waiting');assert.equal(row.next_action,'대기 사유 확인 후 재접촉');assert.equal(row.next_action_date.toISOString().slice(0,10),'2026-10-01');assert.equal(row.stage_contexts.waiting.fields.evidence,'관리소장 전화 확인');assert.equal(row.version,2);assert.equal((await db.query("SELECT count(*)::int n FROM public.next_actions WHERE deal_id=$1 AND status='open'",[deal])).rows[0].n,1);for(const [table,where] of [['public.activities',"deal_id=$1 AND type='대기정보'"],['crm_security.audit_events',"deal_id=$1 AND action='waiting_context'"],['crm_security.command_receipts',"object_id=$1 AND operation='waiting_context'"]])assert.equal((await db.query(`SELECT count(*)::int n FROM ${table} WHERE ${where}`,[deal])).rows[0].n,1);});
 await t.test('operational source returns durable context and replacement Next UUID',async()=>{await db.exec(`SET request.jwt.claim.sub='${auth}';`);const data=(await db.query("SELECT public.crm_operational_source_v1('deal_core',null,100) a")).rows[0].a,row=data.items.find(x=>x.id===deal),wake=(await db.query("SELECT (wake_up_at AT TIME ZONE 'Asia/Seoul')::date::text d FROM public.deals WHERE id=$1",[deal])).rows[0].d;assert.equal(wake,'2026-10-01');assert.equal(row.stage_contexts.waiting.fields.statement,p().waiting_customer_statement);assert.equal(row.stage_contexts.waiting.fields.contact_date,'2026-10-01');assert.equal(row.next_action.text,'대기 사유 확인 후 재접촉');});
 await t.test('replay exact; reuse, stale, foreign scope and non-waiting state fail',async()=>{const replay=await write(db,0,1,p(),rid(1));assert.equal(replay.replayed,true);await assert.rejects(write(db,0,1,{...p(),waiting_reason:'변경 사유'},rid(1)),e=>e.code==='PT409');await assert.rejects(write(db,0,1,p(),rid(2)),e=>e.code==='PT409');await assert.rejects(write(db,1,2,p(),rid(3)),e=>e.code==='42501');await db.query("UPDATE public.deals SET stage_code='sent' WHERE id=$1",[deal]);await assert.rejects(write(db,0,2,p(),rid(4)),e=>e.code==='PT409');assert.equal((await db.query("SELECT count(*)::int n FROM public.activities WHERE deal_id=$1 AND type='대기정보'",[deal])).rows[0].n,1);for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('late audit failure rolls back context, Next and Activity',async()=>{const db=await setup();try{await db.exec("CREATE FUNCTION pg_temp.fail_wait_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='waiting_context' THEN RAISE EXCEPTION 'injected';END IF;RETURN NEW;END$$;CREATE TRIGGER fail_wait_audit BEFORE INSERT ON crm_security.audit_events FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_wait_audit();");await assert.rejects(write(db,0,1,p(),rid(20)),/injected/);const row=(await db.query('SELECT wake_up_at,stage_contexts,version FROM public.deals WHERE id=$1',[deal])).rows[0];assert.deepEqual(row,{wake_up_at:null,stage_contexts:{},version:1});assert.equal((await db.query("SELECT count(*)::int n FROM public.next_actions WHERE deal_id=$1 AND status='open'",[deal])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM public.activities WHERE deal_id=$1 AND type='대기정보'",[deal])).rows[0].n,0);}finally{await db.close();}});
test('rollback restores amount layer and archives receipts',async()=>{const db=await setup();try{await write(db,0,1,p(),rid(30));await db.exec(waiting.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_deal_expected_amount_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query('SELECT count(*)::int n FROM crm_waiting_context_archive.command_receipts')).rows[0].n,1);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)') IS NULL dropped")).rows[0].dropped,true);}finally{await db.close();}});
