'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),deal=s.uid(6,1),auth=s.mapping.accounts[0].auth_uid;
const rid=n=>`f6090600-0050-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());return db;}
async function call(db,id,version,payload,account=0){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query("SELECT public.crm_write_command_v2($1,'quote_version',$2,$3,$4) a",[id,deal,version,JSON.stringify(payload)])).rows[0].a;}
test('quote version chains after actions with server numbering, actor and idempotency',async t=>{const db=await setup();try{
 await t.test('client number/actor/time are ignored and Deal expected amount is untouched',async()=>{const before=(await db.query('SELECT amount,version FROM public.deals WHERE id=$1',[deal])).rows[0],ack=await call(db,rid(1),before.version,{version_no:99,amount:120000000,reason:'공사 범위 조정',created_at:'2000-01-01',created_by:'forged'});assert.equal(ack.version_no,1);assert.equal(ack.actor_auth_uid,auth);assert.equal(ack.version,before.version+1);const row=(await db.query('SELECT * FROM crm_security.quote_versions WHERE id=$1',[ack.quote_version_id])).rows[0];assert.equal(Number(row.amount),120000000);assert.notEqual(row.created_at.toISOString().slice(0,10),'2000-01-01');assert.equal((await db.query('SELECT amount FROM public.deals WHERE id=$1',[deal])).rows[0].amount,before.amount);});
 await t.test('replay is exact, changed payload conflicts and server increments version_no',async()=>{const replay=await call(db,rid(1),1,{amount:120000000,reason:'공사 범위 조정'});assert.equal(replay.replayed,true);await assert.rejects(call(db,rid(1),1,{amount:130000000,reason:'공사 범위 조정'}),e=>e.code==='PT409');const second=await call(db,rid(2),2,{version_no:1,amount:130000000,reason:'자재 변경'});assert.equal(second.version_no,2);assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.quote_versions WHERE deal_id=$1',[deal])).rows[0].n,2);});
 await t.test('stale, foreign scope and client direct access fail',async()=>{await assert.rejects(call(db,rid(3),1,{amount:1,reason:'정상 사유'}),e=>e.code==='PT409');await assert.rejects(call(db,rid(4),3,{amount:1,reason:'정상 사유'},1),e=>e.code==='42501');for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_table_privilege($1,'crm_security.quote_versions','SELECT,INSERT,UPDATE,DELETE') allowed",[role])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('rollback restores action layer and archives quote evidence',async()=>{const db=await setup();try{await call(db,rid(9),1,{amount:99000000,reason:'최초 견적'});await db.exec(quote.rollbackSql());assert.equal((await db.query("SELECT to_regclass('crm_security.quote_versions') IS NULL gone")).rows[0].gone,true);assert.equal((await db.query('SELECT count(*)::int n FROM crm_quote_version_archive.quote_versions')).rows[0].n,1);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_pipeline_action_command_v1(uuid,text,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);}finally{await db.close();}});
