'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname,root=path.resolve(dir,'../../..'),baseDir=path.resolve(dir,'../../mobile-today-outcome/20260906');
const read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function one(source,from,to,label){if(!source.includes(from))throw Error('customer support build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=read(path.join(baseDir,'operational-adapter.candidate.js'));
 source=one(source,"if(ack?.contract_version!==1||ack.ok!==true||ack.request_id!==command.request_id||ack.operation!==command.operation||ack.object_id!==command.object_id||ack.actor_auth_uid!==command.auth_uid||ack.actor_user_id!==command.user_id||typeof ack.replayed!=='boolean')fail('ACK_CONTRACT_MISMATCH');", "if(ack?.contract_version!==1||ack.ok!==true||ack.request_id!==command.request_id||ack.operation!==command.operation||ack.object_id!==command.object_id||typeof ack.replayed!=='boolean'||(!['opportunity_create','customer_support_action'].includes(command.operation)&&(ack.actor_auth_uid!==command.auth_uid||ack.actor_user_id!==command.user_id)))fail('ACK_CONTRACT_MISMATCH');",'frozen ACK actor compatibility');
 source=one(source,"'attachment_prepare','attachment_complete','expansion_pool_update']","'attachment_prepare','attachment_complete','expansion_pool_update','customer_support_action']",'operation');
 source=one(source,' function normalizeExpansionUpdate(objectId,payload){',` function normalizeSupport(objectId,payload){const allowed=['client_ref','target_type','target_key','opportunity_id','inquiry_id','site_name','rep_name','action_key','action_label','reason','completion_rule','status','requested_by','requested_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||!/^support-[0-9]{10,16}-[a-z0-9]{5}$/.test(payload.client_ref)||!['deal','inq'].includes(payload.target_type)||payload.target_key!==payload.target_type+':'+objectId||(payload.target_type==='deal'?(payload.opportunity_id!==objectId||payload.inquiry_id!==null):(payload.inquiry_id!==objectId||payload.opportunity_id!==null))||payload.status!=='requested')fail('CUSTOMER_SUPPORT_ACTION_NOT_CONNECTED');const keys=['response_request','inquiry_review','call','message','recontact_result','waiting_context','manager_consult','waiting_review','material_support','meeting_check','contact_check','contact_activity','reactivate_review','dormant_review','recontact_schedule','support_detail'];if(!keys.includes(payload.action_key))fail('INVALID_SUPPORT_ACTION');return {client_ref:payload.client_ref,target_type:payload.target_type,action_key:payload.action_key,action_label:text(payload.action_label,1,200,'INVALID_SUPPORT_ACTION'),reason:text(payload.reason,1,4000,'INVALID_SUPPORT_ACTION'),completion_rule:text(payload.completion_rule,1,1000,'INVALID_SUPPORT_ACTION')};}
 function normalizeExpansionUpdate(objectId,payload){`,'normalizer');
 source=one(source,"'attachment_prepare','attachment_complete'].includes(operation)","'attachment_prepare','attachment_complete','customer_support_action'].includes(operation)",'sentinel');
 source=one(source,"else if(operation==='expansion_pool_update')normalized=normalizeExpansionUpdate(objectId,payload);else normalized=normalizeTrash", "else if(operation==='expansion_pool_update')normalized=normalizeExpansionUpdate(objectId,payload);else if(operation==='customer_support_action')normalized=normalizeSupport(objectId,payload);else normalized=normalizeTrash",'normalize route');
 source=one(source,"  if(command.operation==='lineage_link'&&(ack.intent!=='lineage_link'",`  if(command.operation==='customer_support_action'&&(ack.support_action_id==null||ack.client_ref!==command.payload.client_ref||ack.target_type!==command.payload.target_type||ack.target_id!==command.object_id||!UUID.test(ack.rep_user_id)||typeof ack.rep_name!=='string'||ack.action_key!==command.payload.action_key||ack.action_label!==command.payload.action_label||ack.status!=='requested'||!UUID.test(ack.requested_by_auth_uid)||!UUID.test(ack.requested_by_user_id)||typeof ack.requested_by_name!=='string'||typeof ack.requested_at!=='string'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='lineage_link'&&(ack.intent!=='lineage_link'`,'ACK');
 return source;
}
function overlay(){let source=read(path.join(baseDir,'operational-overlay.candidate.js'));
 source=one(source,"'lineage_link','expansion_pool_update'])","'lineage_link','expansion_pool_update','customer_support_action'])",'connected');
 source=one(source,"expansion_events:scoped.expansion_events||[],dups:[]", "expansion_events:scoped.expansion_events||[],customerSupportActions:scoped.customer_support_actions||[],customer_support_actions:scoped.customer_support_actions||[],dups:[]",'shell');
 source=one(source,'createOwnerOverride=null,expansionIntent=false;','createOwnerOverride=null,expansionIntent=false,supportIntent=false;','state');
 source=one(source,'  function applyExpansionAck(q){',`  function applySupportAck(q){root.B=root.B||{};const rows=Array.isArray(root.B.customerSupportActions)?root.B.customerSupportActions:(root.B.customerSupportActions=[]);if(!rows.some(x=>x.client_ref===q.ack.client_ref))rows.push({id:q.ack.support_action_id,client_ref:q.ack.client_ref,target_type:q.ack.target_type,target_key:q.ack.target_type+':'+q.object_id,opportunity_id:q.ack.target_type==='deal'?q.object_id:null,inquiry_id:q.ack.target_type==='inq'?q.object_id:null,rep_user_id:q.ack.rep_user_id,rep_name:q.ack.rep_name,action_key:q.ack.action_key,action_label:q.ack.action_label,reason:q.payload.reason,completion_rule:q.payload.completion_rule,status:'requested',requested_by:q.ack.requested_by_name,requested_at:q.ack.requested_at});root.B.customer_support_actions=rows;if(typeof root.paintRepManagement==='function')root.paintRepManagement();}
  function applyExpansionAck(q){`,'ACK hydrator');
 source=one(source,"  function extraAck(q){if(q.operation==='expansion_pool_update')applyExpansionAck(q);}","  function extraAck(q){if(q.operation==='expansion_pool_update')applyExpansionAck(q);if(q.operation==='customer_support_action')applySupportAck(q);}",'ACK route');
 source=one(source,"  root.pushWrite=function(op,payload){if(todayOutcome)","  root.pushWrite=function(op,payload){if(op==='customer_support_action'&&!supportIntent)throw error('CUSTOMER_SUPPORT_ACTION_NOT_CONNECTED');if(todayOutcome)",'guard');
 source=one(source,"expected=op==='expansion_pool_update'?expansionVersionFor(id):op.startsWith('inquiry_')", "expected=op==='expansion_pool_update'?expansionVersionFor(id):op==='customer_support_action'||op.startsWith('inquiry_')",'version sentinel');
 source=one(source,"  if(typeof root.pickToday==='function')",`  if(typeof root.repSupportRecord==='function'){const original=root.repSupportRecord;root.repSupportRecord=function(){const prior=supportIntent;supportIntent=true;try{return original.apply(this,arguments);}finally{supportIntent=prior;}};}
  if(typeof root.pickToday==='function')`,'named handler');
 return source;
}
function transport(){let source=read(path.join(baseDir,'transport.candidate.js'));
 source=one(source,"const [deals,inquiries,expansion_pool]=await Promise.all([collect('deal_core'),collect('inquiry_core'),collect('expansion_pool')]);", "const [deals,inquiries,expansion_pool,customer_support_actions]=await Promise.all([collect('deal_core'),collect('inquiry_core'),collect('expansion_pool'),collect('customer_support_action')]);",'collect');
 source=one(source,'deals,inquiries,expansion_pool,expansion_events:', 'deals,inquiries,expansion_pool,customer_support_actions,customerSupportActions:customer_support_actions,expansion_events:','bundle');
 return source;
}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-mobile-today.sql':applySql(),'rollback-before-mobile-today.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':transport()};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md',...Object.keys(generated)],sources=['sql/mobile-today-outcome/20260906/manifest.json','crm.html','sql/20260905_customer_support_actions.sql','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operation:'customer_support_action',ui_coverage_candidate:['O02'],prerequisite:'mobile-today-outcome/20260906',surface:'pc_admin_only',meaning:'append-only requested support record; downstream action is independent',allowed_action_keys:['response_request','inquiry_review','call','message','recontact_result','waiting_context','manager_consult','waiting_review','material_support','meeting_check','contact_check','contact_activity','reactivate_review','dormant_review','recontact_schedule','support_detail'],server_rules:{actor:'approved unexpired admin UUID',scope:'current can_deal(...,true) or can_inquiry target scope',target_owner:'approved active rep UUID from locked target',status:'requested only',idempotency:'common command receipt; client_ref preserved only for UI correlation'},read_additions:['customer_support_action admin-scoped operational source'],blocked:['downstream completion inference','client actor/time/status/rep/site authority','O01 head-office rep eligibility'],rollback:'request ledger/receipts archived; P09M write/read layer restored',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,transport,applySql,rollbackSql,build};
