'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const personal=require('../../personal-state-compat/20260906/build.cjs'),cutover=require('../../operational-cutover-candidate/20260906/build.cjs'),won=require('../../pipeline-close-won/20260906/build.cjs'),update=require('../../expansion-pool-update/20260906/build.cjs'),notes=require('../../expansion-note-context/20260906/build.cjs'),reminder=require('../../message-reminder/20260906/build.cjs'),postpone=require('../../next-action-postpone/20260906/build.cjs'),today=require('../../mobile-today-outcome/20260906/build.cjs'),support=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const deal=s.uid(6,1),inq=s.uid(5,1),admin=s.uid(1,5),adminAuth=s.mapping.accounts[4].auth_uid,repAuth=s.mapping.accounts[0].auth_uid;
async function one(db,sql,params=[]){return (await db.query(sql,params)).rows[0];}
async function storage(db){await db.exec(`CREATE SCHEMA IF NOT EXISTS storage;CREATE TABLE IF NOT EXISTS storage.buckets(id text PRIMARY KEY,name text NOT NULL,public boolean NOT NULL DEFAULT false,file_size_limit bigint,allowed_mime_types text[]);CREATE TABLE IF NOT EXISTS storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text NOT NULL REFERENCES storage.buckets(id),name text NOT NULL,owner_id text,metadata jsonb,UNIQUE(bucket_id,name));GRANT USAGE ON SCHEMA storage TO authenticated;GRANT INSERT ON storage.objects TO authenticated;`);}
async function setup(){const db=await personal.setup();await storage(db);await db.exec(cutover.compose('apply',{localPersonalCandidate:true}));await db.exec(won.applySql());await db.exec(update.applySql());await db.exec(notes.applySql());await db.exec(reminder.applySql());await db.exec(postpone.applySql());await db.exec(today.applySql());await db.query("INSERT INTO crm_security.object_scope(scope_id,user_id,deal_id,inquiry_id,can_write,reviewed_by,expires_at) VALUES($1,$2,$3,NULL,true,'O02 test',now()+interval '1 day'),($4,$2,NULL,$5,true,'O02 test',now()+interval '1 day')",[s.uid(10,201),admin,deal,s.uid(10,202),inq]);await db.exec(support.applySql());await db.exec(`SET request.jwt.claim.sub='${adminAuth}'`);return db;}
function payload(type='deal',key='call'){return {client_ref:'support-1788700000000-abc12',target_type:type,action_key:key,action_label:key==='call'?'재접촉 실행':'응대 요청',reason:'약속일이 지났습니다.',completion_rule:type==='deal'?'접촉 결과 + 다음 Stage 판단':'최초 통화·문자 Activity 기록'};}
async function write(db,target=deal,p=payload(),request='f6090600-0910-4000-8000-000000000001'){return (await db.query("SELECT public.crm_write_command_v2($1,'customer_support_action',$2,0,$3) ack",[request,target,JSON.stringify(p)])).rows[0].ack;}
test('admin creates one requested Deal support record with server actor and owner UUID',async()=>{const db=await setup();try{const ack=await write(db);assert.equal(ack.status,'requested');assert.equal(ack.target_id,deal);assert.equal(ack.rep_user_id,s.uid(1,1));assert.equal(ack.requested_by_user_id,admin);const row=await one(db,'SELECT target_type,target_id,rep_user_id,status,requested_by_auth_uid FROM crm_security.customer_support_actions WHERE id=$1',[ack.support_action_id]);assert.deepEqual(row,{target_type:'deal',target_id:deal,rep_user_id:s.uid(1,1),status:'requested',requested_by_auth_uid:adminAuth});const read=(await db.query("SELECT public.crm_operational_source_v1('customer_support_action',NULL,100) x")).rows[0].x;assert.equal(read.items.length,1);assert.equal(read.items[0].client_ref,ack.client_ref);assert.equal(read.items[0].target_key,'deal:'+deal);}finally{await db.close();}});
test('inquiry request is separate from downstream Activity and Next state',async()=>{const db=await setup();try{const beforeA=(await one(db,'SELECT count(*)::int n FROM public.activities')).n,beforeN=(await one(db,'SELECT count(*)::int n FROM public.next_actions')).n,ack=await write(db,inq,{...payload('inq','response_request'),client_ref:'support-1788700000001-def34'},'f6090600-0910-4000-8000-000000000002');assert.equal(ack.target_type,'inq');assert.equal((await one(db,'SELECT count(*)::int n FROM public.activities')).n,beforeA);assert.equal((await one(db,'SELECT count(*)::int n FROM public.next_actions')).n,beforeN);assert.equal((await one(db,'SELECT assigned_to FROM public.inquiries WHERE id=$1',[inq])).assigned_to,s.uid(1,1));}finally{await db.close();}});
test('receipt replay is exact while reuse, non-admin and unscoped target fail',async()=>{const db=await setup();try{const request='f6090600-0910-4000-8000-000000000003',ack=await write(db,deal,payload(),request),replay=await write(db,deal,payload(),request);assert.equal(replay.replayed,true);assert.equal(replay.support_action_id,ack.support_action_id);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_security.customer_support_actions')).n,1);await assert.rejects(write(db,deal,{...payload(),reason:'다른 사유'},request),e=>e.code==='PT409');await db.exec(`SET request.jwt.claim.sub='${repAuth}'`);await assert.rejects(write(db,deal,payload(),'f6090600-0910-4000-8000-000000000004'),e=>e.code==='42501');await db.exec(`SET request.jwt.claim.sub='${adminAuth}'`);await assert.rejects(write(db,s.uid(6,2),{...payload(),client_ref:'support-1788700000002-ghi56'},'f6090600-0910-4000-8000-000000000005'),e=>e.code==='42501');}finally{await db.close();}});
test('rollback archives support evidence and restores the P09M write/read layer',async()=>{const db=await setup();try{await write(db);await db.exec(support.rollbackSql());assert.equal((await one(db,'SELECT count(*)::int n FROM crm_customer_support_archive.actions')).n,1);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_customer_support_archive.command_receipts')).n,1);assert.equal((await one(db,"SELECT to_regprocedure('crm_security.crm_mobile_today_outcome_command_v1(uuid,text,uuid,integer,jsonb)') IS NOT NULL present")).present,true);assert.equal((await one(db,"SELECT to_regprocedure('public.crm_operational_source_v1(text,uuid,integer)') IS NOT NULL present")).present,true);}finally{await db.close();}});
