'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),transition=require('../../pipeline-transition/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),twelve=transition.twelve;
const thirteen=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text]))`;
const helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');
function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function sourceFragment(){let text=transition.sourceFragment();const marker='d.lifecycle_status,d.outcome,d.wake_up_at,d.stage_entered_at,';one(text,marker,'close read fields');return text.replace(marker,'d.lifecycle_status,d.outcome,d.lost_reason,d.lost_kind,d.badfit_type,d.wake_up_at,d.stage_entered_at,');}
function adapter(){let text=transition.adapter();const ops="'stage_check','transition']";one(text,ops,'close adapter operations');text=text.replace(ops,"'stage_check','transition','close']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'close normalize marker');
 const fn=" const CLOSE_OUTCOMES=new Set(['lost','badfit','nocontact']),CLOSE_STRUCTURED=new Set(['lost','badfit_lead','nocontact']);\n function normalizeClose(objectId,payload){let from,outcome,closed_date,category,detail,reason_source,note;if(object(payload.stage_context)){const allowed=['opportunity_id','from','to','stage_code','at','transition_date','note','reason','stage_context','stage_contexts','contract_amount','completion_date','outcome','closed_at','won_amount'],s=payload.stage_context,f=s&&s.fields;if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||!object(f)||Object.keys(f).some(k=>!['close_reason','close_detail'].includes(k))||!CLOSE_STRUCTURED.has(payload.to)||payload.outcome!==payload.to||payload.stage_code!==payload.from||s.from!==payload.from||s.to!==payload.to||s.transition_date!==payload.transition_date||s.terminal!==true||payload.won_amount!==null||payload.contract_amount!==undefined||payload.completion_date!==undefined||!/^\\d{4}-\\d{2}-\\d{2}$/.test(payload.transition_date)||typeof f.close_reason!=='string'||!f.close_reason.trim()||f.close_reason.length>500||typeof f.close_detail!=='string'||f.close_detail.trim().length<5||f.close_detail.length>8000||typeof payload.note!=='string'||!payload.note.trim()||payload.note.length>16000)fail('CLOSE_INTENT_NOT_CONNECTED');from=payload.from;outcome=payload.to==='badfit_lead'?'badfit':payload.to;closed_date=payload.transition_date;category=f.close_reason.trim();detail=f.close_detail.trim();reason_source='structured';note=payload.note.trim();}else{const allowed=['opportunity_id','outcome','reason','reason_source','stage_code','closed_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||!CLOSE_OUTCOMES.has(payload.outcome)||typeof payload.stage_code!=='string'||!payload.stage_code||typeof payload.reason!=='string'||payload.reason.length>8500||typeof payload.reason_source!=='string'||!payload.reason_source.trim()||payload.reason_source.length>50||typeof payload.closed_at!=='string')fail('CLOSE_INTENT_NOT_CONNECTED');const i=payload.reason.indexOf(' · ');if(i<1)fail('INVALID_CLOSE');from=payload.stage_code;outcome=payload.outcome;closed_date=null;category=payload.reason.slice(0,i).trim();detail=payload.reason.slice(i+3).trim();reason_source=payload.reason_source.trim();note=payload.reason.trim();if(!category||category.length>500||detail.length<5||detail.length>8000)fail('INVALID_CLOSE');}return {from,outcome,closed_date,category,detail,reason_source,note};}\n";
 text=text.replace(marker,fn+marker);
 const dispatch="else if(operation==='stage_check')normalized=normalizeStage(objectId,payload);else normalized=normalizeTransition(objectId,payload);";one(text,dispatch,'close adapter dispatch');text=text.replace(dispatch,"else if(operation==='stage_check')normalized=normalizeStage(objectId,payload);else if(operation==='transition')normalized=normalizeTransition(objectId,payload);else normalized=normalizeClose(objectId,payload);");
 const ack="  if(command.operation==='close'&&(ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||ack.from_stage!==command.payload.from||ack.outcome!==command.payload.outcome||ack.lifecycle_status!=='closed'||!UUID.test(ack.close_event_id)||!UUID.test(ack.stage_history_id)||!UUID.test(ack.activity_id)||!UUID.test(ack.audit_event_id)||!Array.isArray(ack.completed_action_ids)||!ack.stage_contexts||typeof ack.stage_contexts!=='object'||typeof ack.closed_at!=='string'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','close ACK return');return text.replace('  return ack;}',ack+'  return ack;}');}
function overlay(){let text=transition.overlay();const connected="'stage_check','transition']";one(text,connected,'close overlay connected');text=text.replace(connected,"'stage_check','transition','close']");
 const state='let compound=null,actionIntent=null,completeActionId=null,stageIntent=false,transitionCompound=false;const versions=new Map(),seenAcks=new Set();';one(text,state,'close overlay state');text=text.replace(state,'let compound=null,actionIntent=null,completeActionId=null,stageIntent=false,transitionCompound=false,closeCompound=false,preClose=false;const versions=new Map(),seenAcks=new Set();');
 const transitionAck="  function applyTransitionAck(q){const a=q.ack;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.stage_code=d.code=a.to_stage;d.stage_contexts=d.stageContexts=a.stage_contexts;if(Array.isArray(d.stageHistory))d.stageHistory.push({id:a.stage_history_id,from:a.from_stage,to:a.to_stage,at:a.stage_entered_at});}}";one(text,transitionAck,'close ACK marker');
 text=text.replace(transitionAck,transitionAck+"\n  function applyCloseAck(q){const a=q.ack;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.outcome=a.outcome;d.lifecycle_status='closed';d.closed_at=a.closed_at;d.stage_contexts=d.stageContexts=a.stage_contexts;d.lost_reason=a.lost_reason;d.lost_kind=a.lost_kind;d.badfit_type=a.badfit_type;d.nextAction=d.nextActionObj=null;if(Array.isArray(d.stageHistory))d.stageHistory.push({id:a.stage_history_id,from:a.from_stage,to:a.outcome,at:a.closed_at});}}");
 const sync="if(q.operation==='transition')applyTransitionAck(q);";one(text,sync,'close ACK sync');text=text.replace(sync,sync+"if(q.operation==='close')applyCloseAck(q);");
 const push='root.pushWrite=function(op,payload){if(transitionCompound&&companion.has(op))';one(text,push,'close push marker');text=text.replace(push,"root.pushWrite=function(op,payload){if(preClose&&(op==='activity'||op==='next_action_complete'))return 'absorbed:'+op;if(closeCompound&&op==='activity')return 'absorbed:'+op;if(transitionCompound&&companion.has(op))");
 const enqueue="if(op==='transition'){transitionCompound=true;(root.queueMicrotask||queueMicrotask)(()=>{transitionCompound=false;});}syncQueue();";one(text,enqueue,'close enqueue marker');text=text.replace(enqueue,"if(op==='transition'){transitionCompound=true;(root.queueMicrotask||queueMicrotask)(()=>{transitionCompound=false;});}if(op==='close'){closeCompound=true;(root.queueMicrotask||queueMicrotask)(()=>{closeCompound=false;});}syncQueue();");
 const wrapMarker="  function wrap(name,intent,predicate){";one(text,wrapMarker,'close legacy wrapper marker');text=text.replace(wrapMarker,"  if(typeof root.commitClose==='function'){const original=root.commitClose;root.commitClose=function(outcome){if(!['lost','badfit','nocontact'].includes(outcome))return original.apply(this,arguments);const previous=preClose;preClose=true;try{return original.apply(this,arguments);}finally{preClose=previous;}};}\n"+wrapMarker);
 const mobile="stage_contexts:d.stage_contexts||{},stageHistory:d.stage_history||[],tl:[]";one(text,mobile,'close mobile aliases');text=text.replace(mobile,"stage_contexts:d.stage_contexts||{},stageHistory:d.stage_history||[],outcome:d.outcome||null,lifecycle_status:d.lifecycle_status||'active',closed_at:d.closed_at||null,lost_reason:d.lost_reason||null,lost_kind:d.lost_kind||null,badfit_type:d.badfit_type||null,tl:[]");
 return text;}
function applySql(){return `SET crm.close_nonwon_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.close_nonwon_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu'
 OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb)') IS NULL
 OR to_regprocedure('crm_security.crm_operational_source_fragment_v1(text,uuid,integer)') IS NULL OR NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name='stage_contexts')
 OR to_regprocedure('crm_security.crm_write_command_v2_transition_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_close_nonwon_20260906(text,uuid,integer)') IS NOT NULL
 OR to_regprocedure('crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL OR to_regclass('crm_security.deal_close_events') IS NOT NULL
 OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twelve}$expected$
 THEN RAISE EXCEPTION 'close nonwon after-transition prerequisite drift';END IF;END $guard$;
CREATE TEMP TABLE close_source_guard AS SELECT p.oid,p.prosrc,p.proconfig,coalesce(p.proacl::text,'') acl FROM pg_proc p WHERE p.oid='public.crm_operational_source_v1(text,uuid,integer)'::regprocedure;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_transition_20260906;ALTER FUNCTION public.crm_write_command_v2_transition_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;
REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_transition_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) RENAME TO crm_operational_source_fragment_pre_close_nonwon_20260906;REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_pre_close_nonwon_20260906(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE crm_security.deal_close_events(event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id uuid NOT NULL UNIQUE,deal_id uuid NOT NULL REFERENCES public.deals(id) ON DELETE RESTRICT,from_stage text NOT NULL,outcome text NOT NULL CHECK(outcome IN ('lost','badfit','nocontact')),closed_date date NOT NULL,category text NOT NULL,detail text NOT NULL,reason_source text NOT NULL,actor_auth_uid uuid NOT NULL,actor_user_id uuid NOT NULL REFERENCES public.users(user_id) ON DELETE RESTRICT,recorded_at timestamptz NOT NULL,stage_history_id uuid NOT NULL REFERENCES public.stage_history(id) ON DELETE RESTRICT,activity_id uuid NOT NULL REFERENCES public.activities(id) ON DELETE RESTRICT,completed_action_ids jsonb NOT NULL CHECK(jsonb_typeof(completed_action_ids)='array'));
ALTER TABLE crm_security.deal_close_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON crm_security.deal_close_events FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close'));
${helper()}
${sourceFragment()}
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN IF p_operation='close' THEN RETURN crm_security.crm_deal_close_nonwon_command_v1(p_request_id,p_object_id,p_expected_version,p_payload);END IF;RETURN crm_security.crm_write_command_v2_transition_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ DECLARE changed integer;BEGIN SELECT count(*) INTO changed FROM close_source_guard g JOIN pg_proc p ON p.oid=g.oid WHERE p.prosrc IS DISTINCT FROM g.prosrc OR p.proconfig IS DISTINCT FROM g.proconfig OR coalesce(p.proacl::text,'') IS DISTINCT FROM g.acl;
 IF changed<>0 OR has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') OR has_table_privilege('authenticated','crm_security.deal_close_events','SELECT') OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='crm_security.deal_close_events'::regclass) OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${thirteen}$expected$ THEN RAISE EXCEPTION 'close nonwon post-apply drift';END IF;END $post$;
COMMIT;`}
function rollbackSql(){return `SET crm.close_nonwon_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.close_nonwon_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_transition_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_close_nonwon_20260906(text,uuid,integer)') IS NULL OR to_regclass('crm_security.deal_close_events') IS NULL OR to_regnamespace('crm_close_nonwon_archive') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${thirteen}$expected$ THEN RAISE EXCEPTION 'close nonwon rollback drift';END IF;END $guard$;
CREATE SCHEMA crm_close_nonwon_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_close_nonwon_archive FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE crm_close_nonwon_archive.deal_close_events AS TABLE crm_security.deal_close_events;CREATE TABLE crm_close_nonwon_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation='close';REVOKE ALL ON crm_close_nonwon_archive.deal_close_events,crm_close_nonwon_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;
DELETE FROM crm_security.command_receipts WHERE operation='close';DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb);DROP TABLE crm_security.deal_close_events;
ALTER FUNCTION crm_security.crm_write_command_v2_transition_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DROP FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer);ALTER FUNCTION crm_security.crm_operational_source_fragment_pre_close_nonwon_20260906(text,uuid,integer) RENAME TO crm_operational_source_fragment_v1;REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_transition_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL OR to_regclass('crm_security.deal_close_events') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twelve}$expected$ THEN RAISE EXCEPTION 'close nonwon rollback verification drift';END IF;END $post$;COMMIT;`}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-transition.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-transition.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-transition.sql','rollback-after-transition.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_TRANSITION_NOT_APPLIED',prerequisites:['pipeline-transition/20260906'],operation:'close',intent:'non_won_close_only',outcomes:['lost','badfit','nocontact'],absorbed_children:{pc_after_parent:['activity'],mobile_before_parent:['activity','next_action_complete']},blocked_meanings:['won','amount','completion','expansion_pool_upsert'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),golden_mobile:sha(fs.readFileSync(path.join(root,'mobile.html'))),stage_transition:sha(fs.readFileSync(path.join(root,'stage-transition.js'))),stage_ui:sha(fs.readFileSync(path.join(root,'stage-transition-ui.js'))),transition_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-transition/20260906/manifest.json')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,build,sourceFragment,twelve,thirteen};
