'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('../../pipeline-stage-check/20260906/build.cjs'),transition=require('../../pipeline-transition/20260906/build.cjs'),close=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),deal=s.uid(6,1),auth=s.mapping.accounts[0].auth_uid;
const rid=n=>`f6090600-0081-4000-8000-${String(n).padStart(12,'0')}`;
const todayKst=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());await db.exec(transition.applySql());await db.exec(close.applySql());return db;}
async function write(db,account,version,payload,request,op='close'){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[request,op,deal,version,JSON.stringify(payload)])).rows[0].a;}
const lost=()=>({from:'first_contact',outcome:'lost',closed_date:'2026-09-01',category:'가격 열세',detail:'타사 최종 견적 선정 사실을 관리소장에게 확인함',reason_source:'structured',note:'실주 사유: 가격 열세'});
const mobileBadfit=()=>({from:'first_contact',outcome:'badfit',closed_date:null,category:'공사범위 밖',detail:'현재 회사의 영업 공사범위에 포함되지 않음을 확인함',reason_source:'text',note:'공사범위 밖 · 현재 회사의 영업 공사범위에 포함되지 않음을 확인함'});
test('non-won close is one actor-scoped transaction and preserves source stage',async t=>{const db=await setup();try{
 await t.test('deal, open Next, history, Activity, private event, audit and receipt are exact',async()=>{const ack=await write(db,0,1,lost(),rid(1));assert.equal(ack.actor_auth_uid,auth);assert.equal(ack.version,2);assert.equal(ack.from_stage,'first_contact');assert.equal(ack.stage_code,'first_contact');assert.equal(ack.outcome,'lost');assert.equal(ack.lifecycle_status,'closed');assert.equal(ack.completed_action_ids.length,1);const row=(await db.query('SELECT stage_code,outcome,lifecycle_status,lost_reason,lost_kind,next_action,next_action_date,stage_contexts,version FROM public.deals WHERE id=$1',[deal])).rows[0];assert.equal(row.stage_code,'first_contact');assert.equal(row.outcome,'lost');assert.equal(row.lifecycle_status,'closed');assert.equal(row.lost_reason,'가격 열세');assert.equal(row.lost_kind,'뺏김');assert.equal(row.next_action,null);assert.equal(row.next_action_date,null);assert.equal(row.stage_contexts.lost.fields.close_detail,lost().detail);assert.equal(row.version,2);const completed=(await db.query("SELECT count(*)::int n,bool_and(completed_at>=created_at) sane FROM public.next_actions WHERE deal_id=$1 AND status='completed' AND completed_at IS NOT NULL",[deal])).rows[0];assert.equal(completed.n,1);assert.equal(completed.sane,true);for(const [table,where] of [['public.stage_history',"opportunity_id=$1 AND to_stage='lost'"],['public.activities',"deal_id=$1 AND type='종료'"],['crm_security.deal_close_events',"deal_id=$1"],['crm_security.audit_events',"deal_id=$1 AND action='close'"],['crm_security.command_receipts',"object_id=$1 AND operation='close'"]])assert.equal((await db.query(`SELECT count(*)::int n FROM ${table} WHERE ${where}`,[deal])).rows[0].n,1);});
 await t.test('operational source exposes closure fields and durable detail',async()=>{await db.exec(`SET request.jwt.claim.sub='${auth}';`);const data=(await db.query("SELECT public.crm_operational_source_v1('deal_core',null,100) a")).rows[0].a,row=data.items.find(x=>x.id===deal);assert.equal(row.stage_code,'first_contact');assert.equal(row.outcome,'lost');assert.equal(row.lost_reason,'가격 열세');assert.equal(row.lost_kind,'뺏김');assert.equal(row.stage_contexts.lost.fields.close_detail,lost().detail);assert.equal(row.stage_history[0].to,'lost');});
 await t.test('replay is exact; reuse, stale, reopen, won and foreign scope fail with no duplicates',async()=>{const replay=await write(db,0,1,lost(),rid(1));assert.equal(replay.replayed,true);const changed=lost();changed.detail+=' 변경';await assert.rejects(write(db,0,1,changed,rid(1)),e=>e.code==='PT409');await assert.rejects(write(db,0,1,lost(),rid(2)),e=>e.code==='PT409');await assert.rejects(write(db,0,2,lost(),rid(3)),e=>e.code==='PT409');await assert.rejects(write(db,0,2,{...lost(),outcome:'won'},rid(4)),e=>e.code==='22023');await assert.rejects(write(db,1,2,lost(),rid(5)),e=>e.code==='42501');assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.deal_close_events WHERE deal_id=$1',[deal])).rows[0].n,1);for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'crm_security.crm_deal_close_nonwon_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);assert.equal((await db.query("SELECT has_table_privilege('authenticated','crm_security.deal_close_events','SELECT') allowed")).rows[0].allowed,false);});
 }finally{await db.close();}});
test('mobile badfit alias stores DB outcome and server close date',async()=>{const db=await setup();try{const ack=await write(db,0,1,mobileBadfit(),rid(10));assert.equal(ack.outcome,'badfit');assert.equal(ack.badfit_type,'공사범위 밖');assert.equal((await db.query("SELECT (closed_at AT TIME ZONE 'Asia/Seoul')::date::text d FROM public.deals WHERE id=$1",[deal])).rows[0].d,todayKst());const row=(await db.query('SELECT stage_code,outcome,badfit_type FROM public.deals WHERE id=$1',[deal])).rows[0];assert.deepEqual(row,{stage_code:'first_contact',outcome:'badfit',badfit_type:'공사범위 밖'});}finally{await db.close();}});
test('injected late audit failure rolls back every closure side effect',async()=>{const db=await setup();try{await db.exec("CREATE FUNCTION pg_temp.fail_close_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='close' THEN RAISE EXCEPTION 'injected';END IF;RETURN NEW;END$$;CREATE TRIGGER fail_close_audit BEFORE INSERT ON crm_security.audit_events FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_close_audit();");await assert.rejects(write(db,0,1,lost(),rid(20)),/injected/);assert.deepEqual((await db.query('SELECT stage_code,outcome,lifecycle_status,version,stage_contexts FROM public.deals WHERE id=$1',[deal])).rows[0],{stage_code:'first_contact',outcome:null,lifecycle_status:'active',version:1,stage_contexts:{}});assert.equal((await db.query("SELECT count(*)::int n FROM public.next_actions WHERE deal_id=$1 AND status='open'",[deal])).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM public.stage_history WHERE opportunity_id=$1',[deal])).rows[0].n,0);assert.equal((await db.query("SELECT count(*)::int n FROM public.activities WHERE deal_id=$1 AND type='종료'",[deal])).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.deal_close_events WHERE deal_id=$1',[deal])).rows[0].n,0);}finally{await db.close();}});
test('rollback restores transition layer and privately archives close evidence',async()=>{const db=await setup();try{await write(db,0,1,lost(),rid(30));await db.exec(close.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query('SELECT count(*)::int n FROM crm_close_nonwon_archive.deal_close_events')).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM crm_close_nonwon_archive.command_receipts')).rows[0].n,1);assert.equal((await db.query("SELECT to_regclass('crm_security.deal_close_events') IS NULL dropped")).rows[0].dropped,true);}finally{await db.close();}});
