'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),build=require('./build.cjs');
const deal='f6090500-0006-4000-8000-000000000001';
function load(text,name){const m=new Module(name);m._compile(text,name+'.js');return m.exports;}
function structured(){const fields={close_reason:'가격 열세',close_detail:'타사 최종 견적 선정 사실을 확인함'},s={transition_date:'2026-09-01',skip_reason:'',memo:'',fields,from:'compete',to:'lost',recorded_at:'client',actor:'client',terminal:true,next:null};return {opportunity_id:deal,from:'compete',to:'lost',stage_code:'compete',at:'client',transition_date:'2026-09-01',note:'실주 사유: 가격 열세',reason:'가격 열세',stage_context:s,stage_contexts:{lost:s},outcome:'lost',closed_at:'client',won_amount:null};}
function base(extra={}){const queued=[],listeners={},adapter=load(build.adapter(),'close-adapter'),root={OperationalAdapter:adapter,TOKEN:'jwt',ME:{id:'u'},WRITE_Q:[],console,B:{deals:[]},Phase1:{read:async()=>({data:{deals:[],inquiries:[]}}),queue:{list:()=>[],enqueue:(op,id,version,payload)=>{const c=adapter.normalize(op,id,version,payload),q={...c,payload:c.payload,request_id:'f6090600-0081-4000-8000-000000000099'};queued.push(q);return q;},flush:async()=>{}}},addEventListener:(n,fn)=>{listeners[n]=fn},...extra};return {root,queued,ui:load(build.overlay(),'close-overlay')};}
test('PC structured close absorbs its following Activity',()=>{const x=base({saveStructured(){this.pushWrite('close',structured());this.pushWrite('activity',{opportunity_id:deal,type:'단계전환',note:'실주',result:'가격 열세',occurred_at:'2026-09-01T00:00:00Z'});}});x.ui.install(x.root).versions.set(deal,5);x.root.saveStructured();assert.equal(x.queued.length,1);assert.equal(x.queued[0].operation,'close');assert.equal(x.queued[0].payload.outcome,'lost');});
test('mobile legacy close absorbs Activity and Next completion sent before parent',()=>{const payload={opportunity_id:deal,outcome:'nocontact',reason:'3회 이상 시도 · 전화와 문자 모두 응답이 없었음',reason_source:'text',stage_code:'sent',closed_at:'2026-09-06T12:00:00Z'},x=base({commitClose(){this.pushWrite('activity',{opportunity_id:deal,type:'종료'});this.pushWrite('next_action_complete',{opportunity_id:deal,action_id:'f6090500-0009-4000-8000-000000000001'});this.pushWrite('close',payload);}});x.ui.install(x.root).versions.set(deal,3);x.root.commitClose('nocontact');assert.equal(x.queued.length,1);assert.equal(x.queued[0].operation,'close');assert.equal(x.queued[0].payload.closed_date,null);});
test('won remains blocked before Activity or expansion children can escape',()=>{const p=structured();p.to=p.outcome='won';p.stage_context.to='won';p.stage_context.fields={completion_date:'2026-09-01',completion_checks:['공사 완료','준공검사 완료'],contract_amount:1000};p.won_amount=1000;const x=base({saveWon(){this.pushWrite('close',p);this.pushWrite('activity',{opportunity_id:deal});this.pushWrite('expansion_pool_upsert',{opportunity_id:deal});}});x.ui.install(x.root).versions.set(deal,5);assert.throws(()=>x.root.saveWon(),/CLOSE_INTENT_NOT_CONNECTED/);assert.equal(x.queued.length,0);});
test('mobile hydration includes closure fields and manifest remains local',async()=>{let normalized;const row={id:deal,stage_code:'first_contact',outcome:'lost',lifecycle_status:'closed',closed_at:'2026-09-01T00:00:00Z',lost_reason:'가격 열세',lost_kind:'뺏김',version:2,stage_contexts:{lost:{fields:{close_reason:'가격 열세'}}},stage_history:[]};const x=base({Phase1:{read:async()=>({data:{deals:[row],inquiries:[]}}),queue:{list:()=>[],enqueue:()=>{},flush:async()=>{}}},normalizeDeal:d=>(normalized=d),rebuildAdmin(){},render(){},CUR:'mine'});x.ui.install(x.root);await x.root.loadLive();assert.equal(normalized.outcome,'lost');assert.equal(normalized.lost_kind,'뺏김');assert.equal(normalized.code,'first_contact');const m=build.build();assert.equal(m.staging_ddl_dml_performed,false);assert.deepEqual(m.outcomes,['lost','badfit','nocontact']);});
