'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8');
const deal=s.uid(6,1),auth=s.mapping.accounts[0].auth_uid,rid=n=>`f6090600-0070-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());return db;}
async function write(db,account,version,payload,request){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[request,'stage_check',deal,version,JSON.stringify(payload)])).rows[0].a;}
test('manual stage check chains after next completion and remains actor scoped',async t=>{const db=await setup();try{
 await t.test('manual toggle writes one boolean, version, receipt and private audit',async()=>{const ack=await write(db,0,1,{stage_code:'first_contact',item_index:1,checked:true},rid(1));assert.equal(ack.actor_auth_uid,auth);assert.equal(ack.version,2);assert.equal(ack.item_text,'공사 예정시기 확인');assert.equal(ack.stage_checklist.first_contact['1'],true);assert.deepEqual((await db.query("SELECT stage_checklist,version FROM public.deals WHERE id=$1",[deal])).rows[0],{stage_checklist:{first_contact:{1:true}},version:2});assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='stage_check'",[deal])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE object_id=$1 AND operation='stage_check'",[deal])).rows[0].n,1);});
 await t.test('operational source returns the same checklist',async()=>{await db.exec(`SET request.jwt.claim.sub='${auth}';`);const value=(await db.query("SELECT public.crm_operational_source_v1('deal_core',null,100) a")).rows[0].a,found=value.items.find(x=>x.id===deal);assert.equal(found.stage_checklist.first_contact['1'],true);});
 await t.test('exact replay is stable and changed reuse is rejected',async()=>{const replay=await write(db,0,1,{stage_code:'first_contact',item_index:1,checked:true},rid(1));assert.equal(replay.replayed,true);await assert.rejects(write(db,0,1,{stage_code:'first_contact',item_index:3,checked:true},rid(1)),e=>e.code==='PT409');assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='stage_check'",[deal])).rows[0].n,1);});
 await t.test('toggle back is a second valid mutation',async()=>{const ack=await write(db,0,2,{stage_code:'first_contact',item_index:1,checked:false},rid(2));assert.equal(ack.version,3);assert.equal(ack.stage_checklist.first_contact['1'],false);});
 await t.test('stale, same-state, wrong stage, automatic item and foreign scope fail closed',async()=>{await assert.rejects(write(db,0,2,{stage_code:'first_contact',item_index:3,checked:true},rid(3)),e=>e.code==='PT409');await assert.rejects(write(db,0,3,{stage_code:'first_contact',item_index:1,checked:false},rid(4)),e=>e.code==='PT409');await assert.rejects(write(db,0,3,{stage_code:'consulting',item_index:3,checked:true},rid(5)),e=>e.code==='PT409');await assert.rejects(write(db,0,3,{stage_code:'first_contact',item_index:0,checked:true},rid(6)),e=>e.code==='22023');await assert.rejects(write(db,1,3,{stage_code:'first_contact',item_index:3,checked:true},rid(7)),e=>e.code==='42501');for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'crm_security.crm_stage_check_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('rollback restores ten-op/read layer and archives checklist evidence',async()=>{const db=await setup();try{await write(db,0,1,{stage_code:'first_contact',item_index:1,checked:true},rid(8));await db.exec(stage.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_next_action_complete_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query("SELECT count(*)::int n FROM crm_stage_check_archive.deal_stage_checklist")).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_stage_check_archive.command_receipts")).rows[0].n,1);assert.equal((await db.query("SELECT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name='stage_checklist') present")).rows[0].present,false);await db.exec(`SET request.jwt.claim.sub='${auth}';`);const value=(await db.query("SELECT public.crm_operational_source_v1('deal_core',null,100) a")).rows[0].a;assert.equal(Object.hasOwn(value.items.find(x=>x.id===deal),'stage_checklist'),false);}finally{await db.close();}});
