'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=require('../../inquiry-stage-progress/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const read=name=>fs.readFileSync(path.join(dir,name),'utf8').replace(/\r\n?/g,'\n');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function replaceOne(source,pattern,replacement,label){const next=source.replace(pattern,replacement);if(next===source)throw Error('inquiry action/check build anchor missing: '+label);return next;}
function applySql(){return tx(read('helper.sql'));}
function rollbackSql(){return tx(read('rollback-fragment.sql'));}
function adapter(){let source=base.adapter();
 source=replaceOne(source,/ function normalizeNext\(payload\)\{.*?\}\n function normalizeQuote/s,` function normalizeNext(objectId,payload){if(payload&&payload.inquiry_id!==undefined){const allowed=['inquiry_id','intent','type','text','due_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.inquiry_id!==objectId||payload.intent!=='inquiry_next_set'||payload.type!=='\uC804\uD654')fail('INQUIRY_NEXT_SET_INTENT_NOT_CONNECTED');return {intent:'inquiry_next_set',type:'\uC804\uD654',text:text(payload.text,1,500,'INVALID_NEXT_TEXT'),due_at:date(payload.due_at)};}const allowed=['opportunity_id','intent','type','text','due_at','assignee'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.intent!=='standalone')fail('NEXT_ACTION_INTENT_NOT_CONNECTED');const out={type:text(payload.type,1,100,'INVALID_NEXT_TYPE'),text:text(payload.text,1,500,'INVALID_NEXT_TEXT'),due_at:date(payload.due_at)};if(payload.assignee!=null&&payload.assignee!=='')out.assignee=text(payload.assignee,1,100,'INVALID_ASSIGNEE');return out;}\n function normalizeQuote`,'normalize inquiry next set');
 source=replaceOne(source,/ function normalizeComplete\(objectId,payload\)\{.*?\}\n const STAGE_MANUAL/s,` function normalizeComplete(objectId,payload){if(payload&&payload.inquiry_id!==undefined){const allowed=['inquiry_id','intent','action_id'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.inquiry_id!==objectId||payload.intent!=='inquiry_next_complete'||!UUID.test(payload.action_id))fail('INQUIRY_NEXT_COMPLETE_INTENT_NOT_CONNECTED');return {intent:'inquiry_next_complete',action_id:payload.action_id};}const allowed=['opportunity_id','action_id','text','due_at','at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||!UUID.test(payload.action_id))fail('INVALID_NEXT_ACTION_COMPLETE');return {action_id:payload.action_id};}\n const STAGE_MANUAL`,'normalize inquiry next complete');
 source=replaceOne(source,/ function normalizeStage\(objectId,payload\)\{.*?\}\n const TRANSITION_STAGES/s,` function normalizeStage(objectId,payload){if(payload&&payload.inquiry_id!==undefined){const labels=['\uCD5C\uCD08 \uC5F0\uB77D \uC644\uB8CC','\uD604\uC7A5 \uC870\uAC74 \uD655\uC778','\uC758\uC0AC\uACB0\uC815\uAD8C\uC790 \uD655\uC778','\uACAC\uC801\uC11C \uBC1C\uC1A1 \uD655\uC778','\uB2E4\uC74C \uD589\uB3D9\uC77C \uD655\uC815','\uD6C4\uC18D \uD1B5\uD654 \uAE30\uB85D'],allowed=['inquiry_id','intent','item_index','item_text','checked'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.inquiry_id!==objectId||payload.intent!=='inquiry_check'||!Number.isSafeInteger(payload.item_index)||payload.item_index<0||payload.item_index>=labels.length||typeof payload.checked!=='boolean'||labels[payload.item_index]!==payload.item_text)fail('INQUIRY_CHECK_INTENT_NOT_CONNECTED');return {intent:'inquiry_check',item_index:payload.item_index,checked:payload.checked};}const allowed=['opportunity_id','stage_code','item_index','item_text','checked'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||typeof payload.stage_code!=='string'||!Number.isSafeInteger(payload.item_index)||typeof payload.checked!=='boolean'||STAGE_MANUAL[payload.stage_code]?.[payload.item_index]!==payload.item_text)fail('INVALID_STAGE_CHECK');return {stage_code:payload.stage_code,item_index:payload.item_index,checked:payload.checked};}\n const TRANSITION_STAGES`,'normalize inquiry check');
 source=replaceOne(source,"const sentinel=['inquiry_assign'","const inquirySentinel=['next_action','next_action_complete','stage_check'].includes(operation)&&payload.inquiry_id!==undefined;const sentinel=inquirySentinel||['inquiry_assign'",'inquiry sentinel');
 source=replaceOne(source,"normalized=normalizeNext(payload)","normalized=normalizeNext(objectId,payload)",'next object id');
 source=replaceOne(source,"if(command.operation==='next_action'&&(ack.previous_version", "if(command.operation==='next_action'&&command.payload.intent!=='inquiry_next_set'&&(ack.previous_version",'deal next ACK guard');
 source=replaceOne(source,"if(command.operation==='next_action_complete'&&(ack.previous_version", "if(command.operation==='next_action_complete'&&command.payload.intent!=='inquiry_next_complete'&&(ack.previous_version",'deal complete ACK guard');
 source=replaceOne(source,"if(command.operation==='stage_check'&&(ack.previous_version", "if(command.operation==='stage_check'&&command.payload.intent!=='inquiry_check'&&(ack.previous_version",'deal check ACK guard');
 source=replaceOne(source,"  if(command.operation==='lineage_link'",`  if(command.operation==='next_action'&&command.payload.intent==='inquiry_next_set'&&(ack.intent!=='inquiry_next_set'||!UUID.test(ack.next_action_id)||!Array.isArray(ack.cancelled_action_ids)||ack.next_action_date!==command.payload.due_at||typeof ack.assignee_name!=='string'||!UUID.test(ack.inquiry_audit_event_id)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='next_action_complete'&&command.payload.intent==='inquiry_next_complete'&&(ack.intent!=='inquiry_next_complete'||ack.next_action_id!==command.payload.action_id||!['completed'].includes(ack.action_status)||!(ack.next_action_date===null||typeof ack.next_action_date==='string')||!UUID.test(ack.inquiry_audit_event_id)||typeof ack.completed_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='stage_check'&&command.payload.intent==='inquiry_check'&&(ack.intent!=='inquiry_check'||ack.item_index!==command.payload.item_index||ack.checked!==command.payload.checked||typeof ack.item_text!=='string'||!Array.isArray(ack.checks)||ack.checks.length!==6||!ack.checks.every(x=>typeof x==='boolean')||!UUID.test(ack.inquiry_audit_event_id)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='lineage_link'`,'inquiry action ACKs');
 return source;
}
function overlay(){let source=base.overlay();
 source=replaceOne(source,'let compound=null,actionIntent=null,completeActionId=null,stageIntent=false',"let compound=null,actionIntent=null,inquiryActionIntent=null,completeActionId=null,stageIntent=false",'inquiry action state');
 source=replaceOne(source,"function idFor(op,p){return op.startsWith('inquiry_')?p?.inquiry_id:p?.opportunity_id;}","function idFor(op,p){return op.startsWith('inquiry_')||p?.inquiry_id?p?.inquiry_id:p?.opportunity_id;}",'inquiry action id');
 source=replaceOne(source,"  function applyStageAck(q){",`  function applyInquiryActionAck(q){const a=q.ack;for(const rows of inquiryRows())for(const i of rows)if(String(i.id||i.inquiry_id||i.key)===String(q.object_id)){i.activities=Array.isArray(i.activities)?i.activities:[];if(q.payload.intent==='inquiry_next_set'){const n={id:a.next_action_id,type:q.payload.type,text:q.payload.text,due:a.next_action_date,due_at:a.next_action_date,assignee:a.assignee_name,status:'open'};i.nextActionObj=i.nextAction=n;i.nextActionText=q.payload.text;i.next_action_date=i.nextActionDate=i.due=a.next_action_date;}else if(q.payload.intent==='inquiry_next_complete'){if(i.nextActionObj&&i.nextActionObj.id===a.next_action_id)i.nextActionObj={...i.nextActionObj,status:'completed',completed_at:a.completed_at};i.nextAction=i.nextActionObj=null;i.nextActionText='';i.next_action_date=i.nextActionDate=i.due=a.next_action_date;}else if(q.payload.intent==='inquiry_check'){i.checks=a.checks.slice();}if(!i.activities.some(x=>x.id===a.inquiry_audit_event_id))i.activities.push({id:a.inquiry_audit_event_id,type:q.payload.intent==='inquiry_check'?'\uCCB4\uD06C':q.payload.intent==='inquiry_next_complete'?'\uD589\uB3D9\uC644\uB8CC':'\uB2E4\uC74C\uD589\uB3D9\uB4F1\uB85D',note:a.item_text||q.payload.text||a.completed_title,result:q.payload.intent==='inquiry_check'?(a.checked?'\uD655\uC778':'\uD574\uC81C'):(q.payload.intent==='inquiry_next_complete'?'\uC644\uB8CC \uCC98\uB9AC':'\uAE30\uD55C '+a.next_action_date),actor:a.actor_name,at:a.server_at||a.completed_at});}}
  function applyStageAck(q){`,'inquiry action ACK apply');
 source=replaceOne(source,"if(q.operation==='next_action')applyNextAck(q);", "if(q.operation==='next_action'&&q.payload.intent==='inquiry_next_set')applyInquiryActionAck(q);else if(q.operation==='next_action')applyNextAck(q);",'sync inquiry next set');
 source=replaceOne(source,"if(q.operation==='stage_check')applyStageAck(q);", "if(q.operation==='stage_check'&&q.payload.intent==='inquiry_check')applyInquiryActionAck(q);else if(q.operation==='stage_check')applyStageAck(q);if(q.operation==='next_action_complete'&&q.payload.intent==='inquiry_next_complete')applyInquiryActionAck(q);",'sync inquiry complete/check');
 source=replaceOne(source,"if(op==='stage_check'&&!stageIntent)","if(op==='stage_check'&&!stageIntent&&inquiryActionIntent!=='check')",'inquiry check push guard');
 source=replaceOne(source,"if(op==='next_action_complete'){if(compound!=='next_action_complete'||!completeActionId)throw error('NEXT_ACTION_ID_REQUIRED');payload={opportunity_id:payload&&payload.opportunity_id,action_id:completeActionId};}","if(op==='next_action_complete'){if(inquiryActionIntent==='complete'){payload={inquiry_id:payload&&payload.inquiry_id,intent:'inquiry_next_complete',action_id:payload&&payload.action_id};}else{if(compound!=='next_action_complete'||!completeActionId)throw error('NEXT_ACTION_ID_REQUIRED');payload={opportunity_id:payload&&payload.opportunity_id,action_id:completeActionId};}}",'inquiry completion payload');
 source=replaceOne(source,"if(action.has(op)){if(!actionIntent)","if(op==='next_action'&&inquiryActionIntent==='set'){payload={inquiry_id:payload&&payload.inquiry_id,intent:'inquiry_next_set',type:'\uC804\uD654',text:payload&&payload.text,due_at:payload&&payload.due_at};}else if(action.has(op)){if(!actionIntent)",'inquiry next payload');
 source=replaceOne(source,"expected=op.startsWith('inquiry_')||personal.has(op)?0:versionFor(id,payload);", "expected=op.startsWith('inquiry_')||personal.has(op)||(/^inquiry_/.test(payload&&payload.intent||''))?0:versionFor(id,payload);",'inquiry action version sentinel');
 source=replaceOne(source,"  if(typeof root.inqCtlConfirmReason==='function')",`  if(typeof root.splitSaveNext==='function'){const original=root.splitSaveNext;root.splitSaveNext=function(){const q=root.splitSel&&root.splitSel(),get=id=>root.document&&root.document.getElementById?root.document.getElementById(id):null,payload={inquiry_id:String(q&&(q.id||q.inquiry_id||(root.inqKey&&root.inqKey(q)))||''),intent:'inquiry_next_set',type:'\uC804\uD654',text:String(get('spNextText')?.value||'').trim(),due_at:String(get('spNextDue')?.value||'')};root.OperationalAdapter.normalize('next_action',payload.inquiry_id,0,payload);const prior=inquiryActionIntent;inquiryActionIntent='set';try{const out=original.apply(this,arguments);root.pushWrite('next_action',payload);return out;}finally{inquiryActionIntent=prior;}};}
  if(typeof root.applyInqBulkAction==='function'){const original=root.applyInqBulkAction;root.applyInqBulkAction=function(){const keys=Object.keys(root.INQ_SEL||{}),get=id=>root.document&&root.document.getElementById?root.document.getElementById(id):null,text=String(get('inqActText')?.value||'').trim(),due=String(get('inqActDue')?.value||''),rows=keys.map(k=>(root.B&&root.B.inquiries||[]).find(q=>String(root.inqKey?root.inqKey(q):q.id)===String(k))).filter(Boolean),payloads=rows.map(q=>({inquiry_id:String(q.id||q.inquiry_id||(root.inqKey&&root.inqKey(q))),intent:'inquiry_next_set',type:'\uC804\uD654',text,due_at:due}));for(const p of payloads)root.OperationalAdapter.normalize('next_action',p.inquiry_id,0,p);const prior=inquiryActionIntent;inquiryActionIntent='set';try{const out=original.apply(this,arguments);for(const p of payloads)root.pushWrite('next_action',p);return out;}finally{inquiryActionIntent=prior;}};}
  if(typeof root.splitDoneAction==='function'){const original=root.splitDoneAction;root.splitDoneAction=function(){const q=root.splitSel&&root.splitSel(),p=q&&root.detailPatchFor&&root.detailPatchFor('inq',root.inqKey?root.inqKey(q):q.id),a=q&&root.actionObj&&root.actionObj(q,p),payload={inquiry_id:String(q&&(q.id||q.inquiry_id||(root.inqKey&&root.inqKey(q)))||''),intent:'inquiry_next_complete',action_id:a&&a.id};root.OperationalAdapter.normalize('next_action_complete',payload.inquiry_id,0,payload);const prior=inquiryActionIntent;inquiryActionIntent='complete';try{const out=original.apply(this,arguments);root.pushWrite('next_action_complete',payload);return out;}finally{inquiryActionIntent=prior;}};}
  if(typeof root.splitCheck==='function'){const original=root.splitCheck,labels=['\uCD5C\uCD08 \uC5F0\uB77D \uC644\uB8CC','\uD604\uC7A5 \uC870\uAC74 \uD655\uC778','\uC758\uC0AC\uACB0\uC815\uAD8C\uC790 \uD655\uC778','\uACAC\uC801\uC11C \uBC1C\uC1A1 \uD655\uC778','\uB2E4\uC74C \uD589\uB3D9\uC77C \uD655\uC815','\uD6C4\uC18D \uD1B5\uD654 \uAE30\uB85D'];root.splitCheck=function(index,checked){const q=root.splitSel&&root.splitSel(),payload={inquiry_id:String(q&&(q.id||q.inquiry_id||(root.inqKey&&root.inqKey(q)))||''),intent:'inquiry_check',item_index:index,item_text:labels[index],checked};root.OperationalAdapter.normalize('stage_check',payload.inquiry_id,0,payload);const prior=inquiryActionIntent;inquiryActionIntent='check';try{const out=original.apply(this,arguments);root.pushWrite('stage_check',payload);return out;}finally{inquiryActionIntent=prior;}};}
  if(typeof root.inqCtlConfirmReason==='function')`,'named inquiry action wrappers');
 return source;
}
function build(){const files={'staging-apply-after-inquiry-stage-progress.sql':applySql(),'rollback-before-inquiry-stage-progress.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay()};for(const [name,value] of Object.entries(files))fs.writeFileSync(path.join(dir,name),value);
 const own=['build.cjs','helper.sql','rollback-fragment.sql','review.md','contract.test.cjs','db.test.cjs','ui.test.cjs',...Object.keys(files)];
 const sources=['sql/inquiry-stage-progress/20260906/manifest.json','crm.html','sql/operational-bundle/20260906/after.json'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',operations:['next_action','next_action_complete','stage_check'],intents:['inquiry_next_set','inquiry_next_complete','inquiry_check'],ui_coverage_candidate:['I07'],status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',surface:'pc_only',handlers:['splitSaveNext','applyInqBulkAction','splitDoneAction','splitCheck'],deal_meanings_preserved:true,roles:['assigned_rep','assigned_consultation','scoped_admin'],transaction:['inquiry next set/replace','inquiry next complete','private inquiry checklist state','private inquiry audit','command receipt'],staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={applySql,rollbackSql,adapter,overlay,build,dir};
