'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const personal=require('../../personal-state-compat/20260906/build.cjs'),cutover=require('../../operational-cutover-candidate/20260906/build.cjs'),response=require('../../inquiry-response-progress/20260906/build.cjs'),pipeline=require('../../inquiry-pipeline-lineage/20260906/build.cjs'),progress=require('../../inquiry-stage-progress/20260906/build.cjs'),build=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const inq=n=>s.uid(5,n),user=n=>s.uid(1,n),request=n=>`f6090600-0117-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(cutover.compose('apply',{localPersonalCandidate:true,skipResponse:true,skipInquiryPipeline:true}));await db.exec(response.applySql());await db.exec(pipeline.applySql());await db.exec(progress.applySql());await db.exec(build.applySql());return db;}
async function actor(db,index=0){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[s.mapping.accounts[index].auth_uid]);await db.exec('SET ROLE authenticated');}
async function rpc(db,requestId,operation,payload,index=0,id=inq(1)){await actor(db,index);try{return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,0,$4) a',[requestId,operation,id,JSON.stringify(payload)])).rows[0].a;}finally{await db.exec('RESET ROLE');}}
async function one(db,sql,params=[]){return (await db.query(sql,params)).rows[0];}
async function due(db,days=2){return (await one(db,"SELECT ((clock_timestamp() AT TIME ZONE 'Asia/Seoul')::date+$1::int)::text d",[days])).d;}

test('set, replace, complete and check are atomic and visible in scoped read',async()=>{const db=await setup();try{
 await db.query("UPDATE public.inquiries SET assigned_to=$1,assignee_name='TEST INTERNAL_REP',status='\uBC30\uC815\uC644\uB8CC',next_action_date=NULL WHERE id=$2",[user(1),inq(1)]);const d=await due(db),set=await rpc(db,request(1),'next_action',{intent:'inquiry_next_set',type:'\uC804\uD654',text:'\uD604\uC7A5 \uD655\uC778',due_at:d});assert.equal(set.intent,'inquiry_next_set');assert.equal(set.cancelled_action_ids.length,0);
 const d2=await due(db,3),replace=await rpc(db,request(2),'next_action',{intent:'inquiry_next_set',type:'\uC804\uD654',text:'\uB3C4\uBA74 \uC694\uCCAD',due_at:d2});assert.deepEqual(replace.cancelled_action_ids,[set.next_action_id]);assert.equal((await one(db,"SELECT count(*)::int n FROM public.next_actions WHERE inquiry_id=$1 AND status='open'",[inq(1)])).n,1);
 const complete=await rpc(db,request(3),'next_action_complete',{intent:'inquiry_next_complete',action_id:replace.next_action_id});assert.equal(complete.action_status,'completed');assert.equal(complete.next_action_date,null);
 const check=await rpc(db,request(4),'stage_check',{intent:'inquiry_check',item_index:2,checked:true});assert.deepEqual(check.checks,[false,false,true,false,false,false]);
 await actor(db);const read=(await db.query("SELECT public.crm_operational_source_v1('inquiry_core',NULL,100) a")).rows[0].a;await db.exec('RESET ROLE');const item=read.items.find(x=>x.id===inq(1));assert.equal(item.next_action,null);assert.deepEqual(item.checks,[false,false,true,false,false,false]);assert.equal(item.activities.filter(x=>['\uB2E4\uC74C\uD589\uB3D9\uB4F1\uB85D','\uD589\uB3D9\uC644\uB8CC','\uCCB4\uD06C'].includes(x.type)).length,4);
 }finally{await db.close();}});

test('replay is duplicate-free; reuse, foreign action, same check and foreign actor fail closed',async()=>{const db=await setup();try{
 await db.query("UPDATE public.inquiries SET assigned_to=$1,assignee_name='TEST INTERNAL_REP',status='\uBC30\uC815\uC644\uB8CC' WHERE id=$2",[user(1),inq(1)]);const d=await due(db),p={intent:'inquiry_next_set',type:'\uC804\uD654',text:'\uD604\uC7A5 \uD655\uC778',due_at:d},a=await rpc(db,request(10),'next_action',p),replay=await rpc(db,request(10),'next_action',p);assert.equal(replay.replayed,true);assert.equal((await one(db,"SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_next_set'",[inq(1)])).n,1);await assert.rejects(rpc(db,request(10),'next_action',{...p,text:'\uB2E4\uB978 \uD589\uB3D9'}),e=>e.code==='PT409');
 await assert.rejects(rpc(db,request(11),'next_action_complete',{intent:'inquiry_next_complete',action_id:a.next_action_id},1),e=>e.code==='42501');
 await rpc(db,request(12),'stage_check',{intent:'inquiry_check',item_index:0,checked:true});await assert.rejects(rpc(db,request(13),'stage_check',{intent:'inquiry_check',item_index:0,checked:true}),e=>e.code==='PT409');
 await db.query("INSERT INTO public.next_actions(inquiry_id,title,due_at,assignee_name) VALUES($1,'\uD0C0 \uBB38\uC758 \uD589\uB3D9',now()+'1 day'::interval,'TEST INTERNAL_REP') RETURNING id",[inq(2)]).then(async r=>assert.rejects(rpc(db,request(14),'next_action_complete',{intent:'inquiry_next_complete',action_id:r.rows[0].id}),e=>e.code==='42501'));
 }finally{await db.close();}});

test('late audit failure rolls public action/check state and receipt back',async()=>{const db=await setup();try{
 await db.query("UPDATE public.inquiries SET assigned_to=$1,assignee_name='TEST INTERNAL_REP',status='\uBC30\uC815\uC644\uB8CC',next_action_date=NULL WHERE id=$2",[user(1),inq(1)]);await db.exec("CREATE FUNCTION crm_security.reject_inquiry_action_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action IN ('inquiry_next_set','inquiry_next_complete','inquiry_check') THEN RAISE EXCEPTION 'injected inquiry action audit failure';END IF;RETURN NEW;END$$;CREATE TRIGGER reject_inquiry_action_audit BEFORE INSERT ON crm_security.inquiry_audit_events FOR EACH ROW EXECUTE FUNCTION crm_security.reject_inquiry_action_audit();");await assert.rejects(rpc(db,request(20),'next_action',{intent:'inquiry_next_set',type:'\uC804\uD654',text:'\uD604\uC7A5 \uD655\uC778',due_at:await due(db)}),/injected inquiry action audit failure/);assert.equal((await one(db,'SELECT count(*)::int n FROM public.next_actions WHERE inquiry_id=$1',[inq(1)])).n,0);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_security.command_receipts WHERE request_id=$1',[request(20)])).n,0);assert.equal((await one(db,'SELECT next_action_date FROM public.inquiries WHERE id=$1',[inq(1)])).next_action_date,null);
 }finally{await db.close();}});

test('rollback restores prior dispatcher/read and archives only candidate evidence',async()=>{const db=await setup();try{
 const beforeWrite=(await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_write_command_v2_inquiry_stage_progress_20260906(uuid,text,uuid,integer,jsonb)'::regprocedure")).d,beforeRead=(await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_operational_source_fragment_pre_inquiry_action_check_20260906(text,uuid,integer)'::regprocedure")).d;await db.query("UPDATE public.inquiries SET assigned_to=$1,assignee_name='TEST INTERNAL_REP',status='\uBC30\uC815\uC644\uB8CC' WHERE id=$2",[user(1),inq(1)]);await rpc(db,request(30),'stage_check',{intent:'inquiry_check',item_index:1,checked:true});await db.exec(build.rollbackSql());assert.equal((await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)'::regprocedure")).d,beforeWrite);assert.equal((await one(db,"SELECT prosrc d FROM pg_proc WHERE oid='crm_security.crm_operational_source_fragment_v1(text,uuid,integer)'::regprocedure")).d,beforeRead);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_inquiry_action_check_archive.command_receipts')).n,1);assert.equal((await one(db,'SELECT count(*)::int n FROM crm_inquiry_action_check_archive.inquiry_audit_events')).n,1);
 }finally{await db.close();}});
