'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),build=require('./build.cjs');
function load(text,name){const m=new Module(name);m._compile(text,name+'.js');return m.exports;}
const uuid=n=>`f6090600-0117-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(){const adapter=load(build.adapter(),'inq-action-ui-adapter'),overlay=load(build.overlay(),'inq-action-ui-overlay'),queued=[],listeners={},id=uuid(1),values={spNextText:'\uD604\uC7A5 \uD655\uC778',spNextDue:'2026-09-08',inqActText:'\uC77C\uAD04 \uD6C4\uC18D',inqActDue:'2026-09-09'},q={id,key:id,status:'\uBC30\uC815\uC644\uB8CC',assignee:'TEST INTERNAL_REP',checks:[],activities:[],nextActionObj:null};let seq=10;const root={OperationalAdapter:adapter,TOKEN:'jwt',ME:{id:'u'},WRITE_Q:[],INQ_SEL:{},G:{inqSelKey:id},B:{inquiries:[q],deals:[]},INQUIRIES:[q],ADMIN:{inquiries:[q]},console,crypto:{randomUUID:()=>uuid(++seq)},document:{getElementById:k=>values[k]===undefined?null:{value:values[k]},querySelectorAll:()=>[]},inqKey:x=>x.id,splitSel:()=>q,detailPatchFor:()=>q,actionObj:x=>x.nextActionObj,addEventListener:(n,f)=>{listeners[n]=f},splitSaveNext(){q.nextActionObj={text:values.spNextText,due:values.spNextDue,status:'open'};},applyInqBulkAction(){for(const x of root.B.inquiries)x.nextActionObj={text:values.inqActText,due:values.inqActDue,status:'open'};root.INQ_SEL={};},splitDoneAction(){q.nextActionObj={...q.nextActionObj,status:'completed'};},splitCheck(i,v){q.checks[i]=v;},Phase1:{queue:{enqueue(op,objectId,version,payload){const c=adapter.normalize(op,objectId,version,payload),x={...c,payload:c.payload,request_id:uuid(++seq),status:'pending'};queued.push(x);return x;},list:()=>queued,flush:async()=>queued}}};overlay.install(root);return{root,q,queued,listeners,values};}
test('single and bulk Next handlers emit inquiry_next_set commands only after validation',()=>{const x=fixture();x.root.splitSaveNext();assert.equal(x.queued.length,1);assert.equal(x.queued[0].operation,'next_action');assert.equal(x.queued[0].payload.intent,'inquiry_next_set');x.root.INQ_SEL={[x.q.id]:1};x.root.applyInqBulkAction();assert.equal(x.queued.length,2);assert.equal(x.queued[1].payload.text,'\uC77C\uAD04 \uD6C4\uC18D');});
test('completion requires server action id and emits one inquiry completion',()=>{const x=fixture();x.q.nextActionObj={text:'\uD604\uC7A5 \uD655\uC778',due:'2026-09-08',status:'open'};assert.throws(()=>x.root.splitDoneAction(),/INQUIRY_NEXT_COMPLETE_INTENT_NOT_CONNECTED/);assert.equal(x.queued.length,0);x.q.nextActionObj.id=uuid(80);x.root.splitDoneAction();assert.equal(x.queued.length,1);assert.deepEqual(x.queued[0].payload,{intent:'inquiry_next_complete',action_id:uuid(80)});});
test('fixed checklist handler emits canonical item and blocks wrong index',()=>{const x=fixture();x.root.splitCheck(2,true);assert.equal(x.queued[0].operation,'stage_check');assert.deepEqual(x.queued[0].payload,{intent:'inquiry_check',item_index:2,checked:true});assert.throws(()=>x.root.splitCheck(8,true),/INQUIRY_CHECK_INTENT_NOT_CONNECTED/);});
test('ACK hydration is idempotent for Next and check evidence',()=>{const x=fixture();x.root.splitSaveNext();let c=x.queued[0];c.status='done';c.ack={next_action_id:uuid(90),next_action_date:'2026-09-08',assignee_name:'TEST INTERNAL_REP',inquiry_audit_event_id:uuid(91),server_at:'2026-09-06T00:00:00Z',actor_name:'TEST INTERNAL_REP'};x.listeners['phase1:queue']();x.listeners['phase1:queue']();assert.equal(x.q.nextActionObj.id,uuid(90));assert.equal(x.q.activities.length,1);x.root.splitCheck(0,true);c=x.queued[1];c.status='done';c.ack={item_text:'\uCD5C\uCD08 \uC5F0\uB77D \uC644\uB8CC',checked:true,checks:[true,false,false,false,false,false],inquiry_audit_event_id:uuid(92),server_at:'2026-09-06T00:00:01Z',actor_name:'TEST INTERNAL_REP'};x.listeners['phase1:queue']();x.listeners['phase1:queue']();assert.deepEqual(x.q.checks,[true,false,false,false,false,false]);assert.equal(x.q.activities.length,2);});
