'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const dir=__dirname,root=path.resolve(dir,'../../..'),baseDir=path.resolve(dir,'../../next-action-postpone/20260906');
const read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function one(source,from,to,label){if(!source.includes(from))throw Error('mobile Today build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=read(path.join(baseDir,'operational-adapter.candidate.js'));
 source=one(source,"function normalizeComplete(objectId,payload){if(payload&&payload.inquiry_id!==undefined)",`function normalizeTodayOutcome(objectId,payload){const allowed=['opportunity_id','intent','action_id','outcome'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||payload.intent!=='today_outcome'||!UUID.test(payload.action_id)||!['progress','next_week','missed'].includes(payload.outcome))fail('MOBILE_TODAY_OUTCOME_NOT_CONNECTED');return {intent:'today_outcome',action_id:payload.action_id,outcome:payload.outcome};}
 function normalizeComplete(objectId,payload){if(payload&&payload.intent==='today_outcome')return normalizeTodayOutcome(objectId,payload);if(payload&&payload.inquiry_id!==undefined)`,'normalizer');
 source=one(source,"command.operation==='next_action_complete'&&command.payload.intent!=='inquiry_next_complete'",`command.operation==='next_action_complete'&&!['inquiry_next_complete','today_outcome'].includes(command.payload.intent)`,'base complete ACK exclusion');
 source=one(source,"  if(command.operation==='next_action_complete'&&command.payload.intent==='inquiry_next_complete'",`  if(command.operation==='next_action_complete'&&command.payload.intent==='today_outcome'&&(ack.intent!=='today_outcome'||ack.outcome!==command.payload.outcome||ack.completed_action_id!==command.payload.action_id||ack.action_status!=='completed'||!UUID.test(ack.next_action_id)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(ack.due_at)||!Number.isSafeInteger(ack.postpone_count)||ack.postpone_count<0||(command.payload.outcome==='next_week'?!UUID.test(ack.postpone_event_id):ack.postpone_event_id!==null)||!UUID.test(ack.activity_id)||!UUID.test(ack.audit_event_id)||!Array.isArray(ack.cancelled_action_ids)||typeof ack.completed_at!=='string'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='next_action_complete'&&command.payload.intent==='inquiry_next_complete'`,'Today ACK');
 return source;
}
function overlay(){let source=read(path.join(baseDir,'operational-overlay.candidate.js'));
 source=one(source,'postponeAction=null,inquiryActionIntent=null','postponeAction=null,todayOutcome=null,inquiryActionIntent=null','state');
 source=one(source,"  function applyNextAck(q){",`  function applyTodayOutcomeAck(q){for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.postpone=d.postpone_count=d.postponeCount=q.ack.postpone_count;const n=d.nextActionObj||(d.nextAction&&typeof d.nextAction==='object'?d.nextAction:null);if(n){n.id=q.ack.next_action_id;n.due=n.due_at=q.ack.due_at;n.status='open';}}}
  function applyNextAck(q){`,'ACK hydrator');
 source=one(source,"if(q.operation==='next_action_complete'&&q.payload.intent==='inquiry_next_complete')applyInquiryActionAck(q);",`if(q.operation==='next_action_complete'&&q.payload.intent==='today_outcome')applyTodayOutcomeAck(q);else if(q.operation==='next_action_complete'&&q.payload.intent==='inquiry_next_complete')applyInquiryActionAck(q);`,'ACK route');
 source=one(source,"  root.pushWrite=function(op,payload){if(technicalTransfer",`  root.pushWrite=function(op,payload){if(todayOutcome){if(todayOutcome.parentQueued&&(op==='activity'||op==='next_action'))return 'absorbed:'+op;if(op==='next_action_complete'){payload={opportunity_id:payload&&payload.opportunity_id,intent:'today_outcome',action_id:todayOutcome.action_id,outcome:todayOutcome.outcome};todayOutcome.parentQueued=true;}}if(technicalTransfer`,'parent capture');
 source=one(source,"if(op==='next_action_complete'){if(inquiryActionIntent==='complete')",`if(op==='next_action_complete'){if(payload&&payload.intent==='today_outcome'){}else if(inquiryActionIntent==='complete')`,'complete preservation');
 source=one(source,"  if(typeof root.applyTodayPostponeM==='function')",`  if(typeof root.pickToday==='function'){const original=root.pickToday;root.pickToday=function(i,label){const q=root.todayInquiry&&root.todayInquiry(i),d=!q&&root.todayDeal&&root.todayDeal(i);if(!d)return original.apply(this,arguments);const outcomes={'진행됨 — 다음 잡음':'progress','다음주 다시':'next_week','못 받으심 (내일 재시도)':'missed'},outcome=outcomes[label],a=root.execNextM&&root.execNextM(d);if(!outcome||!a||!UUID.test(String(a.id||'')))throw error('MOBILE_TODAY_OUTCOME_NOT_CONNECTED');const prior=todayOutcome;todayOutcome={action_id:String(a.id),outcome,parentQueued:false};try{return original.apply(this,arguments);}finally{todayOutcome=prior;}};}
  if(typeof root.applyTodayPostponeM==='function')`,'handler');
 return source;
}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-next-postpone.sql':applySql(),'rollback-before-next-postpone.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':read(path.join(baseDir,'transport.candidate.js'))};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md',...Object.keys(generated)],sources=['sql/next-action-postpone/20260906/manifest.json','mobile.html','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operation:'next_action_complete',intent:'today_outcome',ui_coverage_candidate:['P09M'],prerequisite:'next-action-postpone/20260906',surface:'mobile_only',allowed_outcomes:['progress','next_week','missed'],absorbed_children:['activity','next_action'],server_rules:{scope:'crm_security.can_deal(deal_id,true)',identity:'server-projected earliest open Next Action UUID',dates:'server KST +3/+7/+1',counter:'Deal-level; increment only next_week',transaction:'complete current Action + cancel other open + Activity + replacement Next + Deal version/contact + audit + receipt'},read_dependency:['next_action.id','next_action.postpone_count'],blocked:['temporary action id','client Activity/Next/time/count','inquiry response meaning'],rollback:'Today event/audit/receipt archived; business Action/Activity retained; P09X remains active',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,applySql,rollbackSql,build};
