'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const personal=require('../../personal-state-compat/20260906/build.cjs'),cutover=require('../../operational-cutover-candidate/20260906/build.cjs'),won=require('../../pipeline-close-won/20260906/build.cjs'),update=require('../../expansion-pool-update/20260906/build.cjs'),notes=require('../../expansion-note-context/20260906/build.cjs'),reminder=require('../../message-reminder/20260906/build.cjs'),postpone=require('../../next-action-postpone/20260906/build.cjs'),today=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
async function scalar(db,sql,params=[]){return (await db.query(sql,params)).rows[0];}
async function storage(db){await db.exec(`CREATE SCHEMA IF NOT EXISTS storage;CREATE TABLE IF NOT EXISTS storage.buckets(id text PRIMARY KEY,name text NOT NULL,public boolean NOT NULL DEFAULT false,file_size_limit bigint,allowed_mime_types text[]);CREATE TABLE IF NOT EXISTS storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),bucket_id text NOT NULL REFERENCES storage.buckets(id),name text NOT NULL,owner_id text,metadata jsonb,UNIQUE(bucket_id,name));GRANT USAGE ON SCHEMA storage TO authenticated;GRANT INSERT ON storage.objects TO authenticated;`);}
async function setup(){const db=await personal.setup();await storage(db);await db.exec(cutover.compose('apply',{localPersonalCandidate:true}));await db.exec(won.applySql());await db.exec(update.applySql());await db.exec(notes.applySql());await db.exec(reminder.applySql());await db.exec(postpone.applySql());await db.exec(today.applySql());await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[0].auth_uid}'`);return db;}
async function kstDay(db,days){return (await scalar(db,"SELECT ((clock_timestamp() AT TIME ZONE 'Asia/Seoul')::date+$1::integer)::text value",[days])).value;}
async function seedAction(db){const d=await scalar(db,"SELECT d.id,d.version FROM public.deals d JOIN public.users u ON u.user_id=d.owner_id WHERE u.auth_uid=current_setting('request.jwt.claim.sub')::uuid ORDER BY d.id LIMIT 1"),due=await kstDay(db,1),ack=(await db.query("SELECT public.crm_write_command_v2($1,'next_action',$2,$3,$4) ack",['f6090600-0901-4000-8000-000000000001',d.id,d.version,JSON.stringify({type:'전화',text:'오늘 확인',due_at:due})])).rows[0].ack;return {id:d.id,version:ack.version,action:ack.next_action_id,due};}
async function outcome(db,x,kind,request='f6090600-0901-4000-8000-000000000011'){return (await db.query("SELECT public.crm_write_command_v2($1,'next_action_complete',$2,$3,$4) ack",[request,x.id,x.version,JSON.stringify({intent:'today_outcome',action_id:x.action,outcome:kind})])).rows[0].ack;}
test('progress completes current Action and atomically records Activity plus replacement Next',async()=>{const db=await setup();try{const x=await seedAction(db),ack=await outcome(db,x,'progress'),expected=await kstDay(db,3);assert.equal(ack.completed_action_id,x.action);assert.equal(ack.action_status,'completed');assert.equal(ack.due_at,expected);assert.equal(ack.postpone_count,0);assert.equal(ack.postpone_event_id,null);assert.equal((await scalar(db,'SELECT status FROM public.next_actions WHERE id=$1',[x.action])).status,'completed');assert.equal((await scalar(db,"SELECT count(*)::int n FROM public.next_actions WHERE deal_id=$1 AND status='open'",[x.id])).n,1);assert.equal((await scalar(db,"SELECT detail->>'meaningful_contact' meaningful,detail->>'note' note FROM public.activities WHERE id=$1",[ack.activity_id])).meaningful,'true');assert.equal((await scalar(db,"SELECT count(*)::int n FROM crm_security.audit_events WHERE event_id=$1 AND action='next_action_today_outcome'",[ack.audit_event_id])).n,1);const read=(await db.query("SELECT public.crm_operational_source_v1('deal_core',NULL,100) x")).rows[0].x.items.find(d=>d.id===x.id);assert.equal(read.next_action.id,ack.next_action_id);assert.equal(read.next_action.postpone_count,0);}finally{await db.close();}});
test('next_week continues the Deal-level P09X count across Action replacement',async()=>{const db=await setup();try{const x=await seedAction(db),later=await kstDay(db,2),p=(await db.query("SELECT public.crm_write_command_v2($1,'next_action',$2,$3,$4) ack",['f6090600-0901-4000-8000-000000000021',x.id,x.version,JSON.stringify({intent:'postpone',action_id:x.action,due_at:later})])).rows[0].ack,ack=await outcome(db,{...x,version:p.version},'next_week','f6090600-0901-4000-8000-000000000022');assert.equal(p.postpone_count,1);assert.equal(ack.postpone_count,2);assert.notEqual(ack.next_action_id,x.action);assert.equal((await scalar(db,"SELECT event_kind,postpone_count,replacement_action_id FROM crm_security.next_action_postponements WHERE event_id=$1",[ack.postpone_event_id])).event_kind,'today_next_week');const read=(await db.query("SELECT public.crm_operational_source_v1('deal_core',NULL,100) x")).rows[0].x.items.find(d=>d.id===x.id);assert.equal(read.next_action.id,ack.next_action_id);assert.equal(read.next_action.postpone_count,2);}finally{await db.close();}});
test('missed is non-meaningful; replay is exact and reuse, stale and foreign scope fail',async()=>{const db=await setup();try{const x=await seedAction(db),request='f6090600-0901-4000-8000-000000000031',ack=await outcome(db,x,'missed',request),replay=await outcome(db,x,'missed',request);assert.equal(replay.replayed,true);assert.equal(replay.activity_id,ack.activity_id);assert.equal((await scalar(db,"SELECT detail->>'meaningful_contact' value FROM public.activities WHERE id=$1",[ack.activity_id])).value,'false');await assert.rejects(outcome(db,x,'progress',request),e=>e.code==='PT409');await assert.rejects(outcome(db,{...x,version:x.version-1},'missed','f6090600-0901-4000-8000-000000000032'),e=>e.code==='PT409');await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[1].auth_uid}'`);await assert.rejects(outcome(db,{...x,version:ack.version},'missed','f6090600-0901-4000-8000-000000000033'),e=>e.code==='42501');}finally{await db.close();}});
test('rollback archives Today evidence, retains business rows and restores P09X',async()=>{const db=await setup();try{const x=await seedAction(db),ack=await outcome(db,x,'next_week','f6090600-0901-4000-8000-000000000041');await db.exec(today.rollbackSql());assert.equal((await scalar(db,'SELECT count(*)::int n FROM crm_mobile_today_archive.events')).n,1);assert.equal((await scalar(db,'SELECT count(*)::int n FROM crm_mobile_today_archive.audit_events')).n,1);assert.equal((await scalar(db,'SELECT count(*)::int n FROM public.next_actions WHERE id=$1',[ack.next_action_id])).n,1);assert.equal((await scalar(db,'SELECT count(*)::int n FROM public.activities WHERE id=$1',[ack.activity_id])).n,1);assert.equal((await scalar(db,"SELECT to_regprocedure('crm_security.crm_next_action_postpone_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL present")).present,true);}finally{await db.close();}});
