'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),base=require('../../expansion-pool-update/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function transport(){const source=base.transport(),from="'crm_write_command_v2','crm_operational_source_v1'",to="'crm_write_command_v2','crm_operational_source_v1','crm_expansion_note','crm_expansion_context'";if(!source.includes(from))throw Error('expansion note transport anchor missing');return source.replace(from,to);}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-expansion-update.sql':applySql(),'rollback-before-expansion-update.sql':rollbackSql(),'operational-adapter.candidate.js':base.adapter(),'operational-overlay.candidate.js':base.overlay(),'transport.candidate.js':transport()};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md',...Object.keys(generated)],sources=['sql/expansion-pool-update/20260906/manifest.json','expansion-pool.js','sql/20260905_expansion_quote_handoff.sql','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',rpcs:['crm_expansion_note','crm_expansion_context'],ui_coverage_candidate:['X02'],prerequisite:'expansion-pool-update/20260906',surface:'pc_only',note_contract:{target:'source Closed Won Deal UUID',length:'1..8000 trimmed',idempotency:'request_id common receipt',effects:['private expansion event','Deal audit','receipt']},context_contract:{events:'actor-scoped safe event projection',dispatches:'empty until verified X03 provider ledger'},blocked:['quote dispatch fabrication','Pipeline conversion','client actor/time'],rollback:'note evidence archived; X01 remains active',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={transport,applySql,rollbackSql,build};
