'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),stage=require('../../pipeline-stage-check/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),eleven=stage.eleven;
const twelve=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text]))`;
const validator=()=>fs.readFileSync(path.join(dir,'validator.sql'),'utf8'),helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');
function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function sourceFragment(){let fn=stage.sourceFragment();const field='d.work_scope_type,d.work_summary,d.stage_checklist,d.version,';one(fn,field,'transition context projection');fn=fn.replace(field,'d.work_scope_type,d.work_summary,d.stage_checklist,d.stage_contexts,d.version,');const history="jsonb_build_object('from',h.from_stage,'to',h.to_stage,'changed_at',h.changed_at)";one(fn,history,'transition history projection');return fn.replace(history,"jsonb_build_object('from',h.from_stage,'to',h.to_stage,'at',h.changed_at,'changed_at',h.changed_at,'reason',h.reason,'actor',h.actor_name,'actor_id',h.actor_id)");}
function adapter(){let text=stage.adapter();one(text,"'next_action_complete','stage_check']",'adapter operations');text=text.replace("'next_action_complete','stage_check']","'next_action_complete','stage_check','transition']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'adapter normalize marker');const fn=" const TRANSITION_STAGES=new Set(['first_contact','consulting','sent','rapport','silent','waiting','compete','imminent','bidding','contract','construction','completion']);\n function normalizeTransition(objectId,payload){const allowed=['opportunity_id','from','to','stage_code','at','transition_date','note','reason','stage_context','stage_contexts','contract_amount','completion_date'],s=payload.stage_context,f=s&&s.fields;if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||!object(s)||!object(f)||payload.stage_code!==payload.from||s.from!==payload.from||s.to!==payload.to||s.transition_date!==payload.transition_date||!TRANSITION_STAGES.has(payload.to)||typeof payload.transition_date!=='string'||!/^\\d{4}-\\d{2}-\\d{2}$/.test(payload.transition_date)||typeof s.skip_reason!=='string'||s.skip_reason.length>2000||typeof s.memo!=='string'||s.memo.length>8000||typeof payload.note!=='string'||!payload.note.trim()||payload.note.length>16000)fail('TRANSITION_INTENT_NOT_CONNECTED');if(payload.contract_amount!==undefined&&payload.contract_amount!==f.contract_amount||payload.completion_date!==undefined&&payload.completion_date!==f.completion_date)fail('TRANSITION_FIELD_CONFLICT');return {from:payload.from,to:payload.to,transition_date:payload.transition_date,fields:JSON.parse(JSON.stringify(f)),skip_reason:s.skip_reason.trim(),memo:s.memo.trim(),note:payload.note.trim()};}\n";text=text.replace(marker,fn+marker);
 const old="else if(operation==='next_action_complete')normalized=normalizeComplete(objectId,payload);else normalized=normalizeStage(objectId,payload);";one(text,old,'adapter dispatch');text=text.replace(old,"else if(operation==='next_action_complete')normalized=normalizeComplete(objectId,payload);else if(operation==='stage_check')normalized=normalizeStage(objectId,payload);else normalized=normalizeTransition(objectId,payload);");
 const ack="  if(command.operation==='transition'&&(ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||ack.from_stage!==command.payload.from||ack.to_stage!==command.payload.to||ack.transition_date!==command.payload.transition_date||!UUID.test(ack.transition_event_id)||!UUID.test(ack.stage_history_id)||!UUID.test(ack.activity_id)||!UUID.test(ack.audit_event_id)||!Array.isArray(ack.cancelled_action_ids)||(ack.next_action_id!==null&&!UUID.test(ack.next_action_id))||!ack.stage_contexts||typeof ack.stage_contexts!=='object'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','adapter ack return');return text.replace('  return ack;}',ack+'  return ack;}');}
function overlay(){let text=stage.overlay();const connected="const connected=new Set(['opportunity_work_set','inquiry_assign','inquiry_unassign','service_change','favorite_set','opportunity_touch','activity','next_action','quote_version','next_action_complete','stage_check']);";one(text,connected,'overlay connected');text=text.replace(connected,connected.replace("'stage_check'","'stage_check','transition'"));
 const state='let compound=null,actionIntent=null,completeActionId=null,stageIntent=false;const versions=new Map(),seenAcks=new Set();';one(text,state,'overlay state');text=text.replace(state,'let compound=null,actionIntent=null,completeActionId=null,stageIntent=false,transitionCompound=false;const versions=new Map(),seenAcks=new Set();');
 const stageAck="  function applyStageAck(q){const value=q.ack&&q.ack.stage_checklist;if(!value)return;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.stage_checklist=value;d.stageChecklist=value;}}";one(text,stageAck,'transition ACK marker');text=text.replace(stageAck,stageAck+"\n  function applyTransitionAck(q){const a=q.ack;for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(q.object_id)){d.stage_code=d.code=a.to_stage;d.stage_contexts=d.stageContexts=a.stage_contexts;if(Array.isArray(d.stageHistory))d.stageHistory.push({id:a.stage_history_id,from:a.from_stage,to:a.to_stage,at:a.stage_entered_at});}}");
 const sync="if(q.operation==='stage_check')applyStageAck(q);";one(text,sync,'transition ACK sync');text=text.replace(sync,sync+"if(q.operation==='transition')applyTransitionAck(q);");
 const push="root.pushWrite=function(op,payload){if(op==='stage_check'&&!stageIntent)throw error('STAGE_CHECK_INTENT_NOT_CONNECTED');";one(text,push,'overlay push');text=text.replace(push,"root.pushWrite=function(op,payload){if(transitionCompound&&companion.has(op))return 'absorbed:'+op;if(op==='stage_check'&&!stageIntent)throw error('STAGE_CHECK_INTENT_NOT_CONNECTED');");
 const enqueue="const q=root.Phase1.queue.enqueue(op,id,expected,payload);syncQueue();";one(text,enqueue,'transition enqueue');text=text.replace(enqueue,"const q=root.Phase1.queue.enqueue(op,id,expected,payload);if(op==='transition'){transitionCompound=true;(root.queueMicrotask||queueMicrotask)(()=>{transitionCompound=false;});}syncQueue();");
 const shell='nextActionObj:n,nextAction:n';one(text,shell,'PC transition aliases');text=text.replace(shell,"nextActionObj:n,nextAction:n,stageContexts:d.stage_contexts||{},stageHistory:d.stage_history||[]");
 const mobile="stage_checklist:d.stage_checklist||{},stageChecklist:d.stage_checklist||{},tl:[]";one(text,mobile,'mobile transition aliases');text=text.replace(mobile,"stage_checklist:d.stage_checklist||{},stageChecklist:d.stage_checklist||{},stage_contexts:d.stage_contexts||{},stageHistory:d.stage_history||[],tl:[]");
 return text;}
function applySql(){return `SET crm.transition_ref='rprechiaglyjaydkmxsu';
BEGIN;
SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN
 IF current_user<>'postgres' OR current_setting('crm.transition_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu'
  OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL
  OR to_regprocedure('crm_security.crm_stage_check_command_v1(uuid,uuid,integer,jsonb)') IS NULL
  OR to_regprocedure('crm_security.crm_operational_source_fragment_v1(text,uuid,integer)') IS NULL
  OR NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name='stage_checklist')
  OR EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name='stage_contexts')
  OR to_regprocedure('crm_security.crm_write_command_v2_stage_check_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_transition_20260906(text,uuid,integer)') IS NOT NULL
  OR to_regprocedure('crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL
  OR to_regclass('crm_security.stage_transition_events') IS NOT NULL
  OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${eleven}$expected$
 THEN RAISE EXCEPTION 'transition after-stage-check prerequisite drift'; END IF;
END $guard$;
CREATE TEMP TABLE transition_source_guard AS SELECT p.oid,p.prosrc,p.proconfig,coalesce(p.proacl::text,'') acl FROM pg_proc p WHERE p.oid='public.crm_operational_source_v1(text,uuid,integer)'::regprocedure;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_stage_check_20260906;
ALTER FUNCTION public.crm_write_command_v2_stage_check_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;
REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_stage_check_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) RENAME TO crm_operational_source_fragment_pre_transition_20260906;
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_pre_transition_20260906(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE public.deals ADD COLUMN stage_contexts jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE TABLE crm_security.stage_transition_events(
 event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id uuid NOT NULL UNIQUE,deal_id uuid NOT NULL REFERENCES public.deals(id) ON DELETE RESTRICT,
 from_stage text NOT NULL,to_stage text NOT NULL,transition_date date NOT NULL,fields jsonb NOT NULL CHECK(jsonb_typeof(fields)='object'),skip_reason text,memo text,
 actor_auth_uid uuid NOT NULL,actor_user_id uuid NOT NULL REFERENCES public.users(user_id) ON DELETE RESTRICT,recorded_at timestamptz NOT NULL,
 stage_history_id uuid NOT NULL REFERENCES public.stage_history(id) ON DELETE RESTRICT,activity_id uuid NOT NULL REFERENCES public.activities(id) ON DELETE RESTRICT,next_action_id uuid REFERENCES public.next_actions(id) ON DELETE RESTRICT);
ALTER TABLE crm_security.stage_transition_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON crm_security.stage_transition_events FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;
ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition'));
${validator()}
${helper()}
${sourceFragment()}
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$
BEGIN
 IF p_operation='transition' THEN RETURN crm_security.crm_deal_transition_command_v1(p_request_id,p_object_id,p_expected_version,p_payload); END IF;
 RETURN crm_security.crm_write_command_v2_stage_check_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);
END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ DECLARE changed integer; BEGIN
 SELECT count(*) INTO changed FROM transition_source_guard g JOIN pg_proc p ON p.oid=g.oid WHERE p.prosrc IS DISTINCT FROM g.prosrc OR p.proconfig IS DISTINCT FROM g.proconfig OR coalesce(p.proacl::text,'') IS DISTINCT FROM g.acl;
 IF changed<>0 OR has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE')
  OR has_function_privilege('authenticated','crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_transition_validate_v1(text,jsonb,date)','EXECUTE') OR has_table_privilege('authenticated','crm_security.stage_transition_events','SELECT') OR NOT (SELECT relrowsecurity FROM pg_class WHERE oid='crm_security.stage_transition_events'::regclass)
  OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twelve}$expected$
 THEN RAISE EXCEPTION 'transition post-apply drift'; END IF;
END $post$;
COMMIT;
`;}
function rollbackSql(){return `SET crm.transition_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN
 IF current_setting('crm.transition_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL
  OR to_regprocedure('crm_security.crm_write_command_v2_stage_check_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb)') IS NULL
  OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_transition_20260906(text,uuid,integer)') IS NULL OR to_regclass('crm_security.stage_transition_events') IS NULL OR to_regnamespace('crm_transition_archive') IS NOT NULL
  OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twelve}$expected$
 THEN RAISE EXCEPTION 'transition rollback drift'; END IF;
END $guard$;
CREATE SCHEMA crm_transition_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_transition_archive FROM PUBLIC,anon,authenticated,service_role;
CREATE TABLE crm_transition_archive.deal_stage_contexts AS SELECT id AS deal_id,stage_contexts,clock_timestamp() AS archived_at FROM public.deals WHERE stage_contexts<>'{}'::jsonb;
CREATE TABLE crm_transition_archive.stage_transition_events AS TABLE crm_security.stage_transition_events;
CREATE TABLE crm_transition_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation='transition';
REVOKE ALL ON crm_transition_archive.deal_stage_contexts,crm_transition_archive.stage_transition_events,crm_transition_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;
DELETE FROM crm_security.command_receipts WHERE operation='transition';
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_transition_validate_v1(text,jsonb,date);DROP FUNCTION crm_security.crm_transition_field_date_v1(jsonb,text,boolean);DROP TABLE crm_security.stage_transition_events;
ALTER FUNCTION crm_security.crm_write_command_v2_stage_check_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DROP FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer);ALTER FUNCTION crm_security.crm_operational_source_fragment_pre_transition_20260906(text,uuid,integer) RENAME TO crm_operational_source_fragment_v1;REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE public.deals DROP COLUMN stage_contexts;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_stage_check_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL OR to_regclass('crm_security.stage_transition_events') IS NOT NULL OR EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name='stage_contexts') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${eleven}$expected$ THEN RAISE EXCEPTION 'transition rollback verification drift'; END IF; END $post$;
COMMIT;
`;}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-stage-check.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-stage-check.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['validator.sql','helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-stage-check.sql','rollback-after-stage-check.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_STAGE_CHECK_NOT_APPLIED',prerequisites:['personal-state-compat/20260906','pipeline-action-bundle/20260906','pipeline-quote-version/20260906','operational-read-source/20260906','pipeline-next-complete/20260906','pipeline-stage-check/20260906'],operation:'transition',intent:'structured_non_terminal_only',absorbed_children:['activity','next_action'],blocked_meanings:['inquiry_promote_transition','close','won','expansion','amount'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),golden_mobile:sha(fs.readFileSync(path.join(root,'mobile.html'))),stage_transition:sha(fs.readFileSync(path.join(root,'stage-transition.js'))),stage_ui:sha(fs.readFileSync(path.join(root,'stage-transition-ui.js'))),golden_sql:sha(fs.readFileSync(path.join(root,'sql/20260905_structured_stage_transition.sql'))),stage_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-stage-check/20260906/manifest.json')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,build,sourceFragment,eleven,twelve};
