'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('../../pipeline-stage-check/20260906/build.cjs'),transition=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),deal=s.uid(6,1),auth=s.mapping.accounts[0].auth_uid;
const rid=n=>`f6090600-0080-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());await db.exec(transition.applySql());return db;}
async function write(db,account,version,payload,request,op='transition'){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[request,op,deal,version,JSON.stringify(payload)])).rows[0].a;}
const consulting=()=>({from:'first_contact',to:'consulting',transition_date:'2026-09-01',fields:{quote_request:'옥상 방수 범위 견적',required_materials:'도면',quote_due:'2026-09-12'},skip_reason:'',memo:'관리소장 요청',note:'견적 요청내용: 옥상 방수 범위 견적'});
const waiting=()=>({from:'first_contact',to:'waiting',transition_date:'2026-09-01',fields:{reason:'입주자대표회의 대기',last_contact:'2026-08-31',speaker:'관리소장',statement:'회의 후 재개',resume_date:'2026-09-20',contact_date:'2026-09-15'},skip_reason:'',memo:'',note:'대기 사유: 입주자대표회의 대기'});
test('structured non-terminal transition is one actor-scoped transaction',async t=>{const db=await setup();try{
 await t.test('core, context, history, activity, private event, audit and receipt are exact',async()=>{const ack=await write(db,0,1,consulting(),rid(1));assert.equal(ack.actor_auth_uid,auth);assert.equal(ack.version,2);assert.equal(ack.from_stage,'first_contact');assert.equal(ack.to_stage,'consulting');assert.equal(ack.next_action_id,null);const row=(await db.query('SELECT stage_code,stage_raw,stage_group,lifecycle_status,stage_contexts,version FROM public.deals WHERE id=$1',[deal])).rows[0];assert.equal(row.stage_code,'consulting');assert.equal(row.stage_raw,'consulting');assert.equal(row.stage_group,'design');assert.equal(row.lifecycle_status,'active');assert.equal(row.stage_contexts.consulting.fields.quote_request,'옥상 방수 범위 견적');assert.equal(row.version,2);for(const [table,where] of [['public.stage_history',"opportunity_id=$1"],['public.activities',"deal_id=$1 AND type='단계전환'"],['crm_security.stage_transition_events','deal_id=$1'],['crm_security.audit_events',"deal_id=$1 AND action='transition'"],['crm_security.command_receipts',"object_id=$1 AND operation='transition'"]])assert.equal((await db.query(`SELECT count(*)::int n FROM ${table} WHERE ${where}`,[deal])).rows[0].n,1);});
 await t.test('source exposes durable context and rich history aliases',async()=>{await db.exec(`SET request.jwt.claim.sub='${auth}';`);const data=(await db.query("SELECT public.crm_operational_source_v1('deal_core',null,100) a")).rows[0].a,row=data.items.find(x=>x.id===deal);assert.equal(row.stage_contexts.consulting.fields.quote_request,'옥상 방수 범위 견적');assert.equal(row.stage_history[0].from,'first_contact');assert.equal(row.stage_history[0].to,'consulting');assert.equal(row.stage_history[0].actor_id,s.uid(1,1));});
 await t.test('replay is exact and changed request reuse creates no duplicates',async()=>{const replay=await write(db,0,1,consulting(),rid(1));assert.equal(replay.replayed,true);const changed=consulting();changed.memo='다른 메모';await assert.rejects(write(db,0,1,changed,rid(1)),e=>e.code==='PT409');assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.stage_transition_events WHERE deal_id=$1',[deal])).rows[0].n,1);});
 await t.test('stale, state mismatch, terminal, invalid required fields and foreign scope fail',async()=>{await assert.rejects(write(db,0,1,consulting(),rid(2)),e=>e.code==='PT409');await assert.rejects(write(db,0,2,consulting(),rid(3)),e=>e.code==='PT409');const terminal={...consulting(),to:'won'};await assert.rejects(write(db,0,2,terminal,rid(4)),e=>e.code==='22023');const bad={...consulting(),from:'consulting',to:'sent',fields:{materials:['견적서'],quote_version:'',recipient:'관리소장',sent_date:'2026-09-01',reaction:'검토중',followup_date:'2026-09-03'}};await assert.rejects(write(db,0,2,bad,rid(5)),e=>e.code==='22023');await assert.rejects(write(db,1,2,{...consulting(),from:'consulting',to:'sent',fields:{materials:['제안서'],quote_version:'',recipient:'관리소장',sent_date:'2026-09-01',reaction:'검토중',followup_date:'2026-09-03'}},rid(6)),e=>e.code==='42501');for(const fn of ['crm_security.crm_deal_transition_command_v1(uuid,uuid,integer,jsonb)','crm_security.crm_transition_validate_v1(text,jsonb,date)'])for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query('SELECT has_function_privilege($1,$2,\'EXECUTE\') allowed',[role,fn])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('transition-derived next replaces open action without child duplicates',async()=>{const db=await setup();try{const created=await write(db,0,1,{type:'전화',text:'기존 후속',due_at:'2026-09-10'},rid(10),'next_action');const ack=await write(db,0,2,waiting(),rid(11));assert.equal(ack.version,3);assert.ok(ack.cancelled_action_ids.includes(created.next_action_id));assert.ok(ack.next_action_id);assert.equal((await db.query('SELECT status FROM public.next_actions WHERE id=$1',[created.next_action_id])).rows[0].status,'cancelled');assert.equal((await db.query("SELECT count(*)::int n FROM public.next_actions WHERE deal_id=$1 AND status='open'",[deal])).rows[0].n,1);assert.deepEqual((await db.query('SELECT stage_code,lifecycle_status,next_action,next_action_date::text,version FROM public.deals WHERE id=$1',[deal])).rows[0],{stage_code:'waiting',lifecycle_status:'parked',next_action:'고객 재접촉',next_action_date:'2026-09-15',version:3});}finally{await db.close();}});
test('injected late failure rolls back every transition side effect',async()=>{const db=await setup();try{await db.exec("CREATE FUNCTION pg_temp.fail_transition_event() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'injected'; END$$; CREATE TRIGGER fail_transition_event BEFORE INSERT ON crm_security.stage_transition_events FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_transition_event();");await assert.rejects(write(db,0,1,consulting(),rid(20)),/injected/);assert.deepEqual((await db.query('SELECT stage_code,version,stage_contexts FROM public.deals WHERE id=$1',[deal])).rows[0],{stage_code:'first_contact',version:1,stage_contexts:{}});assert.equal((await db.query('SELECT count(*)::int n FROM public.stage_history WHERE opportunity_id=$1',[deal])).rows[0].n,0);assert.equal((await db.query("SELECT count(*)::int n FROM public.activities WHERE deal_id=$1 AND type='단계전환'",[deal])).rows[0].n,0);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='transition'",[deal])).rows[0].n,0);}finally{await db.close();}});
test('rollback restores stage-check layer and privately archives context/events/receipts',async()=>{const db=await setup();try{await write(db,0,1,consulting(),rid(30));await db.exec(transition.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_stage_check_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query('SELECT count(*)::int n FROM crm_transition_archive.deal_stage_contexts')).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM crm_transition_archive.stage_transition_events')).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM crm_transition_archive.command_receipts')).rows[0].n,1);assert.equal((await db.query("SELECT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='deals' AND column_name='stage_contexts') present")).rows[0].present,false);}finally{await db.close();}});
