'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),build=require('./build.cjs');
const deal='f6090500-0006-4000-8000-000000000001';
function load(text,name){const m=new Module(name);m._compile(text,name+'.js');return m.exports;}
function raw(){const fields={reason:'입주자대표회의 대기',last_contact:'2026-08-31',speaker:'관리소장',statement:'회의 후 재개',resume_date:'2026-09-20',contact_date:'2026-09-15'},snapshot={transition_date:'2026-09-01',skip_reason:'',memo:'',fields,from:'first_contact',to:'waiting',recorded_at:'client',actor:'client',terminal:false,next:{type:'후속접촉',text:'고객 재접촉',due:'2026-09-15'}};return {opportunity_id:deal,from:'first_contact',to:'waiting',stage_code:'first_contact',at:'client',transition_date:'2026-09-01',note:'대기 사유: 입주자대표회의 대기',reason:'대기 사유',stage_context:snapshot,stage_contexts:{waiting:snapshot}};}
function base(extra={}){const queued=[],listeners={},adapter=load(build.adapter(),'transition-adapter'),root={OperationalAdapter:adapter,TOKEN:'jwt',ME:{id:'u'},WRITE_Q:[],console,B:{deals:[]},Phase1:{read:async()=>({data:{deals:[],inquiries:[]}}),queue:{list:()=>[],enqueue:(op,id,version,payload)=>{const c=adapter.normalize(op,id,version,payload),q={...c,payload:c.payload,request_id:'f6090600-0080-4000-8000-000000000099'};queued.push(q);return q;},flush:async()=>{}}},addEventListener:(n,fn)=>{listeners[n]=fn},...extra};return {root,queued,ui:load(build.overlay(),'transition-overlay')};}
test('one structured transition absorbs the derived Activity and Next writes',()=>{const x=base({saveStructured(){this.pushWrite('transition',raw());this.pushWrite('activity',{opportunity_id:deal,type:'단계전환',note:'대기고객',result:'대기',occurred_at:'2026-09-01T00:00:00Z'});this.pushWrite('next_action',{opportunity_id:deal,type:'후속접촉',text:'고객 재접촉',due_at:'2026-09-15'});}});x.ui.install(x.root).versions.set(deal,5);x.root.saveStructured();assert.equal(x.queued.length,1);assert.equal(x.queued[0].operation,'transition');assert.equal(x.queued[0].payload.to,'waiting');assert.equal(x.queued[0].payload.fields.contact_date,'2026-09-15');});
test('simple inquiry-promote transition remains explicitly unconnected',()=>{const x=base();x.ui.install(x.root).versions.set(deal,1);assert.throws(()=>x.root.pushWrite('transition',{opportunity_id:deal,from:'first_contact',to:'consulting',note:'문의 승격'}),/TRANSITION_INTENT_NOT_CONNECTED/);});
test('operational hydration supplies contexts and rich history to PC and mobile',async()=>{let normalized;const row={id:deal,stage_code:'consulting',version:2,stage_contexts:{consulting:{fields:{quote_request:'견적'}}},stage_history:[{from:'first_contact',to:'consulting',at:'2026-09-01T00:00:00Z'}]};const x=base({Phase1:{read:async()=>({data:{deals:[row],inquiries:[]}}),queue:{list:()=>[],enqueue:()=>{},flush:async()=>{}}},normalizeDeal:d=>(normalized=d),rebuildAdmin(){},render(){},CUR:'mine'});x.ui.install(x.root);const bundle=await x.root.loadLive();assert.deepEqual(bundle.deals[0].stageContexts,row.stage_contexts);assert.deepEqual(normalized.stage_contexts,row.stage_contexts);assert.deepEqual(normalized.stageHistory,row.stage_history);});
test('generated adapter checks transition ACK and manifest remains local',()=>{const text=build.adapter();assert.match(text,/command\.operation==='transition'/);const manifest=build.build();assert.equal(manifest.staging_ddl_dml_performed,false);assert.deepEqual(manifest.absorbed_children,['activity','next_action']);});
