'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const service=require('./build.cjs');
const s=require('../../../scripts/crm-phase1.cjs');
const deal=s.uid(6,1),otherDeal=s.uid(6,2),inquiry=s.uid(5,5);
const rep=s.uid(1,1),admin=s.uid(1,5);
const repAuth=s.mapping.accounts[0].auth_uid,adminAuth=s.mapping.accounts[4].auth_uid;
const rid=n=>`f6090500-0099-4000-8000-${String(n).padStart(12,'0')}`;
async function rpc(db,{request=rid(1),operation='service_change',object=deal,version=1,payload},account=0){
 await db.exec(`SET ROLE authenticated; SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);
 try{return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,$4,$5) a',[request,operation,object,version,JSON.stringify(payload)])).rows[0].a;}
 finally{await db.exec('RESET ROLE');}
}
const payload=(patch={})=>({from_service:'FORGED OLD',to_service:'TEST NEW BUSINESS',origin_channel:'FORGED ORIGIN',reason:'사업유형 변경 테스트 근거',reason_source:'text',next_action:null,at:'1900-01-01T00:00:00Z',...patch});
test('service_change candidate on isolated PostgreSQL engine',async t=>{const db=await service.setup();try{
 const frozenBefore=(await db.query("SELECT oid,prosrc FROM pg_proc WHERE oid='public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)'::regprocedure")).rows[0];
 await db.exec(service.approval+service.candidate);
 const frozenAfter=(await db.query("SELECT oid,prosrc FROM pg_proc WHERE oid='crm_security.crm_write_command_v2_frozen_20260906(uuid,text,uuid,integer,jsonb)'::regprocedure")).rows[0];
 await t.test('frozen dispatcher body and OID are preserved',()=>{assert.equal(frozenAfter.oid,frozenBefore.oid);assert.equal(frozenAfter.prosrc,frozenBefore.prosrc);});
 let first;
 await t.test('owner rep writes canonical business/history/activity/audit with server actor and one version',async()=>{
  const before=(await db.query('SELECT current_business,brand,origin_business,service_type,business_history,version,last_customer_contact_at FROM public.deals WHERE id=$1',[deal])).rows[0];
  first=await rpc(db,{payload:payload()});
  assert.equal(first.ok,true);assert.equal(first.operation,'service_change');assert.equal(first.actor_auth_uid,repAuth);assert.equal(first.actor_user_id,rep);assert.equal(first.previous_version,1);assert.equal(first.version,2);assert.equal(first.from_service,before.current_business||before.brand);assert.equal(first.to_service,'TEST NEW BUSINESS');
  const row=(await db.query('SELECT current_business,brand,origin_business,service_type,business_history,version,last_activity_at,last_customer_contact_at FROM public.deals WHERE id=$1',[deal])).rows[0];
  assert.equal(row.current_business,'TEST NEW BUSINESS');assert.equal(row.brand,'TEST NEW BUSINESS');assert.equal(row.service_type,'TEST NEW BUSINESS');assert.equal(row.origin_business,before.origin_business||before.current_business||before.brand);assert.equal(row.version,2);assert.equal(row.last_customer_contact_at?.toISOString(),before.last_customer_contact_at?.toISOString());
  const entry=row.business_history.at(-1);assert.equal(entry.from,before.current_business||before.brand);assert.equal(entry.to,'TEST NEW BUSINESS');assert.equal(entry.reason,'사업유형 변경 테스트 근거');assert.equal(entry.actor,'TEST INTERNAL_REP');assert.notEqual(entry.at,'1900-01-01T00:00:00Z');
  const h=(await db.query('SELECT from_business,to_business,reason,reason_source,actor_name,changed_at FROM public.business_history WHERE id=$1',[first.business_history_id])).rows[0];assert.equal(h.from_business,entry.from);assert.equal(h.to_business,entry.to);assert.equal(h.reason,entry.reason);assert.equal(h.reason_source,entry.source);assert.equal(h.actor_name,entry.actor);assert.equal(h.changed_at.toISOString(),new Date(entry.at).toISOString());
  const activity=(await db.query('SELECT actor_email,actor_name,type,detail,occurred_at FROM public.activities WHERE id=$1',[first.activity_id])).rows[0];assert.equal(activity.actor_email,'crm-internal-rep@example.invalid');assert.equal(activity.actor_name,'TEST INTERNAL_REP');assert.equal(activity.type,'사업유형전환');assert.equal(activity.detail.result,'사업유형 변경 테스트 근거');assert.equal(activity.detail.meaningful_contact,false);assert.equal(activity.occurred_at.toISOString(),new Date(entry.at).toISOString());assert.equal(row.last_activity_at.toISOString(),activity.occurred_at.toISOString());
  const audit=(await db.query('SELECT actor_auth_uid,actor_user_id,actor_name,action,reason,before_data,after_data FROM crm_security.audit_events WHERE event_id=$1',[first.audit_event_id])).rows[0];assert.equal(audit.actor_auth_uid,repAuth);assert.equal(audit.actor_user_id,rep);assert.equal(audit.actor_name,'TEST INTERNAL_REP');assert.equal(audit.action,'service_change');assert.equal(audit.reason,'사업유형 변경 테스트 근거');assert.equal(audit.before_data.version,1);assert.equal(audit.after_data.version,2);
 });
 await t.test('same request replays without duplicate durable effects',async()=>{const a=await rpc(db,{payload:payload()});assert.equal(a.replayed,true);assert.equal(a.activity_id,first.activity_id);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE operation='service_change'")).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE action='service_change'")).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM public.activities WHERE type='사업유형전환' AND deal_id=$1",[deal])).rows[0].n,1);});
 await t.test('same request with changed payload is 409',async()=>{await assert.rejects(rpc(db,{payload:payload({reason:'다른 재사용 변경 근거'})}),e=>e.code==='PT409');});
 await t.test('stale version, short reason, foreign owner and consultation role are rejected',async()=>{await assert.rejects(rpc(db,{request:rid(2),version:1,payload:payload()}),e=>e.code==='PT409');await assert.rejects(rpc(db,{request:rid(3),version:2,payload:payload({reason:'짧음'})}),e=>e.code==='22023');await assert.rejects(rpc(db,{request:rid(4),object:otherDeal,version:1,payload:payload()}),e=>e.code==='42501');await assert.rejects(rpc(db,{request:rid(5),version:2,payload:payload()},2),e=>e.code==='42501');});
 await t.test('optional next action follows deployed append/default rule',async()=>{const a=await rpc(db,{request:rid(6),version:2,payload:payload({to_service:'TEST NEXT BUSINESS',reason:'후속 행동 포함 변경 근거',reason_source:'voice',next_action:'담당자 후속 확인',next_due:'2026-09-20'})});const n=(await db.query('SELECT action_type,title,due_at,assignee_name,status,source_activity_id FROM public.next_actions WHERE id=$1',[a.next_action_id])).rows[0];assert.deepEqual({action_type:n.action_type,title:n.title,assignee_name:n.assignee_name,status:n.status,source_activity_id:n.source_activity_id},{action_type:'기타',title:'담당자 후속 확인',assignee_name:'TEST INTERNAL_REP',status:'open',source_activity_id:null});assert.equal(n.due_at.toISOString(),'2026-09-20T09:00:00.000Z');});
 await t.test('mid-transaction activity failure rolls back deal/history/receipt/audit',async()=>{await db.exec("CREATE FUNCTION pg_temp.fail_service_activity() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.type='사업유형전환' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END$$; CREATE TRIGGER fail_service_activity BEFORE INSERT ON public.activities FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_service_activity();");const before=(await db.query('SELECT to_jsonb(d) row FROM public.deals d WHERE id=$1',[deal])).rows[0].row;const counts=(await db.query("SELECT (SELECT count(*) FROM public.business_history) h,(SELECT count(*) FROM crm_security.audit_events WHERE action='service_change') a,(SELECT count(*) FROM crm_security.command_receipts WHERE operation='service_change') r")).rows[0];await assert.rejects(rpc(db,{request:rid(7),version:3,payload:payload({to_service:'TEST ROLLBACK',reason:'원자 롤백 검증 근거'})}));assert.deepEqual((await db.query('SELECT to_jsonb(d) row FROM public.deals d WHERE id=$1',[deal])).rows[0].row,before);assert.deepEqual((await db.query("SELECT (SELECT count(*) FROM public.business_history) h,(SELECT count(*) FROM crm_security.audit_events WHERE action='service_change') a,(SELECT count(*) FROM crm_security.command_receipts WHERE operation='service_change') r")).rows[0],counts);await db.exec('DROP TRIGGER fail_service_activity ON public.activities; DROP FUNCTION pg_temp.fail_service_activity()');});
 await t.test('frozen work and direct_assign operations retain their behavior',async()=>{const work=await rpc(db,{request:rid(8),operation:'opportunity_work_set',object:otherDeal,version:1,payload:{primary_work:'TEST 회귀 공종',work_items:['TEST 회귀 공종'],reason:'동결 공종 회귀 근거'}},1);assert.equal(work.ok,true);assert.equal(work.operation,'opportunity_work_set');assert.equal(work.version,2);await db.query("UPDATE public.inquiries SET assigned_to=NULL,assigned_at=NULL,status='접수' WHERE id=$1",[inquiry]);const assigned=await rpc(db,{request:rid(9),operation:'inquiry_assign',object:inquiry,version:0,payload:{intent:'direct_assign',to_name:'TEST INTERNAL_REP'}},4);assert.equal(assigned.ok,true);assert.equal(assigned.operation,'inquiry_assign');assert.equal(assigned.assigned_to,rep);});
 }finally{await db.close();}});
test('guarded apply and evidence-preserving rollback restore prior metadata',async()=>{await service.build();const db=await service.setup();try{const before=await service.capture(db),apply=fs.readFileSync(path.join(service.dir,'staging-apply.sql'),'utf8'),rollback=fs.readFileSync(path.join(service.dir,'rollback.sql'),'utf8');await db.exec(apply);await rpc(db,{request:rid(20),payload:payload()});await db.exec(rollback);assert.deepEqual(await service.capture(db),before);assert.equal((await db.query("SELECT count(*)::int n FROM crm_pipeline_service_archive.command_receipts WHERE operation='service_change'")).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE action='service_change'")).rows[0].n,1);}finally{await db.close();}});

