'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),trash=require('../../inquiry-trash-restore/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),nineteen=trash.nineteen,auditBefore=trash.auditAfter;
const twenty=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text, 'waiting_context'::text, 'inquiry_reclassify'::text, 'inquiry_status'::text, 'inquiry_trash'::text, 'inquiry_restore'::text, 'inquiry_purge'::text]))`;
const auditAfter=`CHECK (action = ANY (ARRAY['direct_assign'::text, 'direct_reassign'::text, 'inquiry_unassign'::text, 'inquiry_reclassify'::text, 'inquiry_hold'::text, 'inquiry_trash'::text, 'inquiry_restore'::text, 'inquiry_purge'::text]))`;
const helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');
function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function adapter(){let text=trash.adapter();
 const ops="'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore']";one(text,ops,'operations');text=text.replace(ops,"'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'normalize marker');text=text.replace(marker," function normalizePurge(objectId,payload){if(payload.inquiry_id!==objectId)fail('INVALID_INQUIRY_PURGE_COMMAND');const allowed=['inquiry_id','purged_at','purged_by'];if(Object.keys(payload).some(k=>!allowed.includes(k)))fail('INQUIRY_PURGE_INTENT_NOT_CONNECTED');return {intent:'purge'};}\n"+marker);
 const sentinel="['inquiry_assign','inquiry_unassign','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','favorite_set','opportunity_touch'].includes(operation)";one(text,sentinel,'sentinel');text=text.replace(sentinel,"['inquiry_assign','inquiry_unassign','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','favorite_set','opportunity_touch'].includes(operation)");
 const dispatch="else if(operation==='inquiry_status')normalized=normalizeHold(objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);";one(text,dispatch,'dispatch');text=text.replace(dispatch,"else if(operation==='inquiry_status')normalized=normalizeHold(objectId,payload);else if(operation==='inquiry_purge')normalized=normalizePurge(objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);");
 const ack="  if(command.operation==='inquiry_purge'&&(ack.purged!==true||typeof ack.purged_at!=='string'||typeof ack.purged_by!=='string'||!['removed_scope_count','cascaded_assignment_history_count','cascaded_next_action_count','cascaded_stage_history_count'].every(k=>Number.isInteger(ack[k])&&ack[k]>=0)||!UUID.test(ack.inquiry_audit_event_id)))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','ACK return');return text.replace('  return ack;}',ack+'  return ack;}');}
function overlay(){let text=trash.overlay();
 const connected="'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore']";one(text,connected,'connected');text=text.replace(connected,"'inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge']");
 const state='holdIntent=false,trashIntent=false,restoreIntent=false;const versions';one(text,state,'state');text=text.replace(state,'holdIntent=false,trashIntent=false,restoreIntent=false,purgeIntent=false;const versions');
 const rows="  function inquiryRows(){return [root.B&&root.B.inquiries,root.B&&root.B.inquiryTrash,root.INQUIRIES,root.ADMIN&&root.ADMIN.inquiries].filter(Array.isArray);}\n";one(text,rows,'rows');text=text.replace(rows,rows+"  function applyPurgeAck(q){for(const rows of inquiryRows())for(let i=rows.length-1;i>=0;i--)if(String(rows[i].id||rows[i].inquiry_id||rows[i].key)===String(q.object_id))rows.splice(i,1);if(typeof root.inqCtlPartition==='function')root.inqCtlPartition();}\n");
 const sync="if(q.operation==='inquiry_trash')applyTrashAck(q);if(q.operation==='inquiry_restore')applyRestoreAck(q);";one(text,sync,'sync');text=text.replace(sync,sync+"if(q.operation==='inquiry_purge')applyPurgeAck(q);");
 const push="root.pushWrite=function(op,payload){if(op==='inquiry_trash'&&!trashIntent)throw error('INQUIRY_TRASH_INTENT_NOT_CONNECTED');if(op==='inquiry_restore'&&!restoreIntent)throw error('INQUIRY_RESTORE_INTENT_NOT_CONNECTED');";one(text,push,'push');text=text.replace(push,push+"if(op==='inquiry_purge'&&!purgeIntent)throw error('INQUIRY_PURGE_INTENT_NOT_CONNECTED');");
 const wrapper="  if(typeof root.inqCtlRestore==='function'){const original=root.inqCtlRestore;root.inqCtlRestore=function(){const previous=restoreIntent;restoreIntent=true;try{return original.apply(this,arguments);}finally{restoreIntent=previous;}};}";one(text,wrapper,'wrapper');text=text.replace(wrapper,wrapper+"\n  if(typeof root.inqCtlHardDelete==='function'){const original=root.inqCtlHardDelete;root.inqCtlHardDelete=function(){const previous=purgeIntent;purgeIntent=true;try{return original.apply(this,arguments);}finally{purgeIntent=previous;}};}");return text;}
function applySql(){return `SET crm.inquiry_purge_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.inquiry_purge_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_trash_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_restore_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_trash_restore_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_purge_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${nineteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry purge prerequisite drift';END IF;END $guard$;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_inquiry_trash_restore_20260906;ALTER FUNCTION public.crm_write_command_v2_inquiry_trash_restore_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_inquiry_trash_restore_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign','inquiry_reclassify','inquiry_hold','inquiry_trash','inquiry_restore','inquiry_purge'));
${helper()}
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN IF p_operation='inquiry_purge' THEN IF p_expected_version IS DISTINCT FROM 0 THEN RAISE EXCEPTION 'invalid inquiry management version sentinel' USING ERRCODE='22023';END IF;RETURN crm_security.crm_inquiry_purge_command_v1(p_request_id,p_object_id,p_payload);END IF;RETURN crm_security.crm_write_command_v2_inquiry_trash_restore_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ BEGIN IF has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_inquiry_purge_command_v1(uuid,uuid,jsonb)','EXECUTE') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twenty}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry purge post-apply drift';END IF;END $post$;COMMIT;`;}
function rollbackSql(){return `SET crm.inquiry_purge_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.inquiry_purge_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_trash_restore_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_purge_command_v1(uuid,uuid,jsonb)') IS NULL OR EXISTS(SELECT 1 FROM crm_security.command_receipts WHERE operation='inquiry_purge') OR EXISTS(SELECT 1 FROM crm_security.inquiry_audit_events WHERE action='inquiry_purge') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twenty}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry purge rollback blocked: drift or runtime purge evidence exists';END IF;END $guard$;
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_inquiry_purge_command_v1(uuid,uuid,jsonb);ALTER FUNCTION crm_security.crm_write_command_v2_inquiry_trash_restore_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign','inquiry_reclassify','inquiry_hold','inquiry_trash','inquiry_restore'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_inquiry_trash_restore_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_purge_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${nineteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry purge rollback verification drift';END IF;END $post$;COMMIT;`;}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-trash-restore.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-trash-restore.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-trash-restore.sql','rollback-after-trash-restore.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_TRASH_RESTORE_NOT_APPLIED',prerequisites:['inquiry-trash-restore/20260906'],operations:['inquiry_purge'],intent:'admin_manual_irreversible_purge_only',blocked_meanings:['automatic_purge','non_admin_purge','linked_inquiry_purge'],rollback:'PRE_USE_ONLY_RUNTIME_PURGE_IS_IRREVERSIBLE',staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),trash_manifest:sha(fs.readFileSync(path.join(root,'sql/inquiry-trash-restore/20260906/manifest.json'))),inquiry_contracts:sha(fs.readFileSync(path.join(root,'docs/operational-cutover-20260906/inquiry-management-contracts.md')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,build,nineteen,twenty,auditBefore,auditAfter};
