'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('../../pipeline-stage-check/20260906/build.cjs'),transition=require('../../pipeline-transition/20260906/build.cjs'),close=require('../../pipeline-close-nonwon/20260906/build.cjs'),amount=require('../../pipeline-amount-expected/20260906/build.cjs'),waiting=require('../../pipeline-waiting-context/20260906/build.cjs'),reclassify=require('../../inquiry-reclassify/20260906/build.cjs'),hold=require('../../inquiry-hold/20260906/build.cjs'),trash=require('../../inquiry-trash-restore/20260906/build.cjs'),purge=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),inquiry=s.uid(5,5),assignee=s.fixture.mapped[0].user_id,deal=s.uid(6,5);const rid=n=>`f6090600-0096-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());await db.exec(transition.applySql());await db.exec(close.applySql());await db.exec(amount.applySql());await db.exec(waiting.applySql());await db.exec(reclassify.applySql());await db.exec(hold.applySql());await db.exec(trash.applySql());await db.exec(purge.applySql());await db.query("UPDATE public.inquiries SET status='배정완료',assigned_to=$2,deal_id=NULL,opportunity_id=NULL WHERE id=$1",[inquiry,assignee]);await db.query('UPDATE public.deals SET origin_inquiry_id=NULL WHERE origin_inquiry_id=$1',[inquiry]);return db;}
async function write(db,account,op,payload,request,object=inquiry){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query('SELECT public.crm_write_command_v2($1,$2,$3,0,$4) a',[request,op,object,JSON.stringify(payload)])).rows[0].a;}
const trashPayload={delete_reason:'중복 문의',delete_note:'완전삭제 시험'},purgePayload={intent:'purge'};
test('admin manual purge deletes only the unlinked trashed aggregate and preserves private evidence',async()=>{const db=await setup();try{
 await db.query("INSERT INTO public.assignment_history(inquiry_id,to_owner,reason) VALUES($1,'TEST','PURGE TEST')",[inquiry]);await db.query("INSERT INTO public.next_actions(inquiry_id,title,due_at,assignee_name) VALUES($1,'PURGE TEST',now(),'TEST')",[inquiry]);await db.query("INSERT INTO public.stage_history(inquiry_id,to_stage,reason) VALUES($1,'first_contact','PURGE TEST')",[inquiry]);
 await write(db,4,'inquiry_trash',trashPayload,rid(1));const ack=await write(db,4,'inquiry_purge',purgePayload,rid(2));assert.equal(ack.purged,true);assert.ok(ack.removed_scope_count>0);assert.ok(ack.cascaded_assignment_history_count>0);assert.ok(ack.cascaded_next_action_count>0);assert.ok(ack.cascaded_stage_history_count>0);
 for(const [table,column] of [['inquiries','id'],['assignment_history','inquiry_id'],['next_actions','inquiry_id'],['stage_history','inquiry_id']])assert.equal((await db.query(`SELECT count(*)::int n FROM public.${table} WHERE ${column}=$1`,[inquiry])).rows[0].n,0,table);assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.object_scope WHERE inquiry_id=$1',[inquiry])).rows[0].n,0);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_purge'",[inquiry])).rows[0].n,1);assert.equal((await write(db,4,'inquiry_purge',purgePayload,rid(2))).replayed,true);await assert.rejects(write(db,4,'inquiry_purge',purgePayload,rid(3)),e=>e.code==='PT409');
 }finally{await db.close();}});
test('active, non-admin and linked inquiries cannot be purged',async()=>{const db=await setup();try{await assert.rejects(write(db,4,'inquiry_purge',purgePayload,rid(10)),e=>e.code==='PT409');await assert.rejects(write(db,0,'inquiry_purge',purgePayload,rid(11)),e=>e.code==='42501');await db.query('UPDATE public.inquiries SET deal_id=$2 WHERE id=$1',[inquiry,deal]);const trashed=await write(db,4,'inquiry_trash',trashPayload,rid(12));assert.equal(trashed.archive_protected,true);await assert.rejects(write(db,4,'inquiry_purge',purgePayload,rid(13)),e=>e.code==='PT409');assert.equal((await db.query('SELECT count(*)::int n FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].n,1);}finally{await db.close();}});
test('late receipt failure rolls the physical delete and scope removal back',async()=>{const db=await setup();try{await write(db,4,'inquiry_trash',trashPayload,rid(20));await db.exec("CREATE FUNCTION pg_temp.fail_purge_receipt() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.operation='inquiry_purge' THEN RAISE EXCEPTION 'injected';END IF;RETURN NEW;END$$;CREATE TRIGGER fail_purge_receipt BEFORE INSERT ON crm_security.command_receipts FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_purge_receipt();");await assert.rejects(write(db,4,'inquiry_purge',purgePayload,rid(21)),/injected/);assert.equal((await db.query('SELECT count(*)::int n FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].n,1);assert.ok((await db.query('SELECT count(*)::int n FROM crm_security.object_scope WHERE inquiry_id=$1',[inquiry])).rows[0].n>0);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_purge'",[inquiry])).rows[0].n,0);}finally{await db.close();}});
test('migration rollback works before use and refuses to fake recovery after runtime purge',async()=>{let db=await setup();try{await db.exec(purge.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_inquiry_purge_command_v1(uuid,uuid,jsonb)') IS NULL dropped")).rows[0].dropped,true);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_inquiry_trash_command_v1(uuid,uuid,jsonb)') IS NOT NULL kept")).rows[0].kept,true);}finally{await db.close();}db=await setup();try{await write(db,4,'inquiry_trash',trashPayload,rid(30));await write(db,4,'inquiry_purge',purgePayload,rid(31));await assert.rejects(db.exec(purge.rollbackSql()),/rollback blocked/);}finally{await db.close();}});
