'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),base=require('../../message-reminder/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),baseDir=path.resolve(dir,'../../message-reminder/20260906'),read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function one(source,from,to,label){if(!source.includes(from))throw Error('next postpone build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=read(path.join(baseDir,'operational-adapter.candidate.js'));
 source=one(source,"function normalizeNext(objectId,payload){if(payload&&payload.intent==='message_reminder')",`function normalizePostpone(objectId,payload){const allowed=['opportunity_id','intent','action_id','due_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||payload.intent!=='postpone'||!UUID.test(payload.action_id)||!/^\\d{4}-\\d{2}-\\d{2}$/.test(payload.due_at))fail('NEXT_POSTPONE_INTENT_NOT_CONNECTED');return {intent:'postpone',action_id:payload.action_id,due_at:payload.due_at};}
 function normalizeNext(objectId,payload){if(payload&&payload.intent==='postpone')return normalizePostpone(objectId,payload);if(payload&&payload.intent==='message_reminder')`,'normalizer');
 source=one(source,"!['inquiry_next_set','message_reminder'].includes(command.payload.intent)","!['inquiry_next_set','message_reminder','postpone'].includes(command.payload.intent)",'generic ACK exclusion');
 source=one(source,"  if(command.operation==='next_action'&&command.payload.intent==='message_reminder'",`  if(command.operation==='next_action'&&command.payload.intent==='postpone'&&(ack.intent!=='postpone'||ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||ack.next_action_id!==command.payload.action_id||ack.due_at!==command.payload.due_at||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(ack.previous_due_at)||!Number.isSafeInteger(ack.postpone_count)||ack.postpone_count<1||!UUID.test(ack.postpone_event_id)||!UUID.test(ack.activity_id)||!UUID.test(ack.audit_event_id)||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='next_action'&&command.payload.intent==='message_reminder'`,'postpone ACK');
 return source;
}
function overlay(){let source=read(path.join(baseDir,'operational-overlay.candidate.js'));
 source=one(source," 'use strict';\n const connected",` 'use strict';\n const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;\n const connected`,'UUID validator');
 source=one(source,"draft_body:d.next_action.draft_body||null,draftBody:d.next_action.draft_body||null","draft_body:d.next_action.draft_body||null,draftBody:d.next_action.draft_body||null,postpone_count:Number(d.next_action.postpone_count||0),postponeCount:Number(d.next_action.postpone_count||0)",'read shell');
 source=one(source,"actionIntent=null,inquiryActionIntent=null","actionIntent=null,postponeAction=null,inquiryActionIntent=null",'state');
 source=one(source,"if(actionIntent==='message_reminder'&&op==='activity')return 'absorbed:activity';","if((actionIntent==='message_reminder'||actionIntent==='postpone')&&op==='activity')return 'absorbed:activity';",'activity absorption');
 source=one(source,"}else if(op==='next_action'&&actionIntent==='message_reminder'){payload={...payload,intent:'message_reminder'};}","}else if(op==='next_action'&&actionIntent==='message_reminder'){payload={...payload,intent:'message_reminder'};}else if(op==='next_action'&&actionIntent==='postpone'){if(!postponeAction)throw error('NEXT_POSTPONE_ACTION_REQUIRED');payload={opportunity_id:payload&&payload.opportunity_id,intent:'postpone',action_id:postponeAction.id,due_at:payload&&payload.due_at};}",'push normalization');
 source=one(source,"if(q.payload.intent==='message_reminder'){const n=",`if(q.payload.intent==='postpone'){const n=d.nextActionObj||(d.nextAction&&typeof d.nextAction==='object'?d.nextAction:null);if(n){n.due=n.due_at=q.ack.due_at;n.postpone=n.postpone_count=n.postponeCount=q.ack.postpone_count;}d.postpone=d.postpone_count=d.postponeCount=q.ack.postpone_count;}if(q.payload.intent==='message_reminder'){const n=`,'ACK hydration');
 source=one(source,"  wrap('rmScheduleM','message_reminder');",`  wrap('rmScheduleM','message_reminder');
  function runPostpone(action,days,fn,args){if(!action||!UUID.test(String(action.id||'')))throw error('NEXT_POSTPONE_ACTION_REQUIRED');const before=String(action.due_at||action.due||'').slice(0,10),delay=Number(days),after=new Date(Date.now()+delay*864e5).toISOString().slice(0,10);if(!Number.isSafeInteger(delay)||delay<1||!before||after<=before){if(typeof root.toast==='function')root.toast('현재 기한보다 뒤의 날짜만 연기할 수 있습니다.');return false;}const pi=actionIntent,pa=postponeAction;actionIntent='postpone';postponeAction={id:String(action.id),before_due:before};try{return fn.apply(this,args);}finally{actionIntent=pi;postponeAction=pa;}}
  if(typeof root.todoDelay==='function'){const original=root.todoDelay;root.todoDelay=function(k){const d=(root.B&&root.B.deals||[]).find(x=>String(root.dealKey?root.dealKey(x):x.id)===String(k)),a=d&&root.actionObj&&root.actionObj(d,root.itemPatch?root.itemPatch(d,'deal'):null);return runPostpone.call(this,a,3,original,[k]);};}
  if(typeof root.applyTodayPostponeM==='function'){const original=root.applyTodayPostponeM;root.applyTodayPostponeM=function(days){const t=root.G&&root.G._today&&root.G._today[root.G.execTask],d=t&&root.todayDeal&&root.todayDeal(root.G.execTask),a=d&&root.execNextM&&root.execNextM(d);if(!d)return original.apply(this,arguments);return runPostpone.call(this,a,days,original,[days]);};}`,'wrappers');
 return source;
}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-message-reminder.sql':applySql(),'rollback-before-message-reminder.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':read(path.join(baseDir,'transport.candidate.js'))};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md',...Object.keys(generated)],sources=['sql/message-reminder/20260906/manifest.json','crm.html','mobile.html','docs/operational-cutover-20260906/coverage-matrix.csv'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operation:'next_action',intent:'postpone',ui_coverage_candidate:['P09X'],prerequisite:'message-reminder/20260906',surface:'pc_mobile',payload:['action_id','due_at'],server_rules:{scope:'crm_security.can_deal(deal_id,true)',identity:'server-projected current open Next Action UUID',date:'strictly later than current due and server KST date',counter:'append-only per-Deal server count',transaction:'same Next Action due + event + non-meaningful Activity + Deal version + audit + receipt'},read_additions:['next_action.postpone_count'],blocked:['temporary client action id','earlier or same date','client postpone_count','standalone derived Activity'],rollback:'event/audit/receipt archived; changed business due and Activity retained; M04 remains active',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,applySql,rollbackSql,build};
