'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),waiting=require('../../pipeline-waiting-context/20260906/build.cjs'),close=require('../../pipeline-close-nonwon/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex'),fifteen=waiting.fifteen;
const sixteen=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text, 'waiting_context'::text, 'inquiry_reclassify'::text]))`;
const auditBefore=`CHECK (action = ANY (ARRAY['direct_assign'::text, 'direct_reassign'::text, 'inquiry_unassign'::text]))`;
const auditAfter=`CHECK (action = ANY (ARRAY['direct_assign'::text, 'direct_reassign'::text, 'inquiry_unassign'::text, 'inquiry_reclassify'::text]))`;
const helper=()=>fs.readFileSync(path.join(dir,'helper.sql'),'utf8');function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function sourceFragment(){let fn=close.sourceFragment();const old='i.first_response_at,i.responded_at,i.next_action_date,i.contact_name,i.phone';one(fn,old,'inquiry projection');const add=`i.first_response_at,i.responded_at,i.next_action_date,i.contact_name,i.phone,
    (SELECT e.after_data->>'review_status' FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_reclassify' ORDER BY e.created_at DESC,e.event_id DESC LIMIT 1) AS legacy_review_status,
    (SELECT e.after_data->>'reviewed_at' FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_reclassify' ORDER BY e.created_at DESC,e.event_id DESC LIMIT 1) AS legacy_reviewed_at,
    (SELECT e.after_data->>'reviewed_by' FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_reclassify' ORDER BY e.created_at DESC,e.event_id DESC LIMIT 1) AS legacy_reviewed_by,
    coalesce((SELECT jsonb_agg(jsonb_build_object('id',e.event_id,'type','데이터정리','note',coalesce(e.before_data->>'brand','기술자문')||' → '||coalesce(e.after_data->>'brand',''),'result','정상 견적문의로 재분류','at',e.created_at,'actor',e.after_data->>'reviewed_by') ORDER BY e.created_at,e.event_id) FROM crm_security.inquiry_audit_events e WHERE e.inquiry_id=i.id AND e.action='inquiry_reclassify'),'[]'::jsonb) AS activities`;
 return fn.replace(old,add);}
function adapter(){let text=waiting.adapter();const ops="'amount','waiting_context']";one(text,ops,'adapter operations');text=text.replace(ops,"'amount','waiting_context','inquiry_reclassify']");const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'normalize marker');const fn=" function normalizeReclassify(objectId,payload){const allowed=['inquiry_id','from_brand','to_brand','review_status','reviewed_at','reviewed_by'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.inquiry_id!==objectId||payload.from_brand!=='기술자문'||payload.review_status!=='reclassified'||typeof payload.to_brand!=='string'||!payload.to_brand.trim()||payload.to_brand.trim()==='기술자문'||payload.to_brand.length>100)fail('INQUIRY_RECLASSIFY_INTENT_NOT_CONNECTED');return {to_brand:payload.to_brand.trim()};}\n";text=text.replace(marker,fn+marker);const sentinel="['inquiry_assign','inquiry_unassign','favorite_set','opportunity_touch'].includes(operation)";one(text,sentinel,'sentinel operations');text=text.replace(sentinel,"['inquiry_assign','inquiry_unassign','inquiry_reclassify','favorite_set','opportunity_touch'].includes(operation)");const dispatch="else if(operation==='amount')normalized=normalizeAmount(objectId,payload);else normalized=normalizeWaiting(objectId,payload);";one(text,dispatch,'adapter dispatch');text=text.replace(dispatch,"else if(operation==='amount')normalized=normalizeAmount(objectId,payload);else if(operation==='waiting_context')normalized=normalizeWaiting(objectId,payload);else normalized=normalizeReclassify(objectId,payload);");const ack="  if(command.operation==='inquiry_reclassify'&&(ack.from_brand!=='기술자문'||ack.to_brand!==command.payload.to_brand||ack.review_status!=='reclassified'||typeof ack.reviewed_at!=='string'||typeof ack.reviewed_by!=='string'||!UUID.test(ack.inquiry_audit_event_id)))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','ACK return');return text.replace('  return ack;}',ack+'  return ack;}');}
function overlay(){let text=waiting.overlay();const connected="'amount','waiting_context']";one(text,connected,'overlay connected');text=text.replace(connected,"'amount','waiting_context','inquiry_reclassify']");const state='waitingIntent=false,waitingChild=false;const versions';one(text,state,'overlay state');text=text.replace(state,'waitingIntent=false,waitingChild=false,reclassifyIntent=false;const versions');const marker='  function syncQueue(){';one(text,marker,'queue marker');const apply="  function applyReclassifyAck(q){const a=q.ack;for(const rows of [root.B&&root.B.inquiries,root.INQUIRIES])if(Array.isArray(rows))for(const i of rows)if(String(i.id||i.inquiry_id)===String(q.object_id)){i.brand=a.to_brand;i.business_type=a.to_brand;i.legacy_review_status=a.review_status;i.legacy_reviewed_at=a.reviewed_at;i.legacy_reviewed_by=a.reviewed_by;i.activities=Array.isArray(i.activities)?i.activities:[];i.activities.push({id:a.inquiry_audit_event_id,type:'데이터정리',note:'기술자문 → '+a.to_brand,result:'정상 견적문의로 재분류',at:a.reviewed_at,actor:a.reviewed_by});}}\n";text=text.replace(marker,apply+marker);const sync="if(q.operation==='waiting_context')applyWaitingAck(q);";one(text,sync,'queue sync');text=text.replace(sync,sync+"if(q.operation==='inquiry_reclassify')applyReclassifyAck(q);");const push='root.pushWrite=function(op,payload){';one(text,push,'push marker');text=text.replace(push,push+"if(op==='inquiry_reclassify'&&!reclassifyIntent)throw error('INQUIRY_RECLASSIFY_INTENT_NOT_CONNECTED');");const wrapper="  if(typeof root.dccSaveWaitingContext==='function'){const original=root.dccSaveWaitingContext;root.dccSaveWaitingContext=function(){const previous=waitingIntent;waitingIntent=true;try{return original.apply(this,arguments);}finally{waitingIntent=previous;}};}";one(text,wrapper,'wrapper marker');text=text.replace(wrapper,wrapper+"\n  if(typeof root.inqTechReclassify==='function'){const original=root.inqTechReclassify;root.inqTechReclassify=function(){const previous=reclassifyIntent;reclassifyIntent=true;try{return original.apply(this,arguments);}finally{reclassifyIntent=previous;}};}");return text;}
function applySql(){return `SET crm.inquiry_reclassify_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.inquiry_reclassify_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_v1(text,uuid,integer)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_waiting_context_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_inquiry_reclassify_20260906(text,uuid,integer)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fifteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry reclassify after-waiting prerequisite drift';END IF;END $guard$;
CREATE TEMP TABLE inquiry_reclassify_source_guard AS SELECT p.oid,p.prosrc,p.proconfig,coalesce(p.proacl::text,'') acl FROM pg_proc p WHERE p.oid='public.crm_operational_source_v1(text,uuid,integer)'::regprocedure;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_waiting_context_20260906;ALTER FUNCTION public.crm_write_command_v2_waiting_context_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_waiting_context_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) RENAME TO crm_operational_source_fragment_pre_inquiry_reclassify_20260906;REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_pre_inquiry_reclassify_20260906(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign','inquiry_reclassify'));
${helper()}
${sourceFragment()}
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN IF p_operation='inquiry_reclassify' THEN IF p_expected_version IS DISTINCT FROM 0 THEN RAISE EXCEPTION 'invalid inquiry reclassify version sentinel' USING ERRCODE='22023';END IF;RETURN crm_security.crm_inquiry_reclassify_command_v1(p_request_id,p_object_id,p_payload);END IF;RETURN crm_security.crm_write_command_v2_waiting_context_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ DECLARE changed integer;BEGIN SELECT count(*) INTO changed FROM inquiry_reclassify_source_guard g JOIN pg_proc p ON p.oid=g.oid WHERE p.prosrc IS DISTINCT FROM g.prosrc OR p.proconfig IS DISTINCT FROM g.proconfig OR coalesce(p.proacl::text,'') IS DISTINCT FROM g.acl;IF changed<>0 OR has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('authenticated','crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)','EXECUTE') OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${sixteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry reclassify post-apply drift';END IF;END $post$;COMMIT;`;}
function rollbackSql(){return `SET crm.inquiry_reclassify_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.inquiry_reclassify_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu' OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_waiting_context_20260906(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_inquiry_reclassify_20260906(text,uuid,integer)') IS NULL OR to_regnamespace('crm_inquiry_reclassify_archive') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${sixteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditAfter}$expected$ THEN RAISE EXCEPTION 'inquiry reclassify rollback drift';END IF;END $guard$;
CREATE SCHEMA crm_inquiry_reclassify_archive AUTHORIZATION postgres;REVOKE ALL ON SCHEMA crm_inquiry_reclassify_archive FROM PUBLIC,anon,authenticated,service_role;CREATE TABLE crm_inquiry_reclassify_archive.audit_events AS SELECT * FROM crm_security.inquiry_audit_events WHERE action='inquiry_reclassify';CREATE TABLE crm_inquiry_reclassify_archive.command_receipts AS SELECT * FROM crm_security.command_receipts WHERE operation='inquiry_reclassify';REVOKE ALL ON crm_inquiry_reclassify_archive.audit_events,crm_inquiry_reclassify_archive.command_receipts FROM PUBLIC,anon,authenticated,service_role;
UPDATE public.inquiries i SET brand='기술자문',updated_at=clock_timestamp() FROM (SELECT DISTINCT ON(inquiry_id) inquiry_id,after_data FROM crm_inquiry_reclassify_archive.audit_events ORDER BY inquiry_id,created_at DESC,event_id DESC)x WHERE i.id=x.inquiry_id AND i.brand=x.after_data->>'brand';
DELETE FROM crm_security.command_receipts WHERE operation='inquiry_reclassify';DELETE FROM crm_security.inquiry_audit_events WHERE action='inquiry_reclassify';
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb);ALTER FUNCTION crm_security.crm_write_command_v2_waiting_context_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DROP FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer);ALTER FUNCTION crm_security.crm_operational_source_fragment_pre_inquiry_reclassify_20260906(text,uuid,integer) RENAME TO crm_operational_source_fragment_v1;REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context'));
ALTER TABLE crm_security.inquiry_audit_events DROP CONSTRAINT inquiry_audit_events_action_check;ALTER TABLE crm_security.inquiry_audit_events ADD CONSTRAINT inquiry_audit_events_action_check CHECK(action IN ('direct_assign','direct_reassign','inquiry_unassign'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_waiting_context_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${fifteen}$expected$ OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.inquiry_audit_events'::regclass AND conname='inquiry_audit_events_action_check') IS DISTINCT FROM $expected$${auditBefore}$expected$ THEN RAISE EXCEPTION 'inquiry reclassify rollback verification drift';END IF;END $post$;COMMIT;`;}
function build(){fs.writeFileSync(path.join(dir,'staging-apply-after-waiting.sql'),applySql());fs.writeFileSync(path.join(dir,'rollback-after-waiting.sql'),rollbackSql());fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),adapter());fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),overlay());const names=['helper.sql','adapter-contract.js','contract.test.cjs','db.test.cjs','ui.test.cjs','review.md','staging-apply-after-waiting.sql','rollback-after-waiting.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_WAITING_NOT_APPLIED',prerequisites:['pipeline-waiting-context/20260906'],operation:'inquiry_reclassify',intent:'technical_inquiry_to_quote_brand_only',blocked_meanings:['technical_inquiry_promote','linked_inquiry','inquiry_status','arbitrary_brand'],staging_ddl_dml_performed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{golden_pc:sha(fs.readFileSync(path.join(root,'crm.html'))),waiting_manifest:sha(fs.readFileSync(path.join(root,'sql/pipeline-waiting-context/20260906/manifest.json'))),inquiry_contracts:sha(fs.readFileSync(path.join(root,'docs/operational-cutover-20260906/inquiry-management-contracts.md')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));module.exports={applySql,rollbackSql,adapter,overlay,sourceFragment,build,fifteen,sixteen,auditBefore,auditAfter};
