'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const personal=require('../../personal-state-compat/20260906/build.cjs'),action=require('../../pipeline-action-bundle/20260906/build.cjs'),quote=require('../../pipeline-quote-version/20260906/build.cjs'),next=require('../../pipeline-next-complete/20260906/build.cjs'),stage=require('../../pipeline-stage-check/20260906/build.cjs'),transition=require('../../pipeline-transition/20260906/build.cjs'),close=require('../../pipeline-close-nonwon/20260906/build.cjs'),amount=require('../../pipeline-amount-expected/20260906/build.cjs'),waiting=require('../../pipeline-waiting-context/20260906/build.cjs'),reclassify=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const sourceApproval="SET crm.operational_source_ref='rprechiaglyjaydkmxsu';\n",sourceSql=fs.readFileSync(path.join(__dirname,'../../operational-read-source/20260906/candidate.sql'),'utf8'),personalSql=fs.readFileSync(path.join(__dirname,'../../personal-state-compat/20260906/candidate.sql'),'utf8'),inquiry=s.uid(5,5),admin=s.mapping.accounts[4].auth_uid,deal=s.uid(6,5);const rid=n=>`f6090600-0093-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(personal.approval+personalSql);await db.exec(action.applySql());await db.exec(quote.applySql());await db.exec(sourceApproval+sourceSql);await db.exec(next.applySql());await db.exec(stage.applySql());await db.exec(transition.applySql());await db.exec(close.applySql());await db.exec(amount.applySql());await db.exec(waiting.applySql());await db.exec(reclassify.applySql());await db.query("UPDATE public.inquiries SET brand='기술자문',deal_id=NULL,opportunity_id=NULL WHERE id=$1",[inquiry]);await db.query('UPDATE public.deals SET origin_inquiry_id=NULL WHERE origin_inquiry_id=$1',[inquiry]);return db;}
async function write(db,account,brand,request){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[account].auth_uid}';`);return (await db.query("SELECT public.crm_write_command_v2($1,'inquiry_reclassify',$2,0,$3) a",[request,inquiry,JSON.stringify({to_brand:brand})])).rows[0].a;}
test('technical inquiry reclassification is one scoped transaction',async t=>{const db=await setup();try{
 await t.test('brand, durable review audit, receipt and read projection are exact',async()=>{const ack=await write(db,4,'POUR솔루션',rid(1));assert.equal(ack.actor_auth_uid,admin);assert.equal(ack.from_brand,'기술자문');assert.equal(ack.review_status,'reclassified');assert.equal((await db.query('SELECT brand FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].brand,'POUR솔루션');assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_reclassify'",[inquiry])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE object_id=$1 AND operation='inquiry_reclassify'",[inquiry])).rows[0].n,1);await db.exec(`SET request.jwt.claim.sub='${admin}';`);const data=(await db.query("SELECT public.crm_operational_source_v1('inquiry_core',null,100) a")).rows[0].a,row=data.items.find(x=>x.id===inquiry);assert.equal(row.legacy_review_status,'reclassified');assert.equal(row.legacy_reviewed_by,'TEST ADMIN');assert.equal(row.activities.length,1);assert.equal(row.activities[0].type,'데이터정리');});
 await t.test('replay exact; reuse, non-admin and linked inquiry fail',async()=>{const replay=await write(db,4,'POUR솔루션',rid(1));assert.equal(replay.replayed,true);await assert.rejects(write(db,4,'아파트스퀘어',rid(1)),e=>e.code==='PT409');await db.query("UPDATE public.inquiries SET brand='기술자문',deal_id=$2 WHERE id=$1",[inquiry,deal]);await assert.rejects(write(db,4,'POUR솔루션',rid(2)),e=>e.code==='PT409');await db.query('UPDATE public.inquiries SET deal_id=NULL WHERE id=$1',[inquiry]);await assert.rejects(write(db,0,'POUR솔루션',rid(3)),e=>e.code==='42501');assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.inquiry_audit_events WHERE inquiry_id=$1 AND action='inquiry_reclassify'",[inquiry])).rows[0].n,1);for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);});
 }finally{await db.close();}});
test('late audit failure rolls back brand',async()=>{const db=await setup();try{await db.exec("CREATE FUNCTION pg_temp.fail_reclass_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='inquiry_reclassify' THEN RAISE EXCEPTION 'injected';END IF;RETURN NEW;END$$;CREATE TRIGGER fail_reclass_audit BEFORE INSERT ON crm_security.inquiry_audit_events FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_reclass_audit();");await assert.rejects(write(db,4,'POUR솔루션',rid(20)),/injected/);assert.equal((await db.query('SELECT brand FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].brand,'기술자문');assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE object_id=$1 AND operation='inquiry_reclassify'",[inquiry])).rows[0].n,0);}finally{await db.close();}});
test('rollback restores technical brand and prior layer',async()=>{const db=await setup();try{await write(db,4,'POUR솔루션',rid(30));await db.exec(reclassify.rollbackSql());assert.equal((await db.query('SELECT brand FROM public.inquiries WHERE id=$1',[inquiry])).rows[0].brand,'기술자문');assert.equal((await db.query('SELECT count(*)::int n FROM crm_inquiry_reclassify_archive.audit_events')).rows[0].n,1);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_deal_waiting_context_command_v1(uuid,uuid,integer,jsonb)') IS NOT NULL kept")).rows[0].kept,true);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_inquiry_reclassify_command_v1(uuid,uuid,jsonb)') IS NULL dropped")).rows[0].dropped,true);}finally{await db.close();}});
