-- 경남지사 운영 소속 / 대표 보고 분류 분리
-- 적용 순서: Supabase SQL Editor 실행 → crm-api 번들에 sales_people 포함
-- 기존 crm-write inquiry_assign 라우트는 동일한 RPC 이름을 계속 사용할 수 있다.

begin;

create table if not exists public.sales_people (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_label text,
  team text not null check (team in ('head_office','gyeongnam','external')),
  reporting_group text not null check (reporting_group in ('internal','external')),
  member_role text not null default 'member' check (member_role in ('member','branch_pool')),
  inquiry_assignable boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sales_people
  add column if not exists inquiry_assignable boolean not null default false;

insert into public.sales_people (name,display_label,team,reporting_group,member_role,inquiry_assignable)
values
 ('황윤선','황윤선','head_office','internal','member',true),
 ('이필선','이필선','head_office','internal','member',true),
 ('한준엽','한준엽','head_office','internal','member',true),
 ('정정훈','정정훈','head_office','internal','member',true),
 ('김성민','김성민','head_office','internal','member',true),
 ('조현식','조현식','head_office','internal','member',true),
 ('조민준','조민준','gyeongnam','external','member',false),
 ('김훈','김훈','gyeongnam','external','member',false),
 ('경남지사','경남지사 미지정','gyeongnam','external','branch_pool',false)
on conflict (name) do update set
  display_label=excluded.display_label,
  team=excluded.team,
  reporting_group=excluded.reporting_group,
  member_role=excluded.member_role,
  inquiry_assignable=excluded.inquiry_assignable,
  active=true,
  updated_at=now();

alter table public.inquiries
  add column if not exists assignment_group text,
  add column if not exists branch_code text,
  add column if not exists reporting_group text;

alter table public.deals
  add column if not exists assignment_group text,
  add column if not exists branch_code text,
  add column if not exists reporting_group text;

alter table public.crm_inquiry_assignment_history
  add column if not exists assignment_group text,
  add column if not exists reporting_group text;

alter table public.inquiries drop constraint if exists inquiries_assignment_group_check;
alter table public.inquiries add constraint inquiries_assignment_group_check
  check (assignment_group is null or assignment_group in ('head_office','gyeongnam','external'));
alter table public.inquiries drop constraint if exists inquiries_reporting_group_check;
alter table public.inquiries add constraint inquiries_reporting_group_check
  check (reporting_group is null or reporting_group in ('internal','external'));

alter table public.deals drop constraint if exists deals_assignment_group_check;
alter table public.deals add constraint deals_assignment_group_check
  check (assignment_group is null or assignment_group in ('head_office','gyeongnam','external'));
alter table public.deals drop constraint if exists deals_reporting_group_check;
alter table public.deals add constraint deals_reporting_group_check
  check (reporting_group is null or reporting_group in ('internal','external'));

create index if not exists sales_people_team_idx
  on public.sales_people (team,reporting_group,active);
create index if not exists inquiries_branch_active_idx
  on public.inquiries (branch_code,assigned_at desc) where deleted_at is null;
create index if not exists deals_branch_open_idx
  on public.deals (branch_code) where branch_code is not null;

alter table public.sales_people enable row level security;
drop policy if exists sales_people_read on public.sales_people;
create policy sales_people_read on public.sales_people
  for select to authenticated using (true);

create or replace function public.crm_sales_people()
returns jsonb language sql stable security definer set search_path=public as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',id,'name',name,'display_label',coalesce(display_label,name),
    'team',team,'reporting_group',reporting_group,'member_role',member_role,
    'inquiry_assignable',inquiry_assignable,'active',active
  ) order by team,name),'[]'::jsonb)
  from public.sales_people where active;
$$;

create or replace function public.crm_inquiry_assign(
  p_inquiry_id text,
  p_to text,
  p_changed_by text,
  p_reason text default '업무량 확인 후 담당자 배정'
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare
  v_row public.inquiries;
  v_from text;
  v_action text;
  v_team text;
  v_reporting_group text;
begin
  select * into v_row from public.inquiries where id::text=p_inquiry_id for update;
  if not found then raise exception 'inquiry not found: %', p_inquiry_id; end if;
  if v_row.deleted_at is not null then raise exception 'trashed inquiry cannot be assigned'; end if;

  select team,reporting_group into v_team,v_reporting_group
  from public.sales_people where name=p_to and active limit 1;
  if not found then
    v_team := 'external';
    v_reporting_group := 'external';
  end if;

  v_from := coalesce(v_row.assigned_to,'미배정');
  v_action := case when v_row.assigned_to is null then 'assign' else 'reassign' end;
  if v_action='reassign' and nullif(trim(p_reason),'') is null then
    raise exception 'reassignment reason is required';
  end if;

  update public.inquiries set
    assigned_to=p_to,
    assigned_at=now(),
    assigned_by=p_changed_by,
    assignment_group=v_team,
    branch_code=case when v_team='gyeongnam' then 'gyeongnam' else null end,
    reporting_group=v_reporting_group,
    inquiry_status=case when inquiry_status in ('접수','신규') then '배정완료' else inquiry_status end
  where id::text=p_inquiry_id returning * into v_row;

  insert into public.crm_inquiry_assignment_history
    (inquiry_id,from_assignee,to_assignee,changed_by,reason,action,assignment_group,reporting_group)
  values
    (p_inquiry_id,v_from,p_to,p_changed_by,
     coalesce(nullif(trim(p_reason),''),'업무량 확인 후 담당자 배정'),v_action,
     v_team,v_reporting_group);
  return v_row;
end $$;

-- 기존 데이터는 이름 조건문이 아니라 담당자 Master 조인으로 1회 보정한다.
update public.inquiries i set
  assignment_group=p.team,
  branch_code=case when p.team='gyeongnam' then 'gyeongnam' else null end,
  reporting_group=p.reporting_group
from public.sales_people p
where p.name=i.assigned_to
  and (i.assignment_group is distinct from p.team
    or i.reporting_group is distinct from p.reporting_group);

-- 운영 스키마의 담당자 컬럼명 차이를 확인하고 존재하는 컬럼으로만 1회 보정한다.
do $$
declare owner_col text;
begin
  select column_name into owner_col
  from information_schema.columns
  where table_schema='public' and table_name='deals'
    and column_name in ('assignee','owner_name','owner')
  order by case column_name when 'assignee' then 1 when 'owner_name' then 2 else 3 end
  limit 1;
  if owner_col is not null then
    execute format($sql$
      update public.deals d set
        assignment_group=p.team,
        branch_code=case when p.team='gyeongnam' then 'gyeongnam' else null end,
        reporting_group=p.reporting_group
      from public.sales_people p
      where p.name=d.%I
        and (d.assignment_group is distinct from p.team
          or d.reporting_group is distinct from p.reporting_group)
    $sql$,owner_col);
  end if;
end $$;

grant select on public.sales_people to authenticated;
grant execute on function public.crm_inquiry_assign(text,text,text,text) to authenticated;
grant execute on function public.crm_sales_people() to authenticated;

commit;
