-- 사람 역할 정본 + 견적문의 상담담당/영업담당 분리
-- 적용 순서:
-- 1) 20260905_inquiry_control_center.sql
-- 2) 20260905_gyeongnam_branch.sql
-- 3) 이 파일
-- 4) crm-api 번들에 crm_sales_people() 결과 및 inquiries의 consultant_* 필드 포함
-- 5) crm-write inquiry_consultant -> crm_inquiry_set_consultant RPC 연결

begin;

alter table public.sales_people
  add column if not exists employment_type text not null default 'unknown',
  add column if not exists report_badge text,
  add column if not exists sales_rep boolean not null default false,
  add column if not exists inquiry_consultable boolean not null default false,
  add column if not exists performance_included boolean not null default false;

-- 이전 경남지사 마이그레이션의 좁은 역할/보고분류 제약을 명시적 역할 체계로 확장한다.
alter table public.sales_people drop constraint if exists sales_people_reporting_group_check;
alter table public.sales_people add constraint sales_people_reporting_group_check check (
  reporting_group in ('internal','external','executive','employee','operations','excluded','unclassified')
);
alter table public.sales_people drop constraint if exists sales_people_member_role_check;
alter table public.sales_people add constraint sales_people_member_role_check check (
  member_role in ('member','sales','consultation','company_employee','ceo','external_sales','branch_sales','branch_pool','operations','inactive','unknown')
);

insert into public.sales_people
  (name,display_label,team,reporting_group,employment_type,member_role,report_badge,
   sales_rep,inquiry_consultable,inquiry_assignable,performance_included,active)
values
 ('황윤선','황윤선','head_office','internal','employee','sales','내부영업',true,true,true,true,true),
 ('이필선','이필선','head_office','internal','employee','sales','내부영업',true,true,true,true,true),
 ('한준엽','한준엽','head_office','internal','employee','sales','내부영업',true,true,true,true,true),
 ('정정훈','정정훈','head_office','internal','employee','sales','내부영업',true,true,true,true,true),
 ('김성민','김성민','head_office','internal','employee','sales','내부영업',true,true,true,true,true),
 ('조현식','조현식','head_office','internal','employee','sales','내부영업',true,true,true,true,true),
 ('이승우','이승우','head_office','executive','executive','ceo','대표이사',false,false,false,false,true),
 ('조재연','조재연','head_office','employee','employee','consultation','회사직원',false,true,false,false,true),
 ('주현진','주현진','head_office','employee','employee','company_employee','회사직원',false,false,false,false,true),
 ('전용성','전용성','external','external','contractor','external_sales','외부',true,false,false,true,true),
 ('조성용','조성용','external','external','contractor','external_sales','외부',true,false,false,true,true),
 ('조민준','조민준','gyeongnam','external','branch','branch_sales','경남지사',true,true,false,true,true),
 ('김훈','김훈','gyeongnam','external','branch','branch_sales','경남지사',true,true,false,true,true),
 ('경남지사','경남지사 미지정','gyeongnam','external','branch','branch_pool','경남지사',false,false,false,false,true),
 ('한인규','한인규','head_office','excluded','inactive','inactive',null,false,false,false,false,false)
on conflict (name) do update set
  display_label=excluded.display_label,
  team=excluded.team,
  reporting_group=excluded.reporting_group,
  employment_type=excluded.employment_type,
  member_role=excluded.member_role,
  report_badge=excluded.report_badge,
  sales_rep=excluded.sales_rep,
  inquiry_consultable=excluded.inquiry_consultable,
  inquiry_assignable=excluded.inquiry_assignable,
  performance_included=excluded.performance_included,
  active=excluded.active,
  updated_at=now();

alter table public.inquiries
  add column if not exists consultant_name text,
  add column if not exists consulted_at timestamptz,
  add column if not exists consultation_status text not null default 'none',
  add column if not exists sales_assigned_at timestamptz;

alter table public.inquiries drop constraint if exists inquiries_consultation_status_check;
alter table public.inquiries add constraint inquiries_consultation_status_check check (
  consultation_status in ('none','assigned','in_progress','completed')
);

create table if not exists public.crm_inquiry_consultation_history (
  id bigint generated by default as identity primary key,
  inquiry_id text not null,
  from_consultant text,
  to_consultant text,
  consultation_status text not null,
  changed_at timestamptz not null default now(),
  changed_by text not null,
  note text
);
create index if not exists inquiry_consultation_history_lookup_idx
  on public.crm_inquiry_consultation_history (inquiry_id,changed_at desc);

alter table public.crm_inquiry_consultation_history enable row level security;
drop policy if exists crm_inquiry_consultation_history_read on public.crm_inquiry_consultation_history;
create policy crm_inquiry_consultation_history_read
  on public.crm_inquiry_consultation_history for select to authenticated using (true);
drop policy if exists crm_inquiry_consultation_history_write on public.crm_inquiry_consultation_history;
create policy crm_inquiry_consultation_history_write
  on public.crm_inquiry_consultation_history for insert to authenticated with check (true);

-- 기존 조재연 배정 문의는 삭제하지 않는다. 기존 assignment_history는 그대로 두고,
-- 현재 귀속만 상담담당으로 옮겨 영업배정 대기 상태로 만든다.
update public.inquiries
set consultant_name=coalesce(consultant_name,'조재연'),
    consulted_at=coalesce(consulted_at,assigned_at,now()),
    consultation_status=case when first_response_at is null then 'assigned' else 'completed' end,
    assigned_to=null,
    assigned_at=null,
    assigned_by=null,
    sales_assigned_at=null,
    assignment_group=null,
    branch_code=null,
    reporting_group=null,
    inquiry_status=case
      when inquiry_status in ('영업전환','전환완료','보류') then inquiry_status
      when first_response_at is null then '상담중 · 영업배정 필요'
      else '상담 완료 · 영업배정 필요'
    end
where assigned_to='조재연';

create or replace function public.crm_inquiry_set_consultant(
  p_inquiry_id text,
  p_consultant_name text,
  p_consultation_status text default 'assigned',
  p_changed_by text default '관리자',
  p_note text default null
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare
  v_row public.inquiries;
  v_from text;
  v_allowed boolean;
begin
  if p_consultation_status not in ('none','assigned','in_progress','completed') then
    raise exception 'invalid consultation status';
  end if;
  if nullif(trim(coalesce(p_consultant_name,'')),'') is not null then
    select inquiry_consultable and active into v_allowed
    from public.sales_people where name=p_consultant_name;
    if coalesce(v_allowed,false)=false then raise exception 'person is not inquiry consultable'; end if;
  end if;

  select * into v_row from public.inquiries where id::text=p_inquiry_id for update;
  if not found then raise exception 'inquiry not found: %',p_inquiry_id; end if;
  if v_row.deleted_at is not null then raise exception 'trashed inquiry cannot be changed'; end if;
  v_from:=v_row.consultant_name;

  update public.inquiries set
    consultant_name=nullif(trim(coalesce(p_consultant_name,'')),''),
    consulted_at=case when nullif(trim(coalesce(p_consultant_name,'')),'') is null then null else now() end,
    consultation_status=case when nullif(trim(coalesce(p_consultant_name,'')),'') is null then 'none' else p_consultation_status end
  where id::text=p_inquiry_id returning * into v_row;

  insert into public.crm_inquiry_consultation_history
    (inquiry_id,from_consultant,to_consultant,consultation_status,changed_by,note)
  values
    (p_inquiry_id,v_from,v_row.consultant_name,v_row.consultation_status,p_changed_by,p_note);
  return v_row;
end $$;

-- 담당자 배정 RPC는 상담담당/회사직원을 영업담당으로 받을 수 없게 강제한다.
create or replace function public.crm_inquiry_assign(
  p_inquiry_id text,
  p_to text,
  p_changed_by text,
  p_reason text default '업무량 확인 후 영업담당자 배정'
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare
  v_row public.inquiries;
  v_from text;
  v_action text;
  v_team text;
  v_reporting_group text;
  v_sales_rep boolean;
  v_role text;
begin
  select * into v_row from public.inquiries where id::text=p_inquiry_id for update;
  if not found then raise exception 'inquiry not found: %',p_inquiry_id; end if;
  if v_row.deleted_at is not null then raise exception 'trashed inquiry cannot be assigned'; end if;

  select team,reporting_group,sales_rep,member_role
  into v_team,v_reporting_group,v_sales_rep,v_role
  from public.sales_people where name=p_to and active limit 1;
  if not found or (coalesce(v_sales_rep,false)=false and v_role<>'branch_pool') then
    raise exception 'person is not a sales assignee: %',p_to;
  end if;

  v_from:=coalesce(v_row.assigned_to,'미배정');
  v_action:=case when v_row.assigned_to is null then 'assign' else 'reassign' end;
  if v_action='reassign' and nullif(trim(p_reason),'') is null then
    raise exception 'reassignment reason is required';
  end if;

  update public.inquiries set
    assigned_to=p_to,
    assigned_at=now(),
    sales_assigned_at=now(),
    assigned_by=p_changed_by,
    assignment_group=v_team,
    branch_code=case when v_team='gyeongnam' then 'gyeongnam' else null end,
    reporting_group=v_reporting_group,
    inquiry_status=case when inquiry_status in ('접수','신규','상담중 · 영업배정 필요','상담 완료 · 영업배정 필요') then '배정완료' else inquiry_status end
  where id::text=p_inquiry_id returning * into v_row;

  insert into public.crm_inquiry_assignment_history
    (inquiry_id,from_assignee,to_assignee,changed_by,reason,action,assignment_group,reporting_group)
  values
    (p_inquiry_id,v_from,p_to,p_changed_by,
     coalesce(nullif(trim(p_reason),''),'업무량 확인 후 영업담당자 배정'),v_action,
     v_team,v_reporting_group);
  return v_row;
end $$;

create or replace function public.crm_sales_people()
returns jsonb language sql stable security definer set search_path=public as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',id,
    'name',name,
    'display_label',coalesce(display_label,name),
    'team',team,
    'reporting_group',reporting_group,
    'employment_type',employment_type,
    'member_role',member_role,
    'report_badge',report_badge,
    'sales_rep',sales_rep,
    'inquiry_consultable',inquiry_consultable,
    'inquiry_assignable',inquiry_assignable,
    'performance_included',performance_included,
    'active',active
  ) order by
    case reporting_group when 'internal' then 1 when 'external' then 2 when 'executive' then 3 when 'employee' then 4 else 9 end,
    name),'[]'::jsonb)
  from public.sales_people where active;
$$;

grant select on public.crm_inquiry_consultation_history to authenticated;
grant execute on function public.crm_inquiry_set_consultant(text,text,text,text,text) to authenticated;
grant execute on function public.crm_inquiry_assign(text,text,text,text) to authenticated;
grant execute on function public.crm_sales_people() to authenticated;

commit;
