-- 견적문의 접수·배정 Control Center
-- 적용 순서: Supabase SQL Editor에서 이 파일 실행 → n8n write router에 아래 RPC 매핑
-- inquiry_assign  -> crm_inquiry_assign
-- inquiry_unassign/status/trash/restore/purge/duplicate -> 이름이 같은 crm_inquiry_* RPC

begin;

alter table public.inquiries
  add column if not exists assigned_to text,
  add column if not exists assigned_at timestamptz,
  add column if not exists assigned_by text,
  add column if not exists inquiry_status text not null default '접수',
  add column if not exists hold_reason text,
  add column if not exists held_at timestamptz,
  add column if not exists first_response_at timestamptz,
  add column if not exists valid_inquiry boolean not null default true,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text,
  add column if not exists delete_reason text,
  add column if not exists delete_note text,
  add column if not exists purge_at timestamptz,
  add column if not exists archive_protected boolean not null default false,
  add column if not exists trash_snapshot jsonb,
  add column if not exists restored_at timestamptz,
  add column if not exists restored_by text,
  add column if not exists duplicate_of_inquiry_id text,
  add column if not exists duplicate_resolution text,
  add column if not exists duplicate_reviewed_at timestamptz;

alter table public.inquiries drop constraint if exists inquiries_delete_reason_check;
alter table public.inquiries add constraint inquiries_delete_reason_check check (
  delete_reason is null or delete_reason in
    ('중복 문의','테스트 문의','스팸','잘못된 연락처','관련 없는 문의','기타')
);

alter table public.inquiries drop constraint if exists inquiries_trash_consistent;
alter table public.inquiries add constraint inquiries_trash_consistent check (
  (deleted_at is null and purge_at is null)
  or
  (deleted_at is not null and deleted_by is not null and delete_reason is not null
   and purge_at = deleted_at + interval '30 days')
);

create table if not exists public.crm_inquiry_assignment_history (
  id bigint generated by default as identity primary key,
  inquiry_id text not null,
  from_assignee text,
  to_assignee text,
  changed_at timestamptz not null default now(),
  changed_by text not null,
  reason text not null,
  action text not null default 'assign'
    check (action in ('assign','reassign','unassign'))
);

create index if not exists inquiries_active_received_idx
  on public.inquiries (received_at desc) where deleted_at is null;
create index if not exists inquiries_trash_purge_idx
  on public.inquiries (purge_at) where deleted_at is not null;
create index if not exists inquiry_assignment_history_lookup_idx
  on public.crm_inquiry_assignment_history (inquiry_id, changed_at desc);

alter table public.crm_inquiry_assignment_history enable row level security;
drop policy if exists crm_inquiry_assignment_history_read on public.crm_inquiry_assignment_history;
create policy crm_inquiry_assignment_history_read
  on public.crm_inquiry_assignment_history for select to authenticated using (true);
drop policy if exists crm_inquiry_assignment_history_write on public.crm_inquiry_assignment_history;
create policy crm_inquiry_assignment_history_write
  on public.crm_inquiry_assignment_history for insert to authenticated with check (true);

create or replace function public.crm_inquiry_assign(
  p_inquiry_id text,
  p_to text,
  p_changed_by text,
  p_reason text default '업무량 확인 후 담당자 배정'
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare v_row public.inquiries; v_from text; v_action text;
begin
  select * into v_row from public.inquiries where id::text=p_inquiry_id for update;
  if not found then raise exception 'inquiry not found: %', p_inquiry_id; end if;
  if v_row.deleted_at is not null then raise exception 'trashed inquiry cannot be assigned'; end if;
  v_from := coalesce(v_row.assigned_to, '미배정');
  v_action := case when v_row.assigned_to is null then 'assign' else 'reassign' end;
  if v_action='reassign' and nullif(trim(p_reason),'') is null then
    raise exception 'reassignment reason is required';
  end if;
  update public.inquiries set
    assigned_to=p_to, assigned_at=now(), assigned_by=p_changed_by,
    inquiry_status=case when inquiry_status in ('접수','신규') then '배정완료' else inquiry_status end
  where id::text=p_inquiry_id returning * into v_row;
  insert into public.crm_inquiry_assignment_history
    (inquiry_id,from_assignee,to_assignee,changed_by,reason,action)
  values (p_inquiry_id,v_from,p_to,p_changed_by,coalesce(nullif(trim(p_reason),''),'업무량 확인 후 담당자 배정'),v_action);
  return v_row;
end $$;

create or replace function public.crm_inquiry_unassign(
  p_inquiry_id text, p_changed_by text, p_reason text
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare v_row public.inquiries; v_from text;
begin
  if nullif(trim(p_reason),'') is null then raise exception 'unassignment reason is required'; end if;
  select * into v_row from public.inquiries where id::text=p_inquiry_id for update;
  if not found then raise exception 'inquiry not found: %', p_inquiry_id; end if;
  v_from := coalesce(v_row.assigned_to,'미배정');
  update public.inquiries set assigned_to=null,assigned_at=null,assigned_by=null,
    inquiry_status=case when first_response_at is null then '접수' else inquiry_status end
  where id::text=p_inquiry_id returning * into v_row;
  insert into public.crm_inquiry_assignment_history
    (inquiry_id,from_assignee,to_assignee,changed_by,reason,action)
  values (p_inquiry_id,v_from,'미배정',p_changed_by,p_reason,'unassign');
  return v_row;
end $$;

create or replace function public.crm_inquiry_status(
  p_inquiry_id text, p_status text, p_changed_by text, p_reason text
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare v_row public.inquiries;
begin
  if nullif(trim(p_reason),'') is null then raise exception 'status reason is required'; end if;
  update public.inquiries set inquiry_status=p_status,
    hold_reason=case when p_status='보류' then p_reason else hold_reason end,
    held_at=case when p_status='보류' then now() else held_at end
  where id::text=p_inquiry_id and deleted_at is null returning * into v_row;
  if not found then raise exception 'active inquiry not found: %', p_inquiry_id; end if;
  return v_row;
end $$;

create or replace function public.crm_inquiry_trash(
  p_inquiry_id text, p_deleted_by text, p_delete_reason text, p_delete_note text default null
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare v_row public.inquiries; v_now timestamptz:=clock_timestamp();
begin
  if p_delete_reason not in ('중복 문의','테스트 문의','스팸','잘못된 연락처','관련 없는 문의','기타') then
    raise exception 'invalid delete reason';
  end if;
  select * into v_row from public.inquiries where id::text=p_inquiry_id for update;
  if not found then raise exception 'inquiry not found: %', p_inquiry_id; end if;
  update public.inquiries set
    trash_snapshot=jsonb_build_object('status',inquiry_status,'assigned_to',assigned_to,'assigned_at',assigned_at),
    valid_inquiry=false,deleted_at=v_now,deleted_by=p_deleted_by,delete_reason=p_delete_reason,
    delete_note=p_delete_note,purge_at=v_now+interval '30 days',
    archive_protected=(deal_id is not null)
  where id::text=p_inquiry_id returning * into v_row;
  return v_row;
end $$;

create or replace function public.crm_inquiry_restore(
  p_inquiry_id text, p_restored_by text
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare v_row public.inquiries;
begin
  update public.inquiries set
    valid_inquiry=true,deleted_at=null,deleted_by=null,delete_reason=null,delete_note=null,purge_at=null,
    restored_at=now(),restored_by=p_restored_by,archive_protected=false
  where id::text=p_inquiry_id and deleted_at is not null returning * into v_row;
  if not found then raise exception 'trashed inquiry not found: %', p_inquiry_id; end if;
  return v_row;
end $$;

create or replace function public.crm_inquiry_duplicate(
  p_inquiry_id text, p_resolution text, p_target_inquiry_id text default null
) returns public.inquiries
language plpgsql security definer set search_path=public as $$
declare v_row public.inquiries;
begin
  if p_resolution not in ('linked','keep_separate') then raise exception 'invalid duplicate resolution'; end if;
  if p_resolution='linked' and p_target_inquiry_id is null then raise exception 'target inquiry is required'; end if;
  update public.inquiries set duplicate_resolution=p_resolution,
    duplicate_of_inquiry_id=case when p_resolution='linked' then p_target_inquiry_id else null end,
    duplicate_reviewed_at=now()
  where id::text=p_inquiry_id and deleted_at is null returning * into v_row;
  if not found then raise exception 'active inquiry not found: %', p_inquiry_id; end if;
  return v_row;
end $$;

create or replace function public.crm_inquiry_purge(
  p_inquiry_id text
) returns boolean
language plpgsql security definer set search_path=public as $$
declare v_count integer;
begin
  -- 영업기회로 전환된 원본은 유입 이력 보존을 위해 물리 삭제하지 않는다.
  delete from public.crm_inquiry_assignment_history where inquiry_id=p_inquiry_id
    and exists (select 1 from public.inquiries i where i.id::text=p_inquiry_id and i.deal_id is null and not i.archive_protected);
  delete from public.inquiries where id::text=p_inquiry_id and deleted_at is not null
    and deal_id is null and not archive_protected;
  get diagnostics v_count = row_count;
  return v_count=1;
end $$;

create or replace function public.crm_purge_expired_inquiries()
returns integer
language plpgsql security definer set search_path=public as $$
declare v_ids text[]; v_count integer;
begin
  select coalesce(array_agg(id::text),'{}'::text[]) into v_ids
  from public.inquiries
  where deleted_at is not null and purge_at <= now() and deal_id is null and not archive_protected;
  delete from public.crm_inquiry_assignment_history where inquiry_id=any(v_ids);
  delete from public.inquiries where id::text=any(v_ids);
  get diagnostics v_count = row_count;
  return v_count;
end $$;

grant execute on function public.crm_inquiry_assign(text,text,text,text) to authenticated;
grant execute on function public.crm_inquiry_unassign(text,text,text) to authenticated;
grant execute on function public.crm_inquiry_status(text,text,text,text) to authenticated;
grant execute on function public.crm_inquiry_trash(text,text,text,text) to authenticated;
grant execute on function public.crm_inquiry_restore(text,text) to authenticated;
grant execute on function public.crm_inquiry_duplicate(text,text,text) to authenticated;
grant execute on function public.crm_inquiry_purge(text) to authenticated;

commit;

-- pg_cron이 이미 활성화된 프로젝트에서만 매일 12:15(KST, 03:15 UTC)에 자동 정리 작업을 등록한다.
-- Supabase 프로젝트가 UTC cron을 사용하므로 실제 실행시각은 한국시간 정오 12:15이다.
do $$
begin
  if exists(select 1 from pg_extension where extname='pg_cron') then
    execute $cron$
      select cron.schedule(
        'crm-purge-expired-inquiries',
        '15 3 * * *',
        'select public.crm_purge_expired_inquiries();'
      )
      where not exists (
        select 1 from cron.job where jobname='crm-purge-expired-inquiries'
      )
    $cron$;
  end if;
end $$;
