'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const follow=require('../../inquiry-followup/20260906/build.cjs');
const trash=require('../../inquiry-trash-restore/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const twentyOne=follow.twentyOne;
const twentyTwo=`CHECK (operation = ANY (ARRAY['opportunity_work_set'::text, 'inquiry_assign'::text, 'service_change'::text, 'inquiry_unassign'::text, 'favorite_set'::text, 'opportunity_touch'::text, 'next_action'::text, 'activity'::text, 'quote_version'::text, 'next_action_complete'::text, 'stage_check'::text, 'transition'::text, 'close'::text, 'amount'::text, 'waiting_context'::text, 'inquiry_reclassify'::text, 'inquiry_status'::text, 'inquiry_trash'::text, 'inquiry_restore'::text, 'inquiry_purge'::text, 'inquiry_followup'::text, 'opportunity_create'::text]))`;
function one(text,needle,label){const n=text.split(needle).length-1;if(n!==1)throw Error(`${label} drift (${n})`);}
function helper(){return fs.readFileSync(path.join(dir,'helper.sql'),'utf8');}
function sourceFragment(){let text=trash.sourceFragment();const marker='d.stage_code,d.stage_raw,d.stage_group,d.brand,d.list_name,';one(text,marker,'deal work name projection');return text.replace(marker,"d.stage_code,d.stage_raw,d.stage_group,d.brand,d.list_name,d.list_fields->>'work_name' AS work_name,d.list_fields->>'work_name' AS work,");}
function adapter(){let text=follow.adapter();
 one(text,"'inquiry_followup']",'adapter operation list');text=text.replace("'inquiry_followup']","'inquiry_followup','opportunity_create']");
 const marker=' function normalize(operation,objectId,expectedVersion,payload){';one(text,marker,'adapter normalize marker');
 const create=` function normalizeCreate(objectId,payload){
  const allowed=['surface','site_id','name','work_name','work_type','primaryWork','workItems','workScopeType','workSummary','primary_work','work_items','work_scope_type','work_summary','brand','owner','amount','address','reason','reason_source','origin','at','gj','office_phone','office_email','manager_name','manager_mobile','manager_role','person_key','contact_started_at','source_opportunity_id','origin_source','client_ref'];
  if(Object.keys(payload).some(k=>!allowed.includes(k))||!['pc','mobile'].includes(payload.surface))fail('OPPORTUNITY_CREATE_INTENT_NOT_CONNECTED');
  const primary=payload.primary_work??payload.primaryWork,items=payload.work_items??payload.workItems,scope=payload.work_scope_type??payload.workScopeType,summary=payload.work_summary??payload.workSummary;
  if(payload.primary_work!==undefined&&payload.primaryWork!==undefined&&payload.primary_work!==payload.primaryWork)fail('WORK_ALIAS_CONFLICT');
  if(payload.work_items!==undefined&&payload.workItems!==undefined&&JSON.stringify(payload.work_items)!==JSON.stringify(payload.workItems))fail('WORK_ALIAS_CONFLICT');
  if(payload.work_scope_type!==undefined&&payload.workScopeType!==undefined&&payload.work_scope_type!==payload.workScopeType)fail('WORK_ALIAS_CONFLICT');
  if(payload.work_summary!==undefined&&payload.workSummary!==undefined&&payload.work_summary!==payload.workSummary)fail('WORK_ALIAS_CONFLICT');
  if(!UUID.test(objectId)||typeof payload.client_ref!=='string'||!payload.client_ref.trim()||typeof payload.name!=='string'||!payload.name.trim()||payload.name.length>300||typeof payload.work_name!=='string'||!payload.work_name.trim()||payload.work_name.length>500||typeof payload.work_type!=='string'||!payload.work_type.trim()||payload.work_type.length>200||typeof primary!=='string'||!primary.trim()||primary.length>100||!Array.isArray(items)||items.length<1||items.length>30||items.some(x=>typeof x!=='string'||!x.trim()||x.length>100)||new Set(items).size!==items.length||!items.includes(primary)||scope!==(items.length===1?'single':'multi')||typeof summary!=='string'||!summary.trim()||summary.length>2000)fail('INVALID_OPPORTUNITY_CREATE');
  if(!['POUR솔루션','아파트스퀘어','석민이앤씨','기술자문'].includes(payload.brand)||typeof payload.owner!=='string'||!payload.owner.trim()||payload.owner.length>100||typeof payload.reason!=='string'||payload.reason.trim().length<5||payload.reason.length>2000||payload.origin!==undefined&&payload.origin!==payload.brand||payload.source_opportunity_id!=null||payload.origin_source!==undefined&&payload.origin_source!=='direct')fail('OPPORTUNITY_CREATE_INTENT_NOT_CONNECTED');
  if(payload.amount!=null&&(!Number.isSafeInteger(payload.amount)||payload.amount<0)||payload.address!=null&&(typeof payload.address!=='string'||payload.address.length>1000)||payload.reason_source!=null&&(typeof payload.reason_source!=='string'||payload.reason_source.length>200)||payload.office_email!=null&&(typeof payload.office_email!=='string'||payload.office_email.length>320)||payload.site_id!=null&&!UUID.test(payload.site_id))fail('INVALID_OPPORTUNITY_CREATE');
  const office=String(payload.office_phone||'').replace(/[^0-9]/g,''),mobile=String(payload.manager_mobile||'').replace(/[^0-9]/g,'');
  if(office.length<8||office.length>20||mobile.length<10||mobile.length>20||typeof payload.manager_name!=='string'||!payload.manager_name.trim()||payload.manager_name.length>200||payload.manager_role!=='관리소장'||payload.person_key!=='mobile:'+mobile)fail('INVALID_CONTACT_IDENTITY');
  return Object.freeze({surface:payload.surface,...(payload.site_id?{site_id:payload.site_id}:{}),name:payload.name.trim(),work_name:payload.work_name.trim(),work_type:payload.work_type.trim(),primary_work:primary.trim(),work_items:items.slice(),work_scope_type:scope,work_summary:summary.trim(),brand:payload.brand,owner:payload.owner.trim(),...(payload.amount==null?{}:{amount:payload.amount}),...(payload.address&&payload.address.trim()?{address:payload.address.trim()}:{}),reason:payload.reason.trim(),...(payload.reason_source&&payload.reason_source.trim()?{reason_source:payload.reason_source.trim()}:{}),office_phone:office,...(payload.office_email&&payload.office_email.trim()?{office_email:payload.office_email.trim()}:{}),manager_name:payload.manager_name.trim(),manager_mobile:mobile,manager_role:'관리소장',person_key:'mobile:'+mobile,client_ref:payload.client_ref.trim()});
 }
`;
 text=text.replace(marker,create+marker);
 const sentinel="['inquiry_assign','inquiry_unassign','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup','favorite_set','opportunity_touch'].includes(operation)";one(text,sentinel,'adapter sentinel');text=text.replace(sentinel,"['inquiry_assign','inquiry_unassign','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup','opportunity_create','favorite_set','opportunity_touch'].includes(operation)");
 const dispatch="else if(operation==='inquiry_followup')normalized=normalizeInquiryFollowup(objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);";one(text,dispatch,'adapter dispatch');text=text.replace(dispatch,"else if(operation==='inquiry_followup')normalized=normalizeInquiryFollowup(objectId,payload);else if(operation==='opportunity_create')normalized=normalizeCreate(objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);");
 const ack="  if(command.operation==='opportunity_create'&&(!UUID.test(ack.new_opportunity_id)||!UUID.test(ack.site_id)||!UUID.test(ack.owner_id)||!UUID.test(ack.contact_id)||!UUID.test(ack.contact_assignment_id)||!UUID.test(ack.activity_id)||(command.payload.surface==='mobile'?!UUID.test(ack.next_action_id):ack.next_action_id!==null)||!UUID.test(ack.audit_event_id)||ack.version!==1||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');\n";one(text,'  return ack;}','adapter ACK return');return text.replace('  return ack;}',ack+'  return ack;}');
}
function overlay(){let text=follow.overlay();
 const connected="'inquiry_followup']";one(text,connected,'overlay connected');text=text.replace(connected,"'inquiry_followup','opportunity_create']");
 const state='followupIntent=false;const versions';one(text,state,'overlay state');text=text.replace(state,'followupIntent=false,createSurface=null,createOwnerOverride=null;const versions');
 const rows="  function applyFollowupAck(q){for(const rows of inquiryRows())for(const i of rows)if(String(i.id||i.inquiry_id||i.key)===String(q.object_id))for(const x of [i,i.raw].filter(Boolean)){x.next_action_date=x.nextActionDate=x.due=q.ack.next_action_date;x.updated_at=q.ack.updated_at;}}\n";one(text,rows,'overlay ACK insertion');text=text.replace(rows,rows+"  function applyCreateAck(q){const a=q.ack,ref=q.payload.client_ref;versions.set(a.new_opportunity_id,1);for(const rows of [root.B&&root.B.deals,root.DEALS])if(Array.isArray(rows))for(const d of rows)if(String(d.id||d.opportunity_id)===String(ref)){d.id=d.opportunity_id=d.server_id=a.new_opportunity_id;d.site_id=a.site_id;d.owner_id=a.owner_id;d.contact_id=a.contact_id;d.version=1;if(q.payload.owner)d.assignee=d.rep=q.payload.owner;if(q.payload.surface==='mobile'&&d.nextAction)d.nextAction.id=a.next_action_id;}}\n");
 const sync="if(q.operation==='inquiry_followup')applyFollowupAck(q);";one(text,sync,'overlay ACK sync');text=text.replace(sync,sync+"if(q.operation==='opportunity_create')applyCreateAck(q);");
 const push='root.pushWrite=function(op,payload){';one(text,push,'overlay push');text=text.replace(push,"root.pushWrite=function(op,payload){if(createSurface==='mobile'&&companion.has(op))return 'absorbed:'+op;if(op==='opportunity_create'&&!createSurface)throw error('OPPORTUNITY_CREATE_INTENT_NOT_CONNECTED');");
 const enqueue="const id=idFor(op,payload);const expected=op.startsWith('inquiry_')||personal.has(op)?0:versionFor(id,payload);const q=root.Phase1.queue.enqueue(op,id,expected,payload);";one(text,enqueue,'overlay enqueue');text=text.replace(enqueue,"let id=idFor(op,payload),expected;if(op==='opportunity_create'){const requestId=root.crypto.randomUUID(),rows=root.DEALS||[],last=rows[rows.length-1],clientRef=payload.client_ref||(last&&last.id);if(!clientRef)throw error('CREATE_CLIENT_REF_REQUIRED');payload={...payload,surface:createSurface,client_ref:String(clientRef),...(createOwnerOverride?{owner:createOwnerOverride}:{})};id=requestId;expected=0;var q=root.Phase1.queue.enqueue(op,id,expected,payload,requestId);}else{expected=op.startsWith('inquiry_')||personal.has(op)?0:versionFor(id,payload);var q=root.Phase1.queue.enqueue(op,id,expected,payload);}");
 const wrapper="  if(typeof root.applyTodayPostponeM==='function'){const original=root.applyTodayPostponeM;root.applyTodayPostponeM=function(){const t=root.G&&root.G._today&&root.G._today[root.G.execTask],previous=followupIntent;followupIntent=!!(t&&t.kind==='inquiry');try{return original.apply(this,arguments);}finally{followupIntent=previous;}};}";one(text,wrapper,'overlay create wrapper marker');
 const additions=`
  function wrapCreate(name,surface){if(typeof root[name]!=='function')return;const original=root[name];root[name]=function(){if(surface==='mobile'&&root.G&&root.G.user&&root.G.user.role==='viewer'){if(typeof root.toast==='function')root.toast('상담 역할은 영업담당자를 지정할 수 없어 직접 영업등록을 사용할 수 없습니다.');return false;}const priorSurface=createSurface,priorOwner=createOwnerOverride,before=new Set((root.DEALS||[]).map(d=>String(d.id)));createSurface=surface;createOwnerOverride=null;if(surface==='mobile'&&root.G&&root.G.user&&['admin','dual'].includes(root.G.user.role)){const select=root.document&&root.document.getElementById('powner');if(!select||!select.value){if(typeof root.toast==='function')root.toast('영업담당자를 선택해 주세요');createSurface=priorSurface;return false;}createOwnerOverride=select.value;}try{const result=original.apply(this,arguments);if(createOwnerOverride)for(const d of root.DEALS||[])if(!before.has(String(d.id)))d.rep=d.assignee=createOwnerOverride;return result;}finally{createSurface=priorSurface;createOwnerOverride=priorOwner;}};}
  wrapCreate('saveNewDeal','pc');wrapCreate('addProspect','mobile');
  if(typeof root.rProspect==='function'){const original=root.rProspect;root.rProspect=function(){const result=original.apply(this,arguments),user=root.G&&root.G.user;if(user&&['admin','dual'].includes(user.role)&&root.document&&!root.document.getElementById('powner')){const submit=root.document.querySelector('button[data-gate="nd"]'),box=root.document.createElement('div'),label=root.document.createElement('div'),select=root.document.createElement('select');box.id='powner-wrap';label.className='hint';label.textContent='영업담당자 *';select.id='powner';select.style.cssText='width:100%;margin:6px 0 10px;border:1px solid var(--line-2);border-radius:11px;padding:12px;font:inherit';const empty=root.document.createElement('option');empty.value='';empty.textContent='영업담당자를 선택해 주세요';select.appendChild(empty);for(const name of root.REP_INTERNAL||[]){const option=root.document.createElement('option');option.value=name;option.textContent=name;select.appendChild(option);}box.append(label,select);if(submit)submit.parentNode.insertBefore(box,submit);}return result;};}
  if(typeof root.render==='function'){const original=root.render;root.render=function(){const result=original.apply(this,arguments);if(root.G&&root.G.user&&root.G.user.role==='viewer'&&root.document){for(const button of root.document.querySelectorAll('button')){const click=button.getAttribute('onclick')||'';if(click.includes("G.tab='find'"))button.remove();}}return result;};}
`;
 text=text.replace(wrapper,wrapper+additions);
 const mobile="primaryWork:d.primary_work||'',workItems:d.work_items||[],workScopeType:d.work_scope_type||'',workSummary:d.work_summary||'',";one(text,mobile,'mobile work mapping');text=text.replace(mobile,"work:d.work_name||'',work_name:d.work_name||'',"+mobile);
 return text;
}
function applySql(){return `SET crm.opportunity_create_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_user<>'postgres' OR current_setting('crm.opportunity_create_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu'
 OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL
 OR to_regprocedure('crm_security.crm_inquiry_followup_command_v1(uuid,uuid,jsonb)') IS NULL
 OR to_regprocedure('crm_security.crm_operational_source_fragment_v1(text,uuid,integer)') IS NULL
 OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_followup_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL
 OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_opportunity_create_20260906(text,uuid,integer)') IS NOT NULL
 OR to_regprocedure('crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)') IS NOT NULL
 OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twentyOne}$expected$
 THEN RAISE EXCEPTION 'opportunity create prerequisite drift';END IF;END $guard$;
LOCK TABLE crm_security.command_receipts IN ACCESS EXCLUSIVE MODE;
ALTER FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2_inquiry_followup_20260906;
ALTER FUNCTION public.crm_write_command_v2_inquiry_followup_20260906(uuid,text,uuid,integer,jsonb) SET SCHEMA crm_security;
REVOKE EXECUTE ON FUNCTION crm_security.crm_write_command_v2_inquiry_followup_20260906(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;
ALTER FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) RENAME TO crm_operational_source_fragment_pre_opportunity_create_20260906;
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_pre_opportunity_create_20260906(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;
ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup','opportunity_create'));
${helper()}
${sourceFragment()}
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.crm_write_command_v2(p_request_id uuid,p_operation text,p_object_id uuid,p_expected_version integer,p_payload jsonb) RETURNS jsonb
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path='' AS $fn$ BEGIN
 IF p_operation='opportunity_create' THEN IF p_expected_version IS DISTINCT FROM 0 OR p_object_id IS DISTINCT FROM p_request_id THEN RAISE EXCEPTION 'invalid create sentinel' USING ERRCODE='22023';END IF;RETURN crm_security.crm_opportunity_create_command_v1(p_request_id,p_object_id,p_payload);END IF;
 RETURN crm_security.crm_write_command_v2_inquiry_followup_20260906(p_request_id,p_operation,p_object_id,p_expected_version,p_payload);END $fn$;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
DO $post$ BEGIN IF has_function_privilege('anon','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR NOT has_function_privilege('authenticated','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE') OR has_function_privilege('service_role','public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)','EXECUTE')
 OR has_function_privilege('authenticated','crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)','EXECUTE')
 OR has_function_privilege('authenticated','crm_security.crm_site_common_key_v1(text)','EXECUTE')
 OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twentyTwo}$expected$
 THEN RAISE EXCEPTION 'opportunity create post-apply drift';END IF;END $post$;COMMIT;`}
function rollbackSql(){return `SET crm.opportunity_create_ref='rprechiaglyjaydkmxsu';
BEGIN;SET LOCAL search_path=pg_catalog;SET LOCAL lock_timeout='3s';SET LOCAL statement_timeout='60s';
DO $guard$ BEGIN IF current_setting('crm.opportunity_create_ref',true) IS DISTINCT FROM 'rprechiaglyjaydkmxsu'
 OR to_regprocedure('public.crm_write_command_v2(uuid,text,uuid,integer,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_write_command_v2_inquiry_followup_20260906(uuid,text,uuid,integer,jsonb)') IS NULL
 OR to_regprocedure('crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)') IS NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_opportunity_create_20260906(text,uuid,integer)') IS NULL
 OR EXISTS(SELECT 1 FROM crm_security.command_receipts WHERE operation='opportunity_create') OR EXISTS(SELECT 1 FROM crm_security.audit_events WHERE action='opportunity_create')
 OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twentyTwo}$expected$
 THEN RAISE EXCEPTION 'opportunity create rollback blocked: drift or runtime create evidence exists';END IF;END $guard$;
DROP FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb);DROP FUNCTION crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb);
DROP FUNCTION crm_security.crm_site_mobile_key_v1(text);DROP FUNCTION crm_security.crm_site_pc_key_v1(text);DROP FUNCTION crm_security.crm_site_common_key_v1(text);
DROP FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer);
ALTER FUNCTION crm_security.crm_operational_source_fragment_pre_opportunity_create_20260906(text,uuid,integer) RENAME TO crm_operational_source_fragment_v1;
REVOKE EXECUTE ON FUNCTION crm_security.crm_operational_source_fragment_v1(text,uuid,integer) FROM PUBLIC,anon,authenticated,service_role;
ALTER FUNCTION crm_security.crm_write_command_v2_inquiry_followup_20260906(uuid,text,uuid,integer,jsonb) RENAME TO crm_write_command_v2;
ALTER FUNCTION crm_security.crm_write_command_v2(uuid,text,uuid,integer,jsonb) SET SCHEMA public;
REVOKE EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) FROM PUBLIC,anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION public.crm_write_command_v2(uuid,text,uuid,integer,jsonb) TO authenticated;
ALTER TABLE crm_security.command_receipts DROP CONSTRAINT command_receipts_operation_check;
ALTER TABLE crm_security.command_receipts ADD CONSTRAINT command_receipts_operation_check CHECK(operation IN ('opportunity_work_set','inquiry_assign','service_change','inquiry_unassign','favorite_set','opportunity_touch','next_action','activity','quote_version','next_action_complete','stage_check','transition','close','amount','waiting_context','inquiry_reclassify','inquiry_status','inquiry_trash','inquiry_restore','inquiry_purge','inquiry_followup'));
DO $post$ BEGIN IF to_regprocedure('crm_security.crm_write_command_v2_inquiry_followup_20260906(uuid,text,uuid,integer,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)') IS NOT NULL OR to_regprocedure('crm_security.crm_operational_source_fragment_pre_opportunity_create_20260906(text,uuid,integer)') IS NOT NULL
 OR (SELECT pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid='crm_security.command_receipts'::regclass AND conname='command_receipts_operation_check') IS DISTINCT FROM $expected$${twentyOne}$expected$
 THEN RAISE EXCEPTION 'opportunity create rollback verification drift';END IF;END $post$;COMMIT;`}
function build(){const apply=applySql(),rollback=rollbackSql(),a=adapter(),o=overlay();fs.writeFileSync(path.join(dir,'staging-apply-after-reachable-bundle.sql'),apply);fs.writeFileSync(path.join(dir,'rollback-before-runtime-create.sql'),rollback);fs.writeFileSync(path.join(dir,'operational-adapter.candidate.js'),a);fs.writeFileSync(path.join(dir,'operational-overlay.candidate.js'),o);const names=['helper.sql','build.cjs','db.test.cjs','contract.test.cjs','ui.test.cjs','review.md','staging-apply-after-reachable-bundle.sql','rollback-before-runtime-create.sql','operational-adapter.candidate.js','operational-overlay.candidate.js'];const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'LOCAL_CHAIN_CANDIDATE_AFTER_REACHABLE_BUNDLE_NOT_APPLIED',classification:'DERIVED_SAFE_LOCAL_CANDIDATE',operation:'opportunity_create',intent:'direct_pc_mobile_only',prerequisite:'reachable-operations-bundle/20260906',site_identity:{canonical:'common exact key: remove bracket tags, whitespace and 아파트; lowercase',broad_match:'PC/mobile-only variants require explicit site selection',substring_match:'forbidden',collision:'409'},creator_owner_matrix:{rep:'approved rep target',admin:'approved rep target',branch:'self only',consultation:'denied'},surface_side_effects:{pc:{activity:1,next_action:0},mobile:{activity:1,next_action:1}},absorbed_children:['mobile activity','mobile next_action'],blocked_meanings:['inquiry_promote','technical_inquiry_transfer','expansion_convert','semantic_duplicate_auto_merge'],rollback:'PRE_RUNTIME_CREATE_USE_ONLY',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(names.map(n=>[n,sha(fs.readFileSync(path.join(dir,n)))])),source_sha256:{'crm.html':sha(fs.readFileSync(path.join(root,'crm.html'))),'mobile.html':sha(fs.readFileSync(path.join(root,'mobile.html'))),'sql/reachable-operations-bundle/20260906/manifest.json':sha(fs.readFileSync(path.join(root,'sql/reachable-operations-bundle/20260906/manifest.json'))),'docs/operational-cutover-20260906/pipeline-lifecycle-contracts.md':sha(fs.readFileSync(path.join(root,'docs/operational-cutover-20260906/pipeline-lifecycle-contracts.md'))),'docs/operational-cutover-20260906/opportunity-create-resolution-20260906.json':sha(fs.readFileSync(path.join(root,'docs/operational-cutover-20260906/opportunity-create-resolution-20260906.json')))}};fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={applySql,rollbackSql,adapter,overlay,sourceFragment,build,twentyOne,twentyTwo};
