'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const personal=require('../../personal-state-compat/20260906/build.cjs'),bundle=require('../../reachable-operations-bundle/20260906/build.cjs'),create=require('./build.cjs'),s=require('../../../scripts/crm-phase1.cjs');
const rid=n=>`f6090600-0111-4000-8000-${String(n).padStart(12,'0')}`;
async function setup(){const db=await personal.setup();await db.exec(bundle.compose('apply',{localPersonalCandidate:true}));await db.exec(create.applySql());return db;}
async function userName(db,index){return (await db.query('SELECT name FROM public.users WHERE user_id=$1',[s.fixture.mapped[index].user_id])).rows[0].name;}
async function write(db,index,payload,request){await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[index].auth_uid}';`);return (await db.query("SELECT public.crm_write_command_v2($1,'opportunity_create',$1,0,$2) a",[request,JSON.stringify(payload)])).rows[0].a;}
async function payload(db,index,surface='pc',suffix='A'){const owner=await userName(db,index);return{surface,client_ref:`new-${suffix}`,name:`TEST 신규 아파트 ${suffix}`,work_name:`TEST 공종 ${suffix}`,work_type:`TEST 공종 ${suffix}`,primary_work:'방수',work_items:['방수'],work_scope_type:'single',work_summary:`TEST 방수 ${suffix}`,brand:'아파트스퀘어',owner,amount:123000,address:`TEST 주소 ${suffix}`,reason:'신규 영업 등록 시험 사유',office_phone:'0551234567',office_email:`${suffix.toLowerCase()}@example.invalid`,manager_name:`TEST 소장 ${suffix}`,manager_mobile:`0109000${String(suffix.charCodeAt(0)).padStart(4,'0')}`,manager_role:'관리소장',person_key:`mobile:0109000${String(suffix.charCodeAt(0)).padStart(4,'0')}`};}
test('PC/mobile direct create is atomic, scoped and idempotent while unsafe role/site meanings fail closed',async()=>{const db=await setup();try{
 const pc=await payload(db,0,'pc','A'),before={sites:(await db.query('SELECT count(*)::int n FROM public.sites')).rows[0].n,deals:(await db.query('SELECT count(*)::int n FROM public.deals')).rows[0].n};
 const ack=await write(db,0,pc,rid(1));assert.equal(ack.next_action_id,null);assert.equal(ack.version,1);assert.equal((await write(db,0,pc,rid(1))).replayed,true);
 assert.equal((await db.query('SELECT count(*)::int n FROM public.sites')).rows[0].n,before.sites+1);assert.equal((await db.query('SELECT count(*)::int n FROM public.deals')).rows[0].n,before.deals+1);
 assert.equal((await db.query('SELECT count(*)::int n FROM public.activities WHERE deal_id=$1',[ack.new_opportunity_id])).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM public.next_actions WHERE deal_id=$1',[ack.new_opportunity_id])).rows[0].n,0);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.audit_events WHERE deal_id=$1 AND action='opportunity_create'",[ack.new_opportunity_id])).rows[0].n,1);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE request_id=$1 AND operation='opportunity_create'",[rid(1)])).rows[0].n,1);
 await assert.rejects(write(db,0,{...pc,reason:'변경된 신규 영업 등록 사유'},rid(1)),e=>e.code==='PT409');
 const mobile=await payload(db,0,'mobile','B'),mAck=await write(db,0,mobile,rid(2));assert.ok(mAck.next_action_id);assert.equal((await db.query('SELECT count(*)::int n FROM public.activities WHERE deal_id=$1',[mAck.new_opportunity_id])).rows[0].n,1);assert.equal((await db.query('SELECT count(*)::int n FROM public.next_actions WHERE deal_id=$1',[mAck.new_opportunity_id])).rows[0].n,1);
 await assert.rejects(write(db,0,{...mobile,client_ref:'new-B2'},rid(3)),e=>e.code==='PT409');
 const beforeExact=(await db.query('SELECT count(*)::int n FROM public.sites')).rows[0].n,existingExact=await write(db,0,{...await payload(db,0,'pc','G'),name:'[지역] TEST 아파트 A'},rid(8));assert.equal(existingExact.site_id,s.uid(2,1));assert.equal((await db.query('SELECT count(*)::int n FROM public.sites')).rows[0].n,beforeExact);
 await assert.rejects(write(db,0,{...await payload(db,0,'pc','H'),name:'TEST 아파트 A 현장'},rid(9)),e=>e.code==='PT409');
 const consultation=await payload(db,2,'mobile','C');await assert.rejects(write(db,2,consultation,rid(4)),e=>e.code==='42501');
 const branch=await payload(db,3,'mobile','D'),branchAck=await write(db,3,branch,rid(5));assert.equal(branchAck.owner_id,s.fixture.mapped[3].user_id);assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.object_scope WHERE deal_id=$1 AND user_id=$2',[branchAck.new_opportunity_id,s.fixture.mapped[3].user_id])).rows[0].n,1);
 const repName=await userName(db,0);await assert.rejects(write(db,3,{...await payload(db,3,'mobile','E'),owner:repName},rid(6)),e=>e.code==='42501');
 const adminToRep=await write(db,4,{...await payload(db,4,'mobile','J'),owner:repName},rid(10));assert.equal(adminToRep.owner_id,s.fixture.mapped[0].user_id);assert.equal((await db.query('SELECT count(*)::int n FROM crm_security.object_scope WHERE deal_id=$1 AND user_id=$2',[adminToRep.new_opportunity_id,s.fixture.mapped[4].user_id])).rows[0].n,1);
 const existing=s.uid(2,1);await assert.rejects(write(db,0,{...await payload(db,0,'pc','F'),site_id:existing},rid(7)),e=>e.code==='PT409');
 await db.exec(`SET request.jwt.claim.sub='${s.mapping.accounts[0].auth_uid}';`);const read=(await db.query("SELECT public.crm_operational_source_v1('deal_core',null,100) a")).rows[0].a,created=read.items.find(x=>x.id===ack.new_opportunity_id);assert.equal(created.work_name,'TEST 공종 A');assert.equal(created.work,'TEST 공종 A');
 for(const fn of ['crm_opportunity_create_command_v1','crm_site_common_key_v1','crm_site_pc_key_v1','crm_site_mobile_key_v1'])for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query(`SELECT has_function_privilege($1,'crm_security.${fn}(${fn==='crm_opportunity_create_command_v1'?'uuid,uuid,jsonb':'text'})','EXECUTE') allowed`,[role])).rows[0].allowed,false);
 }finally{await db.close();}});
test('late audit failure rolls every created row back and migration rollback is pre-runtime only',async()=>{let db=await setup();try{
 const p=await payload(db,0,'pc','Z'),counts={sites:(await db.query('SELECT count(*)::int n FROM public.sites')).rows[0].n,deals:(await db.query('SELECT count(*)::int n FROM public.deals')).rows[0].n,contacts:(await db.query('SELECT count(*)::int n FROM public.contacts')).rows[0].n};
 await db.exec("CREATE FUNCTION pg_temp.fail_create_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='opportunity_create' THEN RAISE EXCEPTION 'injected';END IF;RETURN NEW;END$$;CREATE TRIGGER fail_create_audit BEFORE INSERT ON crm_security.audit_events FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_create_audit();");
 await assert.rejects(write(db,0,p,rid(20)),/injected/);for(const [table,n] of Object.entries(counts))assert.equal((await db.query(`SELECT count(*)::int n FROM public.${table}`)).rows[0].n,n);assert.equal((await db.query("SELECT count(*)::int n FROM crm_security.command_receipts WHERE operation='opportunity_create'")).rows[0].n,0);
 }finally{await db.close();}
 db=await setup();try{await db.exec(create.rollbackSql());assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_opportunity_create_command_v1(uuid,uuid,jsonb)') IS NULL dropped")).rows[0].dropped,true);assert.equal((await db.query("SELECT to_regprocedure('crm_security.crm_inquiry_followup_command_v1(uuid,uuid,jsonb)') IS NOT NULL kept")).rows[0].kept,true);}finally{await db.close();}
 db=await setup();try{await write(db,0,await payload(db,0,'pc','Y'),rid(21));await assert.rejects(db.exec(create.rollbackSql()),/runtime create evidence exists/);}finally{await db.close();}
});
