'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Module=require('node:module'),build=require('./build.cjs');
function load(text,name){const m=new Module(name);m._compile(text,name+'.js');return m.exports;}
const uuid=n=>`f6090600-0112-4000-8000-${String(n).padStart(12,'0')}`;
function basePayload(owner,ref){return{client_ref:ref,name:'TEST 신규 아파트 UI',work_name:'TEST UI 공종',work_type:'TEST UI 공종',primaryWork:'방수',workItems:['방수'],workScopeType:'single',workSummary:'TEST UI 방수',brand:'아파트스퀘어',owner,amount:1000,address:'TEST UI 주소',reason:'신규 영업 등록 UI 시험',office_phone:'055-123-4567',manager_name:'TEST UI 소장',manager_mobile:'010-8888-7777',manager_role:'관리소장',person_key:'mobile:01088887777'};}
function fixture(){const adapter=load(build.adapter(),'create-adapter'),overlay=load(build.overlay(),'create-overlay'),queued=[],listeners={};let seq=0;const pc=[],mobile=[];
 const root={OperationalAdapter:adapter,TOKEN:'jwt',ME:{id:'u'},WRITE_Q:[],B:{deals:pc},DEALS:mobile,console,crypto:{randomUUID:()=>uuid(++seq)},G:{user:{role:'rep'}},addEventListener:(n,f)=>{listeners[n]=f},document:{getElementById:()=>null,querySelectorAll:()=>[]},Phase1:{queue:{enqueue(op,id,version,payload,requestId){const c=adapter.normalize(op,id,version,payload),q={...c,payload:c.payload,request_id:requestId||uuid(++seq),status:'pending'};queued.push(q);return q;},list:()=>queued,flush:async()=>queued}},saveNewDeal(){const ref='pc-temp';this.B.deals.push({id:ref});this.pushWrite('opportunity_create',basePayload('TEST INTERNAL_REP',ref));},addProspect(){const ref='mobile-temp';this.DEALS.push({id:ref,nextAction:{}});const p=basePayload('TEST INTERNAL_REP',ref);this.pushWrite('activity',{opportunity_id:ref,type:'영업등록'});this.pushWrite('next_action',{opportunity_id:ref,type:'첫통화'});this.pushWrite('opportunity_create',p);}};
 overlay.install(root);return{root,queued,listeners,pc,mobile};}
test('PC create queues one parent command and hydrates the server UUID without a Next Action',()=>{const x=fixture();x.root.saveNewDeal();assert.equal(x.queued.length,1);const q=x.queued[0];assert.equal(q.operation,'opportunity_create');assert.equal(q.object_id,q.request_id);assert.equal(q.expected_version,0);assert.equal(q.payload.surface,'pc');q.status='done';q.ack={new_opportunity_id:uuid(20),site_id:uuid(21),owner_id:uuid(22),contact_id:uuid(23),contact_assignment_id:uuid(24),activity_id:uuid(25),next_action_id:null,audit_event_id:uuid(26),version:1};x.listeners['phase1:queue']();assert.equal(x.pc[0].id,uuid(20));assert.equal(x.pc[0].version,1);});
test('mobile child Activity/Next are absorbed into one create command and ACK hydrates its single Next UUID',()=>{const x=fixture();x.root.addProspect();assert.deepEqual(x.queued.map(q=>q.operation),['opportunity_create']);const q=x.queued[0];assert.equal(q.payload.surface,'mobile');q.status='done';q.ack={new_opportunity_id:uuid(30),site_id:uuid(31),owner_id:uuid(32),contact_id:uuid(33),contact_assignment_id:uuid(34),activity_id:uuid(35),next_action_id:uuid(36),audit_event_id:uuid(37),version:1};x.listeners['phase1:queue']();assert.equal(x.mobile[0].id,uuid(30));assert.equal(x.mobile[0].nextAction.id,uuid(36));});
test('consultation/viewer mobile direct create is denied before any command is queued',()=>{const x=fixture();x.root.G.user.role='viewer';assert.equal(x.root.addProspect(),false);assert.equal(x.queued.length,0);});
