'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const close=require('../../pipeline-close-won/20260906/build.cjs');
const dir=__dirname,root=path.resolve(dir,'../../..'),read=f=>fs.readFileSync(f,'utf8').replace(/\r\n?/g,'\n'),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const tx=body=>`-- LOCAL REVIEW CANDIDATE ONLY. Separate Staging approval is required.\nBEGIN;\n${body.trim()}\nCOMMIT;\n`;
function replaceOne(source,from,to,label){if(!source.includes(from))throw Error('expansion update build anchor missing: '+label);return source.replace(from,to);}
function adapter(){let source=close.adapter();
 source=replaceOne(source,"'attachment_prepare','attachment_complete']","'attachment_prepare','attachment_complete','expansion_pool_update']",'operation allowlist');
 source=replaceOne(source,' function normalizeClose(objectId,payload){',` function normalizeExpansionUpdate(objectId,payload){const allowed=['opportunity_id','source_opportunity_id','expansion_status','next_contact_at','last_contact_at','relationship_state','created_opportunity_id','need_note','updated_at'];if(Object.keys(payload).some(k=>!allowed.includes(k))||payload.opportunity_id!==objectId||payload.source_opportunity_id!==objectId||!['신규 대상','접촉 예정','관계 관리중','추가 니즈 확인','보류/휴면'].includes(payload.expansion_status)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(payload.next_contact_at)||payload.relationship_state!=='기존고객'||!(payload.created_opportunity_id==null||payload.created_opportunity_id==='')||!(payload.last_contact_at==null||typeof payload.last_contact_at==='string'&&payload.last_contact_at.length<=64)||!(payload.need_note==null||typeof payload.need_note==='string'&&payload.need_note.length<=4000)||typeof payload.updated_at!=='string'||payload.updated_at.length>64)fail('EXPANSION_UPDATE_INTENT_NOT_CONNECTED');return {expansion_status:payload.expansion_status,next_contact_at:payload.next_contact_at};}
 function normalizeClose(objectId,payload){`,'normalizer');
 source=replaceOne(source,"else if(operation==='attachment_prepare'||operation==='attachment_complete')normalized=normalizeAttachment(operation,objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);","else if(operation==='attachment_prepare'||operation==='attachment_complete')normalized=normalizeAttachment(operation,objectId,payload);else if(operation==='expansion_pool_update')normalized=normalizeExpansionUpdate(objectId,payload);else normalized=normalizeTrash(operation,objectId,payload);",'normalize switch');
 source=replaceOne(source,"  if(command.operation==='close'&&command.payload.outcome==='won'",`  if(command.operation==='expansion_pool_update'&&(ack.source_opportunity_id!==command.object_id||ack.previous_version!==command.expected_version||ack.version!==command.expected_version+1||ack.expansion_status!==command.payload.expansion_status||ack.next_contact_at!==command.payload.next_contact_at||!['status_change','next_contact_change','status_and_next_contact'].includes(ack.kind)||!UUID.test(ack.expansion_event_id)||!UUID.test(ack.audit_event_id)||typeof ack.actor_name!=='string'||typeof ack.server_at!=='string'))fail('ACK_CONTRACT_MISMATCH');
  if(command.operation==='close'&&command.payload.outcome==='won'`,'ACK');
 return source;
}
function overlay(){let source=close.overlay();
 source=replaceOne(source,"'opportunity_create','lineage_link'])","'opportunity_create','lineage_link','expansion_pool_update'])",'connected');
 source=replaceOne(source,'createSurface=null,createOwnerOverride=null;const versions=new Map(),seenAcks=new Set();','createSurface=null,createOwnerOverride=null,expansionIntent=false;const versions=new Map(),poolVersions=new Map(),seenAcks=new Set();','state');
 source=replaceOne(source,'  function applyPersonalAck(q){',`  function expansionVersionFor(id){let value=poolVersions.get(String(id));if(!Number.isSafeInteger(value)){for(const row of root.B&&root.B.expansion_pool||root.B&&root.B.expansionPool||[]){const source=String(row.source_deal_id||row.source_opportunity_id||row.sourceOpportunityId||row.id||'');if(source===String(id)&&Number.isSafeInteger(row.version)){value=row.version;poolVersions.set(String(id),value);break;}}}if(!Number.isSafeInteger(value)||value<1)throw error('EXPANSION_READ_VERSION_REQUIRED');return value;}
  function applyExpansionAck(q){const a=q.ack;poolVersions.set(String(q.object_id),a.version);const lists=[root.B&&root.B.expansion_pool,root.B&&root.B.expansionPool,root.LOCAL&&root.LOCAL.expansionPool].filter(Array.isArray);for(const rows of lists)for(const r of rows){const id=String(r.source_deal_id||r.source_opportunity_id||r.sourceOpportunityId||r.opportunity_id||r.id||'');if(id===String(q.object_id)){r.version=a.version;r.expansion_status=r.status=a.expansion_status;r.next_contact_at=r.nextContactAt=a.next_contact_at;r.updated_at=r.updatedAt=a.server_at;}}root.B=root.B||{};root.B.expansion_events=Array.isArray(root.B.expansion_events)?root.B.expansion_events:[];if(!root.B.expansion_events.some(e=>e.id===a.expansion_event_id))root.B.expansion_events.push({id:a.expansion_event_id,source_opportunity_id:q.object_id,kind:a.kind,note:a.kind==='status_change'?'상태 '+a.expansion_status:a.kind==='next_contact_change'?'다음 접촉 '+a.next_contact_at:'상태 '+a.expansion_status+' · 다음 접촉 '+a.next_contact_at,actor:a.actor_name,occurred_at:a.server_at,created_at:a.server_at});if(typeof root.paintExpansion==='function')root.paintExpansion();}
  function applyPersonalAck(q){`,'pool helpers');
 source=replaceOne(source,'if(Number.isSafeInteger(q.ack.version))versions.set(q.object_id,q.ack.version);','if(Number.isSafeInteger(q.ack.version)){if(q.operation===\'expansion_pool_update\')poolVersions.set(String(q.object_id),q.ack.version);else versions.set(q.object_id,q.ack.version);}extraAck(q);','version route');
 source=replaceOne(source,'  root.pushWrite=function(op,payload){',"  function extraAck(q){if(q.operation==='expansion_pool_update')applyExpansionAck(q);}\n  root.pushWrite=function(op,payload){",'ack hook');
 source=replaceOne(source,"if(op==='next_action'&&inquiryActionIntent==='set')","if(op==='expansion_pool_update'&&!expansionIntent)throw error('EXPANSION_UPDATE_INTENT_NOT_CONNECTED');if(op==='next_action'&&inquiryActionIntent==='set')",'named guard');
 source=replaceOne(source,"else{expected=op.startsWith('inquiry_')||personal.has(op)||(/^inquiry_/.test(payload&&payload.intent||''))?0:versionFor(id,payload);var q=root.Phase1.queue.enqueue(op,id,expected,payload);}","else{expected=op==='expansion_pool_update'?expansionVersionFor(id):op.startsWith('inquiry_')||personal.has(op)||(/^inquiry_/.test(payload&&payload.intent||''))?0:versionFor(id,payload);var q=root.Phase1.queue.enqueue(op,id,expected,payload);}",'pool version');
 source=replaceOne(source,"  if(typeof root.commitClose==='function')",`  function wrapExpansion(name,validate){if(typeof root[name]!=='function')return;const original=root[name];root[name]=function(id,value){if(!validate(value))throw error('EXPANSION_UPDATE_INTENT_NOT_CONNECTED');const prior=expansionIntent;expansionIntent=true;try{return original.apply(this,arguments);}finally{expansionIntent=prior;}};}
  wrapExpansion('expansionSetStatus',value=>['관리대상','접촉예정','관계관리','니즈확인','보류'].includes(value));
  wrapExpansion('expansionSetNext',value=>/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(String(value||'')));
  if(typeof root.commitClose==='function')`,'named wrappers');
 source=replaceOne(source,"inquiries:scoped.inquiries||[],expansion_pool:scoped.expansion_pool||[],expansionPool:scoped.expansion_pool||[],dups:[]","inquiries:scoped.inquiries||[],expansion_pool:scoped.expansion_pool||[],expansionPool:scoped.expansion_pool||[],expansion_events:scoped.expansion_events||[],dups:[]",'shell events');
 source=replaceOne(source,"async function scoped(){const response=await root.Phase1.read('operational',{limit:100});for(const d of response.data.deals||[])if(Number.isSafeInteger(d.version))versions.set(d.id,d.version);return response.data;}","async function scoped(){const response=await root.Phase1.read('operational',{limit:100});for(const d of response.data.deals||[])if(Number.isSafeInteger(d.version))versions.set(d.id,d.version);for(const x of response.data.expansion_pool||[])if(Number.isSafeInteger(x.version))poolVersions.set(String(x.source_deal_id||x.source_opportunity_id||x.id),x.version);return response.data;}",'scoped versions');
 source=replaceOne(source,'()=>{versions.clear();seenAcks.clear();}','()=>{versions.clear();poolVersions.clear();seenAcks.clear();}','identity reset');
 source=replaceOne(source,'return Object.freeze({versions,connected,versionFor,','return Object.freeze({versions,poolVersions,connected,versionFor,expansionVersionFor,','API');
 return source;
}
function transport(){let source=close.transport();
 source=replaceOne(source,"data:{contract_version:4,deals,inquiries,expansion_pool}","data:{contract_version:5,deals,inquiries,expansion_pool,expansion_events:expansion_pool.flatMap(x=>Array.isArray(x.events)?x.events:[])}",'event flattening');
 return source;
}
function applySql(){return tx(read(path.join(dir,'helper.sql')));}
function rollbackSql(){return tx(read(path.join(dir,'rollback-fragment.sql')));}
function build(){const generated={'staging-apply-after-close-won.sql':applySql(),'rollback-before-close-won.sql':rollbackSql(),'operational-adapter.candidate.js':adapter(),'operational-overlay.candidate.js':overlay(),'transport.candidate.js':transport()};for(const [name,value] of Object.entries(generated))fs.writeFileSync(path.join(dir,name),value);
 const own=['build.cjs','helper.sql','rollback-fragment.sql','contract.test.cjs','ui.test.cjs','db.test.cjs','review.md',...Object.keys(generated)];
 const sources=['sql/pipeline-close-won/20260906/manifest.json','crm.html','expansion-pool.js','expansion-flow.js','sql/20260905_expansion_management.sql','docs/operational-cutover-20260906/coverage-matrix.csv'];
 const manifest={project_ref:'rprechiaglyjaydkmxsu',status:'DERIVED_SAFE_LOCAL_CANDIDATE_NOT_APPLIED',operation:'expansion_pool_update',ui_coverage_candidate:['X01'],prerequisite:'pipeline-close-won/20260906',surface:'pc_only',allowed_changes:['expansion_status','next_contact_at'],allowed_statuses:['신규 대상','접촉 예정','관계 관리중','추가 니즈 확인','보류/휴면'],blocked_changes:['Pipeline 전환','created_opportunity_id','last_contact_at','need_note','relationship_state','client actor/time'],server_rules:{scope:'crm_security.can_deal(source_deal_id,true)',concurrency:'private expansion pool version',history:'one private event + deal audit + receipt per mutation'},read_additions:['expansion_pool.version','expansion_events safe projection'],rollback:'business status/date retained; evidence archived; adapter/read layer restored',staging_ddl_dml_performed:false,production_accessed:false,n8n_accessed:false,files_sha256:Object.fromEntries(own.map(f=>[f,sha(fs.readFileSync(path.join(dir,f)))])),source_sha256:Object.fromEntries(sources.map(f=>[f,sha(fs.readFileSync(path.join(root,f)))]))};
 fs.writeFileSync(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
if(require.main===module)console.log(JSON.stringify(build(),null,2));
module.exports={adapter,overlay,transport,applySql,rollbackSql,build};
